kubeshop/tracetest

docs/docs/configuration/connecting-to-data-stores/honeycomb.md

This PR...
- See fixes
- resolves #2529

fixed shorthand naming convention (honeycomb)

---

cli/cmd/config.go

This PR fixes a bug with the default output for non-resources commands.
- fix cli default output
- fixes #2522

fix(cli): fix default output for non-resources commands

---

web/src/components/Visualization/components/DAG/SpanNode.styled.ts

In our current graph view, we highlight the selected span by using a blue line around the span. However, it is not easy no identify it specially when you are in the "Test Spec" detail mode. This PR improves this design to have a clear understanding of which span is selected.
- Improve selected span in graph view
- fixes #2495

fix(frontend): highlight selected span

---

web/src/components/CodeBlock/CodeBlock.tsx
web/src/components/RunDetailTriggerResponse/ResponseBody.tsx
web/src/components/RunDetailTriggerResponse/ResponseHeaders.tsx
web/src/components/RunDetailTriggerResponse/RunDetailTriggerResponse.tsx

This PR fixes a bug where the frontend was showing an infinite loading spinner if the test returned an empty body/headers for the trigger.
- fix empty body/headers issue
-

fix(frontend): fix empty body and headers in trigger tab

---

server/executor/poller_executor.go
server/executor/poller_executor_test.go
server/model/events/events.go
server/tracedb/awsxray.go
server/tracedb/elasticsearchdb.go
server/tracedb/jaegerdb.go
server/tracedb/opensearchdb.go
server/tracedb/otlp.go
server/tracedb/signalfxdb.go
server/tracedb/tempodb.go
server/tracedb/tracedb.go

This PR updates the `TracePollingStart` event to include information as the DataStore `type` and `URLs`.
- Update `TracePollingStart` event
- fixes #2508

feat(server): add traceDB endpoints to event log

---

testing/server-tracetesting/features/transaction/05_delete_transaction.yml

This PR fixes the delete transaction method
-
-

fix: handle delete for transactions with more than 1 run

---

go.work.sum
server/model/tests.go
server/model/trigger_json.go
server/model/trigger_json_test.go

This PR fixes a retrocompat issue, where tests created before this version would fail to be correctly read from DB. This was caused by a change in the JSON encoding of the `model.Trigger` entity.
This PR fixes this by adding basic versioning support for the entity

fix: add versioning for trigger encoding

---

server/expression/executor_test.go
server/expression/parser_rules.go
server/expression/parser_test.go

This PR makes the assertion engine support dashes in attribute names. Related to #2564

feat: support dashes in attribute names

---

server/http/controller.go

This PR fixes an internal error on the controller, happening on integartion, making our pipeline fail.

hotfix: fix controller

---

testing/server-tracetesting/features/environment/01_create_environment.yml
testing/server-tracetesting/features/environment/02_list_environment.yml
testing/server-tracetesting/features/environment/03_delete_environment.yml
testing/server-tracetesting/features/environment/_test_suite.yml
testing/server-tracetesting/features/grpc_test/01_create_grpc_test.yml
testing/server-tracetesting/features/grpc_test/02_list_grpc_test.yml
testing/server-tracetesting/features/grpc_test/03_run_grpc_test.yml
testing/server-tracetesting/features/grpc_test/04_delete_grpc_test.yml
testing/server-tracetesting/features/grpc_test/05_create_grpc_test_with_invalid_metadata.yml
testing/server-tracetesting/features/grpc_test/06_run_grpc_test_with_invalid_metadata.yml
testing/server-tracetesting/features/grpc_test/_test_suite.yml
testing/server-tracetesting/features/http_test/01_delete_http_test_with_non_existing_id.yml
testing/server-tracetesting/features/http_test/02_create_http_test_with_non_existing_id.yml
testing/server-tracetesting/features/http_test/04_delete_http_test_with_existing_id.yml
testing/server-tracetesting/features/http_test/05_create_http_test.yml
testing/server-tracetesting/features/http_test/06_list_http_test.yml
testing/server-tracetesting/features/http_test/07_run_http_test.yml
testing/server-tracetesting/features/http_test/08_rerun_http_test.yml
testing/server-tracetesting/features/http_test/09_delete_http_test_run.yml
testing/server-tracetesting/features/http_test/10_delete_http_test.yml
testing/server-tracetesting/features/http_test/_test_suite.yml
testing/server-tracetesting/features/transaction/_test_suite.yml
testing/server-tracetesting/features/transaction/create_transaction.yml
testing/server-tracetesting/features/transaction/create_transaction_step.yml
testing/server-tracetesting/features/transaction/delete_transaction.yml
testing/server-tracetesting/features/transaction/delete_transaction_step.yml
testing/server-tracetesting/features/transaction/list_transaction.yml
testing/server-tracetesting/features/transaction/list_transaction_as_resource.yml
testing/server-tracetesting/features/transaction/update_transaction.yml

This PR sets static IDs for tests. This allows tests to be updated instead of always created as new. This makes it easier to navigate the integration UI and makes the history of runs visually clearer

fix: set static IDs for dogfood tests and transactions

---

cli/actions/transaction.go

This PR fixes how the CLI handles relative paths on transaction definitions.
The code was assuming that the test files references in a transaction are relative to the CWD, but they should be relative to the transaction file.

fix: correctly handle transaction relative paths

---

server/resourcemanager/resource_manager.go

This PR fixes an issue triggered by running `tracetest get datastore  --id current -o json`, where the server panics. The underlying issue is that the request is being sent with the `X-Tracetest-Agumented` header, but the resource handler doesn't implement the method, causing a nil pointer reference.
This PR handles the nil pointer.

fix: improve resourcemanager handling of augmented header

---

docs/docs/examples-tutorials/overview.md

This PR adds the Honeycomb integration blog post to Examples+Recipes integrations list.
-
-

docs(examples-recipes): add honeycomb to list of integrations

---

docs/docs/cli/creating-transactions.md
docs/sidebars.js

This PR adds a section of how to create transactions from the CLI

add section about creating transactions and enable envs docs

---

docs/docs/cli/creating-transactions.md
docs/sidebars.js

This PR fixes an issue with the sidebar menu in our docs. It removes the Creating environments and Creating transactions menu from the Web UI section, and enables it under the CLI section.
- fix sidebar menu in docs
-

fix(docs): fix cli transactions menu

---

web/src/services/DAG.service.ts

This PR removes the decross option from the dag layout setup, as it breaks with large traces
Related issue https://github.com/erikbrinkman/d3-dag/issues/98
- Removes decross option from dag layout setup

fix(frontend): removing decross option for the dat layout

---

server/model/traces.go
server/model/traces_test.go

This PR fixes the issue that root spans don't point to the root tracetest span as it's parent.

fix: nil parent when multi root trace

---

cli/cmd/apply_cmd.go
cli/cmd/config.go
cli/cmd/configure_cmd.go
cli/cmd/datastore_legacy_cmd.go
cli/cmd/delete_cmd.go
cli/cmd/environment_legacy_cmd.go
cli/cmd/export_cmd.go
cli/cmd/get_cmd.go
cli/cmd/list_cmd.go
cli/cmd/middleware.go
cli/cmd/server_install_cmd.go
cli/cmd/test_list_cmd.go
cli/cmd/version_cmd.go
cli/parameters/configure.go
cli/parameters/installer.go
cli/parameters/parameters.go
cli/parameters/resources.go

This PR adds parameter based logic to validate different flags and args for each of the commands, returns all errors at once depending on the validation checks
- Adds new middleware to support parameter validation
- Adds new parameters interface and validators for commands
- #2305 
https://www.loom.com/share/9efaab50749045bf9ce4557b93230806

feature(cli): adding flag and parameter validations for commands

---

web/src/constants/TestSpecs.constants.ts

This PR fixes the attribute in the Test Spec snippet for `All gRPC Spans: Status is Ok`
- fix attribute in test spec snippet
- fix #2601

fix(frontend): fix grpc test spec snippet

---

cli/actions/version.go
cli/cmd/config.go
testing/cli-e2etest/testscenarios/version_test.go

This PR adds a server version match for the CLI. It automatically breaks any command if we find a mismatch.
It is skipped if the `TRACETEST_DEV` flag is set.
- Adds version match for server and CLI
- #2298 
https://www.loom.com/share/b09b566e12664f49bfcdcda73a079576

feature(cli): adding server and cli version match

---

web/src/redux/apis/OtelRepo.api.ts

This PR fixes the OpenTelemetry Semantic Conventions URL. We use this repository to get details about the Trace Semantic Conventions and display it in our attribute list component. In the last release (`v1.21.0`) of the [Opentelemetry Specification](https://github.com/open-telemetry/opentelemetry-specification) they moved the [Semantic Conventions](https://github.com/open-telemetry/semantic-conventions) to a separate repository.
- fix OpenTelemetry Semantic Conventions URL
-

fix(frontend): fix otel semantic conventions repository url

---

server/app/facade.go
server/executor/default_poller_executor.go
server/executor/poller_executor_test.go
server/executor/pollingprofile/polling_profile_resource.go
server/executor/pollingprofile/polling_profile_resource_test.go
server/executor/runner.go
server/executor/runner_test.go
server/executor/selector_based_poller_executor.go
server/executor/selector_based_poller_executor_test.go
server/executor/trace_poller.go

This PR introduces another algorithm parameter for our trace poller. When we don't detect changes in the trace anymore, we try matching the selectors with spans. If all selectors get at least one span, we consider the polling successful, otherwise, try again in the next polling cycle. If we have no changes in the trace and we cannot match the selectors with spans from the trace 3 times in a row, we end the polling and mark it as complete (to prevent issues when writing TDD)
There are more things that could be done and  I'll do in the future if needed:
* Make this configurable via a polling profile option (either another strategy, or just an option inside the `periodic` object)
| # Run | Action |
|---|---|
| # 01  | Got initial trace |
| # 02  | Got more spans, continue |
| # 03  | Got …

feat: improved poller algorithm

---

server/linter/plugins/common/plugin.go
server/linter/plugins/standards/plugin.go
server/linter/resource/manager.go
server/linter/resource/resource.go
web/src/components/BetaBadge/BetaBadge.styled.ts
web/src/components/BetaBadge/BetaBadge.tsx
web/src/components/RunDetailTrace/LintResults.tsx
web/src/components/Settings/Linter/Linter.tsx
web/src/components/Settings/Linter/LinterForm.tsx
web/src/components/SpanDetail/Header.tsx
web/src/components/Visualization/components/DAG/SpanNode.tsx
web/src/pages/Settings/Content.tsx
web/src/redux/apis/endpoints/Setting.endpoint.ts
web/src/types/Settings.types.ts

This PR includes the Tracetest Analyzer improvements described in the parent ticket plus some fixes
- Adds tab query param for settings
- Updates linter test to the analyzer
- Updates BE resource name
- Fixes save analyzer settings bug
- #2626 
https://www.loom.com/share/d403016d171f4e898d0cdbb3bf39e55b

feature: Tracetest Analyzer Improvements

---

server/executor/trace_poller.go

This PR fixes the issue that was making Tracetest test the data store connection multiple times.

fix: duplicated datastore test events

---

server/app/app.go
server/integration/ensure_server_prefix_test.go

This PR makes the resource manager take the server path prefix into consideration when building the routes. Related to one problem related in #2565

fix: make resource manager take server prefix into consideration

---

cli/cmd/config.go
cli/cmd/server_cmd.go
cli/cmd/server_install_cmd.go

This PR adds a way to skip version mismatch checks for commands when using the `setupCommand` function
- Updates the setup command function to have a way to skip version mismatch validations
- A release bug when trying to install tracetest

fix(cli): adding skip of version mismatch for the server install cmd

---

api/openapi.yaml
api/tests.yaml

This PR updates the openapi specs to make all test endpoints match the resource manager request/response format.

feat: new tests openapi spec

---

server/app/app.go
server/app/facade.go
server/executor/transaction_run_updater.go
server/executor/transaction_runner.go
server/executor/transaction_runner_test.go
server/http/controller.go
server/http/mappings/tests.go
server/http/validation/variable.go
server/http/websocket/subscribe.go
server/model/yaml/file_test.go
server/model/yaml/transaction.go
server/testdb/mock.go
server/testdb/runs.go
server/testdb/tests.go
server/transactions/main_test.go
server/transactions/transaction_runs.go
server/transactions/transactions.go
server/transactions/transactions_runs_test.go
server/transactions/transactions_test.go

This PR moves the `transactions` files from the `tests` module into a new `transactions` module

fix: move transactions to it's own module

---

docs/docs/configuration/connecting-to-data-stores/datadog.md
docs/docs/configuration/connecting-to-data-stores/lightstep.md
docs/docs/configuration/connecting-to-data-stores/new-relic.md
docs/docs/examples-tutorials/recipes/running-tracetest-with-aws-x-ray-adot.md
docs/docs/examples-tutorials/recipes/running-tracetest-with-datadog.md
docs/docs/examples-tutorials/recipes/running-tracetest-with-honeycomb.md
docs/docs/examples-tutorials/recipes/running-tracetest-with-lightstep.md
docs/docs/examples-tutorials/recipes/running-tracetest-with-new-relic.md
examples/quick-start-datadog-nodejs/tracetest/collector.config.yaml
examples/tracetest-amazon-x-ray-adot/collector.config.yaml
examples/tracetest-datadog/tracetest/collector.config.yaml
examples/tracetest-honeycomb/collector.config.yaml
examples/tracetest-lightstep-otel-demo/README.md
examples/tracetest-lightstep-otel-demo/otelcollector/otelcol-config-extras.yml
examples/tracetest-lightstep/tracetest/collector.config.yaml
examples/tracetest-new-relic-otel-demo/README.md
examples/tracetest-new-relic-otel-demo/otelcollector/otelcol-config-extras.yml
examples/tracetest-new-relic/tracetest/collector.config.yaml
web/src/constants/CollectorConfig.constants.ts

Replacing all the abbreviations for tracetest and the data store vendors names with full names to make the docs more clear.
We used the following in our collector configs:
tt for tracetest
nr for newrelic
hc for honeycomb
ls for lightstep
dd for datadog
This pr replaces the abbreviation with the full name. It helps make it clear what the different sections are as opposed to having users have to translate 'tt' into 'tracetest', hopefully making things more clear. This change was recommended by Alayshia at Honeycomb.

Replace abbreviations in collector config

---

web/src/components/RunDetailTrace/RunDetailTrace.styled.ts
web/src/components/RunDetailTrace/Search.tsx

This PR adds the `No matches found` message when performing a Trace search and no results are available.
- new not found message
- #1154

fix(frontend): add no matches message in trace search

---

cli/analytics/analytics.go
cli/utils/api.go
server/app/app.go
server/http/custom_routes.go
server/resourcemanager/resource_manager.go
web/src/redux/apis/TraceTest.api.ts

This PR adds an `analytics middleware` to the router in order to track/send events from the server.
- add analytics middleware
- implements the `x-source` header
- remove route middleware in custom controller
- #2539

feat(server): add analytics middleware

---

server/model/traces.go
server/model/traces_test.go

This PR adds new conditions on when to add the temporary root span in the trace. Now, if one of the root spans is the `Tracetest trigger` span, it gets promoted as the root span. This prevents the issue of having two `Tracetest trigger` spans in the same trace
- #2637

fix: make sure temporary root span is not added to the trace if Tracetest Trigger span already exists

---

web/src/components/TestSpecForm/AssertionCheck.tsx

This PR enables users to delete all checks no matter if its the first or the last
- Enables deletion for all checks from the test spec form
- #2678

feature(frontend): enabling first attribute check deletion

---

web/src/components/CurrentSpanSelector/CurrentSpanSelector.styled.ts
web/src/components/CurrentSpanSelector/CurrentSpanSelector.tsx

This PR fixes a bug when displaying the switch span button while the test spec form is open that caused the prev checks to go out of bounds.
- Updates container to have position absolute
- Updates listener to wrap container
- #2492

fix(frontend): fixing select spans visual bug

---

web/src/components/TestSpecForm/TestSpecForm.tsx

This PR fixes a missing dependency in our `TestSpec` form that was causing a bug when trying to create a new spec from the attribute list using the same selector.
- add missing dependency
- fixes #2484

fix(frontend): fix missing dep in useEffect in TestSpec form

---

api/linters.yaml
cli/openapi/model_linter_result.go
server/executor/linter_runner.go
server/http/mappings/linter.go
server/linter/resource/model.go
server/model/linter.go
server/model/run.go
server/openapi/model_linter_result.go
web/src/components/AnalyzerResult/AnalyzerResult.styled.ts
web/src/components/AnalyzerResult/AnalyzerResult.tsx
web/src/components/AnalyzerResult/GlobalResult.tsx
web/src/components/AnalyzerResult/Plugins.tsx
web/src/components/LintScore/LintScore.styled.ts
web/src/components/LintScore/LintScore.tsx
web/src/components/LintScore/PercentageScore.tsx
web/src/components/RunCard/TestRunCard.tsx
web/src/components/TransactionRunResult/ExecutionStep.tsx
web/src/constants/Theme.constants.ts
web/src/models/LinterResult.model.ts
web/src/styled.d.ts
web/src/types/Generated.types.ts

This PR improves the way we handle error states for the analyzer. Instead of stopping the test execution, now clients will be reading the linter results to validate if there was a failure or not, and show the proper results.
- Removes stopping of test runs based on analyzer errors
- Updates analyzer errors UI to better showcase the minimum score error
- Updates transaction execution card and test run card to show the proper status
- #2682 
https://www.loom.com/share/6624b56c915b4c41a07f52179bbbdbf7

feature: Improving Analyzer Failure State

---

web/src/components/TestSpecDetail/Content.tsx
web/src/hooks/useScrollTo.ts

This PR adds a way to auto-scroll to any element in the UI and uses it for the assertion results
- Assertion results content scrolls to result when selected span changes
- #2602 
https://www.loom.com/share/82c5917a28f14794b9b9914a7dc3c5bf

feature(frontend): adding auto scroll to assertion result

---

web/cypress/e2e/TestRunDetail/Outputs.spec.ts
web/src/components/AttributeActions/AttributeActions.styled.tsx
web/src/components/AttributeActions/AttributeActions.tsx
web/src/components/AttributeActions/index.ts
web/src/components/AttributeRow/AttributeRow.tsx
web/src/components/HeaderRow/HeaderRow.tsx
web/src/components/RunDetailTrigger/RunDetailTrigger.tsx
web/src/components/RunDetailTriggerResponse/ResponseBody.tsx
web/src/components/RunDetailTriggerResponse/ResponseHeaders.tsx
web/src/components/RunDetailTriggerResponse/RunDetailTriggerResponse.styled.ts
web/src/components/RunDetailTriggerResponse/RunDetailTriggerResponse.tsx
web/src/components/RunDetailTriggerResponse/RunDetailTriggerResponseFactory.tsx

This PR adds the ability to create `TestSpecs` and `TestOutputs` from the `TriggerResponse` data.
- new `AttributeActions` component
- include the actions component in the `TriggerResponse` data
- include the actions component in the `AttributeList` in Trace/Test tab
- fixes #2525 
https://www.loom.com/share/d66773ef46fb4cf99e9535ba26d6343d

feat(frontend): support specs and outputs creation from trigger response

---

server/tracedb/datasource/http.go
server/tracedb/tempodb.go

This PR removes the warning for http ports when using tempo as a data store
- Adds empty port as valid for tempo
- Updates libs to parse urls
- #2155

fix(backend): adding empty port as supported for tempo

---

web/src/components/RunDetailTriggerResponse/RunDetailTriggerResponse.styled.ts
web/src/components/RunDetailTriggerResponse/RunDetailTriggerResponse.tsx

This PR adds the AttributeActions icon to the status and duration fields in the TriggerResponse data section.
- add AttributeActions icon to status and duration
- fixes #2525

fix(frontend): add AttributeActions icon to status and duration fields

---

web/src/components/AnalyzerResult/AnalyzerResult.styled.ts
web/src/components/DocsBanner/DocsBanner.styled.ts
web/src/components/DocsBanner/DocsBanner.tsx
web/src/components/DocsBanner/index.ts
web/src/components/Settings/DataStoreDocsBanner/DataStoreDocsBanner.tsx
web/src/components/Settings/DataStoreForm/DataStoreForm.styled.ts
web/src/components/Settings/DataStoreForm/DataStoreForm.tsx
web/src/components/Settings/DataStorePlugin/forms/AwsXRay/AwsXRay.tsx
web/src/components/Settings/DataStorePlugin/forms/AzureAppInsights/AzureAppInsights.tsx
web/src/components/Settings/DataStorePlugin/forms/BaseClient/BaseClient.tsx
web/src/components/Settings/DataStorePlugin/forms/ElasticSearch/ElasticSearch.tsx
web/src/components/Settings/DataStorePlugin/forms/GrpcClient/GrpcClient.tsx
web/src/components/Settings/DataStorePlugin/forms/HttpClient/HttpClient.tsx
web/src/components/Settings/DataStorePlugin/forms/OpenTelemetryCollector/Configuration.tsx
web/src/components/Settings/DataStorePlugin/forms/OpenTelemetryCollector/Ingestor.tsx
web/src/components/Settings/DataStorePlugin/forms/OpenTelemetryCollector/OpenTelemetryCollector.styled.ts
web/src/components/Settings/DataStorePlugin/forms/OpenTelemetryCollector/OpenTelemetryCollector.tsx
web/src/components/Settings/DataStorePlugin/forms/SignalFx/SignalFx.tsx
web/src/constants/Common.constants.ts
web/src/constants/DataStore.constants.tsx
web/src/models/DataStore.model.ts
web/src/services/DataStore.service.ts
web/src/services/DataStores/AzureAppInsights.service.ts
web/src/services/DataStores/OtelCollector.service.ts
web/src/types/DataStore.types.ts

This PR updates the otlp data store designs and adds a switch to enable the ingestor
- Updates the otlp datastore component
- Moves explanation and title to each datastore form
- Adds logic to handle new field
- #2509 
https://www.loom.com/share/ed6fc3cbfd204cb09090b6d4c7324ff1

feature(frontend): adding enable switch for ingestor for Otel DataStores

---

cli/installer/kubernetes.go

This PR fixes the error thrown by the csv reader when a CSV file contains different fields in each line.

fix: disable csv fields count validation when listing contexts in k8s

---

.github/workflows/deploy-demo.yml
.github/workflows/pull-request.yaml
.goreleaser.demo.yaml
.goreleaser.dev.yaml

This PR fixes the demo release pipeline by allowing docker images for demo build to be published to dockerhub

fix(cicd): fix goreleaser config to actually publish demo docker image

---

.github/workflows/pull-request.yaml
.goreleaser.dev.yaml

This PR updates the pull request pipeline so it can work as expected when triggered both by a PR or by a push to main.
When running on main, the images were exported with the tag `kubeshop/tracetest:pr-`. This is because the pipeline relies on the PR number to build that tag. The problem is that sometimes the cache can be picked by a PR that will try to run images with the tag `kubeshop/tracetest:pr-{the pr number}`. Since the image is exported with the wrong tag, the docker stack cannot start and everything fails.
This happens by removing the references to PR specific info, like PR number, and replacing it by the sha of whatever commit triggered the action.

fix(cicd): make pull request pipeline work as expected for push to main

---

docs/docs/ci-cd-automation/overview.md
docs/docs/cli/configuring-your-cli.md

Adding docs in two places per #2611 to document how to use the Tracetest image to run the CLI in docker without installing locally.

Documenting running cli in docker

---

cli/actions/environments.go
cli/utils/api.go
server/environment/manager.go
server/environment/resource.go
server/resourcemanager/operations.go
server/resourcemanager/resource_manager.go

This PR adds a new method for upsert the resource into the database. And enables it for transactions

feat: add upsert method and enable it for environments

---

server/app/app.go
server/test/test_repository.go
server/test/tests.go

This PR adds the augmented option to the list tests endpoint

feat: test list augmented response

---

web/src/components/Router/Router.tsx
web/src/components/RunDetailLayout/HeaderRight.tsx
web/src/pages/AutomatedTestRun/AutomatedTestRun.tsx
web/src/pages/AutomatedTestRun/Content.tsx
web/src/pages/AutomatedTestRun/hooks/useAutomatedTestRun.ts
web/src/pages/AutomatedTestRun/index.ts
web/src/pages/Home/Resources.tsx
web/src/pages/Test/Content.tsx
web/src/providers/CreateTest/CreateTest.provider.tsx
web/src/providers/MissingVariablesModal/MissingVariablesModal.provider.tsx
web/src/providers/Test/Test.provider.tsx
web/src/providers/Test/hooks/useTestCrud.ts

This PR adds a way for users to go to use a deep link to start a test execution
- Adds new page to support automated test runs
- Adds logic to fetch environment and variables from the query
- Updates hooks to use an object as parameters for running tests
- #2745 
https://www.loom.com/share/50de4440c25b46738ca1c643cd72c195

feature(frontend): Adding Test Execution Deep Link

---

web/src/components/Header/Header.styled.tsx
web/src/components/RunDetailAutomate/RunDetailAutomate.styled.ts
web/src/components/RunDetailAutomate/RunDetailAutomate.tsx
web/src/components/RunDetailAutomate/index.ts
web/src/components/RunDetailLayout/RunDetailLayout.styled.ts
web/src/components/RunDetailLayout/RunDetailLayout.tsx
web/src/constants/TestRun.constants.ts

This PR adds the base skeleton for the automate tab
- Adds new tab to the test run detail header
- Adds new pane for the automate feature
- #2749

feature(frontend): Adding Automate Tab Skeleton

---

.goreleaser.dev.yaml
Makefile

This PR fixes an incorrect default value for the `TAG` env var in `goreleaser.dev.yaml`, causing the following build error:

fix(cicd): fix default value for TAG env var

---

docs/docs/ci-cd-automation/overview.md
docs/docs/cli/configuring-your-cli.md

Clarified the instructions on how to run the CLI from docker, including explaining that it would need to connect to a remote Tracetest server.

Clarify instructions for running the CLI from docker

---

examples/tracetest-grafana-tempo-pokeshop/.gitignore
examples/tracetest-grafana-tempo-pokeshop/README.md
examples/tracetest-grafana-tempo-pokeshop/collector.config.yaml
examples/tracetest-grafana-tempo-pokeshop/docker-compose.yml
examples/tracetest-grafana-tempo-pokeshop/grafana.config.yaml
examples/tracetest-grafana-tempo-pokeshop/tempo.config.yaml
examples/tracetest-grafana-tempo-pokeshop/tests/curl_post.sh
examples/tracetest-grafana-tempo-pokeshop/tests/test.yaml
examples/tracetest-grafana-tempo-pokeshop/tracetest.config.yaml
examples/tracetest-grafana-tempo-pokeshop/tracetest.provision.yaml

examples(Grafana tempo pokeshop): initial setup for blog post sample

---

docs/docs/cli/creating-transactions.md
docs/docs/cli/running-tests.md

This PR corrects two minor typos in the CLI section of the docs.
- [Docs › CLI › Configuring Transactions › Creating Transactions](https://docs.tracetest.io/cli/creating-transactions):
`complete-purchase.yaml` instead of `complete-purschase.yaml` ([commit 6866bcf](https://github.com/kubeshop/tracetest/commit/6866bcfd6a3a59bd1863ac350b98374b50dcebae))
- [Docs › CLI › Configuring Tests › Running Tests](https://docs.tracetest.io/cli/running-tests):
`-o json` instead of `- o json` ([commit b29acc3](https://github.com/kubeshop/tracetest/commit/b29acc360cde2cf729caf40ac390e3607dd8bf36))

Minor typos in Docs › CLI

---

server/app/app.go
server/config/demo/demo_entities.go
server/config/demo/demo_repository.go
server/config/demo/demo_repository_test.go
server/config/demo/main_test.go
server/provisioning/provisioning_test.go

This PR updates the names of the demo resource files to a common standard we defined with Tracetest Core contributors.
- Updating demo resource file names and references
-
- [c] tested locally

fix(server): standardize demo resource names

---

cli/cmd/get_cmd.go
cli/formatters/transaction.go
testing/cli-e2etest/helpers/table_unmarshal.go
testing/cli-e2etest/testscenarios/transaction/get_transaction_test.go
testing/cli-e2etest/testscenarios/transaction/list_transactions_test.go

This PR fixes the bugs reported on #2761 and #2760
Loom: https://www.loom.com/share/d3b9abf4134e41dfb46c8d6bc2a7e9c1?sid=d95b69b3-c11f-4515-937d-62e7bba69d3c
- Fixed formatting for transactions on the flag `--output pretty`
- closes #2761
- closes #2760

fix(cli): fixing CLI formatting for transactions

---

cli/formatters/polling.go
testing/cli-e2etest/testscenarios/analyzer/get_analyzer_test.go
testing/cli-e2etest/testscenarios/analyzer/list_analyzer_test.go
testing/cli-e2etest/testscenarios/config/get_config_test.go
testing/cli-e2etest/testscenarios/config/list_config_test.go
testing/cli-e2etest/testscenarios/datastore/get_datastore_test.go
testing/cli-e2etest/testscenarios/datastore/list_datastore_test.go
testing/cli-e2etest/testscenarios/demo/get_demo_test.go
testing/cli-e2etest/testscenarios/demo/list_demos_test.go
testing/cli-e2etest/testscenarios/environment/get_environment_test.go
testing/cli-e2etest/testscenarios/environment/list_environments_test.go
testing/cli-e2etest/testscenarios/pollingprofile/get_pollingprofile_test.go
testing/cli-e2etest/testscenarios/pollingprofile/list_pollingprofile_test.go

This PR updates the CLI e2e tests for the flag `--output=pretty` to the resources: analyzer, config, datastore, demo, environment and pollingprofile.
Loom: https://www.loom.com/share/1c6717266f1b4e299baceb8429eb0980?sid=8ae4d69b-590e-4c13-b5f2-13d2f189bf99
- Updated `get` and `list` tests for the `--output=pretty` scenario to the resources: analyzer, config, datastore, demo, environment and pollingprofile.

chore(cli): update cli e2e table tests validation

---

.github/workflows/pull-request.yaml

This PR allows running cypress in non-parallel mode if the licence key is not present. This is needed for extrnal users and forks to be able to run this pipeline

chore(cicd): allow running cypress without paralellization if licence key is not present

---

.github/workflows/pull-request.yaml
run.sh
server/resourcemanager/encoding.go
server/resourcemanager/encoding_test.go
server/resourcemanager/resource_manager.go

This PR adds support for multi-document YAML requests and responses in the `resourcemanager` package. Previously, it supported single-document YAML.
The implementations uses a new encoder that can be used with the `text/yaml-stream` content-type/accept headers.
With this change, we can handle **requests** and **responses** that contain multiple YAML documents separated by `---` lines.
This means that a client can send a multi document request and it will work, but only if all the documents are of the same type (i.e. all transactions, or all tests, but not a mix of transactions and tests).
See it in action:
https://www.loom.com/share/dee1b1c35a544ee3b31bd00f1058ab1c

feat(server): add yaml stream encoding for resource manager

---

testing/cli-e2etest/README.md

This PR adds the `analyzer` resource to the cli-e2e tests README.
- add analyzer resource to README
-

fix(tests): add analyzer resource to cli e2e table

---

web/src/components/InputOverlay/InputOverlay.styled.ts
web/src/components/InputOverlay/InputOverlay.tsx
web/src/components/InputOverlay/index.ts
web/src/components/RunDetailAutomate/RunDetailAutomate.tsx
web/src/components/RunDetailAutomateDefinition/RunDetailAutomateDefinition.styled.ts
web/src/components/RunDetailAutomateDefinition/RunDetailAutomateDefinition.tsx
web/src/components/RunDetailAutomateMethods/RunDetailAutomateMethods.tsx
web/src/components/RunDetailAutomateMethods/methods/CLICommand/CliCommand.tsx
web/src/components/RunDetailAutomateMethods/methods/CLICommand/Controls.tsx
web/src/services/CliCommand.service.ts

This PR adds a way for users to update the test definition file name and it updates the CLI command accordingly
- Adds InputOverlay component
- Adds logic to carry over the file name across the page
- Updates CLI command and download file name from users input
- #2768 
https://www.loom.com/share/cce3af0532af4b09801aa7a23ae2cde1

chore(frotend): Test Definition Name Input

---

web/src/components/ResizablePanels/LeftPanel.tsx
web/src/components/ResizablePanels/ResizablePanels.styled.ts
web/src/components/ResizablePanels/RightPanel.tsx
web/src/components/ResizablePanels/Splitter.tsx
web/src/components/RunDetailTest/SpanDetailsPanel.tsx
web/src/components/RunDetailTrace/AnalyzerPanel.tsx
web/src/components/RunDetailTrace/SpanDetailsPanel.tsx
web/src/constants/Theme.constants.ts
web/src/styled.d.ts

This PR updates the splitter style for the span detail drawer and analyzer
It also adds a tooltip for extra information
- Adds tooltip for splitter
- Updates styles
- #2765 
https://www.loom.com/share/f6b002011aa54650981ca07b7510e460

chore(frotend): Updating Panel Splitter w/ Tooltip

---

cli/cmd/datastore_legacy_cmd.go
cli/cmd/delete_cmd.go
cli/cmd/export_cmd.go
cli/cmd/get_cmd.go
cli/cmd/list_cmd.go
cli/parameters/resources.go
cli/pkg/resourcemanager/format.go

This PR follows up on https://github.com/kubeshop/tracetest/pull/2829, adding support for the Export verb in the same manner.

feat(cli): update export command with new resourcemanager client

---

web/src/components/AnalyzerErrorsPopover/AnalyzerErrorsPopover.styled.ts
web/src/components/AnalyzerErrorsPopover/AnalyzerErrorsPopover.tsx
web/src/components/AnalyzerErrorsPopover/Content.tsx
web/src/components/AnalyzerErrorsPopover/index.ts
web/src/components/AttributeList/AttributeList.tsx
web/src/components/SpanDetail/Attributes.tsx
web/src/components/SpanDetail/SpanDetail.tsx
web/src/components/SpanDetail/TraceAttributeRow/TraceAttributeRow.styled.ts
web/src/components/SpanDetail/TraceAttributeRow/TraceAttributeRow.tsx
web/src/components/SpanDetail/TraceSubHeader/TraceSubHeader.styled.ts
web/src/components/SpanDetail/TraceSubHeader/TraceSubHeader.tsx
web/src/services/SpanAttribute.service.ts

This PR adds support to map the `analyzer errors` to `span attributes`. The idea is to have a behavior similar to test specs in the test tab, where you can see the errors per attribute in the AttributeList component.
- Analyzer errors by attribute
- New AnalyzerErrorsPopover component
- fixes #2781 
https://www.loom.com/share/3abbfdecf2fb46d1a74e7ecd9ec2945c?sid=9ab48319-9f01-4fdc-ab4e-7f31aa47bcaf

feat(frontend): add analyzer errors by attribute

---

web/src/components/Visualization/components/Timeline/TestSpanNode/Header.tsx
web/src/components/Visualization/components/Timeline/TestSpanNode/TestSpanNode.tsx
web/src/components/Visualization/components/Timeline/Timeline.styled.ts

This PR adds `TestOutputs` to the `Timeline` visualization in order to have feature parity between the different visualizations.
- Add TestOutputs to Timeline
-

feat(frontend): add test outputs mark to Timeline view

---

web/src/components/AnalyzerScore/AnalyzerScore.styled.ts
web/src/components/AnalyzerScore/AnalyzerScore.tsx
web/src/components/AnalyzerScore/Percentage.tsx
web/src/components/ResourceCard/ResourceCardSummary.tsx
web/src/components/RunCard/TestRunCard.tsx

This PR fixes analyzer score component:
- Do not fill the progress circle if the score is 0
- Fix font size issue in the test run list
- Do not fill the progress circle if the score is 0
- Fix font size issue in the test run list
- fixes #2848

fix(frontend): fix analyzer score styles

---

docs/docs/cli/configuring-your-cli.md

This PR fixes a deprecated test command in our docs.
- fix deprecated command
- #2354

fix(docs): fix deprecated test command

---

server/test/test_json.go
server/test/test_json_test.go
server/test/test_repository.go

This PR fixes the issue that didn't allow specs to have empty selectors (select all) in them.

fix: allow empty selector in specs v1

---

cli/actions/run_test_action.go
cli/cmd/config.go
cli/cmd/resources.go
cli/pkg/resourcemanager/apply.go
cli/pkg/resourcemanager/client.go
cli/pkg/resourcemanager/delete.go
cli/pkg/resourcemanager/get.go
cli/pkg/resourcemanager/list.go
cli/pkg/resourcemanager/options.go
cli/preprocessor/test.go
cli/preprocessor/transaction.go
testing/cli-e2etest/testscenarios/test/apply_test_test.go
testing/cli-e2etest/testscenarios/transaction/resources/another-transaction.yaml
testing/cli-e2etest/testscenarios/transaction/resources/new-transaction.yaml
testing/cli-e2etest/testscenarios/transaction/resources/one-more-transaction.yaml
testing/cli-e2etest/testscenarios/transaction/resources/updated-new-transaction.yaml
testing/cli-e2etest/testscenarios/types/test.go

The new cli resources client introduced a bug:
When a test or transaction is run with `tracetest test run ...` command, the files gets preprocessed: tests files embed protobuf files if needed, and transactions map test file references to test IDs.
The original behaviour was to preprocess files both on `test run` and `apply transaction` (`apply test` wasn't implemented beofre).
This PR adds e2e tests to cover this behavior and fixes it.
In order to implement this in a generic way, we introdiuce a `preprocessor` concept to the resource manager client.
Resources can define an optional `applyPreProcessorFn` function when registering. This func can alter the file that gets submitted to the server before submitting it.

fix(cli): preprocess test and transaction files when running and applying

---

server/test/test_json.go
server/test/test_json_test.go

This PR fixes the run output unmarshal

fix: run output unmarshal

---

web/src/redux/apis/OtelRepo.api.ts

This PR fixes a broken URL for the OTel Semantic Conventions.
[This PR](https://github.com/open-telemetry/semantic-conventions/pull/166) in the official Semantic Conventions repository changed the folder semantic_conventions to model.
- fix broken path
-

fix(frontend): fix otel semantic conventions path

---

server/test/test_json.go
server/test/trigger/trigger_json.go
server/test/trigger/trigger_json_test.go

This PR fixes trigger result json unmarshal

fix: trigger result json unmarshal

---

cli/pkg/resourcemanager/apply.go
testing/cli-e2etest/helpers/common.go
testing/cli-e2etest/testscenarios/transaction/apply_transaction_test.go
testing/cli-e2etest/testscenarios/transaction/resources/new-transaction-without-id.yaml
testing/cli-e2etest/testscenarios/types/transaction.go

This PR prevents the CLI from updating the transaction file from being updated with the pre-processed file content.

fix: don't update transaction file other than adding id to it

---

server/model/spans.go
server/model/traces.go
server/model/traces_test.go

This PR adds the structure for Span events. When present, they will be added to the `attributes` map as `events`.

feat: add span events as an attribute called "events"

---

server/model/spans.go
server/traces/otel_converter.go
server/traces/otel_http_converter.go

This PR adds support to events in Jaeger and tempo datastores (both gRPC and HTTP variants)

feat: support events in Jaeger, Tempo, and all OTLP datastores (both gRPC and HTTP variants)

---

docs/docs/cli/creating-test-specifications.md
server/expression/executor_test.go
server/model/spans.go
server/model/traces.go
server/model/traces_test.go
server/tracedb/azureappinsights.go
server/traces/otel_converter.go
server/traces/otel_http_converter.go

This PR adds support for span events as part of the span attributes

feat: support span events

---

server/linter/analyzer/analyzer_metadata.go
server/linter/analyzer/analyzer_repository_test.go

This PR fixes an incorrect errorDescription for the `secure-https-protocol` analyzer rule.
- fix errorDescription in metadata file
-

fix(backend): fix analyzer rule error description

---

web/src/components/Settings/Linter/Rule.tsx

This PR fixes a parse issue that was causing an error when trying to update the rule's weight.
- add normalize prop on rule weight input
-

fix(frontend): fix analyzer config form for weight field

---

web/src/components/Settings/DataStorePlugin/forms/OpenTelemetryCollector/Configuration.tsx
web/src/components/Settings/DataStorePlugin/forms/OpenTelemetryCollector/OpenTelemetryCollector.tsx

This PR fixes the container for the OTel data store in the Settings page.
- fix container size
- fixes #2899

fix(frontend): fix container in OTel settings page

---

web/src/components/CreateTestPlugins/Rest/steps/RequestDetails/RequestDetailsUrlInput.tsx
web/src/components/CreateTestPlugins/Rest/steps/RequestDetails/UrlDockerTipInput.styled.ts
web/src/components/CreateTestPlugins/Rest/steps/RequestDetails/UrlDockerTipInput.tsx
web/src/utils/Common.ts

This PR updates the request url component to include an extra input for the localhost vs docker host prompt
- Adds new docker url component
- Includes logic for validating and parsing urls
- #2910 
https://www.loom.com/share/4ddc663c26934a118175107f01b323cd

feature(frontend): Adding Docker Host Url Prompt

---

web/src/components/TestOutputForm/TestOutputForm.tsx

This PR improves the attribute selection in the TestOutput form by opening the Suggestions menu when the field has focus.
- add onFocus listener for attribute field in test output form
- fixes #2900

feat(frontend): improve attribute selection in test outputs form

---

cli/cmd/resources.go
testing/cli-e2etest/testscenarios/testrunner/apply_testrunner_test.go
testing/cli-e2etest/testscenarios/testrunner/delete_testrunner_test.go
testing/cli-e2etest/testscenarios/testrunner/get_testrunner_test.go
testing/cli-e2etest/testscenarios/testrunner/list_testrunner_test.go
testing/cli-e2etest/testscenarios/testrunner/resources/new-testrunner.yaml
testing/cli-e2etest/testscenarios/types/testrunner.go

This PR adds support for managing `testrunner`s from the CLI
-
-

feat(cli): TestRunner cli client

---

docs/docs/ci-cd-automation/testkube-pipeline.md
docs/docs/tools-and-integrations/testkube.md
go.work.sum

This PR updated Testkube pages to include links to Testkube docs and YT video.
-
-

docs(testkube): update links to testkube docs and YT vid

---

web/src/components/RunDetailTrace/AnalyzerPanel.tsx

This PR fixes the size of the panels for the Trace tab in order to have the same sizes for all the tabs (Trigger, Trace, Test and Automate)
- fix panel size
- fixes #2936

fix(frontend): fix trace panel size

---

k8s/collector.yml

This PR adds the `resources.requests` config into the collector manifest

fix: add resource requests to collector manifest

---

testing/cli-e2etest/README.md

This PR adds the testrunner resource to the cli e2e tests readme.
- add testrunner resource to readme file
-

feat: add testrunner resource to cli e2e readme

---

.github/workflows/pull-request-installer.yaml
go.work.sum
install-cli.sh

This PR adds an option to the installer to allow installing a specific version.

Installer custom version

---

README.md
docs/docs/ci-cd-automation/overview.md
docs/docs/configuration/overview.md

This PR revamps the Readme.
-
-

readme: add initial overhaul

---

docs/docs/cli/cli-installation-reference.md
docs/docs/getting-started/installation.mdx
docs/docs/getting-started/overview.mdx
docs/docs/index.mdx
docs/sidebars.js
docs/src/components/GettingStartedGuide/index.tsx
docs/src/components/WelcomeGuide/index.tsx
examples/quick-start-pokeshop/.gitignore
examples/quick-start-pokeshop/README.md
examples/quick-start-pokeshop/collector.config.yaml
examples/quick-start-pokeshop/docker-compose.yml
examples/quick-start-pokeshop/tests/test.yaml
examples/quick-start-pokeshop/tracetest.config.yaml
examples/quick-start-pokeshop/tracetest.provision.yaml

This PR adds:
- overview page for getting started section
- Docker Compose installation instructions on the installation page
- install specific version of CLI in the CLI reference page
-
-

docs: Onboarding iteration v2

---

cli/formatters/test_run.go
cli/formatters/test_run_test.go
testing/server-tracetesting/features/environment/01_create_environment.yml

This PR makes the CLI show the related TraceID for tests that are failing. Example:
On Success:
On failure:
Transactions:

feat(cli): show trace ID on failed tests

---

cli/cmd/middleware.go
cli/go.mod
cli/go.sum
cli/pkg/resourcemanager/registry.go
go.work.sum

This PR adds suggestions when the resource is missing or misspelled for resource commands.
Examples:
1. Missing resource:
2. Misspelled resource 
-
-

feat(cli): add suggestions for missing or incorrect resource

---

cli/openapi/model_supported_data_stores.go
go.work.sum
web/src/types/Generated.types.ts

This PR adds generated code on FE and CLI to consider a new DataStore on Tracetest: Dynatrace
- FE unit tests that relies on OpenAPI generated types

fix(cli, fe): fix openapi generated code to consider Dynatrace

---

web/src/components/TransactionHeader/TransactionHeader.styled.ts
web/src/components/TransactionRunResult/ExecutionStep.tsx

This PR fixes a navigation issue in the Transaction page by using the proper Link component.
- use Link component instead of the `react-router-dom` instance
-

fix(frontend): use Link component in transaction page

---

server/model/spans.go
server/resourcemanager/resource_manager.go
server/traces/otel_converter.go
testing/server-tracetesting/features/http_test/03_create_http_test_with_existent_id.yml

This PR adds support for span status. The status code and description are added as attributes, similar to what we do for span time properties.
As a mean to test the feature, we now set a span status of error on the resource manager when an error happens.
- add new span attrributes for span status code and description
- set span status to error on resource manager when needed
- add a trace-based tests for the feature
- #3027

feat(server): add support for span status

---

testing/cli-e2etest/testscenarios/test/run_test_test.go
testing/cli-e2etest/testscenarios/variableset/delete_variableset_test.go
testing/cli-e2etest/testscenarios/variableset/get_variableset_test.go
web/src/components/RunDetailAutomateMethods/methods/CLICommand/Controls.tsx

This PR fixes typos related to `variable sets` in some comments and the web app ui.
- fix typo
-

fix: typo in variable set ui and comments

---

server/otlp/ingester.go

This PR adds a check on the OTLP server to verify that received traces are part of a running test before persisting them.

fix(server): check if trace belongs to running test before saving it

---

cli/cmd/resource_run_cmd.go
testing/cli-e2etest/testscenarios/test/run_test_test.go

This PR fixes the deprecated environment flag from `env` to `environment`
-
-

feat(cli): fixing deprecated environment flag

---

web/src/components/PulseButton/PulseButton.styled.ts
web/src/components/PulseButton/index.ts
web/src/components/ResizablePanels/LeftPanel.tsx
web/src/components/ResizablePanels/ResizablePanels.styled.ts
web/src/components/ResizablePanels/Splitter.tsx
web/src/components/RunDetailTest/SpanDetailsPanel.tsx
web/src/components/RunDetailTrace/SpanDetailsPanel.tsx
web/src/hooks/useAttributePanelTooltip.ts
web/src/services/UserPreferences.service.ts
web/src/types/User.types.ts

This PR updates the behavior for the attribute list tooltip, showing it when users get to a test run for the first time and saving a flag to the user preferences (local storage) afterwards
- Updates tooltip behavior
- Adds localstorage flag
- Fixex the tooltip animation
- #2902 
https://www.loom.com/share/7b8227121ce54d8bb2abc816cb367b27

fix(frontend): Improving attribute menu tooltip

---

docs/docs/live-examples/opentelemetry-store/overview.md

With Tracetest now included in the OpenTelemetry Demo repo, this change utilizes it for the recipe.
This PR...
-
-

Changed to utilize the embedded Tracetest

---

examples/tracetest-honeycomb/collector.config.yaml
examples/tracetest-honeycomb/docker-compose.yaml
examples/tracetest-honeycomb/test-api.yaml
examples/tracetest-honeycomb/tracetest-provision.yaml

This PR updated the honeycomb sample app.
-
-

examples(honeycomb): update sample app

---

.goreleaser.demo.yaml
web/src/models/KafkaRequest.model.ts

This PR fixes a UI bug caused by tests with Kafka trigger and no headers.
Loom: https://www.loom.com/share/f246f488f58d4aefa2fe34a67bb6b6e4?sid=8753e331-70b6-4462-92a5-b1116ed0c23a
- Add guard clause on KafkaRequest model
- Removed unused field that is blocking `demo` deploy

fix(ui): kafka trigger with null header blocks test render on WebUI

---

api/config.yaml
cli/installer/templates/provision.yaml.tpl
cli/installer/tracetest.go
cli/openapi/api_resource_api.go
cli/openapi/model_demo_pokeshop.go
examples/docker-compose.demo.yaml
server/config/demo/demo_entities.go
server/config/demo/demo_repository_test.go
server/go.mod
server/openapi/api_resource_api.go
server/openapi/api_resource_api_service.go
server/openapi/model_demo_pokeshop.go
web/src/components/Settings/Demo/PokeshopFields.tsx
web/src/constants/Demo.constants.ts
web/src/models/Demo.model.ts
web/src/types/Generated.types.ts

This PR aims to add a Kafka example to the Pokeshop demo, allowing users to test a Kafka trigger quickly.
Loom: https://www.loom.com/share/cc55b4419079472fa4937a4ce6ba61ba
- Added KafkaBroker field to OpenAPI specs
- Added KafkaBroker field to the server
- Added a new field to Pokeshop Demo on UI
- Added a new example on Kafka trigger

chore(ui, api): adding Kafka example to Pokeshop demo

---

server/go.mod
testing/cli-e2etest/Makefile
testing/cli-e2etest/environment/jaeger/server-setup/docker-compose-pokeshop-with-stream.yaml
testing/cli-e2etest/environment/manager.go
testing/cli-e2etest/testscenarios/test/resources/kafka-trigger.yaml
testing/cli-e2etest/testscenarios/test/run_test_test.go

This PR adds a test with Kafka trigger on CLI e2e tests to guarantee that the `CLI -> Tracetest` communication is working as intended.
- Added Pokeshop environment with Kafka
- Added Kafka trigger test on CLI e2e

chore(cli-e2e): adding test with Kafka trigger on e2e

---

testing/server-tracetesting/.gitignore
testing/server-tracetesting/features/kafka_test/01_create_kafka_test.yml
testing/server-tracetesting/features/kafka_test/02_list_kafka_test.yml
testing/server-tracetesting/features/kafka_test/03_run_kafka_test.yml
testing/server-tracetesting/features/kafka_test/04_delete_kafka_test.yml
testing/server-tracetesting/features/kafka_test/_test_suite.yml
testing/server-tracetesting/run.bash

This PR adds Kafka trigger tests for our internal dogfooding tests.
- Update dogfooding script to add Kafka trigger tests

chore(e2e): add kafka tests for on our internal tracetesting/dogfood tests

---

cli/pkg/fileutil/path.go
cli/preprocessor/test.go
testing/cli-e2etest/testscenarios/test/apply_test_test.go
testing/cli-e2etest/testscenarios/test/resources/api-with-comment.proto
testing/cli-e2etest/testscenarios/test/resources/grpc-trigger-embedded-protobuf-with-comment.yaml

This PR fixes https://github.com/kubeshop/tracetest/issues/3090 by improving the relative file detection on gRPC test triggers.
- Improve relative file detection on gRPC test triggers

fix(cli): improving relative file detection for protobuf

---

agent/cmd/start.go
agent/config/config.go
agent/config/config_test.go
agent/initialization/start.go

This PR allows the agent be configured by env variables instead of a file
https://www.loom.com/share/995251a49b784f9c9da9587c95788134

feat(agent): inject env variables in agent configuration

---

cli/actions/configure_action.go
cli/cmd/config.go
cli/cmd/configure_cmd.go
cli/cmd/login_cmd.go
cli/cmd/middleware.go
cli/cmd/resources.go
cli/cmd/root.go
cli/config/config.go
cli/pkg/oauth/oauth.go
cli/pkg/resourcemanager/client.go
cli/utils/api.go

This PR adds the base logic to support CLI cloud login and authentication
- Adds `tracetest login` command
- Implements oauth logic for resources and the API

feature(cli): Adding CLI cloud login and auth logic

---

agent/client/client.go
agent/initialization/start.go
go.work.sum

This prevents the agent from exiting right after connecting to the server

feat: make agent wait until it's disconnected to exit

---

cli/installer/docker_compose.go

This PR fixes the kafka demo when using the installer with docker.
- add missing kafka services to installer
- fixes #3110

fix(cli): add kafka demo services to installer

---

go.work.sum
server/executor/queue.go

This PR sends the test version to the executor queue

feat(queue): send test version to queue

---

server/executor/queue.go

feat(queue): add new fields to job JSON

---

api/tests.yaml
cli/openapi/model_test_run.go
server/executor/runner.go
server/executor/workers/trigger_preparation_worker.go
server/http/mappings/tests.go
server/migrations/32_add_resolved_trigger_to_test_run.down.sql
server/migrations/32_add_resolved_trigger_to_test_run.up.sql
server/openapi/model_test_run.go
server/test/run_repository.go
server/test/test_entities.go
web/src/models/TestRun.model.ts
web/src/types/Generated.types.ts

This PR adds the field `resolved_trigger` to the test run and exposes it thought the API

feat(server): add resolved trigger to test run object

---

agent/cmd/start.go
agent/initialization/start.go
agent/workers/trigger.go
cli/cmd/resource_select_cmd.go
cli/cmd/start_cmd.go
cli/config/configurator.go
cli/config/selector.go
cli/pkg/starter/starter.go
go.work.sum

This PR adds the start command
- Adds the sequence of configure
- Oauth
- Select org/env
- Start agent
https://www.loom.com/share/5d0d2dd361294f89a1e9a63b10d1177b

feat(cli): adding `tracetest start` command

---

api/version.yaml
cli/cmd/config.go
cli/cmd/legacy_test_cmd.go
cli/cmd/resource_select_cmd.go
cli/cmd/resources.go
cli/cmd/root.go
cli/cmd/start_cmd.go
cli/config/config.go
cli/config/configurator.go
cli/openapi/model_version.go
cli/pkg/starter/starter.go
server/http/controller.go
server/openapi/model_version.go
web/src/types/Generated.types.ts

This PR...
-
-
https://www.loom.com/share/650c1c542a734e8c962e9300526f8958

feat(cli): cleanup and dynamic endpoint support

---

web/src/components/AllowButton/AllowButton.tsx
web/src/components/EditTest/EditTest.tsx
web/src/components/EditTestSuite/EditTestSuite.tsx
web/src/components/ResourceCard/ResourceCardActions.tsx
web/src/components/RunActionsMenu/RunActionsMenu.tsx
web/src/components/Settings/Analytics/AnalyticsForm.tsx
web/src/components/Settings/DataStoreForm/DataStoreForm.tsx
web/src/components/Settings/Demo/DemoForm.tsx
web/src/components/Settings/Linter/LinterForm.tsx
web/src/components/Settings/Polling/PollingForm.tsx
web/src/components/Settings/TestRunner/TestRunnerForm.tsx
web/src/components/TestOutputForm/TestOutputForm.tsx
web/src/components/TestSpecForm/TestSpecForm.tsx
web/src/components/TestSuiteRunActionsMenu/TestSuiteRunActionsMenu.tsx
web/src/components/VariableSetSelector/VariableSetSelector.tsx
web/src/components/VariableSetSelector/VariableSetSelectorEntry.tsx
web/src/pages/Home/CreateButton.tsx
web/src/pages/TestSuites/TestSuites.styled.tsx
web/src/pages/VariableSet/VariableSet.styled.tsx
web/src/pages/VariableSet/VariableSetCard.tsx
web/src/pages/VariableSet/VariableSetContent.tsx
web/src/pages/VariableSet/VariableSetList.tsx

This PR adds the UI logic to enable `edit`/`configure` actions in the application.
- enable edit and configure actions
-
https://www.loom.com/share/7a807e4e4f8a49adaefcad2bf137d91e?sid=dee89a54-d94b-46f6-ae43-352123aa028f

feat(frontend): add UI components to allow user actions

---

web/cypress/e2e/TestRunDetail/Outputs.spec.ts

fix(frontend): fixing output specs failure

---

web/src/components/CreateTestPlugins/Rest/steps/RequestDetails/BodyField/BodyFieldContainer.tsx
web/src/components/CustomizationWrapper/CustomizationWrapper.tsx
web/src/constants/Theme.constants.ts
web/src/pages/Settings/Content.tsx
web/src/providers/Customization/Customization.provider.tsx
web/src/providers/Customization/index.ts

This PR adds a `getFlag` value to the `Customization` provider in order to toggle functionality based on the flags.
- getFlag in Customization provider
-

feat(frontend): add flag to toggle the analytics page

---

web/cypress/e2e/TestRunDetail/Outputs.spec.ts
web/src/components/AllowButton/AllowButton.tsx
web/src/components/TestSpecForm/TestSpecForm.tsx

fix(cypress): fixing AllowButton detachment from DOM

---

web/src/utils/Common.ts

This PR fixes a FE bug with the `Url Docker Suggestion` component. It was causing the web app to stop responding when using some specific URLs in your test definition.
- remove url regex validation
- fixes #2968

fix(frontend): fix method to parse url

---

web/src/services/CliCommand.service.ts

This PR fixes the resource type in the automate command service.
- fix resource type in automate command (from `tests` to `test`, from `testsuites` to `testsuite`)
-

fix(frontend): fix resource type in automate command

---

server/executor/trigger_executer_worker.go
server/executor/trigger_result_processor_worker.go
server/test/trigger/trigger.go

This PR fixes a behavior removed in #3120

fix: alert about localhost when trigger is running inside container

---

.github/workflows/pull-request.yaml

This PR aims to split the CLI e2e into 8 containers to speed up the CI pipeline.
- Updated test pipeline

fix: adding github action parallel runs to cli e2e tests

---

examples/observability-driven-development-go-tracetest/bookstore/part1/tracetest/docker-compose.yaml
examples/observability-driven-development-go-tracetest/bookstore/part2.1/tracetest/docker-compose.yaml
examples/observability-driven-development-go-tracetest/bookstore/part2.2/tracetest/docker-compose.yaml
examples/observability-driven-development-go-tracetest/bookstore/part3.1/tracetest/docker-compose.yaml
examples/observability-driven-development-go-tracetest/bookstore/part3.2/tracetest/docker-compose.yaml
examples/observability-to-the-rescue/docker-compose.yaml
examples/quick-start-go-and-kafka/docker-compose.yaml
examples/quick-start-jaeger-nodejs/tracetest/docker-compose.yaml
examples/quick-start-net-core/docker-compose.yaml
examples/quick-start-tail-sampling/docker-compose.yaml
examples/tracetest-jaeger/docker-compose.yml
examples/tracetest-k6/docker-compose.yml
examples/tracetest-otel-demo/docker-compose.yaml
examples/tracetest-provisioning-env/docker-compose.yml
examples/tracetesting-kubernetes/kubetracing/docker-compose.yaml
local-config/jaeger/docker-compose.yml
server/go.mod
server/tracedb/jaegerdb.go
testing/cli-e2etest/environment/jaeger/server-setup/docker-compose-no-api.yaml
testing/load/infra/docker-compose.yaml

This PR fixes the error reported by @danielbdias in #3148 
-
-

fix: jaeger datastore

---

web/src/gateways/WebSocket.gateway.ts
web/src/models/TestSuiteRun.model.ts
web/src/providers/TestRun/TestRun.provider.tsx
web/src/providers/TestSuiteRun/TestSuite.provider.tsx
web/src/redux/apis/Tracetest/endpoints/Setting.endpoint.ts
web/src/redux/apis/Tracetest/endpoints/TestRun.endpoint.ts
web/src/redux/apis/Tracetest/endpoints/TestSuiteRun.endpoint.ts

This PR adds a FE polling mechanism and disables the websocket connection.
- FE polling
- disable websocket
-

feat: add fe polling and disable websocket

---

server/app/app.go
server/app/test_pipeline.go
server/config/server.go
server/config/server_test.go
server/executor/linter_runner.go
server/executor/tracepollerworker/fetcher_worker.go
server/executor/trigger_executer_worker.go

This PR adds options to enable/disable trace fetch and trigger execution.
- Added option for test pipeline

feat(server): add options for test pipeline

---

docs/src/components/ExamplesTutorialsOverview/index.tsx

This PR fixes an edge case breaking the overview links.
-
-

docs(recipes): fix links

---

cli/config/config.go
cli/config/configurator.go
cli/pkg/oauth/oauth.go

This PR fixes the cli oauth flow by adding a `default path` and fixing the `Access-Control-Allow-Origin` header.
- add `default path` and 
- fix `Access-Control-Allow-Origin` header
-

fix(cli): fix oauth flow

---

server/http/controller.go

This PR fixes a lock problem with the notify logic, the notify function uses mutex that locks the step, where the listener is executed, but having the unsubscribe in the same function will lock it again thus the process hangs.

fix: Test Connection Lock

---

agent/collector/collector.go
agent/collector/collector_test.go
agent/config/config.go
agent/config/config_test.go
agent/initialization/start.go
server/otlp/grpc_server.go
server/otlp/http_server.go

This PR makes the agent always start the collector mode. This is important due to OTLP datastores.

feat(agent): start collector at startup

---

agent/collector/cache.go
agent/collector/collector.go
agent/collector/collector_test.go
agent/collector/ingester.go
agent/initialization/start.go
agent/workers/trigger.go
agent/workers/trigger_test.go
cli/pkg/starter/starter.go

This PR makes the agent's internal collector keep track of spans that are generated by tests triggered by the agent.

feat(agent): keep track of spans that were generated by tests

---

agent/initialization/start.go
agent/workers/poller.go
agent/workers/poller/inmemory_datastore.go
agent/workers/poller_test.go

This PR makes the agent use an in-memory datastore that is populated by the collector when receiving traces in the OTLP endpoint.

feat(agent): in-memory datastore to support otlp datastores

---

agent/collector/collector.go
agent/collector/collector_test.go
agent/collector/ingester.go
agent/config/config.go
agent/example/collector.config.yaml
agent/initialization/start.go
cli/pkg/starter/starter.go
server/app/app.go
server/config/server.go

fix(agent): updating support for otlp datastore

---

agent/workers/poller.go
agent/workers/poller/inmemory_datastore.go

fix(agent): fixing connection error check

---

local-config/jaeger/docker-compose.yml
server/test/test_repository.go
server/testsuite/testsuite_run_repository.go

fix(server): fix tenant id query concatenation

---

server/analytics/analytics.go
server/app/app.go
server/executor/assertion_runner.go
server/executor/linter_runner.go
server/executor/trace_poller.go
server/executor/tracepollerworker/evaluator_worker.go
server/executor/trigger_result_processor_worker.go

This PR adds support for the `x-event-properties` header in order to enhance the analytics middleware. It also adds the `tenant_id` (from context) in the `test_run_finished` event.
- support for `x-event-properties` header
- add `tenant_id` in `test_run_finished` event
-

feat(server): support event properties header

---

web/public/index.html
web/src/services/Analytics/Analytics.service.ts
web/src/types/Common.types.ts
web/src/utils/Env.ts

This PR adds the posthog key as a environment variable
-
-

fix(frontend): add posthog key as environment variable

---

docker-compose.yaml
server/testsuite/testsuite_repository.go
testing/cli-e2etest/environment/jaeger/server-setup/docker-compose-no-api.yaml
testing/load/infra/docker-compose.yaml

This PR updates our Dog food and CLI e2e tests to run with Postgres 15.2, to validate if there are more queries with malformation.
- Updated dogfood tests to use Postgres 15.2
- Updated CLI e2e tests to use Postgres 15.2
- Order by Concatenation bug on TestSuite queries

chore: update tests to use a new pg version

---

server/analytics/analytics.go
server/analytics/analytics_test.go
server/analytics/segment.go
server/app/app.go
server/config/server.go

This PR updates the server config to allow analytics keys to override the ones provided during compilation.
- Adds new analytics environment flags
- Overrides feature flags from the app config

fix(server): allow analytics cfg override

---

cli/cmd/start_cmd.go

This PR makes the `tracetest start` command skip the server version validation.
##Why?
We gonna need to run `tracetest start --api-key <key>` and it will fail every time we update the cloud server, forcing all users to upgrade their agents

fix: skip server version validation

---

.github/workflows/pull-request.yaml
.github/workflows/release-candidate.yml
.github/workflows/release-version.yml
agent/Dockerfile

This PR adds the dockerfile for the agent

feat(agent): docker image

---

.github/workflows/release-version.yml
k8s/agent/deploy-agent.sh
k8s/agent/deploy-agent.yaml

This PR adds the k8s manifest to deploy the agent in a cluster

feat(agent): k8s deployment script

---

agent/cmd/start.go
agent/initialization/session.go
agent/initialization/start.go
cli/cmd/start_cmd.go
cli/pkg/starter/starter.go

fix: improve agent startup

---

cli/cmd/config.go
cli/config/version.go

This PR fixes the version command to point it to the cloud FE version file
- Updates endpoint for the version function
- https://github.com/kubeshop/tracetest-cloud/issues/141

fix(CLI): Fixing CLI version command

---

web/src/components/Empty/Empty.styled.ts
web/src/components/Empty/Empty.tsx
web/src/constants/Common.constants.ts
web/src/gateways/TestRun.gateway.ts
web/src/pages/Home/CreateButton.tsx
web/src/pages/Home/Home.styled.tsx
web/src/pages/Home/TestsList.tsx
web/src/pages/TestSuites/TestSuites.styled.tsx
web/src/pages/TestSuites/TestSuitesList.tsx
web/src/pages/VariableSet/VariableSet.styled.tsx
web/src/pages/VariableSet/VariableSetList.tsx

This PR improves the `Test` and `TestSuite` empty components.
- Test and TestSuite empty components
-

feat(frontend): improve empty test and testsuite component

---

cli/config/configurator.go
web/src/pages/Home/CreateButton.tsx
web/src/pages/Home/TestsList.tsx
web/src/pages/TestSuites/TestSuitesList.tsx

This PR fixes an issue when switching between named and local mode where the agent API key wasn't used as the primary auth method.
- Moves the agent API key check before the jwt
- https://github.com/kubeshop/tracetest-cloud/issues/148

fix(cli): Check if Agent API flag exists first

---

web/src/components/Settings/DataStoreForm/DataStoreForm.styled.ts
web/src/components/Settings/DataStoreForm/DataStoreSelectionInput.tsx

This PR updates the datastore settings styles to look better when the screen is too small
- Switches container to use antd tabs
- Updates styles and compoents
- Moves button section to be visible all of the time sticked to the bottom
- [Make footer with buttons visible#144](https://github.com/kubeshop/tracetest-cloud/issues/144)
https://www.loom.com/share/56e95e43bae6452489375136e8fa34bf

fix(web): datastore settings styles

---

server/app/app.go
server/app/test_pipeline.go
server/app/test_suite_pipeline.go
server/executor/queue.go
server/executor/test_suite_runner_test.go
server/pkg/pipeline/postgres_driver.go
server/pkg/pipeline/queue.go

This PR adds metrics about the queues in our test pipeline
https://www.loom.com/share/a316ac8b97a6462a9513fafba8d0101d

feat: report metrics about the test pipeline queues

---

server/app/app.go
server/telemetry/metrics.go
server/test/run_repository.go

This PR adds metrics on the test run cache, it keeps track of two things:
* Number of cache requests (and register hits/misses)
* Histogram of cache latency
https://www.loom.com/share/4adc268b91a045409dbe216bb0c3a006

feat: cache hit metrics

---

server/app/test_pipeline.go
server/executor/worker_metric_middleware.go
server/pkg/pipeline/pipeline.go

This PR adds metrics to the pipeline steps containing data about the test run, and test id.
https://www.loom.com/share/83fb22b1d66c427197b1955f88148995

feat: metrics of pipeline steps

---

web/src/components/Settings/DataStore/DataStore.styled.ts
web/src/components/Settings/DataStoreForm/DataStoreForm.styled.ts

This PR fixes the settings styles to not be pushed down based on the different banners that can appear on screen
- Updates default height and spacing

fix: Settings styles

---

agent/client/client.go
agent/client/workflow_listen_for_ds_connection_tests.go
agent/client/workflow_listen_for_poll_requests.go
agent/client/workflow_listen_for_trigger_requests.go
agent/client/workflow_shutdown.go
cli/config/selector.go

This PR fixes the problem when trying to stop the agent from the CLI option
- Adds missing channel creation
- Validates if the error is context stopped to not yield the errors to the console
- https://github.com/kubeshop/tracetest-cloud/issues/147
https://www.loom.com/share/d0bf6ba20a074b16811e5524b20bb36f

fix(agent): Graceful Stop

---

cli/pkg/oauth/oauth.go

This PR updates the OAuth behavior to use redirects instead of AJAX request, the initial request should contain a return URL which will point to the UI
- Adds redirect behavior
- Removes JSON response
- 
- https://github.com/kubeshop/tracetest/issues/3223

fix(cli): OAuth process

---

docs/docs/getting-started/open.mdx

The repository is quite large and downloading the whole git history wouldn't be helpful apart from increasing the download time. This fix helps increase the speed of the clone.

Update git clone

---

cli/installer/docker_compose.go

This PR makes the installer check for both `docker compose` and `docker-compose` (dash vs space) when doing system checks. On install success, it shows the correct command in the message, depending on the system check
- check for `docker-compose` on installer
- https://github.com/kubeshop/tracetest/issues/3229

fix(cli): check for docker-compose on installer

---

agent/proto/orchestrator.proto
agent/workers/trigger.go
agent/workers/trigger/kafka.go

This PR updates Tracetest Agent to support Kafka triggers.
- Updated agent to have a Kafka trigger

feat: adding support for Kafka on Agent

---

web/package-lock.json
web/package.json
web/src/App.tsx
web/src/components/CaptureWrapper/CaptureWrapper.tsx
web/src/components/CaptureWrapper/Content.tsx
web/src/components/CaptureWrapper/index.ts
web/src/components/WithAnalytics/WithAnalytics.tsx
web/src/providers/Capture/Capture.provider.tsx
web/src/providers/Capture/index.ts
web/src/providers/SettingsValues/SettingsValues.provider.tsx
web/src/services/Analytics/Analytics.service.ts

This PR introduces a refactor to our posthog implementation to support dynamic `load` and `view` methods. It also updates the package to latest.
- refactor posthog
- update posthog-js
-

feat: posthog improvements

---

web/src/components/CustomizationWrapper/CustomizationWrapper.tsx
web/src/pages/Settings/Content.tsx
web/src/providers/Customization/Customization.provider.tsx

This PR removes the unneeded `IsAnalyticsPageEnabled` flag.
- remove `IsAnalyticsPageEnabled` flag
-

chore(frontend): remove unneeded flag

---

.goreleaser.demo.yaml
.goreleaser.dev.yaml
.goreleaser.rc.yaml
.goreleaser.yaml
server/Makefile
server/app/app.go
server/executor/worker_metric_middleware.go
server/http/middleware/metrics.go
server/pkg/pipeline/queue.go
server/telemetry/resource.go
server/telemetry/tracer.go
server/test/run_repository.go
server/version/version.go

This PR fixes all counter metrics. It uses a histogram instead of the `metric.Counter` which is accumulative over time
-
-

fix: use histogram to keep track of request counts

---

agent/workers/poller.go
agent/workers/trigger.go
cli/cmd/start_cmd.go
cli/config/configurator.go
cli/config/selector.go
cli/pkg/starter/starter.go
cli/ui/ui.go

This PR updates a couple of things regarding the `tracetest start` command to show better messaging and remove some of the things we don't need
- Adds start message to inform the user what we are trying to accomplish
- Removes log messages from agent workers
- Fixes stop agent logic (again 🥴 )
- [Change tracetest start CLI to add initial instructions and prompt for launching authentication#192](https://github.com/kubeshop/tracetest-cloud/issues/192)
- https://github.com/kubeshop/tracetest-cloud/issues/136
https://www.loom.com/share/8bb1e837317c4641ac2795ae47e0ff9c

chore(cli): UX Improvements

---

server/traces/caching.go

This PR adds mutex locks to prevent a concurrent map read/write on spans cache.
I hit this issue a few times but it's hard to reproduce

fix(server): panic on concurrent read write

---

agent/initialization/start.go
cli/pkg/starter/starter.go

This PR updates the error message when the ports for the OTLP server are not available to be more descriptive instead of just the default error
- Updates error message
- Adds custom error
- https://github.com/kubeshop/tracetest-cloud/issues/116
https://www.loom.com/share/4660f8bbbb0441e492cba69b73aa7e05

chore(cli): Adding otlp server error handling

---

server/test/trigger/grpc.go

This PR fixes the gRPC mapping for metadata headers
- #3258

fix: json mapping for gRPC metadata headers

---

cli/cmd/start_cmd.go
cli/config/config.go
cli/config/configurator.go
cli/pkg/oauth/oauth.go
cli/pkg/starter/starter.go

This PR adds token support for the `tracetest start` command
- Adds new env variable to support the TOKEN
- Adds config to replace jwt and token from the given flags
https://www.loom.com/share/a1405279a47a429cae4fe0bb8df25233

feat(cli): Token Support

---

server/app/app.go
server/app/ds_test_connection_pipeline.go
server/testconnection/pipeline.go

This PR fixes a problem with the missing meter from the data store pipeline used for the queues
- Adds meter instance to the data store connection test pipeline
https://www.loom.com/share/e1a384635b8b43019ded00ab47e6861d

fix(server): Datastore test pipeline

---

docs/docs/concepts/agent.mdx
docs/docs/configuration/agent.mdx
docs/docs/getting-started/installation.mdx
docs/sidebars.js

This PR adds a better explanation about Tracetest Agent, including a concepts page.
-
-

docs(agent): add more explanations about tracetest agent

---

agent/client/connector.go

This PR updates the agent TLS settings so it can correctly work with port 443. Since this port uses actual TLS, the client needs to be correctly setup.
The TLS settings for port 443 and 8091 are mutually exclusive, so this PR makes sure the agent can work with both ports

feat(agent): add support for port 443

---

.github/workflows/release-version.yml
.goreleaser.demo.yaml
.goreleaser.dev.yaml
.goreleaser.rc.yaml
.goreleaser.yaml
Dockerfile.agent
Makefile
cli/go.mod
cli/go.sum

This PR makes the agent docker image mutliarch. For simplicity, it uses the same approach as the main tracetest image. Meaning the building happens through goreleaser. Because of how goreleaser works, it was not practical to keep the agent image "inheriting" from the main tracetest image, instead the easiest way was to have a dockerfile that simply imports the already built cli binary and set an entrypoint.

chore(agent): make docker image multiarch

---

server/http/middleware/metrics.go

This PR achieves two things:
1. Make sure `GET /` endpoint calls are collected with the correct `http.route`. Today it's considered empty
2. Use `attributes.Set` for recording the metric attributes (it's recommended by OpenTelemetry due to performance)

fix: http metric middleware improvements

---

examples/tracetest-grafana-tempo-pokeshop/README.md
examples/tracetest-grafana-tempo-pokeshop/docker-compose.yml
examples/tracetest-grafana-tempo-pokeshop/tests/test.yaml
examples/tracetest-grafana-tempo-pokeshop/tracetest.config.yaml

This PR updates the grafana pokeshop sample.
-
-

examples(grafana): update pokeshop grafana sample

---

cli/config/version.go
go.mod
go.sum

This PR changes how the CLI checks for version. Instead of an exact mach, it does a semver comparision for [major].[minor], alowing any patch and prereleases to be considered valid.

feat: use semver for version check

---

docs/src/components/CoreGettingStartedGuide/index.tsx
docs/src/components/GettingStartedGuide/index.tsx
docs/src/components/WelcomeGuide/index.tsx

This PR fixes flaky links in the cards on docs landing pages.
-
-

docs(hotfix): fix flaky links

---

cli/installer/docker_compose.go

This PR fixes the docker compose installer. The issue was a libray update that changed the project name to be required, and since we're not using an actual file, the project name cannot be inferred, causing an error.
The fix is to manually set a project name.

fix(cli): update docker compose library call

---

agent/client/connector.go
agent/initialization/start.go

This PR configures the gRPC client retry strategy to allow better handling of connection issues. In the case of connection interruption between the server and the agent for whatever reason (server restarted, networking issues, etc), the client will retry the operation using an exponential backoff strategy. With the currently configured values, this is the retry timeline:
```
Attempt 1 at 0.1 seconds, Backoff Time: 0.1 seconds
Attempt 2 at 0.3 seconds, Backoff Time: 0.2 seconds
Attempt 3 at 0.7 seconds, Backoff Time: 0.4 seconds
Attempt 4 at 1.5 seconds, Backoff Time: 0.8 seconds
Attempt 5 at 3.1 seconds, Backoff Time: 1.6 seconds
Attempt 6 at 6.3 seconds, Backoff Time: 3.2 seconds
Attempt 7 at 11.3 seconds, Backoff Time: 5.0 seconds
Attempt 8 at 16.3 seconds, Backoff Time: 5.0 seconds …
```

feat(agent): configure retry strategy

---

web/src/components/RunDetailTest/RunDetailTest.styled.ts
web/src/components/RunDetailTest/TestPanel.tsx

This PR fixes a broken behavior in the test specs list when trying to open a spec detail.
- fix scroll and styles
-

fix(frontend): fix scroll behavior in test specs list

---

web/src/services/Triggers/Grpc.service.ts

This PR fixes the FE parsing of the protobuf file (GRPC trigger) to get the list of methods.
- fix proto file parsing
- fixes https://github.com/kubeshop/tracetest/issues/3278

fix(frontend): fix proto file methods parsing

---

agent/workers/trigger/http.go
agent/workers/trigger/instrument.go

This PR fixes the propagation error that we had in the agent when running grpc and kafka triggers

fix(agent): trace propagation via agent

---

docs/docs/cli/creating-tests.mdx
go.mod
go.sum
server/expression/executor_test.go
server/expression/functions/function.go
server/expression/functions/function_registry.go
server/expression/functions/function_registry_test.go
server/expression/functions/functions.go

This PR adds support for two new generator functions: `date()` and `dateTime()`.
This was asked by a user in our [discord channel](https://discordapp.com/channels/884464549347074049/963470167327772703/1169196012120834130)
```go
// returns the date in the time.DateOnly format (YYYY-MM-DD)
// if format is provided, it will be formatted based on it.
date(format optional<string>)
// returns the date and time in the time.RFC3339 format (2006-01-02T15:04:05Z07:00)
// if format is provided, it will be formatted based on it.
dateTime(format optional<string>)
```
```
date() : 2023-11-01
date("MM-DD-YYYY") : 11-01-2023
date("DD/MM/YYYY") : 01/11/2023
dateTime() : 2023-11-01T12:38:12Z03:00
dateTime("hh:mm:ss") : 12:38:12
```

feat: date generator functions

---

go.mod
go.sum
server/app/app.go
server/executor/test_suite_runner_test.go
server/http/mappings/tests.go
server/test/run_repository.go
server/test/test_repository_test.go
server/testdb/test_run_event_test.go
server/testsuite/testsuite_repository_test.go
server/testsuite/testsuite_run_repository_test.go
server/traces/span_entitiess.go

This PR fixes some issues when running tests.
1. The test run cache was causing issues, and is no longer required, so it's removed. 
2. When mapping trigger results from openapi to internal models, an empty GRPC result was becoming an empty object instead of nil in the internal model, creating some confusion when handling results later
3. The query to get the test suite run steps was using an incorrect sort field, causing the list to be in an unexpected order.
-
-

fix(server): fix issues when running tests

---

web/src/components/Router/Router.tsx
web/src/components/TriggerTypeModal/TriggerTypeCard.tsx
web/src/components/TriggerTypeModal/TriggerTypeModal.styled.ts
web/src/components/TriggerTypeModal/TriggerTypeModal.tsx
web/src/components/TriggerTypeModal/index.ts
web/src/pages/Home/TestsList.tsx

This PR adds the Trigger type selection modal that should be part of the new Test creation flow.
- Trigger type modal
- fixes https://github.com/kubeshop/tracetest-cloud/issues/253

feat(frontend): add trigger type modal

---

web/src/components/Settings/DataStoreForm/DataStoreSelectionInput.tsx

This PR fixes a bug when switching the data store selection by clicking the tab by moving the event handling to the main tab component.
- Moves the event handling from click to on change
- https://github.com/kubeshop/tracetest-cloud-frontend/issues/131
https://www.loom.com/share/d2d82ec716874d769e87888f9d46409e

fix(UI): Fixing DataStore selection bug

---

server/executor/trigger_result_processor_worker.go
server/test/trigger/trigger_json.go

This PR makes Tracetest handle trigger result errors correctly.

fix: trigger result error handling

---

web/src/constants/Demo.constants.ts

This PR converts zipCode as a string for HTTP tests on OTel Demo. Without this, the OTel Demo can throw an HTTP 500 error.
- Updated OTel Demo template on UI

fix: convert zipCode as string for HTTP tests on OTel Demo

---

server/migrations/34_add_composite_pkey.down.sql
server/migrations/34_add_composite_pkey.up.sql
server/test/run_repository.go
server/test/test_repository.go
server/testsuite/testsuite_repository.go
server/testsuite/testsuite_run_repository.go
server/variableset/variableset_repository.go

This PR fixes the problem when trying to use the same ID for tests, test suites, and variable sets from a different tenant ID perspective
- Adds migrations to use composed primary keys for the missing tables
- Fixes queries around listing and getting tests/test suites by adding tenant id
- https://github.com/kubeshop/tracetest-cloud/issues/259
https://www.loom.com/share/bd1cbd2dc57e46cfb50c710a8ac00119

fix(backend): Adding Composed Primary Keys

---

examples/tracetest-agent-with-pokeshop/README.md
examples/tracetest-agent-with-pokeshop/docker-compose.yaml

This PR adds an example of Pokeshop and Tracetest Agent running together.
- Added `examples/tracetest-agent-with-pokeshop/\`

chore: add example with pokeshop and tracetest agent

---

agent/client/client.go

This PR adds the "server closed" error as a connection error for the agent to reconnect to the server.

fix: add "server closed" as connection error

---

agent/workers/datastores/awsxray.go
agent/workers/datastores/azureappinsights.go
agent/workers/datastores/elasticsearchdb.go
agent/workers/datastores/opensearchdb.go
agent/workers/datastores/signalfxdb.go
agent/workers/poller.go
server/assertions/selectors/selector_test.go
server/executor/assetion_executor_test.go
server/executor/poller_executor_test.go
server/executor/selector_based_poller_executor_test.go
server/expression/benchmark_test.go
server/expression/executor_test.go
server/http/controller_test.go
server/http/mappings/traces.go
server/linter/linter_test.go
server/linter/plugins/plugins_entities_test.go
server/linter/rules/ensure_attribute_naming_rule.go
server/linter/rules/not_empty_attribute_rule.go
server/linter/rules/required_attribute_rule_test.go
server/linter/rules/required_attributes.go
server/tracedb/awsxray.go
server/tracedb/azureappinsights.go
server/tracedb/elasticsearchdb.go
server/tracedb/opensearchdb.go
server/tracedb/signalfxdb.go
server/traces/otel_converter.go
server/traces/otel_http_converter.go
server/traces/span_entitiess.go
server/traces/trace_entities.go
server/traces/traces_test.go

This PR fixes the issue that is caused when multiple threads try to change one span's attribute. We have seem the server panicking because of it

fix: add mutex to span attributes

---

agent/client/client.go
agent/client/connector.go
agent/client/options.go
agent/collector/cache.go
agent/collector/collector.go
agent/collector/collector_test.go
agent/collector/ingester.go
agent/initialization/start.go
agent/workers/poller.go
agent/workers/poller_test.go
agent/workers/testconnnection.go
agent/workers/trigger.go
server/otlp/grpc_server.go
server/otlp/http_server.go

add logging

---

web/src/components/DashboardWrapper/DashboardWrapper.tsx
web/src/components/RunDetailAutomateMethods/methods/DeepLink/hooks/useDeepLink.ts
web/src/providers/Dashboard/Dashboard.provider.tsx
web/src/services/DeepLink.service.ts

This PR makes the dashboard url to be customizable
- Updates dashboard provider to include dashboard URL

fix: Deeplink Base Url

---

web/src/constants/Test.constants.ts

This PR switches the default sort by to use `Last Run` as default
- Updates sort options order 
- https://github.com/kubeshop/tracetest-cloud-frontend/issues/137

fix: Default Sort By

---

web/src/providers/Test/hooks/useTestCrud.ts

This PR fixes the problem of sending the users to the wrong mode when the match doesn't include the mode
- Change the use of  match to params
- https://github.com/kubeshop/tracetest-cloud-frontend/issues/140

fix: Run Test Mode

---

server/traces/trace_entities.go
server/traces/traces_test.go

This PR tries to fix the issue where a trace contains multiple `Temporary Tracetest Root Span` nodes instead of just one.

fix(server): make sure only one temporary root span is present in trace

---

web/src/components/CreateTest/CreateTest.styled.ts
web/src/components/Fields/SkipTraceCollection/SkipTraceCollection.tsx
web/src/components/ImportModal/ImportModal.styled.ts
web/src/components/ImportModal/ImportModal.tsx
web/src/components/ImportModal/Tip.tsx
web/src/components/RunDetailLayout/HeaderLeft.tsx
web/src/components/RunDetailLayout/RunDetailLayout.styled.ts
web/src/components/TestPlugins/Imports/Curl/Curl.tsx
web/src/components/TestPlugins/Imports/Postman/fields/CollectionFileField.tsx
web/src/components/TestPlugins/Imports/Postman/fields/SelectTestFromCollection.tsx
web/src/pages/CreateTest/HeaderLeft.tsx
web/src/pages/CreateTest/HeaderRight.tsx

This PR introduces minor fixes for the test creation flow epic.
- add variable set selector
- fix header height to match the run detail layout
- improve copy
-

fix(frontend): add variable set selector

---

web/src/components/Settings/DataStorePlugin/forms/Agent/Ingestor.tsx
web/src/constants/Common.constants.ts

This PR adds a fix to the ingestor docs URL so it has something to open while we work on the actual explanation
- Adds ingestor endpoint
- https://github.com/kubeshop/tracetest-cloud-frontend/issues/133
https://www.loom.com/share/13afc4ce5b1a4892bf82fcdb06173d5f

fix: Adding ingestor docs link

---

server/traces/trace_entities.go
server/traces/traces_test.go

This PR fixes the issue that the `Temporary Tracetest root span` is not removed after all missing spans are added to the trace.
-
-

fix: temporary root issue when parent is missing

---

web/src/components/Settings/common/Settings.styled.ts
web/src/constants/CollectorConfig.constants.ts

This PR fixes minor UI styles and issues.
- fix switch position in settings page
- fix collector config example for Otel 
-

fix(frontend): fix minor ui styles

---

web/src/components/SkipTraceCollectionInfo/SkipTraceCollectionInfo.tsx
web/src/components/TestPlugins/Forms/Grpc/Grpc.tsx
web/src/components/TestPlugins/Forms/Kafka/Kafka.tsx
web/src/components/TestPlugins/Forms/Rest/Rest.tsx
web/src/hooks/useQueryTabs.ts

This PR fixes a UI issue caused by a conflict between the trigger form tabs and the response section tabs.
- update query param name for trigger form tabs
-

fix(frontend): fix conflict between trigger and response tabs

---

api/tests.yaml
cli/runner/orchestrator.go
server/executor/test_suite_runner.go
server/testsuite/testsuite_run_entities.go
web/src/components/RunCard/TestRunCard.tsx
web/src/components/RunCard/TestSuiteRunCard.tsx
web/src/components/RunDetailLayout/HeaderLeft.tsx
web/src/components/RunDetailTriggerResponse/ResponseMetadata.tsx
web/src/components/RunDetailTriggerResponse/RunDetailTriggerResponse.tsx
web/src/components/VariableSet/VariableSetForm.tsx
web/src/models/RunMetadata.model.ts
web/src/models/TestRun.model.ts
web/src/models/TestSuiteRun.model.ts
web/src/redux/apis/Tracetest/endpoints/TestRun.endpoint.ts
web/src/redux/apis/Tracetest/endpoints/TestSuiteRun.endpoint.ts

This PR adds the run source information for both test and test suite runs
- Adds source as part of metadata
- Adds new metadata model
- Updates metadata logic to add more values from the test suite runner
- Adds metadata tab for test runs
- https://github.com/kubeshop/tracetest-cloud-frontend/issues/139
- https://github.com/kubeshop/tracetest-cloud-frontend/issues/130
https://www.loom.com/share/ec83bf4c312e45e3a5029352bbcd7164

feat: Run Source

---

examples/tracetest-agent/pokeshop/docker-compose.yaml

Docker on Linux doesn't understand `host.docker.internal` automatically. We need to add it as an extra host using `extra_hosts`. This was caught by @mrasu in the issue #3393.
-
-

fix: host network configuration on linux

---

web/src/components/CodeBlock/CodeBlock.tsx
web/src/components/RunDetailTriggerResponse/ResponseBody.tsx

This PR fixes a performance issue related to the `react-syntax-highlighter` package used to render the response body of a test. We were having issues when dealing with `html` types because the package does not support html as a language (see available languages [here](https://github.com/react-syntax-highlighter/react-syntax-highlighter/blob/HEAD/AVAILABLE_LANGUAGES_HLJS.MD)). Also, there are some performance problems described [here](https://github.com/react-syntax-highlighter/react-syntax-highlighter/issues/302) that we are fixing by using a memoization approach.
- fix html language type
- memoize syntax highlighter component
- #3397

fix(frontend): improve syntax highlighter performance

---

web/src/components/ConfirmationModal/ConfirmationModal.tsx
web/src/components/ResourceCard/ResourceCardActions.tsx
web/src/components/ResourceCard/TestCard.tsx
web/src/components/ResourceCard/TestSuiteCard.tsx
web/src/components/ResourceCard/__tests__/ResourceCardActions.test.tsx
web/src/components/ResourceCard/__tests__/TestCard.test.tsx
web/src/components/TestHeader/TestHeader.tsx
web/src/components/TestHeader/__tests__/TestHeader.test.tsx
web/src/hooks/useKeyEvent.ts
web/src/models/TestOutput.model.ts
web/src/pages/Home/TestsList.tsx
web/src/pages/Test/Content.tsx
web/src/pages/TestSuite/Content.tsx
web/src/pages/TestSuites/TestSuitesList.tsx
web/src/providers/CreateTest/CreateTest.provider.tsx
web/src/providers/CreateTestSuite/CreateTestSuite.provider.tsx
web/src/providers/Test/hooks/useTestCrud.ts
web/src/providers/TestSuite/hooks/useTestSuiteCrud.ts
web/src/services/Test.service.ts
web/src/services/TestSuite.service.ts
web/src/types/TestSuite.types.ts

This PR adds the duplicate action for tests and test suites, it triggers the confirmation modal before doing the actual duplication
- Adds duplication logic for tests and test suites
- Adds listeners and confirmation modals for duplications
- https://github.com/kubeshop/tracetest/issues/3062
https://www.loom.com/share/6594163f31b24f0388d9d1a21669fc4c

feat: Duplicate

---

web/src/components/ResizablePanels/Splitter.tsx
web/src/components/RunDetailTest/RunDetailTest.styled.ts
web/src/components/TestOutputForm/TestOutputForm.styled.ts
web/src/components/TestSpecForm/TestSpecForm.styled.ts

This PR fixes styles for the test specs and test outputs container. It also adds a fix for the Attribute tooltip to avoid showing it in the trigger or automate tab.
- container styles
- set pop up container for attribute tooltip
- fixes https://github.com/kubeshop/tracetest-cloud-frontend/issues/146
- fixes https://github.com/kubeshop/tracetest-cloud-frontend/issues/89

fix(frontend): fix test specs container and attribute tooltip

---

web/src/pages/TestSuite/Content.tsx

fix: Wrong Var Name

---

server/linter/rules/ensure_span_naming_rule.go
server/traces/span_entitiess.go

This PR fixes a bug with the `span-naming` and `empty-attributes` rules in the trace analyzer. We were throwing analyzer errors about span naming problems for default `http` spans, and empty `tracetest.span.status_description` attributes.
- add default validation for `http` spans
- include the `tracetest.span.status_description` attribute if it has a value
- fixes https://github.com/kubeshop/tracetest-cloud/issues/265
https://www.loom.com/share/94b6587e7b584f228b9fa6477af4217f?sid=55b817a3-28f5-48b6-86e2-024d96246b7e

fix(server): fix span-naming and empty-attributes rules

---

web/src/services/VariableSet.service.ts

This PR fixes a bug with the description field of a `VariableSet`. It's not required anymore but it was still part of the validation service.
- remove description as required for VariableSet
-

fix(frontend): remove variable set description validation

---

.github/workflows/scheduled-jobs.yml
testing/synthetic-monitoring/otel-demo/01-see-ads.yaml
testing/synthetic-monitoring/otel-demo/02-get-product-recommendation.yaml
testing/synthetic-monitoring/otel-demo/03-browse-product.yaml
testing/synthetic-monitoring/otel-demo/04-add-product-to-cart.yaml
testing/synthetic-monitoring/otel-demo/05-view-cart.yaml
testing/synthetic-monitoring/otel-demo/06-checking-out-cart.yaml
testing/synthetic-monitoring/otel-demo/_testsuite.yaml
testing/synthetic-monitoring/otel-demo/_variableset.yaml
testing/synthetic-monitoring/pokeshop/01-add-pokemon-with-api.yaml
testing/synthetic-monitoring/pokeshop/02-import-pokemon-with-queue.yaml
testing/synthetic-monitoring/pokeshop/03-import-pokemon-with-stream.yaml
testing/synthetic-monitoring/pokeshop/04-list-pokemons.yaml
testing/synthetic-monitoring/pokeshop/_testsuite.yaml

This PR adds synthetic monitoring tests to Tracetest, allowing us to run tests for our demo envs on https://docs.tracetest.io/getting-started/try-live-demos/ 
- Added `testing/synthetic-monitoring` folder and Github action to trigger it.

chore: adding synthetic monitoring tests

---

server/tracedb/azureappinsights.go
server/tracedb/elasticsearchdb.go
server/tracedb/signalfxdb.go
server/tracedb/tempodb.go
server/traces/otel_converter.go
server/traces/span_entitiess.go
server/traces/traces_test.go

This PR solves some of the possible panics we might get when running tracetest. I used [nilaway](https://github.com/uber-go/nilaway) to detect them. I was going to integrate it on our pipeline, however, it still shows some false positive cases of panics, so I decided to postpone this action.
-
-

fix: remove some possible panics

---

web/src/components/Inputs/TestSelection/TestItem.tsx
web/src/components/Inputs/TestSelection/TestsSelection.styled.ts
web/src/components/RunDetailTrigger/RunDetailTrigger.tsx
web/src/components/SkipTraceCollectionInfo/SkipTraceCollectionInfo.tsx

This PR fixes a couple of minor UI issues:
- skip trace collection setting was not updated in the trigger section
- test suite UI was breaking the layout for larger test suites names 
- link to trigger settings tab was not using the proper Link component
- fixes https://github.com/kubeshop/tracetest-cloud/issues/294
- fixes https://github.com/kubeshop/tracetest/issues/3065
https://www.loom.com/share/a084800f1deb434390f04e64f646b0ba?sid=18ad0992-13d0-418a-b18f-1336f990ed50

fix(frontend): minor UI issues

---

docs/docs/tools-and-integrations/k6.mdx

This PR updates the K6 integration documentation to include the changes made to support cloud
- Adds token var information
- Updates examples to match new setup

chore(docs): K6 Cloud Update

---

web/src/components/CodeBlock/CodeBlock.styled.ts
web/src/components/CodeBlock/CodeBlock.tsx
web/src/components/CodeBlock/FramedCodeBlock.tsx
web/src/components/RunDetailAutomate/RunDetailAutomate.styled.ts
web/src/components/RunDetailAutomateDefinition/RunDetailAutomateDefinition.styled.ts
web/src/components/RunDetailAutomateDefinition/RunDetailAutomateDefinition.tsx
web/src/components/RunDetailLayout/RunDetailLayout.styled.ts

This PR adds a couple of improvements to the YAML preview component in the automate tab.
- heigh resizable
- move download button to header
- fixes https://github.com/kubeshop/tracetest-cloud-frontend/issues/155

fix: add full height to FrameCodeBlock

---

.github/workflows/scheduled-jobs.yml
testing/synthetic-monitoring/pokeshop/01-add-pokemon-with-api.yaml
testing/synthetic-monitoring/pokeshop/02-import-pokemon-with-queue.yaml
testing/synthetic-monitoring/pokeshop/03-import-pokemon-with-stream.yaml
testing/synthetic-monitoring/pokeshop/04-list-pokemons.yaml
testing/synthetic-monitoring/pokeshop/_variableset.yaml

This PR updates Pokeshop synthetic monitoring to run in a new URL.

chore: update synthetic monitoring with latest pokeshop changes

---

agent/runner/runstrategy_desktop.go
web/src/components/Router/Router.tsx

This PR fixes the environment URL generated by the CLI start command. It also adds a fix in the FE router to handle redirects when the path does not match any route.
- fix environment URL in CLI
- fix FE router to handle not matched routes
- fixes https://github.com/kubeshop/tracetest-cloud-frontend/issues/161

fix: environment URL in CLI

---

server/analytics/analytics.go
server/app/app.go
server/executor/assertion_runner.go
server/executor/linter_runner.go
server/executor/queue.go
server/executor/trace_poller.go
server/executor/tracepollerworker/evaluator_worker.go
server/executor/trigger_result_processor_worker.go
server/http/middleware/analytics.go

This PR adds event properties in the context so it can be accessed from workers.
-
-

fix(server): add context event properties

---

docs/docs/analyzer/concepts.mdx
docs/docs/cli/configuring-your-cli.mdx
docs/docs/concepts/what-is-trace-based-testing.mdx

This PR fixes a few links that were breaking in edge cases.
-
-

docs(broken links): fixed bad links

---

server/http/custom_routes.go
server/http/middleware/metrics.go
server/resourcemanager/resource_manager.go

This PR adds more information about the response in case of errors in the backend. This is important to help us identify errors

telemetry(server): add more info about response in HTTP spans

---

web/src/components/ResourceCard/TestCard.tsx
web/src/components/RunDetailAutomate/RunDetailAutomate.tsx
web/src/components/RunDetailAutomateDefinition/RunDetailAutomateDefinition.tsx
web/src/components/RunDetailAutomateMethods/RunDetailAutomateMethods.tsx
web/src/components/RunDetailAutomateMethods/methods/CLICommand/CliCommand.tsx
web/src/components/RunDetailAutomateMethods/methods/Cypress/Cypress.styled.ts
web/src/components/RunDetailAutomateMethods/methods/Cypress/Cypress.tsx
web/src/components/RunDetailAutomateMethods/methods/Cypress/index.ts
web/src/components/RunDetailAutomateMethods/methods/DeepLink/DeepLink.tsx
web/src/components/RunDetailLayout/HeaderLeft.tsx
web/src/components/RunDetailTriggerResponse/RunDetailTriggerData.tsx
web/src/constants/Automate.constants.ts

This PR improves the Trigger and Automate tabs for a cypress test run.
- improve Trigger and Automate tabs
- fixes https://github.com/kubeshop/tracetest-cloud-frontend/issues/167
- fixes https://github.com/kubeshop/tracetest-cloud/issues/311
- fixes https://github.com/kubeshop/tracetest-cloud/issues/322
https://www.loom.com/share/520b34e238a34e5687b620784691d4d8?sid=26e417dd-097f-4a01-90fd-462fe1200663

feat(frontend): improve cypress trigger and automate tabs

---

server/traces/trace_entities.go
server/traces/traces_test.go

This PR updates the check for browser spans to return `general` while we decide what to do next.
- Adds a check for browser spans and returns `general` type
- [browser spans show as HTTP#320](https://github.com/kubeshop/tracetest-cloud/issues/320)

fix(server): Return  type for browser spans

---

docs/docs/examples-tutorials/recipes.mdx
docs/docs/examples-tutorials/tutorials.mdx

docs(examples-tutorials): clean up lists

---

agent/client/client.go

This PR adds a log message when the agent reconnects

agent: add log to print error that is making the agent reconnect

---

.github/workflows/scheduled-jobs.yml

This PR adds a timeout for our Synthetic Monitoring action.
- Adds timeout to `.github/workflows/scheduled-jobs.yml`

fix: add timeout to github action

---

web/src/components/Inputs/DataStoreSelection/DataStoreSelection.tsx
web/src/components/NoTracingPopover/NoTracingPopover.tsx
web/src/components/RunEvents/RunEventDataStore.tsx
web/src/components/Settings/DataStoreForm/DataStoreForm.tsx
web/src/components/SetupAlert/SetupAlert.tsx
web/src/pages/Home/ConfigCTA.tsx
web/src/pages/Settings/Content.tsx
web/src/providers/DataStore/DataStore.provider.tsx
web/src/providers/DataStore/hooks/useDataStoreNotification.tsx
web/src/services/EventLog.service.ts

This PR changes the term `DataStore` to `Tracing Backend`.
-
-

feat(frontend): change datastore to tracing backend

---

server/migrations/36_migrate_users_to_opentelemetry.sql

This PR migrates all users using the `agent` datastore to `otlp` and also create the `otlp` datastore in case the user doesn't have any datastore (using Tracetest in `no tracing mode`)

migration: migrate agent and no-tracing to otlp tracing backend

---

cli/config/version.go

This PR adds a small `(outdated)` text next to the user CLI version in case there's a new version available (using the server version as reference)

chore: add a small warning for outdated CLIs

---

web/src/components/RunDetailTest/SpanDetailsPanel.tsx
web/src/components/RunDetailTrace/SpanDetailsPanel.tsx

This PR updates the attribute list to be opened by default
- Updates attr list to be opened by default
- https://github.com/kubeshop/tracetest/issues/3449

fix(frontend): attribute list open by default

---

web/src/components/RunDetailLayout/HeaderRight.tsx
web/src/components/SkipPollingPopover/Content.tsx
web/src/components/SkipPollingPopover/SkipPollingPopover.styled.ts
web/src/components/SkipPollingPopover/SkipPollingPopover.tsx
web/src/components/SkipPollingPopover/index.ts
web/src/services/Triggers/TraceID.service.ts

This PR updates the skip polling to be more intuitive
- Updates behavior of the popover (no longer opens after 10 secs)
- Adds close button
- Adds tooltip
- https://github.com/kubeshop/tracetest-cloud/issues/293
- https://github.com/kubeshop/tracetest-cloud/issues/333

fix(frontend): skip polling improvements

---

docs/docs/examples-tutorials/recipes.mdx
examples/tracetest-core-k6/README.md
examples/tracetest-k6/README.md

This PR fixes the docusaurus build.
-
-

chore(docs): fix build

---

web/src/components/Inputs/DataStoreSelection/DataStoreSelection.tsx

This PR fixes an UI issue that was preventing user to select the first tracing backend option in the settings page.
- add default selected tab
-

fix(frontend): fix tracing backend selected tab

---

.github/workflows/pull-request.yaml
run.sh
web/cypress/e2e/TestRunDetail/Outputs.spec.ts
web/cypress/e2e/TestRunDetail/TestRunDetail.spec.ts

This PR fixes our Cypress e2e tests that are breaking due to a behavior change on our UI. Since we already open the Attribute list on the Trace and Test tabs, there is no need of having of clicking on the expand button to show the list.
- Update e2e to skip open attribute list step

fix: skip open attribute list step on e2e

---

run.sh
server/test/test_repository.go

This PR fix a query on test repository to consider tenant_id

fix: test repository tenant_id query

---

server/migrations/37_test_run_events_tenant.down.sql
server/migrations/37_test_run_events_tenant.up.sql
server/testdb/test_run_event.go

This PR makes test run events to take the tenant id into account when creating and reading events.

fix(server): take tenant_id into account for test run events

---

server/testdb/test_run_event.go

This PR fixes the read query for test run events when the tenant ID is set in the context
-
-

fix(server): correct query with tenant id for test run events

---

docs/docs/examples-tutorials/recipes/running-tracetest-with-sumologic.mdx
examples/quick-start-sumologic-nodejs/collector.config.yaml
examples/quick-start-sumologic-nodejs/readme.md
examples/quick-start-sumologic-nodejs/test-api.yaml
examples/quick-start-sumologic-nodejs/tracetest.datastore.yaml
examples/quick-start-sumologic-nodejs/tracetest/tracetest-provision.yaml

This PR improves the Sumo Logic example app and readme guide.
-
-

examples(sumo): improve example and guide

---

web/src/components/RunDetailAutomate/RunDetailAutomate.tsx
web/src/components/RunDetailAutomateMethods/methods/GithubActions/GithubActions.styled.ts
web/src/components/RunDetailAutomateMethods/methods/GithubActions/GithubActions.tsx
web/src/components/RunDetailAutomateMethods/methods/GithubActions/index.ts
web/src/constants/Common.constants.ts

This PR adds the github actions info to the automate tab
- Adds new automate tab
- https://github.com/kubeshop/tracetest-cloud/issues/297

feat(frontend): Adding Github actions info

---

server/executor/assertion_runner.go
server/executor/linter_runner.go
server/executor/tracepollerworker/evaluator_worker.go
server/executor/tracepollerworker/fetcher_worker.go
server/executor/trigger_executer_worker.go
server/executor/trigger_resolver_worker.go
server/executor/trigger_result_processor_worker.go

This PR adds code to handle test stop request in all the test pipeline steps
-
-

feat(server): allow tests to be stopped in all test pipeline steps

---

web/cypress/e2e/Home/CancelTest.spec.ts
web/cypress/e2e/Home/CreateTest.spec.ts
web/cypress/e2e/Home/CreateTestFromCurl.spec.ts
web/cypress/e2e/Home/CreateTestFromPostman.spec.ts
web/cypress/e2e/Home/CreateTestWithAuthentication.spec.ts
web/cypress/e2e/Home/ShowTestList.spec.ts
web/cypress/e2e/VariableSet/VariableSet.spec.ts
web/cypress/support/commands.ts
web/src/components/Layout/Layout.tsx
web/src/components/Router/Router.tsx
web/src/components/Wizard/Header/Header.styled.ts
web/src/components/Wizard/Header/Header.tsx
web/src/components/Wizard/Header/index.ts
web/src/components/Wizard/StepFactory/StepFactory.tsx
web/src/components/Wizard/StepFactory/index.ts
web/src/components/Wizard/Steps/StepTab.tsx
web/src/components/Wizard/Steps/Steps.styled.ts
web/src/components/Wizard/Steps/Steps.tsx
web/src/components/Wizard/Steps/index.ts
web/src/pages/Wizard/Wizard.styled.ts
web/src/pages/Wizard/Wizard.tsx
web/src/pages/Wizard/index.tsx
web/src/providers/Wizard/Wizard.provider.tsx
web/src/providers/Wizard/index.ts
web/src/types/Wizard.types.ts

This PR adds the layout for the Wizard and the initial architecture to render/control the steps.
- wizard layout
- wizard architecture
- fixes https://github.com/kubeshop/tracetest-cloud/issues/375

feat(frontend): add wizard layout and architecture

---

agent/client/client.go

This PR makes the agent reconnect when the grpc connection is closing.

fix: reconnect agent when grpc connection is closing

---

docs/docs/tools-and-integrations/cypress.mdx
docs/docs/tools-and-integrations/playwright.mdx

This PR fixes a couple issues with the e2e docs for the name of the environment variables file and the docker compose command.
- Fixes wrong content for e2e docs

fix(docs): E2E docs fix

---

examples/quick-start-sumologic-nodejs/readme.md
examples/quick-start-sumologic-nodejs/tracetest/docker-compose.yaml
examples/quick-start-sumologic-nodejs/tracing.otel.grpc.js
examples/quick-start-sumologic-nodejs/tracing.otel.http.js

example(sumologic): edit readme

---

agent/workers/poller.go
server/app/app.go
server/app/test_pipeline.go
server/executor/tracepollerworker/starter_worker.go

This PR changes the Test Connection action on the Trace Polling start to be async.
- Update Test Connection action on the Trace Polling start to be async.

fix: make test connection async on trace polling step

---

web/src/components/DataStoreConfiguration/DataStoreConfiguration.styled.ts
web/src/components/DataStoreConfiguration/DataStoreConfiguration.tsx
web/src/components/TestConnectionStatus/hooks/useTestConnnectionStatus.ts
web/src/components/Wizard/Content/Content.tsx
web/src/components/Wizard/Steps/CreateTest/CreateTest.tsx
web/src/components/Wizard/Steps/TracingBackend/Configuration.tsx
web/src/components/Wizard/Steps/TracingBackend/TracingBackend.tsx
web/src/constants/Analytics.constants.ts
web/src/providers/DataStore/DataStore.provider.tsx
web/src/providers/Wizard/Wizard.provider.tsx
web/src/services/Analytics/Wizard.service.ts

This PR adds the wizard analytics and the success criteria logic for the `Tracing Backend` step.
- wizard analytics 
- success criteria logic for the `Tracing Backend` step
- fixes https://github.com/kubeshop/tracetest-cloud/issues/390

feat(frontend): add wizard analytics

---

docs/docs/tools-and-integrations/cypress.mdx

Changes:
- Explicitly highlighted the npm i as I did not see it when it was in the sentence. 
- Switched to a different syntax on the git clone commend - I see an error for it (which I could fix)... I think this one may work more universally. 
- I also missed the copying of the env file my first time, so pulled it into a code block to make it even more obvious.

Couple changes on the Cypress docs

---

web/src/App.tsx
web/src/BaseApp.tsx
web/src/components/DataStoreConfiguration/DataStoreConfiguration.tsx
web/src/components/Layout/Layout.tsx
web/src/components/RunDetailLayout/RunDetailLayout.tsx
web/src/components/RunDetailLayout/hooks/useRunCompletion.ts
web/src/components/Settings/DataStore/DataStore.tsx
web/src/components/Settings/DataStoreForm/DataStoreForm.tsx
web/src/components/TestConnectionStatus/hooks/useTestConnnectionStatus.ts
web/src/components/Wizard/Steps/TracingBackend/Configuration.tsx
web/src/components/Wizard/Wrapper/Wrapper.tsx
web/src/pages/Wizard/Wizard.tsx
web/src/providers/DataStore/DataStore.provider.tsx
web/src/providers/TestRun/TestRun.provider.tsx
web/src/providers/Wizard/Wizard.provider.tsx
web/src/services/Wizard.service.ts

This PR adds the behavior for users to go through the different steps and completing one by one, it also allows users to skip steps when they complete steps that are later on in the process.
- Adds complete step logic
- Updates otlp test connection logic
- Updates components and factories
- https://github.com/kubeshop/tracetest-cloud/issues/396
[Add your loom video here if your work can be visualized](https://www.loom.com/share/168bad3e5d4b4c219b04d4c7953e14aa)

feat(frontend): Wizard - Completion Steps Wire-Up

---

server/wizard/wizard_repository.go
web/src/components/Wizard/Wrapper/Wrapper.tsx
web/src/providers/Wizard/Wizard.provider.tsx
web/src/types/Wizard.types.ts

This PR updates both the FE and backend to include the agent as step, but the FE will have checks to not render the component as it doesn't exist
- Adds default agent step for the wizard
- Adds logic to avoid rendering undefined components
- https://github.com/kubeshop/tracetest-cloud/issues/393

chore: Updating default wizard steps

---

server/executor/testrunner/testrunner_entities.go
server/executor/testrunner/testrunner_repository_test.go

This PR removes the analyzer-rules as the default required gate for test runs, to avoid failing tests based on that configuration for new users.
- Removes analyzer rules as the default required gates

chore(backend): Removing Analyzer Rules as default

---

server/subscription/message.go
server/subscription/message_test.go
server/testconnection/otlp.go

This PR fixes the error we get when sending `subscription.Message` from another application using NATS.

fix: subscription message decode

---

web/src/components/CreateTest/CreateTest.tsx
web/src/components/CreateTest/Header.tsx
web/src/components/RunDetailLayout/HeaderRight.tsx
web/src/components/RunDetailTrigger/RunDetailTrigger.tsx

This PR adds the FE code to support the Stop test functionality.
- enable stop test run
- fixes https://github.com/kubeshop/tracetest-cloud/issues/348
https://www.loom.com/share/cc241c8b17cd40719009cfc1b299059d?sid=9b0da430-f8cd-4c4e-b611-e3914d50a041

feat(frontend): stop test run

---

server/executor/queue.go
server/executor/test_suite_runner_test.go
server/http/websocket/unsubscribe.go
server/subscription/in_memory_manager.go
server/subscription/in_memory_manager_test.go
server/subscription/manager.go
server/subscription/nats_manager.go
server/subscription/subscription.go
server/testconnection/otlp.go

This PR solves a TODO we had that to implement the unsubscribe function to the nats subscription manager.

feat: unsubscribe from subscription

---

web/src/components/Settings/DataStore/DataStore.styled.ts
web/src/components/Settings/Demo/Demo.tsx
web/src/components/Settings/Linter/Linter.tsx
web/src/components/Settings/Polling/Polling.tsx
web/src/components/Settings/TestRunner/TestRunner.tsx
web/src/components/Settings/common/Settings.styled.ts
web/src/constants/Common.constants.ts
web/src/constants/TracetestAttributes.constants.ts

This PR improves the settings pages by adding help info and links to docs.
- help info in settings pages
-

feat(frontend): add help info in settings pages

---

server/test/test_entities.go
server/test/test_repository.go

This PR fixes a bug with how version change is calculated. Our algorithm checks for the relevant parts of the test and compares the JSON encoded version of each, since that's the easiest way to do it. The problem is that some times, empty fields can have different representations in go, which result in different JSON encoded values.
In this particular case, every time I applied this test:
```yaml
type: Test
spec:
id: test1234
name: Untitled
trigger:
type: http
httpRequest:
method: GET
url: https://google.com
headers:
- key: Content-Type
value: application/json
```
it was creating a new version, which is incorrect. The problem was that when comparing the new version with the one from DB, both have empty `Spec`, but one is a `nil` slice (JSON encoded as `"null"`) and the other one is an …

fix: incrementing test version without any change

---

server/test/run_repository.go
server/test/test_repository.go
server/testsuite/testsuite_run_repository.go

This PR fixes a race condition that happens when running two tests or transactions at the same time for the first time.

fix: pg race condition on sequence creation

---

web/src/components/TestHeader/TestHeader.tsx
web/src/components/TestHeader/__tests__/TestHeader.test.tsx
web/src/components/TestPlugins/FormFactory.tsx
web/src/components/TestPlugins/Forms/Grpc/Grpc.tsx
web/src/components/TestPlugins/Forms/Kafka/Kafka.tsx
web/src/components/TestPlugins/Forms/Rest/Rest.tsx
web/src/components/TriggerTab/TriggerTab.styled.ts
web/src/components/TriggerTab/TriggerTab.tsx
web/src/components/TriggerTab/index.ts
web/src/pages/Test/Content.tsx
web/src/pages/TestSuite/Content.tsx
web/src/redux/Router.middleware.ts
web/src/redux/slices/User.slice.ts

This PR adds the components to indicate which tabs have information on them on the trigger page. It also fixes a small navigation issue in our test suite detail page.
- TriggerTab component and logic to detect tabs with information
- fix navigation issue
- fixes https://github.com/kubeshop/tracetest-cloud/issues/326
- fixes https://github.com/kubeshop/tracetest-cloud-frontend/issues/186

feat(frontend): indicate tabs with info in trigger

---

web/src/components/RunDetailLayout/HeaderRight.tsx
web/src/components/TestState/TestState.tsx
web/src/components/TestState/TestStateProgress.tsx
web/src/constants/TestRun.constants.ts

This PR adds the number of spans in the Test Status component.
- number of spans in awaiting trace status
- fixes https://github.com/kubeshop/tracetest-cloud/issues/360

feat(frontend): add total spans in awaiting trace status

---

web/src/components/Inputs/Overlay/Overlay.tsx
web/src/hooks/useInputActions.ts

This PR fixes the edit test name behavior by improving the click outside logic.
- use the mousedown event
- fixes https://github.com/kubeshop/tracetest-cloud/issues/378

fix(frontend): fix edit test name behavior

---

server/test/run_test.go
server/test/test_json.go

This PR fixes a bug found in production that made the `GetTestRun` endpoint fail. It happened because the database had `Error: {}` as the value in the Outputs JSON.

fix: test run outputs marshal/unmarshal

---

web/src/components/RunDetailAutomate/RunDetailAutomate.tsx
web/src/components/RunDetailAutomateDefinition/RunDetailAutomateDefinition.tsx
web/src/components/RunDetailAutomateMethods/RunDetailAutomateMethods.tsx
web/src/components/RunDetailAutomateMethods/methods/Typescript/Typescript.styled.ts
web/src/components/RunDetailAutomateMethods/methods/Typescript/Typescript.tsx
web/src/components/RunDetailAutomateMethods/methods/Typescript/index.ts
web/src/pages/TestSuiteRunAutomate/Content.tsx

This PR adds the Typescript tab to the automate section, and allows its customization
- Adds Typescript as automate option
- https://github.com/kubeshop/tracetest-cloud/issues/417

feat(frontend): Typescript Test Run Automate Tab

---

web/src/components/ResizablePanels/ResizablePanels.styled.ts
web/src/components/RunDetailTest/RunDetailTest.styled.ts
web/src/components/RunDetailTrace/RunDetailTrace.styled.ts
web/src/components/RunDetailTrace/TracePanel.tsx
web/src/components/RunDetailTrace/Visualization.tsx
web/src/components/Visualization/components/DAG/TraceSpanNode/AnalyzerErrors.tsx
web/src/components/Visualization/components/DAG/TraceSpanNode/TraceSpanNode.tsx

This PR...
-
- fixes https://github.com/kubeshop/tracetest-cloud/issues/330

fix(frontend): improve trace tab ui and behavior

---

agent/runner/runner.go

This PR adds an error message when the agent API key is not found in the last step where is required.
- Adds error message for users that doesn't have access to start the agent for an env
- https://github.com/kubeshop/tracetest-cloud/issues/413
https://www.loom.com/share/8d3ee0ac59a54dc5bee6abfcca5d4b25

Fix agent permissions start

---

cli/cmd/middleware.go
cli/config/config.go
cli/config/configurator.go

This PR shows a more friendly message when the given server url is not reachable.
-
-

fix(cli): improve error message for invalid server url

---

web/src/components/RunDetailTest/TestPanel.tsx
web/src/components/RunDetailTest/Visualization.tsx
web/src/components/RunDetailTrace/RunDetailTrace.tsx
web/src/components/RunDetailTrace/TracePanel.tsx
web/src/components/RunDetailTrace/Visualization.tsx
web/src/components/Visualization/components/Switch/Switch.styled.ts
web/src/components/Visualization/components/Switch/Switch.tsx
web/src/constants/Visualization.constants.ts

This PR hides the DAG view for traces that are over the limit of spans.
- hide DAG view
- fixes #3604

feat(frontend): hide dag view for big traces

---

server/http/controller.go
server/http/mappings/tests.go

This PR reduces the response size of the list test runs endpoint by removing the trace attribute. This attribute is not used on listing and makes the FE slow

feat(server): minimize run list response size

---

web/src/components/Visualization/components/Timeline/BaseSpanNode/BaseSpanNodeV2.tsx
web/src/components/Visualization/components/Timeline/BaseSpanNode/ConnectorV2.tsx
web/src/components/Visualization/components/Timeline/TimelineV2.styled.ts
web/src/constants/Timeline.constants.ts

This PR implements connectors for the `timeline` view visualization.
- Timeline view guide connectors
-

feat: add timeline view connectors

---

docs/docs/examples-tutorials/recipes.mdx
docs/docs/examples-tutorials/recipes/testing-cloudflare-workers-with-opentelemetry-tracetest.mdx

docs(cfw): Add better prerequisites explanation

---

examples/integration-testing-vercel-functions/.env.prod
examples/integration-testing-vercel-functions/test/api.pokemon.spec.prod.yaml

docs(vercel): add prod env vars and test

---

cli/cmd/start_cmd.go

Apply deprecation note from #3563 to the `tracetest start` command as well.

fix: add deprecation node in `--endpoint` for `tracetest start`

---

agent/runner/runstrategy_dashboard.go

This PR fixes a panic in the agent dashboard when `TRACETEST_DEV` is not set.

fix: panic when log level is not defined

---

server/otlp/grpc_server.go

fix(otlp): Increasing the grpc server data max size

---

examples/setup-of-tracetest-tests/.gitignore
examples/setup-of-tracetest-tests/README.md
examples/setup-of-tracetest-tests/delete_pokemon.yaml
examples/setup-of-tracetest-tests/delete_test.ts
examples/setup-of-tracetest-tests/delete_test_suite.yaml
examples/setup-of-tracetest-tests/package-lock.json
examples/setup-of-tracetest-tests/package.json
examples/setup-of-tracetest-tests/setup_pokemon.yaml
examples/setup-of-tracetest-tests/tsconfig.json
examples/setup-of-tracetest-tests/types.ts

Example to support https://www.notion.so/kubeshop/Running-Tracetest-from-Javascript-or-Typescript-682062bd702c4f5eb7c3164a09ad62bd blog post

Example of running setup methods to support blog post

---

web/src/hooks/useDeleteResource.tsx

This PR fixes the navigation path when a `test` or `testsuite` is deleted.
- fix navigation path
- fixes https://github.com/kubeshop/tracetest/issues/3609

fix(frontend): fix delete resource navigation

---

examples/quick-start-typescript/package-lock.json
examples/quick-start-typescript/package.json

This PR updates the @tracetest/client version for the typescript example to show better error logs
- Updates @tracetest/client to latest

chore(examples): Updating @tracetest/client version

---

server/pkg/pipeline/inmemory_driver.go
server/pkg/pipeline/nats_driver.go
server/pkg/pipeline/queue.go

This PR makes the context be propagated to all queues

feat: propagete trace context in queues

---

cli/cmd/configure_cmd.go
cli/cmd/dashboard_cmd.go
cli/cmd/middleware.go
cli/cmd/resource_apply_cmd.go
cli/cmd/resource_delete_cmd.go
cli/cmd/resource_export_cmd.go
cli/cmd/resource_get_cmd.go
cli/cmd/resource_list_cmd.go
cli/cmd/resource_run_cmd.go
cli/cmd/root.go
cli/cmd/start_cmd.go
cli/cmd/version_cmd.go
cli/config/config.go
cli/config/configurator.go
cli/pkg/resourcemanager/client.go
go.mod
go.sum

This PR improves the error handling when the server does not accept the JWT token for whatever reason (corrupted config file, expired token, anything that makes the server return a 401 code).
When an auth error happens, the authentication flow begins, and the issued command is automatically rerun with the new credentials.
For the case of the `start` cmd, this new behaviour was causing the cli to show 2 times the org/env selector: once for the new auth and another one for the `start` command (it shows the selector when started unless org/env are passed via flags).
To overcome this issue, I added some context magic to pass the values around in a relatively seamless way so this command can pick the values and not ask the user 2 times.
-
- …

feat(cli): reauthenticate user in case of invalid token

---

cli/cmd/configure_cmd.go
cli/config/config.go
cli/config/configurator.go
cli/config/selector.go

This PR improves the UX of the cli configure by remembering the last used server, if applicable reuse the last used JWT, and default to the last used env/org when showing the options
-
-
https://www.loom.com/share/95ca3b8de0a846c0804687162dbe1eae

feat(cli): improve configure cmd ux

---

cli/cmd/middleware.go
cli/cmd/start_cmd.go
cli/config/config.go
cli/config/configurator.go

This PR fixes some issues caused by an incorrect merge
-
-

fix(cli): fix merge issues

---

cli/config/configurator.go
cli/config/selector.go

This PR fixes an issue on the CLI preventing the `configure` command to work on automated environments. The command was asking for user input (asking for server) even when the `--token` flag was passed. This flag allows us to infer a non interactive environment so we can use a reasonable fallback (cloud url or previously configured value from config file) if no `--server-url` is provided.
On top of this, there was some incorrect handling of the flags within the configurator. Flags were saved as an instance variable by value instead of reference, so when one method modifies a flag value, the change is lost at the end of the function scope (see comments on PR)
-
-

fix(cli): configure for non interactive environments

---

docs/docs/examples-tutorials/overview.mdx
docs/docs/getting-started/installation.mdx
docs/docs/getting-started/open.mdx
docs/docs/getting-started/overview.mdx
docs/docusaurus.config.js
docs/sidebars.js
docs/src/components/ExamplesTutorialsOverview/index.tsx
docs/src/components/GettingStartedGuide/index.tsx

docs(landing pages): edit components based on user behavior

---

.github/workflows/scheduled-jobs.yml
testing/synthetic-monitoring/pokeshop-serverless/01-add-pokemon-with-api.yaml
testing/synthetic-monitoring/pokeshop-serverless/02-import-pokemon-with-queue.yaml
testing/synthetic-monitoring/pokeshop-serverless/04-list-pokemons.yaml
testing/synthetic-monitoring/pokeshop-serverless/_testsuite.yaml
testing/synthetic-monitoring/pokeshop-serverless/_variableset.yaml

feat(tracetesting): Adding Serverless Synthetic Tests

---

docs/docs/concepts/selectors.mdx
server/assertions/selectors/builder.go
server/assertions/selectors/selector_test.go
server/traces/span_entitiess.go
server/traces/traces_test.go
web/src/components/SpanDetail/Header.tsx
web/src/components/TestSpecDetail/SpanHeader.tsx
web/src/components/Visualization/components/DAG/BaseSpanNode/BaseSpanNode.tsx
web/src/constants/Span.constants.ts
web/src/models/Span.model.ts
web/src/services/Span.service.ts

This PR makes it possible for users to reference the span kind using the attribute `kind` in the selector.

feat: allow selector to use `kind` field from span

---

server/expression/data_store.go
server/expression/executor_test.go

This PR makes the assertion engine return the following error when you try to run an assertion against an attribute when no spans match the selector:
```
resolution error: there are no matching spans to retrieve the attribute "attribute-name" from. To fix this error, create a selector matching at least one span.
```
Related thread message: https://tracetest-community.slack.com/archives/C06CF48NS79/p1708377604787339?thread_ts=1708367051.955759&cid=C06CF48NS79

feat: make the assertion engine return a different error when no spans

---

agent/client/client.go
agent/client/options.go
agent/client/workflow_ping.go
agent/config/config.go
agent/config/flags.go
agent/runner/session.go
agent/telemetry/tracer.go
agent/workers/poller.go
agent/workers/stopper.go
agent/workers/testconnnection.go
agent/workers/trigger.go
cli/cmd/start_cmd.go
cli/config/configurator.go
go.sum

This PR adds support for OTel Collector on Tracetest Agent.
- Added capability of setting verbose mode via env vars
- Added option to inform the address of an OTel Collector to send observability telemetry

feat(cli): add open telemetry support for Tracetest agent

---

Makefile
agent/config/flags.go
cli/config/configurator.go

This PR makes the CLI not ask interactively from the user the desired server URL, and instead automatically select one. 
When passing `--token` or `--api-key` we can no longer asume an interactive environment. Those tokens are usually used in a CI or otherwise automated environment, where user interaction is not available. 
In this case, server url is chose as:
1. if `--server-url` flag is passed, used that.
2. if we have a pre existing config, use that value.
3. otherwise use cloud endpoint.
This behaviour was already implemented for the `--token` flag, but not for the `--api-key` flag.

fix(cli): automatically use cloud endpoint if token is passed

---

.github/workflows/scheduled-jobs.yml
agent/runner/session.go
agent/telemetry/common.go
agent/telemetry/meter.go
agent/telemetry/tracer.go
agent/workers/poller.go
agent/workers/stopper.go
agent/workers/testconnnection.go
agent/workers/trigger.go
server/telemetry/metrics.go

This PR adds metrics for the agent actions. We are adding `run` and `error` counters for the following actions: `test connection`, `test stop`, `trigger` and `polling`.
- added meter on workers
- updated telemetry reporting for traces and metrics
- updated timeouts for synthetic monitoring

feat(agent): add metrics to agent workers

---

agent/client/client.go
agent/client/workflow_listen_for_ds_connection_tests.go
agent/client/workflow_listen_for_otlp_connection_tests.go
agent/client/workflow_listen_for_poll_requests.go
agent/client/workflow_listen_for_stop_requests.go
agent/client/workflow_listen_for_trigger_requests.go
agent/client/workflow_ping.go
agent/client/workflow_shutdown.go
agent/client/workflow_startup.go
agent/runner/runner.go
agent/runner/session.go
cli/cmd/start_cmd.go
cli/config/configurator.go
cli/pkg/oauth/oauth.go

This PR adds debug logs so it's easier to identify issues, mainly when talking with the control plane.
It also fixes the logger configuration to correctly display debug logs when passing the `-v` flag
-
-

feat(agent): add debug logs

---

web/src/components/RunDetailLayout/RunDetailLayout.tsx

This PR updates the default run result tab to be the test instead of the trigger
- Updates default tab for the test run page
- https://github.com/kubeshop/tracetest-cloud/issues/448

chore(frontend): Updating the default test run tab

---

server/pkg/pipeline/queue.go

This PR fixes a propagation error that Core had on Nats, making operations that uses queue to have multiple traces instead of a single one.

fix(server): fixing context propagation on nats

---

server/expression/executor.go
server/expression/executor_test.go
server/expression/filters/json_path_test.go
server/expression/value/value.go

This PR fixes a bug found where escaped characters would not be unescaped before used in the filters.

fix: unescape filter argument before running filter

---

examples/observability-to-the-rescue/tracetest/tests/test-with-error.yaml
examples/observability-to-the-rescue/tracetest/tests/test-with-success.yaml

This PR updates the test files on our "Observability to the Rescue" example, that were broken due to the `|-` yaml syntax usage. 
- Update Observability to the resue example

chore: update observability to the rescue example files

---

agent/ui/dashboard/pages/test_runs_page.go

fix: makes agent header appear on mac

---

web/src/components/AllowButton/AllowButton.tsx
web/src/services/DataStore.service.ts
web/src/services/DataStores/AwsXRay.service.ts
web/src/services/DataStores/AzureAppInsights.service.ts
web/src/services/DataStores/BaseClient.service.ts
web/src/services/DataStores/ElasticSearch.service.ts
web/src/services/DataStores/GrpcClient.service.ts
web/src/services/DataStores/HttpClient.service.ts
web/src/services/DataStores/Jaeger.service.ts
web/src/services/DataStores/OtelCollector.service.ts
web/src/services/DataStores/SignalFx.service.ts
web/src/services/DataStores/SumoLogic.service.ts
web/src/types/DataStore.types.ts

This PR adds the getPublicInfo for the tracing backend service.
- new getPublicInfo method
-

feat(frontend): add getPublicInfo for tracing backend

---

agent/client/client.go

fix: make closing connection not reconnect and actually kill the routine

---

agent/ui/dashboard/pages/test_runs_page.go

fix: agent ui proporsions

---

cli/config/configurator.go

This PR allows full overwrite of the server url, so it allows more flexibility while developing
-
-

fix(cli): allow developer overwrite of entire server url

---

web/src/components/ResourceCard/Box.tsx
web/src/components/ResourceCard/TestCard.tsx
web/src/components/ResourceCard/TestSuiteCard.tsx
web/src/components/Resources/Content/Content.styled.ts
web/src/components/Resources/Content/Content.tsx
web/src/components/RunDetailAutomate/RunDetailAutomate.tsx
web/src/components/RunStatusIcon/RunStatusIcon.styled.ts
web/src/components/RunStatusIcon/RunStatusIcon.tsx
web/src/components/RunStatusIcon/RunTooltipTitle.tsx
web/src/utils/Common.ts

This PR adds UI improvements to the Tests list, Resources component in Home page and Automate tab.
- fix TypeScript title
- change test run summary to include abbreviate number
- add new icon for failed trigger, trace and assertions status
- fix alignment for action links in resources
- fixes https://github.com/kubeshop/tracetest-cloud-frontend/issues/242 
- fixes https://github.com/kubeshop/tracetest-cloud-frontend/issues/251
- fixes https://github.com/kubeshop/tracetest-cloud-frontend/issues/252
- fixes https://github.com/kubeshop/tracetest-cloud-frontend/issues/250
- New test run summary with abbreviated number
- New icon for failed trigger, trace and assertions

fix(frontend): ui cleanup and improvements

---

web/src/components/Wizard/Content/Content.styled.ts

This PR removes the wizard margin-bottom value.
- removes wizard margin-bottom
-

fix(frontend): remove wizard css margin

---

examples/quick-start-tyk/package-lock.json
examples/quick-start-tyk/package.json
examples/quick-start-tyk/playwright/auth.ts
examples/quick-start-tyk/playwright/home.spec.ts

This PR updates the tyk example to match the final version from the presentation
-
-

chore(examples/docs): Updating the Tyk Example with E2E Tests

---

go.mod
go.sum
server/app/app.go
server/cmd/serve.go
server/config/exporters.go
server/telemetry/profiler.go

This PR adds support for Pyroscope, allowing us to have Profiling as an observability signal to understand memory leaks and CPU peaks
- Adding support for Pyroscope

chore: add support for profiling

---

docker-compose.nats.yaml
server/pkg/pipeline/nats_driver.go
server/subscription/nats_manager.go

This PR uses nats queue subscriptions
-
-

feat(server): use nats queue subscriptions

---

web/src/components/ImportModal/ImportModal.tsx
web/src/components/ImportModal/Tip.tsx
web/src/components/VariableSetModal/Tip.tsx
web/src/components/VariableSetModal/VariableSetModal.styled.ts
web/src/components/VariableSetModal/VariableSetModal.tsx

This PR adds the help panel to the Variable Set modal.
- add help panel to variable sets
- fixes https://github.com/kubeshop/tracetest/issues/3427

feat(frontend): add variable set help info

---

docs/docusaurus.config.js

This PR updates the announcement top bar on the docs to link to a blog post about Tracetest going to KubeCon EU.
-
-

docs(announcement-bar): update for kubecon

---

LICENSE
agent/LICENSE
licenses/MIT.txt

This PR updates the licenses used for the overall code and the agent, making the separation between what it will be MIT and the agent that will be switched to a TLC license
- updates license between agent and the rest of the code
- https://github.com/kubeshop/tracetest-cloud/issues/498

chore: Updating license for agent and the rest of the code

---

cli/runner/report/reporter.go
docs/package-lock.json
web/package-lock.json

This PR adds a reporter for the run group to the CLI
https://www.loom.com/share/a0ae371a9238458d8d82d40390a0f3ed

feat: cli run group reporter

---

README.md

This PR fixes a broken link to our docs in the Readme.
- fix broken link
-

fix(readme): update broken docs link

---

cli/cloud/cmd/run_cmd.go
cli/cloud/runner/multifile_orchestrator.go
cli/cmd/resource_run_cmd.go
cli/cmdutil/run_params.go

This PR fixes the way we handle runs by id by enabling it alongside the run groups feature
- Adds support for id when using run groups
https://www.loom.com/share/f272c64edcac42dd929cc9b7f772ef78

fix(cli): Adding run by id

---

examples/quick-start-artillery/package-lock.json
examples/quick-start-artillery/package.json
examples/quick-start-artillery/plugin-test.yaml

This PR updates the artillery example to support the latest changes to the otlp span object structure
- Updates version for tracetest npm packages
- Updates version of artillery

chore(examples): update artillery example

---

docs/docs/examples-tutorials/recipes/running-playwright-performance-tests-with-artillery-and-tracetest.mdx

docs(recipes): update why is this important for artillery recipe

---

docs/vercel.json

This PR updates vercel 301 redirects to fix 404s.
-
-

docs(fix404s): edit 301 redirects

---

agent/collector/cache.go
agent/collector/collector_test.go
agent/collector/ingester.go
agent/runner/session.go
agent/workers/poller.go
agent/workers/poller/inmemory_datastore.go
agent/workers/poller/sent_spans_cache.go

This PR updates the agent collector. Now it's not a `proxy` for open telemetry anymore. It only collects traces for tests and stores them. It also discards the test traces once they are sent back to the server to reduce the memory footprint.
-
-

fix: don't use buffer and run things async

---

api/tests.yaml
cli/cmd/resources.go
cli/openapi/model_test_.go
cli/preprocessor/test.go
cli/preprocessor/testsuite.go
docs/docs/cli/creating-tests.mdx
server/openapi/model_test_.go

This PR makes it possible to reference a polling profile in the definition file of a test.
```yaml
type: Test
spec:
name: my test
pollingProfile: ./path-to-polling-profile.yaml
...
```

feat: cli polling profile

---

cli/cmd/resources.go
cli/config/configurator.go
testing/cli-e2etest/testscenarios/test/run_test_test.go
testing/cli-e2etest/testscenarios/variableset/apply_variableset_test.go
testing/cli-e2etest/testscenarios/variableset/get_variableset_test.go
testing/cli-e2etest/testscenarios/variableset/list_variablesets_test.go
testing/cli-e2etest/testscenarios/variableset/resources/deprecated-environment.yaml

This PR enables the usage of cloud entities as part of the resources definitions
- Adds client for env tokens
- Adds client for org invites
- Adds client for environments
- https://github.com/kubeshop/tracetest-cloud/issues/558
https://www.loom.com/share/1e81fe1cd8dd4c1ba179ff23862ee7a0

feat(cli): Adding cloud resources

---

agent/client/workflow_listen_for_ds_connection_tests.go
agent/client/workflow_listen_for_otlp_connection_tests.go
agent/client/workflow_listen_for_poll_requests.go
agent/client/workflow_listen_for_trigger_requests.go

This PR updates the handling of requests from the control plane to the agent so that the actual processing happens in a newly spawned goroutine. This allows for faster responses.

fix(agent): use goroutines for processing requests from control plane

---

cli/cmd/resources.go

This PR fixes a bug with the plural resource name for `environmenttokens` and `invites`.
- fix plural resource names
-

fix(cli): add valid environmenttokens and invites resource name plural

---

agent/client/client.go
agent/client/workflow_listen_for_ds_connection_tests.go
agent/client/workflow_listen_for_otlp_connection_tests.go
agent/client/workflow_listen_for_poll_requests.go
agent/client/workflow_listen_for_stop_requests.go
agent/client/workflow_listen_for_trigger_requests.go
agent/client/workflow_ping.go
agent/client/workflow_shutdown.go

This PR makes the agent reconnect when the server shuts down (probably a rolling release)
-
-

fix: make agent reconnect on server shutdown

---

cli/formatters/test_run.go

This PR fixes the following panic
```
tracetest run test -f ./test-api.yaml
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x102c23e1c]
goroutine 1 [running]:
github.com/kubeshop/tracetest/cli/formatters.testRun.pretty({_, _, _}, {0x1, 0x1, {0x140008511b0, 0x140008511d0, 0x140008511f0, 0x1400008b768, 0x14000a101e0, ...}, ...})
/home/runner/work/tracetest/tracetest/cli/formatters/test_run.go:90 +0x23c
github.com/kubeshop/tracetest/cli/formatters.testRun.Format({_, _, _}, {0x1, 0x1, {0x140008511b0, 0x140008511d0, 0x140008511f0, 0x1400008b768, 0x14000a101e0, ...}, ...}, ...)
/home/runner/work/tracetest/tracetest/cli/formatters/test_run.go:59 +0xec
github.com/kubeshop/tracetest/cli/runner.testRunner.FormatRes …
```

fix: panic on CLI error

---

docs/docs/concepts/environment-tokens.mdx
docs/docs/concepts/organization-tokens.mdx
docs/sidebars.js

docs(concepts): add org tokens

---

docs/docs/ci-cd-automation/testkube-pipeline.mdx
docs/docs/tools-and-integrations/testkube.mdx

This PR fixes a few broken links.
-
-

docs(examples): fix tk links

---

cli/cmd/resource_run_cmd.go
cli/pkg/fileutil/path.go
testing/cli-e2etest/testscenarios/test/run_test_test.go
testing/cli-e2etest/testscenarios/testsuite/run_testsuite_test.go

This PR adds a validation on the CLI to inform the user that they tried to run a test / testsuite that doesn't exist. 
Example:
- Add validation on `run` command to check if definition files exists

fix(cli): adding validation when trying to run resource that does not exist

---

.github/workflows/pull-request.yaml

This PR disables Signoz tests temporarily until we find out why its internal clickhouse started to misbehave on the example.
Example of runs with problem:
- https://github.com/kubeshop/tracetest/actions/runs/9489935292/job/26152538458

chore(ci): disable signoz to unblock another PRs

---

server/expression/executor.go
server/expression/executor_test.go

fix: unescape strings before comparing them

---

agent/workers/trigger/trigger_json.go

This PR fixes the json field for the playwright engine entry, it should be uppercase `E`
- Updates field json for playwright engine
- https://github.com/kubeshop/tracetest-cloud/issues/750

fix(triggers): Fixing playwright engine trigger field

---

.github/workflows/release-candidate.yml

This PR updates the RC process to remove caches from it.

chore(ci): removing caches from RC process

---

agent/workers/trigger/playwrightengine.go

This PR fixes a bug with the name of the script when there are multiple in parallel executions for the same agent instance
- Adds base name to the script file using the trace id

fix(agent): Playwright Engine Script Name

---

agent/workers/trigger/playwrightengine.go

fix(triggers): Updating playwright Engine lib execution

---

agent/client/connector.go
cli/config/api.go

This PR allows configuring the controlplane client to allow self signed certificates on controlplane servers when the TRACETEST_DEV_FORCE_URL env var is true. This also applies for openapi client

feat(agent): allow connections to  controlplane and api with self signed ssl cert on demand

---

server/expression/executor.go
server/expression/executor_test.go

fix: unescape attribute values

---

docs/docs/concepts/environments.mdx
docs/docs/concepts/organizations.mdx
docs/docs/concepts/polling-profiles.mdx
docs/docs/concepts/roles-and-permissions.mdx
docs/docs/concepts/runs.mdx
docs/docs/concepts/variable-sets.mdx
docs/docs/tools-and-integrations/artillery-engine.mdx
docs/docs/tools-and-integrations/artillery-plugin.mdx
docs/docs/tools-and-integrations/cypress.mdx
docs/docs/tools-and-integrations/playwright.mdx
docs/docs/tools-and-integrations/typescript.mdx

This PR adds callouts to feature pages that are only available in commercial Tracetest.
-
-

docs(upsell): add callout for commercial on features

---

.github/workflows/pull-request.yaml
examples/quick-start-java/quick_start_api/.gitignore

This PR updates our CI pipeline script to use `docker compose` commands instead of `docker-compose`.
- `.github/workflows/pull-request.yaml` calls `docker compose` for starting examples

fix(ci): update example tests to use "docker compose" instead of "docker-compose"

---

docs/docs/concepts/environment-tokens.mdx
docs/docs/examples-tutorials/recipes/running-tracetest-with-grafana-cloud-tempo-pokeshop.mdx
docs/docs/examples-tutorials/recipes/testing-kafka-go-api-with-opentelemetry-tracetest.mdx

This PR...
-
broken 404 links
-

Update 404 broken links in Docs

---

docs/docs/getting-started/installation.mdx
docs/docs/getting-started/open.mdx
docs/docs/getting-started/overview.mdx
docs/docs/index.mdx
examples/quick-start-nodejs/docker-compose.yaml

This PR adds a new getting started flow and adds on-prem onboarding.
-
-

docs(getting-started): updated flow and added on-prem

---

docs/docs/getting-started/installation.mdx
docs/docs/install/cli.mdx
docs/docs/install/deployment-architecture.mdx
docs/docs/install/docker.mdx
docs/docs/install/gcp.mdx
docs/docs/install/helm.mdx
docs/docs/install/kubernetes.mdx
docs/docs/install/overview.mdx
docs/sidebars.js

This PR restructures the get started section and includes a new install section.
-
-

docs(install): new install sections & updated getting started

---

cli/config/config.go
go.mod
go.sum
server/otlp/http_server.go

This PR fixes the agent's OTLP server http ingestion server so that it provides the correct CORS headers. This allows sending traces from a web client directly to the agent.
- add cors middleware to the endpoint
- fix incorrect default domain using http instead of https

fix(agent): return correct cors headers for ingestion endpoint

---

agent/ui/dashboard/sensors/sensor.go

This PR adds a mising `defer` for the calling of mutex Unlock when emmiting events. This avoids seeing this kinds of errors:
```
fatal error: concurrent map writes
goroutine 585 [running]:
github.com/kubeshop/tracetest/agent/ui/dashboard/sensors.(*sensor).Emit(0x140006c2270, {0x105980599, 0x12}, {0x105fb2380?, 0x107531060})
/home/runner/work/tracetest/tracetest/agent/ui/dashboard/sensors/sensor.go:79 +0x154
github.com/kubeshop/tracetest/agent/collector.(*forwardIngester).ingestSpans(0x140006c40d0, 0x1400090a540)
/home/runner/work/tracetest/tracetest/agent/collector/ingester.go:110 +0x1ac
created by github.com/kubeshop/tracetest/agent/collector.(*forwardIngester).Ingest in goroutine 597
/home/runner/work/tracetest/tracetest/agent/collector/ingester.go:91 +0x70
```
- Defer mutex unlock call …

fix(cli): handling of concurrent map read/write

---

docs/docs/tools-and-integrations/playwright.mdx

This PR fixes a code snippet in our playwright docs.
- playwright docs
-

fix: docs playwright code snippet

---

k8s/agent/deploy-agent.sh
k8s/agent/deploy-agent.yaml

This PR adds the `--environment` flag to the script that installs the agent in a Kubernetes cluster. It also replaces the `command` option with the `args` option in the manifest.
Here's a pod running the agent that was installed with this script

fix: agent k8s deployment

---

install-cli.sh

This PR fixes the CLI installer script so that it upgrades tracetst to the latest version when using yum if the package is already installed
-
-

fix(cli installer): make yum update

---

server/app/app.go
server/cmd/root.go
server/cmd/serve.go
server/config/appconfig.go

This PR adds server log info that will be useful in debugging #3985 
-
-

feat: add server debug info

---

cli/config/config.go
cli/config/configurator.go
cli/pkg/oauth/oauth.go

This PR fixes how we build oauth endpoint paths by replacing `fmt.Sprintf` with `path.Join`

fix: oauth path building

---

cli/config/version.go

This PR removes the dependency on the uiEndpoint when checking the server version.

fix: don't use ui endpoint for version checking

---

cli/pkg/oauth/oauth.go

This PR fixes the escaping problem when referencing the `?callback` query string in the OAuth URL.

fix: append callback parameter after joining url path

---

cli/cloud/cmd/run_cmd.go
cli/cloud/cmd/wait_cmd.go
cli/cloud/runner/rungroup.go
cli/cmd/config.go
cli/cmd/resource_run_cmd.go
cli/cmd/resources.go
cli/cmd/wait_cmd.go
cli/cmdutil/logger.go
cli/pkg/resourcemanager/client.go
cli/processor/environment.go
cli/processor/monitor.go
cli/processor/test.go
cli/processor/testsuite.go
cli/processor/trigger_preprocessor/graphql.go
cli/processor/trigger_preprocessor/grpc.go
cli/processor/trigger_preprocessor/http.go
cli/processor/trigger_preprocessor/playwrightengine.go
cli/processor/variableset.go
cli/runner/registry.go

This PR fixes all the references to the logger so they are correctly replaced by a configured instance when ready. this allows to correctly process the verbose flag
-
-

fix: reenable debug logging

---

cli/cloud/runner/multifile_orchestrator.go
cli/cmd/resource_run_cmd.go
cli/runner/orchestrator.go

This PR fixes the error handling of the CLI for the run command. It now allows displaying an error instead of silently failing.
It also attempts to parse the error response from the server as a structured error to display nicer messages when possible
-
-

fix: correctly display general errors

---

cli/cmd/middleware.go
cli/config/configurator.go
cli/runner/orchestrator.go

This PR shows a nicer message for users for the `agent not started` error
-
-

fix: add nicer message for missing agent error

---

cli/cmdutil/logger.go
cli/config/configurator.go
cli/pkg/oauth/oauth.go

This PR improves the error handling of token exchange by showing user friendly error messages
-
-

fix(cli): improve display of error responses for token exchange

---

agent/workers/trigger/http.go
agent/workers/trigger/http_test.go
server/executor/trigger/http.go

This PR makes both agent and opensource triggerer add the `Host` property to the `http.Request` before sending it to the server.

fix: add Host to request in trigger

---

agent/client/workflow_listen_for_otlp_connection_tests.go
agent/runner/session.go

This PR adds debug logs to the otlp connection tester to help debugging
-
-

chore(agent): add debug logs for otlp connection tester

---

agent/entrypoint.sh

This PR changes the entrypoint script to use the API KEY from env instead of as an argument when calling tracetest. This avoids exposing the API KEY as plain text under some circumstances
-
-

fix(agent): use api-key from env on entrypoint cmd

---

agent/runner/runstrategy_verbose.go
agent/runner/session.go

This PR updates the error handling on the agent when it is stopped after an auth error, causing go to give a nil pointer error.

fix(agent): update error handling on shutdown

---

server/traces/otel_converter.go
server/traces/span_entitiess.go

This PR adds the missing span attributes such as
1. Service name
2. Resource spans
- Adds resources attribute to base spans
- Adds service name attribute
- https://github.com/kubeshop/tracetest-cloud/issues/890

fix(traces): fixing missing span attributes

---

testing/synthetic-monitoring/pokeshop/_variableset.yaml

This PR updates the `POKESHOP_KAFKA_BROKER` value for the pokeshop synthetic monitoring tests.
- update `POKESHOP_KAFKA_BROKER`
-

fix: update variable set for pokeshop synthetic test

---

cli/cloud/runner/multifile_orchestrator.go
cli/pkg/fileutil/file.go

This PR enables the cli to filter files by resource types when running an entire directory. This allows to use a single command to launch multiple testsuites from a directory that also contains tests. For example:
```
$ tree tests
├── 01_step_1.yaml
├── 02_step_2.yaml
└── feature_test_suite.yaml
```
Until now, running `tracetest run -f tests` would cause to run `01_step_1.yaml`, `02_step_2.yaml` and `feature_test_suite.yaml`. This might not be desirable
Now, running `tracetest run testsuite -f tests` would cause to only run `feature_test_suite.yaml`.
-
-

feat(cli): allow selecting resource type when running multiple files

---

agent/workers/envelope/spans_envelope.go
agent/workers/envelope/spans_envelope_test.go
agent/workers/poller.go

This PR makes all polling responses to be added to an envelope and to fit a certain size. It tries to fit as many spans as possible in the envelope before sending it to the server. In case a span is let out of the envelope, it will be sent in the next polling iterations.
- grpc was breaking due to max message size
I could not record a loom because it is not supported in firefox :cry: But here is a screencast. In this case, I was running the agent in debug mode and an envelope max size of `5kb`, this is why you see spans increasing slowly. By default, we are going to use `3MB`, which would be more than enough for real-life spans.
[Screencast from 2024-09-17 16-56-18.webm](https://github.com/user-attachments/assets/b44ccf83-97e3-4eff-ab01-d933019e1ce0)

feat: make spans fit an envelope size

---

demo/transaction.yaml
examples/quick-start-github-actions/tracetest/tests/transaction-api.yaml
examples/tracetest-aws-step-functions/tests/transaction.yaml
testing/cli-e2etest/testscenarios/testsuite/resources/legacy-transaction.yaml
testing/synthetic-monitoring/pokeshop-serverless/_testsuite.yaml
testing/synthetic-monitoring/pokeshop/_testsuite.yaml

This PR fixes our test to stop using the old, deprecated `Transaction` type in favor of `TestSuite`
-
-

chore(testing): update old Transaction types to TestSuites

---

agent/runner/runstrategy_dashboard.go

This PR prevents `map concurrent writes` panic in the agent

fix: prevent map concurrent writes panic in the agent

---

agent/tracedb/tempodb.go

This PR temporary increases the max size of messages to 10MB, while we work on a way to paginate results from Tempo
- Adds max received option to 10MB
- https://github.com/kubeshop/tracetest-cloud/issues/924

chore(tempodb): Adding max size for received messages to 10MB

---

cli/cmd/config.go
cli/cmd/configure_cmd.go
cli/cmd/start_cmd.go
cli/config/configurator.go

This PR adds the version validation to the `configure` and `start` commands.
- Adds validation at the configurator level to return the validation error
- CMDs now exit early if version error is found
- https://github.com/kubeshop/tracetest-cloud/issues/930
https://github.com/user-attachments/assets/0acc36d6-56c3-494f-9526-181ae86bdaae

chore(cli): Adding version validation to `configure`  and `start`

---

server/executor/trigger/http_test.go
server/executor/trigger/triggerer.go

fix(server): fix string wrapping for triggers

---

cli/cmd/start_cmd.go

This PR enables the configuration of the trace mode using an env var
- Adds env var default value for trace mode

chore(cli): Enabling trace mode env var

---

agent/runner/runstrategy_desktop.go

This PR fixes the way we build the browser URL when opening the environment from the agent UI

fix: join url paths properly to build browser URL to open

---

agent/runner/runner.go

This PR uses the correct Environment ID when manually running `tracetest start` without any flags, and manually selecting the environment from the dropdown.
-
-

fix(agent): use correct environment id when starting manually

---

agent/runner/runner.go
cli/cmd/configure_cmd.go
cli/config/agent_token.go
cli/config/config.go
cli/config/configurator.go

This PR makes the default agent api key available in the local config file, making it easier to automate agent related setups
-
-

feat(cli): save default agent token to local config

---

docs/docs/getting-started/configure-trace-ingestion.mdx
examples/getting-started/docker/docker-compose.yaml
examples/quick-start-nodejs/Dockerfile
examples/quick-start-nodejs/docker-compose.yaml
examples/quick-start-nodejs/package.json

docs(getstarted): add Beyla for Docker

---

cli/cmd/dashboard_cmd.go
cli/config/config.go

This PR fixes the `tracetest dashboard` command to use the correct URL. It was directing users to `api.tracetest.io`, resulting in a blank `404` page. 
Now the command will try to use the configured env URL, if no env is set fallback to the `uiEndpoint` ("https://app.tracetest.io"), and ultimately return the api url, which was the original behavior, and requried for OSS
-
-

fix(cli): use correct web dashboard URL

---

cli/pkg/oauth/oauth.go

This PR changes the way the configurator chooses an open port to listen for OAuth callback. Previously, we got a free port by opening a `TCPListener` on port 0, which makes the OS return a port. We then closed the listener and use the port.
The problem is that, some times, at least on MacOS, we can get `port already in use` by the time we want to start the actual listener. 
This PR changes the flow, so instead of closing the port, we keep it open, and we pass it to the http server that handles the OAuth listener.
-
-

fix(cli): reuse port listener on configurator
