kubeshop/tracetest

server/go/analytics/analytics.go
=> fix: error handling

server/go/analytics/analytics.go
=> fix: disable tls check on analytics (unsafe)

README.md
Removed downloads and Go images from readme
This PR...
-
-
=> Removed downloads and Go images

README.md
Added link for Tracetest Blogs
This PR...
-
-
=> Added link for Tracetest Blogs

docs/create-test.md
Fixed broken readme link.
This PR...
-
-
=> docs: Update create-test.md

web/src/components/Header/Header.tsx
=> fix: add keys to submenu

server/assertions/assertions.go, server/assertions/assetions_test.go, server/assertions/comparator/basic.go, server/assertions/comparator/basic_test.go, server/assertions/comparator/comparators.go, server/assertions/comparator/comparators_test.go, server/traces/traces.go, server/traces/traces_test.go
Proposal of the assertion engine, including extensible comparators.
=> Assertions engine

server/http/controller.go, server/main.go, web/src/services/Analytics/Analytics.service.ts, web/src/services/Analytics/TestAnalytics.service.ts, web/src/services/Analytics/TraceAnalytics.service.ts, web/src/services/Analytics/TraceDiagramAnalytics.service.ts
This PR updates the event names to have a better description.
- Updates the event string names.
- https://github.com/kubeshop/tracetest/issues/395
=> 395 updating the event names

.gitignore, web/src/pages/Home/TestList.tsx, web/src/pages/Home/useMenuDeleteCallback.tsx, web/src/redux/apis/Test.api.ts
This PR...
Add an actions column to the test table, this column contains a dropdown with the delete test action. 
- https://github.com/kubeshop/tracetest/issues/400
=> adds delete test actions

server/assertions/selectors/builder.go, server/assertions/selectors/selector_test.go
This PR enables filtering by span name.
=> feat: support filter by span name

docs/advanced-selectors.md
This PR adds documentation on how a user can start writing selectors.
=> add docs on selectors

README.md
Added link near bottom
This PR...
-
-
=> Added link to discorded

web/cypress/integration/Home/CreateTest.spec.ts, web/cypress/integration/Home/ShowTestList.spec.ts, web/cypress/integration/TestDetails/ShowTestDetails.spec.ts, web/cypress/integration/Trace/CreateAssertion.spec.ts, web/cypress/integration/Trace/ShowTrace.spec.ts, web/cypress/integration/utils/Common.ts, web/src/components/AssertionsTable/AssertionsTable.tsx, web/src/components/CreateAssertionModal/CreateAssertionForm.tsx, web/src/components/CreateAssertionModal/CreateAssertionModal.tsx, web/src/components/CreateAssertionModal/CreateAssertionSelectorInput.tsx, web/src/components/Diagram/components/DAG.styled.tsx, web/src/components/Diagram/components/DAG.tsx, web/src/components/SpanDetail/components/GenericSpanDetail.tsx, web/src/components/Trace/Trace.styled.ts, web/src/components/Trace/TraceComponent/Attributes.tsx, web/src/components/Trace/TraceComponent/TestResults.tsx, web/src/components/Trace/TraceComponent/TraceComponent.tsx, web/src/components/TraceAssertionsTable/TraceAssertionsTable.tsx, web/src/components/TraceNode/components/GenericTraceNode.tsx
This PR adds unit tests for the trace view flow.
- Adding `data-cy` tags for the trace view section.
- Re-adds the test results tab that was removed
=> 💣  453 adding integration tests for the trace view

api/trace.yaml, server/http/mappings.go, server/openapi/model_span.go, server/testmock/data/pokeshop_import_pokemon.json, server/testmock/data/pokeshop_import_pokemon_failed_assertions.json, server/traces/otel_converter.go, server/traces/traces.go, server/traces/traces_test.go
This PR adds missing info for spans
=> Add spans extra data

server/migrations/migration_test.go
This PR tests if all migrations work (both applying them and rolling them back). This will ensure all migrations we write work (at least are valid sql files). We can improve that later.
=> test: migrations up and down

server/migrations/4_test_version.up.sql
=> fix migration 4

server/http/controller.go
=> fix rerun id

server/assertions/comparator/basic.go, server/assertions/comparator/basic_test.go
This PR adds >= and <= comparators
- add new comparators
=> Add gte and lte comparators

server/assertions/comparator/basic.go, server/assertions/comparator/basic_test.go
This PR adds a not equal comparator
=> add neq comparator

server/app/app.go, server/http/controller.go, server/http/mappings.go
This PR adds validation for selector uniqueness when setting a test definition
=> add selector uniqueness validation

web/src/components/AssertionForm/AssertionFormProvider.tsx, web/src/components/AttributeRow/AttributeCheck.tsx, web/src/components/ResizableDrawer/ResizableDrawer.tsx, web/src/components/ResizableDrawer/useReferenceMemo.tsx, web/src/components/ResizableDrawer/useSetIsCollapsedCallback.tsx, web/src/components/TestHeader/TestHeader.tsx, web/src/components/TraceDrawer/TraceDrawer.styled.ts, web/src/components/TraceDrawer/TraceDrawer.tsx, web/src/components/TraceDrawer/TraceDrawerHeader.tsx, web/src/components/TraceDrawer/useChevronDirectionMemo.tsx
This PR implements isCollapsable as a state instead of a boolean
- Drawer behavior
- #602
=> new drawer behavior

web/src/components/TestCard/TestCard.tsx
This PR make whole TestCard trigguer onCollapsed flow
- TestCard area
=> make whole TestCard trigguer onCollapsed flow #610

web/src/components/ResizableDrawer/useReferenceMemo.tsx, web/src/components/TestCard/TestCard.tsx
This PR changes new drawer max height
=> new drawer max height

api/http.yaml, api/trace.yaml, cli/file/definition_test.go, cli/testdata/definitions/valid_http_test_definition.yml, cli/testdata/definitions/valid_http_test_definition_with_id.yml
This PR fixes tiny things in the cli
=> fix things in places

docs/installing.md, setup.sh
This PR adds a setup script and related documentation, so it's easier for new users to get started. This command can be run as a single copy/paste without downloading anything.
- add setup script
- add docs
=> Setup script

setup.sh
This PR sends a beacon to GA on successful install using setup script
=> feat: add GA beacon to setup script

server/executor/trace_poller.go, server/http/websocket/messages.go, server/http/websocket/subscribe.go, server/model/run.go, server/subscription/message.go
This PR adds resource to websocket responses.
=> feat: add resource to websocket responses

tracetesting/definitions/tracetest_tests_list.yml
This PR adds the test id to tracetest_test_list so it doesn't duplicate on each run
=> add id to test

.github/workflows/deploy-main.yml
This PR updates the pipeline to deploy main commits to integration in parallel to beta. This allows to keep our integration version automatically updated.
=> update pipeline to deploy main commits to integration

.github/workflows/pull-request.yaml, web/cypress.json
This PR adds cache to npm_modules
=> feat: add npm cache on CI

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/enhancement.md, .github/ISSUE_TEMPLATE/feature_request.md
This PR adds issues templates based on monokle
=> add issues templates based on monokle

web/src/components/AssertionCard/AssertionCardSelectorList.tsx, web/src/models/AssertionResults.model.ts, web/src/services/Selector.service.ts, web/src/services/__tests__/Selector.service.test.ts, web/src/types/Common.types.ts, web/src/types/Generated.types.ts, web/src/utils/Tests.tsx
=> use new selector structure

.github/workflows/deploy-main.yml
This PR configures values for trace poller on integration instance.
-
-
=> set polling config to integration instance

setup.sh
Avoids creating an error of existing helm chart
This PR...
-
-
=> Force install helm repo if it exists

server/executor/poller_executor.go, server/executor/trace_poller.go, server/integration/run_and_assert_pokemon_app_test.go
This PR fixes the polling process. This bug was introduced by #790 
- trace polling. Before this patch, polling was marked as `true` the first time it got executed.
=> fix polling

web/package.json, web/src/redux/slices/DAG.slice.ts, web/src/selectors/DAG.selectors.ts, web/src/selectors/TestDefinition.selectors.ts, web/src/selectors/__tests__/CreateTest.selectors.test.ts, web/src/selectors/__tests__/DAG.selectors.test.ts, web/src/selectors/__tests__/Span.selectors.test.ts, web/src/selectors/__tests__/TestDefinition.selectors.test.ts, web/src/services/GuidedTour.service.ts, web/src/services/__tests__/GuidedTour.service.test.ts, web/src/services/__tests__/Selector.service.test.ts, web/src/services/__tests__/Span.service.test.ts, web/src/services/__tests__/TestDefinition.service.test.ts, web/src/services/__tests__/Trace.service.test.ts, web/src/setupTests.ts, web/src/utils/Common.ts, web/src/utils/__tests__/Common.test.ts
This PR adds a couple of unit tests to the project in order to increase code coverage
=> increase coverage

web/src/constants/SpanAttribute.constants.ts, web/src/selectors/Assertion.selectors.ts, web/src/selectors/Span.selectors.ts, web/src/services/SpanAttribute.service.ts
This PR adds tracetest.selected_spans.count attribute to selectAttributeList
=> add tracetest.selected_spans.count attribute to selectAttributeList

docs/command-line-tool.md
This PR adds a very simple and basic documentation for the CLI
=> docs: basic CLI docs

web/src/components/Diagram/components/DAG/SpanNode.styled.ts, web/src/components/Diagram/components/DAG/SpanNode.tsx, web/src/components/Diagram/components/Timeline/Timeline.tsx, web/src/constants/SemanticGroupNames.constants.ts, web/src/models/Span.model.ts, web/src/models/__tests__/Span.model.test.ts, web/src/types/DAG.types.ts, web/src/types/Span.types.ts
This PR adds the latest `Span Node` design.
- Span Node
- #804
=> Add new Span node design

docs/accessing-dashboard.md, docs/installing.md
Added an accessing dashboard page
This PR...
-
-
=> Added an accessing dashboard page

docs/versioning.md
This PR adds documentation about our versioning mechanism
=> docs: write versioning documentation

server/traces/traces.go, server/traces/traces_test.go
=> fix: parent id in flat structure

web/cypress.json, web/cypress/integration/Trace/CreateAssertion.spec.ts, web/src/components/AssertionForm/AssertionForm.tsx, web/src/components/AssertionForm/AssertionFormCheck.tsx, web/src/components/AssertionForm/AssertionFormCheckList.tsx, web/src/components/AssertionForm/DurationFields.tsx, web/src/components/AssertionForm/hooks/useOnFieldsChange.ts, web/src/constants/Common.constants.ts, web/src/utils/Common.ts
This PR adds specific duration fields for assertion checks
=> add duration fields to AssertionForm

docs/index.md
Update index.md with blog post
This PR...
-
-
=> Update index.md with blog post

.github/workflows/pull-request.yaml, web/cypress.json, web/package.json
This PR configures cypress to run tests in parallel!
=> enhancement: run front-end e2e tests in parallel

web/src/components/CreateTestPlugins/Default/steps/SelectPlugin/SelectPlugin.styled.ts, web/src/components/PluginCard/PluginCard.styled.ts, web/src/components/PluginCard/PluginCard.tsx, web/src/components/RunCard/RunCard.tsx, web/src/components/RunCardList/RunCardList.tsx
This PR implements a couple of UX improvements.
- Adds a Link wrapper for test results cards.
- Fixes the select plugin step
- https://github.com/kubeshop/tracetest/issues/833
- https://github.com/kubeshop/tracetest/issues/866
https://www.loom.com/share/cb7f364ee49f45c18436734a8ece1359
=> 866 multiple minor fixes

README.md
Remove reference to demo site and add link for installing
This PR...
-
-
=> Remove demo reference

.github/workflows/deploy-main.yml, .github/workflows/pull-request.yaml, .github/workflows/release-server.yml, config.tests.yaml, docs/installing.md, docs/run-locally.md, docs/server-configuration.md, server/config.yaml.sample, server/config/config.go, server/config/config_test.go, server/config/testdata/jaeger.yaml, server/config/testdata/tempo.yaml, server/testmock/app.go, server/tracedb/jaegerdb_test.go, server/tracedb/tempodb_test.go, server/tracedb/tracedb.go, server/tracedb/tracedb_test.go, setup.sh
This PR changes how we configure the tracing backend in our configuration file. It requires the [helm chart](https://github.com/kubeshop/helm-charts/pull/201) to be updated before it gets merged.
=> enhance: tracing backend config

README.md
Update Readme to include YAML example.  Also corrected a broken link.
This PR...
-
-
=> Update Readme to include YAML example

README.md
This PR only reorders the fields on the yaml example, adds some comments, and set syntax highlighting
=> Improve test definition in readme

k8s/collector.yml
This PR changes the collector sampling to 100%
=> set sampling as 100%

.github/workflows/deploy-main.yml, .github/workflows/release-server.yml, Dockerfile, docker-compose.yaml, server/Makefile, server/analytics/analytics.go, server/app/app.go, web/public/index.html
This PR allows to have different analytics keys for FE and BE.
=> Use different analytics key for FE and BE

README.md
Fix broken link in the install section
This PR...
-
-
=> Fix broken link in the install section

web/cypress.json
=> revert video set as false

README.md
Added a test section
This PR...
-
-
=> Added a test section

README.md
Added some use cases at the top and moved the Getting Started up.  @mathnogueira is going to followup with a PR on adding the install instructions to the readme
This PR...
-
-
=> Update Readme with

README.md
This PR adds the installation command to the readme file.
=> docs: adding installation command to the readme file

docs/index.md
Added blog post to docs
This PR...
-
-
=> Added blog post to docs

web/cypress/integration/utils/Common.ts
This PR fixes the `create test` step in cypress.
- `create test` step in cypress
-
=> Fix cypress tests

docs/index.md
Update docs with Oscar's blog post
This PR...
-
-
=> Update docs with Oscar's blog post

tracetesting/definitions/grpc_test_create.yml, tracetesting/definitions/grpc_test_create_invalid_metadata.yml, tracetesting/definitions/grpc_test_run.yml, tracetesting/definitions/grpc_test_run_invalid_metadata.yml, tracetesting/definitions/test_create.yml, tracetesting/definitions/test_create_with_id_exists.yml, tracetesting/definitions/test_create_with_id_notexists.yml, tracetesting/definitions/test_delete.yml, tracetesting/definitions/test_list.yml, tracetesting/definitions/test_rerun.yml, tracetesting/definitions/test_run.yml, tracetesting/definitions/test_run_delete.yml
This PR fixes the tracing tests that broke after the triggering span PR was merged. 
-
-
=> add tracetest trigger checks

web/package-lock.json, web/src/components/Diagram/components/DAG/AffectedSpanControls.tsx, web/src/components/Diagram/components/DAG/Controls.tsx, web/src/components/Diagram/components/DAG/DAG.styled.tsx, web/src/components/Diagram/components/DAG/useListenToArrowKeysDown.tsx, web/src/components/Diagram/components/Timeline/SpanNode.tsx, web/src/components/Diagram/components/Timeline/Timeline.tsx, web/src/components/Diagram/components/Timeline/useScrollSpanNodeGroupIntoView.tsx, web/src/components/DiagramSwitcher/DiagramSwitcher.styled.tsx, web/src/components/DiagramSwitcher/DiagramSwitcher.tsx, web/src/providers/Span/Span.provider.tsx
This PR implements #983 
- Add Controls components to Timeline View
- Scroll timeline elements when stepping though affected spans
- add listener so user can step though the diagram using arrow keys
=> add timeline step through

.github/workflows/release-server.yml, .goreleaser.yaml
=> add fury.io integration

web/src/components/AdvancedEditor/AdvancedEditor.tsx, web/src/components/Diagram/components/DAG/useListenToArrowKeysDown.tsx
=> fix bug of step though when advanced selector is focused

.gitignore, api/openapi.yaml, server/http/controller.go, server/model/repository.go, server/openapi/api.go, server/openapi/api_api.go, server/openapi/impl.go, server/testdb/mock.go, server/testdb/tests.go, server/testdb/tests_test.go, web/src/hooks/useInfiniteScroll.ts, web/src/pages/Home/HomeContent.tsx, web/src/pages/Home/TestList.tsx, web/src/redux/apis/TraceTest.api.ts
This PR implements search feature on the home test list
- add query parameter to Get test list
- adds frontend necessary code
=> add search for the test list at frontend home

docs/index.md, mkdocs.yml
Will update the issues once merged.
This PR...
-
-
=> docs: Updates from Issues 1045, 1047 1048 and 1049

.github/workflows/release-server.yml, .goreleaser.yaml, docs/installing.md, install-cli.sh, scripts/fury-upload.sh
This PR updates the CLI install script to support apt and yum repos. It also adds docs on how to use those repos manually
=> Update install cli script docs

docs/test-definition-file.md, server/executor/functions/function_registry.go, server/executor/functions/function_registry_test.go, server/executor/functions/functions.go, server/executor/functions/generators.go, server/executor/functions/parser.go, server/executor/functions/parser_test.go, server/executor/replacer/injector.go, server/executor/replacer/options.go, server/executor/replacer/provider.go, server/executor/replacer/replacer.go, server/executor/replacer/replacer_test.go, server/executor/runner.go, server/go.mod, server/go.sum
This PR adds the capability of using generator functions in your tests. 
Now you can use `{{ function(args) }}` in your test definition to generate the value on the fly.
TODO: Add documentation
=> feat: generator functions

.github/workflows/mkdocs.yml, docs/test-definition-file.md, mkdocs.yml
This PR fixes the table renderization in our docs page.
- table renderization
=> docs: add table support for mkdocs

.github/workflows/mkdocs.yml, mkdocs.yml
This PR adds support for emojis on our doc page.
Now emojis are rendered as images instead of showing up as their codes.
=> docs: emoji support

docs/index.md
Forgot to delete a duplicate video link.
This PR...
-
-
=> docs:Update index.md

docs/index.md
Update with new blog post
This PR...
Adds Francesco's blog to our intro page
=> Update with new blog post

README.md
Add comments in test definition example for  #1042
=> Changing test definition example in readme

docs/test-definition-file.md, server/assertions/comparator/basic.go, server/assertions/comparator/basic_test.go, server/encoding/yaml/conversion/parser/assertion_parser.go, server/encoding/yaml/conversion/parser/assertion_parser_test.go, web/src/constants/Operator.constants.ts, web/src/types/Operator.types.ts
This PR adds a new `not-contains` operator
Related to issues: #823  #977
=> feat: implement not-contains operator

docs/index.md
Update index.md with Cartagena blog
=> Update index.md with Cartagena blog

.github/workflows/deploy-main.yml, .github/workflows/release-server.yml, web/src/components/AdvancedEditor/hooks/useEditorTheme.ts, web/src/components/AssertionForm/hooks/useOnFieldsChange.ts, web/src/components/AssertionForm/hooks/useQuerySelector.ts, web/src/components/CreateTestPlugins/Grpc/steps/RequestDetails/RequestDetails.tsx, web/src/components/CreateTestPlugins/Postman/steps/UploadCollection/UploadCollection.tsx, web/src/components/CreateTestPlugins/Postman/steps/UploadCollection/UploadCollectionForm.tsx, web/src/components/ShadowScroll/ShadowScroll.tsx, web/src/components/SkeletonDiagram/SkeletonDiagram.tsx, web/src/pages/CreateTest/CreateTestContent.tsx, web/src/pages/EditTest/EditTestContent.tsx, web/src/pages/Test/TestDetails.tsx
This PR removes warnings from browser console & developer console
##Fixes
Fixes #975
=> remove developer console logs

docs/installing.md, docs/supported-backends.md, examples/tracetest-signalfx/README.md, examples/tracetest-signalfx/collector.config.yaml, examples/tracetest-signalfx/docker-compose.yml, examples/tracetest-signalfx/tests/list-tests.yaml, examples/tracetest-signalfx/tracetest-config.yaml, server/config/config.go, server/tracedb/signalfxdb.go, server/tracedb/tracedb.go
This PR adds support for signalfx as a tracing backend.
=> feat: add signalfx support

tracetesting/definitions/grpc_test_create.yml, tracetesting/definitions/grpc_test_create_invalid_metadata.yml, tracetesting/definitions/test_create.yml, tracetesting/definitions/test_run.yml
=> fix: grpc tests

.github/workflows/pull-request.yaml, cli/Makefile, cli/installer/docker_compose.go, cli/installer/tracetest.go
This PR fixes the collector config creation when using opensearch
=> fix: installer panics when configuring opensearch

web/src/components/RunDetailTrigger/RunDetailTrigger.styled.ts, web/src/components/SpanDetail/SpanDetail.styled.ts
This PR adds scroll in the `Trigger` section and fixes a style in Drawer (`Run Detail page`)
- CSS styles
-
=> [test run details] Add scroll in Trigger section and fix style in Drawer

server/http/mappings/tests.go, server/model/tests.go
This PR fixes the dry-run endpoint for now
=> fix dry-run endpoint

.github/workflows/pull-request.yaml, cli/installer/docker_compose.go
=> CLI Installer: fix collector settings jaeger default endpoint

cli/analytics/analytics.go, server/analytics/segment.go
This PR configures segment clients to track ip
=> Segment config for tracking ip

web/package-lock.json, web/package.json, web/src/components/CodeBlock/CodeBlock.styled.ts, web/src/components/CodeBlock/CodeBlock.tsx, web/src/components/CodeBlock/index.ts, web/src/components/RunDetailTriggerResponse/ResponseBody.tsx, web/src/components/RunDetailTriggerResponse/RunDetailTriggerResponse.styled.ts, web/src/components/RunDetailTriggerResponse/RunDetailTriggerResponse.tsx, web/src/models/TriggerResult.model.ts, web/src/types/Test.types.ts, web/src/utils/Common.ts
This PR adds FE validations to check if the trigger response is not a JSON, it tries to match it with the supported mime-types coming from the headers info.
- Updates the response body section to match the code editor.
- #1181
=> 1181 adding code block and response validation for the test run trigger

web/cypress/support/commands.ts, web/src/components/Header/HeaderMenu.tsx
This PR disables the current onboarding flow
=> disable onboarding

cli/installer/docker_compose.go, cli/installer/installer.go, cli/installer/kubernetes.go, cli/installer/tracetest.go, cli/installer/util.go, cli/openapi/api_api.go, server/config/config.go
This PR adds support for k8s installer
=> CLI installer: kubernetes

docs/introduction.md, mkdocs.yml
Fix spelling mistake in Navigation. Change "Assertions" to "Test Spec".
This PR...
-
-
=> docs: Misc Updates

server/encoding/yaml/conversion/object_to_yaml_conversion.go, server/encoding/yaml/conversion/object_to_yaml_conversion_test.go
This PR fixes the order of the generated YAML file.
=> feat: ensure order of elements in yaml file

web/cypress/e2e/Home/CreateTest.spec.ts, web/package-lock.json, web/package.json, web/src/components/CreateTestPlugins/Postman/steps/UploadCollection/UploadCollectionForm.tsx, web/src/components/CreateTestPlugins/Rest/steps/RequestDetails/BodyField/BodyField.tsx, web/src/components/CreateTestPlugins/Rest/steps/RequestDetails/BodyField/BodyFieldContainer.tsx, web/src/components/CreateTestPlugins/Rest/steps/RequestDetails/BodyField/SingleLabel.tsx, web/src/components/CreateTestPlugins/Rest/steps/RequestDetails/BodyField/useBodyMode.tsx, web/src/components/CreateTestPlugins/Rest/steps/RequestDetails/BodyField/useLanguageExtensionsMemo.tsx, web/src/components/CreateTestPlugins/Rest/steps/RequestDetails/RequestDetails.tsx, web/src/components/CreateTestPlugins/Rest/steps/RequestDetails/RequestDetailsForm.tsx, web/src/services/Triggers/Http.service.ts, web/src/utils/Validator.ts
This PR make the body fields of the create test form be a code editor 
- the body field 
- #1206
=> make body field a Code editor field

k8s/deploy.sh
This PR fixes the deploy script
=> Fix deploy script

docs/installing.md
This PR updates the install docs
=> update install docs

cli/installer/ui.go
update cli UI to use default colors
-
-
=> use default text style

k8s/deploy.sh
=> fix deploy script script

web/src/components/TestSpecForm/useExpectedInputLanguage.tsx
This PR fixes the autocomplete feature of the `expected` value in the Test Spec form.
- Autocomplete logic for expected field
- fixes #1244
=> Fix autocomplete for expected value in Test Spec form

.github/workflows/pull-request.yaml, examples/collector/docker-compose.yml, examples/docker-compose.demo.yaml, examples/docker-compose.opensearch.yaml, examples/tracetest-jaeger/docker-compose.yml, examples/tracetest-opensearch/docker-compose.yml, examples/tracetest-otel-demo/docker-compose.yaml, examples/tracetest-signalfx/docker-compose.yml, examples/tracetest-tempo/docker-compose.yml
=> Avoid exposing not required ports in docker comopse examples

web/src/components/AttributeRow/AttributeRow.tsx, web/src/components/Drawer/Drawer.tsx, web/src/components/RunDetailTrace/Visualization.tsx
This PR makes sure trace details drawer open when clicking a span within Trace mode
- add a Drawer context
- #1239
=> improve trace mode interactions

.github/workflows/pull-request.yaml
This PR updates the pull requiest pipeline integration port forwarding to the new port.
=> fix integration server port

docs/index.md, mkdocs.yml
Change Google analytics code so docs reports to same account as the tracetest.io site and add Oscars blog
=> Change Google analytics code and add blog

docs/index.md, mkdocs.yml
=> Change google analytics code for docs 

web/src/components/TestCard/TestCard.styled.ts, web/src/components/TestCard/TestCard.tsx, web/src/utils/Date.ts
This PR fixes some of the issues @olha23 found on the beta environment, focused on the test card component styles.
- Updates Test card styles
- https://github.com/kubeshop/tracetest/issues/1353
=> 1353 fixing test card styles

k8s/deploy.sh
=> fix deployments

docs/expressions.md, mkdocs.yml
This PR adds documentation about the new features of the expression engine
=> docs: new expressions

web/cypress/e2e/TestRunDetail/CreateAssertion.spec.ts, web/cypress/e2e/TestRunDetail/NewFlows.spec.ts, web/cypress/e2e/TestRunDetail/TestRunDetail.spec.ts, web/cypress/support/commands.ts, web/cypress/support/index.d.ts, web/src/components/AttributeRow/AttributeRow.tsx, web/src/components/SpanDetail/Attributes.tsx
This PR adds new e2e tests to deal with ticket #1327 
- add new test suites
=>  add new cypress test suite to fix tech debt

docs/index.md
Correct duplicate link and add video presentation from Dublin
=> Correct duplicate link and add video presentation

docs/expressions.md, server/assertions/assertions.go, server/expression/benchmark_test.go, server/expression/data_store.go, server/expression/executor.go, server/expression/executor_test.go, server/expression/parser.go, server/expression/parser_rules.go, server/expression/parser_test.go, server/expression/types/types.go, server/expression/variable.go
This PR allow users to reference variables in expressions.
=> feat: support variables in expressions

README.md, docs/index.md
Replace video in intro of docs,  correct error between description and actual yaml test, and add to description
=> Replace video & correct error

ci-cd-best-practices.md, ci-cd-overview.md, command-line-tool.md
This PR removes old files that didn't contain any content.
=> chore: remove empty markdown files from the project's root directory

.github/workflows/release-version.yml, scripts/choco/tools/chocolateyinstall.ps1, scripts/choco/tracetest.nuspec
This PR updates the chocolatey deploy with changes suggested by the chocolatey bot and makes the repo configurable.
=> patch: update chocolatey deploy

README.md
Change to using caps for HTTP and SQL
=> Change to using caps

Dockerfile
This PR adds the CLI to the docker image.
=> feat: add cli to docker image

Dockerfile
=> fix: docker image

README.md
=> Update readme with tag line

docs/index.md
Updated docs to show new tag line
=> Updated docs to show new tag line

cli/analytics/analytics.go, server/analytics/segment.go
This PR fixes an issue with the Identify call. It was missing user ID and being quietly rejected.
-
-
=> fix analytics

server/expression/parser_test.go, server/expression/str.go
This PR fixes the variable resolution
=> fix: don't remove escape backslashes

server/http/controller.go
This PR fixes the algorithm for grouping transactions and tests.
=> fix resource listing endpoint

server/executor/assertion_runner.go, server/executor/runner.go, server/executor/transaction_runner.go, server/http/controller.go
=> fix: create new context for running the transaction

server/testdb/transactions.go
This PR fixes the bug where steps would not be removed from the step list of a transaction after an update.
=> fix: delete existing steps before registering new ones

server/executor/transaction_runner.go
This PR makes tracetest save the environment after each step is executed.
=> fix: save environment after each step is executed

server/testdb/transactions.go, web/src/pages/Transaction/Content.tsx, web/src/pages/TransactionRunDetail/TransactionRunDetail.tsx, web/src/providers/Transaction/Transaction.provider.tsx, web/src/providers/TransactionRun/TransactionRunProvider.tsx, web/src/redux/apis/TraceTest.api.ts, web/src/redux/apis/endpoints/Transaction.endpoint.ts, web/src/types/Generated.types.ts
This PR adds transaction versioning check, including a fix to the backend transaction services.
- Integrates versioning for transactions
- [[Transactions] Websockets and Versioning for Transactions#1491](https://github.com/kubeshop/tracetest/issues/1491) (Partially)
=> 1491 adding transaction versioning

k8s/tracetest.beta.yaml
This PR enables transactions for the beta env 😁
=> enabling transactions feature in beta env

server/executor/trace_poller.go, server/executor/transaction_runner.go, server/executor/transaction_runner_test.go, server/testdb/transactions.go, server/testdb/transactions_runs_test.go, server/testdb/transactions_test.go
This PR fixes the bugs reported in #1495
=> fix: transaction problems

web/src/pages/Environments/Environment.styled.tsx, web/src/pages/Environments/EnvironmentContent.tsx
This PR fixes a couple of styles in the Environments page
- Styles environments page
- fixes #1500
=> Fix environment page header

web/src/components/TestSpecDetail/Assertion.tsx, web/src/components/TestSpecDetail/TestSpecDetail.styled.ts, web/src/pages/TransactionRunDetail/TransactionRunDetail.tsx
This PR fixes a small alignment bug for the assertion results.
- Fixes styles
- #1501
=> 🐛 Fixing assertion result alignment

web/src/components/TestState/TestState.tsx, web/src/components/TransactionRunResult/ExecutionStep.tsx, web/src/components/TransactionRunResult/TransactionRunResult.tsx, web/src/constants/TestRun.constants.ts, web/src/types/TestRun.types.ts
This PR fixes some small UI issues.
- Fixes execution step failed icon.
- Enables default status for waiting and skipped tests.
- [[Transactions] Fix misc UI bugs#1520](https://github.com/kubeshop/tracetest/issues/1520)
=> 1520 fixing several UI issues

server/executor/transaction_runner.go, server/http/mappings/tests.go, server/http/websocket/subscribe.go, server/model/transactions.go
This PR makes websocket notifications send trigger info and test result.
=> fix: transaction ws notifications

.github/workflows/pull-request.yaml, k8s/tracetest.beta.yaml, k8s/tracetest.demo.yaml, web/public/index.html, web/src/components/Layout/Layout.tsx, web/src/components/Router/Router.tsx, web/src/components/RunCard/TestRunCard.tsx, web/src/components/RunCard/TransactionRunCard.tsx, web/src/components/RunDetailTriggerResponse/RunDetailTriggerResponse.tsx, web/src/components/TestHeader/TestHeader.tsx, web/src/pages/Home/HomeActions.tsx, web/src/pages/Test/Content.tsx, web/src/pages/Transaction/Content.tsx
- https://github.com/kubeshop/tracetest/issues/1506
=> Remove transactions experimental feature flag

web/cypress/e2e/Environments/Environments.spec.ts, web/src/components/EnvironmentForm/EnvironmentForm.tsx, web/src/pages/Environments/EnvironmentCard.tsx
This PR adds e2e tests for the new environments page.
- Cypress 2e2 test
- fixes #1527
=> test: add e2e tests for environments page

web/src/components/GuidedTour/StepContent.styled.tsx, web/src/components/Layout/Layout.styled.ts, web/src/components/ResourceCard/ResourceCard.styled.ts
This PR changes the main application color  as suggested on #1533
=> change main "red" color

server/executor/runner.go, server/executor/trigger/http.go
This PR configures more limited http trigger timeouts. By default go is very relaxed on timeouts, so that might lead to trigger workers exhaustion
=> fix(server): set http trigger timeouts

server/executor/assertion_runner.go, server/executor/poller_executor.go, server/executor/trace_poller.go
=> fix(server): add logging to detect freezing behavior

cli/go.mod, cli/go.sum, server/http/controller.go, server/model/yaml/encoding.go, server/model/yaml/test.go, server/model/yaml/testdata/test_http.yaml, server/model/yaml/testdata/transaction.yaml, web/src/types/Generated.types.ts
=> fix definition file export endpoint

server/app/app.go, server/executor/assertion_runner.go, server/executor/runner.go, server/executor/runner_test.go, server/executor/trace_poller.go, server/executor/transaction_runner.go, server/executor/transaction_runner_test.go, server/http/controller.go, server/model/run.go
=> fix: replace channels with subscription manager

web/src/components/TransactionPlugin/steps/TestsSelection/TestsSelectionInput/TestsSelectionInput.tsx
This PR fixes a useEffect loop in the transaction form.
- Fix useEffect loop
-
=> fix(frontend): fix useEffect loop in transaction form

docs/docusaurus.config.js
This PR edits the docs GTM token.
-
-
=> docs(gtm): update id

web/src/constants/Common.constants.ts
This PR fixes a broken link in the FE
- fix broken link
- fixes #1617
=> fix(frontend): fix broken documentation link

docs/docusaurus.config.js
This PR adds Algolia DocSearch.
-
-
=> docs(search): update algolia config

docs/docusaurus.config.js
This PR changes the API key for Algolia to work.
-
-
=> docs(search): change api key

docs/docusaurus.config.js
This PR tries to fix the search feature on our documentation page.
=> fix: update algolia index name

demo/create-pokemon.yaml, demo/transaction.yaml, docs/docusaurus.config.js
=> Fix: api key and app id in doc search plugin

docs/docusaurus.config.js
=> disable contextual search on docusaurus search plugin

api/config.yaml, api/openapi.yaml, web/src/types/Generated.types.ts
This PR adds the initial openAPI definition for the config services
- Includes the open API changes
- Adds the definitions for data stores and exporters
=> feature(backend): config services open api definition

docs/docs/examples-tutorials/recipes/running-tracetest-with-jaeger.md, docs/docs/examples-tutorials/recipes/running-tracetest-with-opensearch.md, docs/docs/examples-tutorials/recipes/running-tracetest-with-tempo.md, docs/docs/examples-tutorials/recipes/running-tracetest-without-a-trace-data-store.md, examples/quick-start-jaeger-nodejs/readme.md, examples/quick-start-nodejs/readme.md, examples/quick-start-opensearch-nodejs/readme.md, examples/quick-start-tempo-nodejs/readme.md
This PR edits the recipes section's explanation for Postgres.
=> docs(recipes): edit postgres explanation

web/src/components/Settings/DataStore/DataStore.styled.ts, web/src/components/Settings/DataStore/DataStore.tsx, web/src/components/Settings/DataStoreForm/DataStoreForm.tsx, web/src/constants/DataStore.constants.ts, web/src/providers/DataStore/DataStore.provider.tsx, web/src/services/DataStore.service.ts
This PR updates several parts of the in app config section to match the new requirements and designs.
- Updates documentation links
- Changes the save/test connection buttons position
- Adds the delete button and logic
- 1657
https://www.loom.com/share/ae0438fd6a4d40db87fc3bdf80dcaea5
=> feature(frontend): multiple in app config updates

docs/docs/getting-started/cli.md, docs/docs/getting-started/docker.md, docs/docs/getting-started/installation.md, docs/sidebars.js
This PR improves the getting started section and sub-pages.
Live preview: https://beautiful-flan-fc263f.netlify.app/getting-started/installation
- Quick start section
- #1678
=> docs(quick-start): update getting started section

go.work.sum, server/app/app.go, server/app/facade.go, server/executor/transaction_runner.go, server/http/controller.go, server/http/controller_test.go, server/http/spa.go
This PR is a tiny cleanup refactor. it does nothing functionally, other than reorganizing the app Start func so it's a bit more concise. Also unifies all the controller's runner dependencies into a facade, so the arg passing is less crowded
-
-
=> chrore(server): refactor app for readability

server/tracedb/tempodb.go
This PR adds the tempo test connection logic and matches whatever we have for the jaeger db as its the same GRPC client.
- Adds the tempo db test connection logic
- #1702
=> feature(backend): adding tempo test connection logic

web/package-lock.json, web/package.json, web/src/components/Settings/DataStorePlugin/forms/SignalFx/SignalFx.tsx, web/src/components/TestConnectionNotification/TestConnectionNotification.styled.ts, web/src/components/TestConnectionNotification/TestConnectionNotification.tsx, web/src/components/TestConnectionNotification/TestConnectionStep.tsx, web/src/constants/Theme.constants.ts, web/src/models/ConnectionResult.model.ts, web/src/models/ConnectionResultStep.model.ts, web/src/providers/DataStore/DataStore.provider.tsx, web/src/providers/DataStore/hooks/useTestConnectionNotification.tsx, web/src/redux/apis/endpoints/Config.endpoint.ts, web/src/services/DataStore.service.ts, web/src/styled.d.ts, web/src/types/Config.types.ts
This PR adds the front-end notification to match the backend changes to the contract and designs.
- Adds data store test connection notification logic
- #1679 
https://www.loom.com/share/55d5f159df4545a3b85cdbba384508e5
=> feature(frontend): adding frontend test connection notification

api/dataStores.yaml, cli/actions/apply_datastore_action.go, cli/formatters/datastore_list.go, cli/openapi/model_data_store.go, server/openapi/model_data_store.go
This PR makes the server validate name and type fields
=> fix: validate data store name and type fields

web/src/providers/DataStore/DataStore.provider.tsx
This PR fixes the delete data store confirmation message.
- Delete data store confirmation message
-
=> fix(frontend): fix delete data store confirmation message

web/src/components/TestConnectionNotification/TestConnectionNotification.styled.ts, web/src/components/TestConnectionNotification/TestConnectionNotification.tsx, web/src/components/TestConnectionNotification/TestConnectionStep.tsx, web/src/providers/DataStore/hooks/useDataStoreNotification.tsx
This PR improves the data store `Test Connection` message.
- Data Store Test Connection message
-
| Before  | Now |
| ------------- | ------------- |
| ![Screenshot 2022-12-27 at 16 41 31](https://user-images.githubusercontent.com/3879892/209725340-7f4c81af-6037-484c-b508-bd5e71980b7b.png)  |  ![Screenshot 2022-12-27 at 16 42 45](https://user-images.githubusercontent.com/3879892/209725370-6338d454-f143-4200-94a1-0e7affc514cb.png) |
| ![Screenshot 2022-12-27 at 16 41 53](https://user-images.githubusercontent.com/3879892/209725341-a450bd9a-6cb2-4cee-b807-a63e1f2cf30d.png)  | ![Screenshot 2022-12-27 at 16 45 03](https://user-images.githubusercontent.com/3879892/209725374-42124b5c-bccf-472f-83e2-f9b5f06e4c9c.png) |
=> fix(frontend): improve data store connection message

server/tracedb/jaegerdb.go, server/tracedb/opensearchdb.go, server/tracedb/signalfxdb.go, server/tracedb/tempodb.go
This PR fixes the Test Connection result which was not including the `connectivity`/`authentication` info if the next step fails.
- Fix test connection results
- fixes #1751 
| Use case  | Example |
| ------------- | ------------- |
| All passed  | ![Screenshot 2022-12-29 at 12 32 01](https://user-images.githubusercontent.com/3879892/209989319-77848bb1-6498-471d-b037-75ce4827ddc0.png)  |
| Fetch traces fails  |  ![Screenshot 2022-12-29 at 12 32 35](https://user-images.githubusercontent.com/3879892/209989355-ba7b0cce-b6ab-4f30-b226-1dfc0ef287ca.png) |
| Auth fails  |  ![Screenshot 2022-12-29 at 12 32 16](https://user-images.githubusercontent.com/3879892/209989377-fb3297c7-4a7f-4ebc-829a-eeb7c6699e32.png) |
| Connectivity fails  |  ![Screenshot 2022-12-29 at 12 32 …
=> fix(server): fix test data store connection results

web/src/components/AttributeRow/AttributeTitle.tsx, web/src/components/CreateTestPlugins/Grpc/steps/RequestDetails/RequestDetails.styled.ts, web/src/components/CreateTestPlugins/Grpc/steps/RequestDetails/RequestDetailsForm.tsx, web/src/components/CreateTestPlugins/Postman/steps/UploadCollection/UploadCollection.styled.ts, web/src/components/CreateTestPlugins/Postman/steps/UploadCollection/UploadCollectionForm.tsx, web/src/components/OutputModal/OutputModal.styled.ts, web/src/components/Settings/DataStorePlugin/forms/OpenTelemetryCollector/OpenTelemetryCollector.styled.ts, web/src/pages/Environments/EnvironmentModal.styled.ts
This PR fixes several small UI problems found on the create test modal, environment modal and some other components.
- Fixes spacing issues
- Fixes button aligments
- #1735 
- #1731 
- #1710
=> fix(frontend): fixing minor UX/UI issues

web/src/services/DataStores/ElasticSearch.service.ts
This PR fixes an uncaught promise in the Elastic Search validation service.
- fix elastic search validation
-
=> fix(frontend): fix elastic search validation

examples/tracetest-elasticapm-with-otel/tracetest-config.yaml
This PR fixes the tracetest config for the ElasticAPM example
- tracetest datastore config
-
=> fix(examples): fix elastic apm tracetest config

web/src/constants/DataStore.constants.tsx
This PR fixes the documentation links for new relic and elastic apm
=> fix(frontend): fixing documentation links

examples/tracetest-elasticapm-with-elastic-agent/README.md, examples/tracetest-elasticapm-with-elastic-agent/docker-compose.yaml, examples/tracetest-elasticapm-with-otel/README.md, examples/tracetest-elasticapm-with-otel/docker-compose.yaml
This PR aims to add TRACETEST_DEV flag and fix minor details on Elastic APM provider doc
- Updated README on examples with Elastic APM
=> fix(docs): added TRACETEST_DEV flag and fixed minor details on doc

examples/keptn-integration/README.md, examples/keptn-integration/job-config.yaml, examples/keptn-integration/shipyard.yaml
This PR update Keptn integration docs to use the new Tracetest image and to fix some documentation steps.
=> update(docs): updating Keptn integration docs

web/src/components/CreateTestPlugins/Default/steps/BasicDetails/BasicDetailsForm.tsx, web/src/services/Test.service.ts
This PR removes the required rule for a test description (create/edit flow)
- remove required rule in test basic details form
- fixes #1853
=> fix(frontend): remove required test description

examples/keptn-integration/README.md, examples/keptn-integration/tracetest-cli-config.yaml
This PR will improve the documentation of Keptn integration based on recent feedback from Keptn team.
- Update examples/keptn-integration/README.md
=> fix(docs): adding Keptn doc suggestions

web/src/components/CreateTestPlugins/TraceID/steps/VariableName/VariableName.tsx, web/src/components/KeyValueRow/KeyValueRow.styled.ts, web/src/components/TestSpecForm/TestSpecForm.tsx, web/src/components/TestSpecForm/hooks/useOnValuesChange.ts, web/src/components/TransactionRunResult/ExecutionStep.tsx, web/src/components/TransactionRunResult/TransactionRunResult.styled.ts
This PR fixes multiple small UX/UI issues across the application.
- #1774 
- #1808 
- #1852 
- #1866
=> fix(frontend): multiple UX-UI fixes

docs/docs/configuration/connecting-to-data-stores/elasticapm.md, docs/docs/examples-tutorials/recipes/running-tracetest-with-elasticapm.md, docs/sidebars.js, examples/tracetest-elasticapm-with-elastic-agent/README.md, examples/tracetest-elasticapm-with-elastic-agent/elastic-apm-agent.js
This PR adds config docs and a recipe for the Elastic integration.
-
-
=> docs(es): add es docs and recipe

examples/tracetest-k6/README.md, examples/tracetest-k6/import-pokemon.js
This PR updates the k6 example readme and test to match the latest features we have added to the binary.
- Non-zero status code result
- Merging summary from both tracetest and the default one
- https://github.com/kubeshop/xk6-tracetest/issues/1
https://www.loom.com/share/9d79af725f8441c1990efde61062efd2
=> chore(k6): update examples and readme

examples/tracetest-k6/README.md, examples/tracetest-k6/import-pokemon.js, server/model/traceid.go
=> Fix traceid variable

cli/actions/run_test_action.go, cli/openapi/api_api.go, cli/ui/ui.go, go.work.sum, server/http/controller.go
This PR makes the CLI ask for missing variables
=> feat: ask for missing variables in the CLI

docs/docs/tools-and-integrations/integrations/k6.md
This PR fixes the loom video embed styles for the k6 docs.
=> fix(docs): fixing k6 docs

cli/Makefile
=> pin goreleaser version

.github/workflows/deploy-main.yml, .github/workflows/pull-request.yaml, .goreleaser.yaml
This PR does some post merge fixes in pipelines
=> chore: post merge fixes

docs/docs/tools-and-integrations/integrations/keptn.md, examples/keptn-integration/job-config.yaml
This PR updates Keptn docs based on feedbacks by Keptn team
- Update Keptn integration page
- Update examples in `examples/keptn-integration`
=> chore(docs): update keptn integration docs based on external feedbacks

docs/docs/getting-started/installation.md
This PR fixes a note in the docker compose installation notes.
- fix docs
-
=> fix(docs): fix docker compose installation note

cli/formatters/test_run.go, cli/formatters/test_run_test.go
=> fix: CLI tests

server/http/controller.go
This PR makes the CreateEnvironment check if the id exists every time.
=> fix: check if env id exists every time

web/package-lock.json, web/package.json, web/src/services/Analytics/Analytics.service.ts
This PR includes PostHog as part of the FE analytics service.
- Install PostHog package
- PostHog init method
- PostHog pageview event
- fixes #1941 
https://www.loom.com/share/291cdfb507594cecba2a66422955fc47
=> feat(frontend): add posthog script

docs/docs/examples-tutorials/recipes/running-tracetest-with-lightstep.md
=> Fix small typo on Lightstep docs

web/src/components/CreateTestPlugins/Rest/steps/RequestDetails/RequestDetails.tsx, web/src/components/CreateTestPlugins/Rest/steps/RequestDetails/RequestDetailsUrlInput.tsx
This PR fixes a bug with a required field (url) in the Test Create modal
- Fix required URL in Test Create modal
- fixes #2022
=> fix(frontend): fix required URL in test create form

web/src/components/Empty/Empty.styled.ts, web/src/components/Empty/Empty.tsx, web/src/components/TestSpecForm/TestSpecForm.tsx, web/src/pages/Environments/EnvironmentList.tsx, web/src/pages/Home/HomeFilters.tsx, web/src/pages/Home/Resources.tsx
This PR updates the empty state for both tests and environments to follow the new UX/UI styles.
- Updates the empty component with new styles.
- #2004 
https://www.loom.com/share/d1d0da28970346b1b8cbf926879dfcf1
=> feature(frontend): updating empty state UX/UI

web/src/components/CreateSteps/CreateStepFooter.tsx
This PR renames the `Create` button to `Create & Run`
- Rename button
- fixes #2047
=> fix(frontend): rename create test button

.github/workflows/pull-request.yaml, cli/smoketest/run.bash, docs/docs/examples-tutorials/recipes/running-tracetest-with-datadog.md, docs/sidebars.js, examples/tracetest-datadog/README.md, examples/tracetest-datadog/tracetest/tracetest.config.yaml
This PR updates our Datadog examples to work correctly with our poller today.
- Update Datadog docs
- Add polling changes on Tracetest Datadog example
=> Update Datadog example documentation

web/src/components/Settings/DataStorePlugin/forms/ElasticSearch/AddressesList.tsx, web/src/components/Settings/DataStorePlugin/forms/ElasticSearch/ElasticSearch.tsx, web/src/components/Settings/DataStorePlugin/forms/GrpcClient/GrpcClient.tsx, web/src/components/Settings/DataStorePlugin/forms/SignalFx/SignalFx.tsx, web/src/constants/DataStore.constants.tsx
This PR improves the `endpoint` hints when setting up a trace data store.
- Fix/improve data store endpoint placeholders
- fixes #2050
=> fix(frontend): improve data store endpoint placeholder

server/otlp/server.go
This PR is based on the issue discovered by @danielbdias where the otlp endpoint was updating the trace even after the polling was complete.
- #1563
=> fix: drop spans from tests that are not polling

cli/openapi/api_api.go, server/tracedb/connection/port_linting.go, server/tracedb/connection/port_linting_test.go, server/tracedb/elasticsearchdb.go, server/tracedb/jaegerdb.go, server/tracedb/opensearchdb.go, server/tracedb/tempodb.go
This PR improves the message showed when user is using a port which might be incorrect for a data store.
=> feat: improve message for port checking

docs/docs/examples-tutorials/recipes/running-tracetest-with-jaeger.md, docs/docs/examples-tutorials/recipes/running-tracetest-without-a-trace-data-store.md, examples/tracetest-datadog/tracetest/tracetest.config.yaml, examples/tracetest-elasticapm-with-elastic-agent/docker-compose.yaml, examples/tracetest-elasticapm-with-elastic-agent/tracetest-config.yaml, examples/tracetest-elasticapm-with-elastic-agent/tracetest-provision.yaml, examples/tracetest-elasticapm-with-otel/docker-compose.yaml, examples/tracetest-elasticapm-with-otel/tracetest-config.yaml, examples/tracetest-elasticapm-with-otel/tracetest-provision.yaml, examples/tracetest-jaeger/docker-compose.yml, examples/tracetest-jaeger/tracetest-config.yaml, examples/tracetest-jaeger/tracetest-provision.yaml, examples/tracetest-signalfx/docker-compose.yml, examples/tracetest-signalfx/tracetest-config.yaml, examples/tracetest-signalfx/tracetest-provision.yaml, examples/tracetest-tempo/docker-compose.yml, examples/tracetest-tempo/tracetest-config.yaml, examples/tracetest-tempo/tracetest-provision.yaml
=> docs: update examples config an documentation

docs/docs/examples-tutorials/recipes/running-tracetest-with-lightstep.md, docs/docs/examples-tutorials/recipes/running-tracetest-with-new-relic.md, examples/tracetest-k6/docker-compose.yml, examples/tracetest-k6/tracetest-config.yaml, examples/tracetest-k6/tracetest-provision.yaml, examples/tracetest-lightstep-otel-demo/README.md, examples/tracetest-lightstep-otel-demo/docker-compose.yaml, examples/tracetest-lightstep-otel-demo/tracetest/tracetest-provision.yaml, examples/tracetest-lightstep-otel-demo/tracetest/tracetest.config.yaml, examples/tracetest-lightstep/tracetest/docker-compose.yaml, examples/tracetest-lightstep/tracetest/tracetest-provision.yaml, examples/tracetest-lightstep/tracetest/tracetest.config.yaml, examples/tracetest-new-relic-otel-demo/README.md, examples/tracetest-new-relic-otel-demo/docker-compose.yaml, examples/tracetest-new-relic-otel-demo/tracetest/tracetest-provision.yaml, examples/tracetest-new-relic-otel-demo/tracetest/tracetest.config.yaml, examples/tracetest-new-relic/tracetest/docker-compose.yaml, examples/tracetest-new-relic/tracetest/tracetest-provision.yaml, examples/tracetest-new-relic/tracetest/tracetest.config.yaml
This PR fixes config/docs for the following examples:
- tracetest-k6
- tracetest-lightstep
- tracetest-lightstep-otel-demo
- tracetest-new-relic
- tracetest-new-relic-otel-demo
- tracetest-no-tracing
-
-
=> fix(examples): fix config examples and docs

server/traces/otel_http_converter.go
This PR fixes the time conversion from grafana cloud
=> fix: time conversion from grafana cloud

docs/docs/examples-tutorials/recipes.md, docs/sidebars.js, examples/tracetest-open-telemetry-store-demo/README.md, examples/tracetest-open-telemetry-store-demo/docker-compose.yml, examples/tracetest-open-telemetry-store-demo/tracetest-config.yaml, examples/tracetest-open-telemetry-store-demo/tracetest-provision.yaml, examples/tracetest-opensearch/README.md, examples/tracetest-opensearch/docker-compose.yml, examples/tracetest-opensearch/tracetest-config.yaml, examples/tracetest-opensearch/tracetest-provision.yaml, examples/tracetest-otel-demo/README.md, examples/tracetest-provisioning-env/README.md
This PR updates the docs and examples for:
- tracetest-open-telemetry-store-demo
- tracetest-opensearch
- tracetest-otel-demo
- tracetest-provisioning-env
=> Updating examples with our latest config changes

server/config/analytics.go, server/config/config.go, server/config/demo_test.go, server/config/old_config.go, server/config/options.go, server/config/util.go
This PR does some code cleanup and reordering, so files are smaller, more cohesive, and easier to follow
=> chore(server): Cleanup config package

k8s/deploy.sh, server/http/mappings/data_store.go
This PR removes a tmp fix on the deploy script. The helm chart is now corrected, so we can fully rely on it
=> fix(ci): remove tmp fix on deploy script

k8s/deploy.sh
=> fix beta deploy

api/config.yaml
This PR fixes a bug on OpenAPI definition introduced on #2131
=> Fixing definition for config

Makefile
=> fix makefile error when trying to regenerate openapi spec

Makefile, api/config.yaml, api/openapi.yaml
This PR aims to add OpenAPI definitions for Demo resources
- Added definitions on ./api/openapi.yaml
- https://github.com/kubeshop/tracetest/issues/2063
=> Add Demo open api definitions

.github/workflows/deploy-demo.yml, .github/workflows/deploy-main.yml, .github/workflows/pull-request.yaml, .github/workflows/release-candidate.yml, .github/workflows/release-version.yml, Makefile
This PR updates goreleaser versions
=> chore: upgrade goreleaser version

docs/docs/examples-tutorials/recipes/running-tracetest-with-aws-terraform.md, docs/docs/examples-tutorials/recipes/running-tracetest-with-aws-x-ray-adot.md, docs/docs/examples-tutorials/recipes/running-tracetest-with-aws-x-ray-pokeshop.md, docs/docs/examples-tutorials/recipes/running-tracetest-with-aws-x-ray.md, docs/docs/examples-tutorials/recipes/running-tracetest-with-datadog.md, docs/docs/examples-tutorials/recipes/running-tracetest-with-elasticapm.md, docs/docs/examples-tutorials/recipes/running-tracetest-with-jaeger.md, docs/docs/examples-tutorials/recipes/running-tracetest-with-lightstep.md, docs/docs/examples-tutorials/recipes/running-tracetest-with-new-relic.md, docs/docs/examples-tutorials/recipes/running-tracetest-with-opensearch.md, docs/docs/examples-tutorials/recipes/running-tracetest-with-step-functions-terraform.md, docs/docs/examples-tutorials/recipes/running-tracetest-with-tempo.md, docs/docs/examples-tutorials/recipes/running-tracetest-without-a-trace-data-store.md, examples/tracetest-amazon-x-ray-adot/tracetest.provision.yaml, examples/tracetest-datadog/tracetest/tracetest-config.yaml, examples/tracetest-lightstep-otel-demo/tracetest/tracetest-provision.yaml, examples/tracetest-lightstep-otel-demo/tracetest/tracetest.config.yaml, examples/tracetest-lightstep/tracetest/tracetest-provision.yaml, examples/tracetest-lightstep/tracetest/tracetest.config.yaml, examples/tracetest-new-relic/tracetest/tracetest.config.yaml
This PR aims to update recipe documentation considering the new Resources configuration.
Fixes https://github.com/kubeshop/tracetest/issues/2170.
=> Fix recipes documentation to consider resources

examples/tracetest-new-relic-otel-demo/docker-compose.yaml, examples/tracetest-otel-demo/docker-compose.yaml, examples/tracetest-otel-demo/tracetest-config.yaml, examples/tracetest-otel-demo/tracetest-provision.yaml, server/model/data_stores.go
This PR fixes a couple of examples related to the issue #2169
=> fix: examples

examples/quick-start-grafana-cloud-tempo-nodejs/tracetest/collector.config.yaml, examples/quick-start-grafana-cloud-tempo-nodejs/tracetest/tracetest-config.yaml, examples/quick-start-grafana-cloud-tempo-nodejs/tracetest/tracetest-provision.yaml, examples/quick-start-jaeger-nodejs/tracetest/tracetest.config.yaml, examples/quick-start-opensearch-nodejs/tracetest/tracetest-config.yaml, examples/quick-start-tempo-nodejs/tracetest/tracetest-config.yaml
This PR aims to fix configs in examples to support Resources
- #2169
=> Fix config in examples

docs/docs/tools-and-integrations/testkube.md
This PR updates the Testkube integration docs with some fixes/improvements.
- Testkube integration docs
-
=> docs: improve testkube executor docs

docs/docs/examples-tutorials/recipes/running-tracetest-with-testkube.md, docs/sidebars.js, examples/tracetest-testkube-executor/README.md
This PR adds a detailed recipe for running Tracetest with Testkube.
-
-
=> docs(recipes): add testkube 

docs/docs/getting-started/detailed-installation.md
=> fix detailed install docs

cli/installer/docker_compose.go, cli/installer/kubernetes.go, cli/installer/templates/config.yaml.tpl, cli/installer/templates/provision.yaml.tpl, cli/installer/tracetest.go, examples/collector/docker-compose.yml
=> Fix cli installer

docs/docs/examples-tutorials/recipes/running-tracetest-with-testkube.md
This PR fixes a typo in the Testkube recipe.
-
-
=> docs(recipes): fix testkube

TESTING.md
This PR aims to update our Testing Checklist considering the latest discoveries that we had yesterday releasing v0.11.1
- Changed TESTING.md
=> Changing checklist to improve formatting and removing automated steps

api/testEvents.yaml, cli/openapi/model_test_run_event.go, server/migrations/24_add_test_run_events_title.down.sql, server/migrations/24_add_test_run_events_title.up.sql, server/model/test_run_event.go, server/openapi/model_test_run_event.go, server/testdb/test_run_event.go, server/testdb/test_run_event_test.go, web/src/types/Generated.types.ts
This PR adds a new field "title" to test run events
=> feat: add title to test run events

server/app/facade.go, server/executor/runner.go, server/executor/runner_test.go, server/model/events/events.go
This PR adds events when triggering tests
=> feat: add trigger resolve and execution events

server/executor/assertion_runner.go, server/model/tests.go
=> Adding safe method to get SpanID on assertion

docs/docs/live-examples/pokeshop/use-cases/add-pokemon.md
This PR...
- The command tracetest test -d test-definition.yml --wait-for-results was missing run. Fiixed it !
-
=> Update Pokeshop use-cases docs typos

docs/docs/configuration/server.md
Add in server section in server config file
This PR...
-
-
=> Add in server section in server config file

.github/workflows/pull-request.yaml, web/src/components/RunCard/RunCard.styled.ts, web/src/components/RunCard/TestRunCard.tsx, web/src/components/RunDetailLayout/HeaderRight.tsx, web/src/components/RunDetailLayout/RunDetailLayout.styled.ts, web/src/components/RunDetailTest/Visualization.tsx, web/src/components/RunDetailTrace/Visualization.tsx, web/src/components/RunEvents/RunEvents.styled.ts, web/src/components/RunEvents/RunEventsTrace.tsx, web/src/components/RunEvents/TraceHeader/FailedTraceHeader.tsx, web/src/components/RunEvents/TraceHeader/FailedTriggerHeader.tsx, web/src/components/RunEvents/TraceHeader/LoadingHeader.tsx, web/src/components/RunEvents/TraceHeader/StoppedHeader.tsx, web/src/constants/TestRun.constants.ts, web/src/models/TestRun.model.ts, web/src/providers/TestRun/TestRun.provider.tsx, web/src/redux/apis/TraceTest.api.ts, web/src/redux/apis/endpoints/TestRun.endpoints.ts, web/src/services/TestRun.service.ts
This PR adds the ability to stop a run from the TestRun page.
- Stop test run action + api call
- FE support
- fixes #2052 
https://www.loom.com/share/35768bc37e7044c181ee8de0ddaccd7c
=> feat(frontend): stop a test run

docs/docs/examples-tutorials/recipes.md
=> docs(recipes): fix links

server/app/app.go, server/environment/manager.go, web/src/types/Generated.types.ts
=> registering environent resource routes

docs/docs/examples-tutorials/recipes/running-tracetest-without-a-trace-data-store-with-manual-instrumentation.md, docs/docs/examples-tutorials/recipes/running-tracetest-without-a-trace-data-store.md, examples/tracetest-amazon-x-ray-adot/docker-compose.yml, examples/tracetest-amazon-x-ray-pokeshop/docker-compose.yml, examples/tracetest-amazon-x-ray/docker-compose.yml
=> fix(examples): awsxray examples tracetes dev flag

server/http/mappings/datastore.go
=> fix(backend): fixing elastic apm connection test

.goreleaser.yaml
This PR disable arch image upload on version release
-
-
=> Disable arch image upload on deploy

docs/docs/index.md, docs/docs/live-examples/opentelemetry-store/overview.md, docs/docs/live-examples/opentelemetry-store/use-cases/add-item-into-shopping-cart.md, docs/docs/live-examples/opentelemetry-store/use-cases/checkout.md, docs/docs/live-examples/opentelemetry-store/use-cases/get-recommended-products.md, docs/docs/live-examples/opentelemetry-store/use-cases/user-purchasing-products.md, docs/docs/live-examples/pokeshop/overview.md, docs/docs/live-examples/pokeshop/use-cases/add-pokemon.md, docs/docs/live-examples/pokeshop/use-cases/get-pokemon-by-id.md, docs/docs/live-examples/pokeshop/use-cases/import-pokemon.md, docs/docs/live-examples/pokeshop/use-cases/list-pokemon.md, docs/sidebars.js
General Updates for the remainder of the docs.
This PR...
-
-
=> v0.11 Doc Updates Part 4

web/src/constants/DataStore.constants.tsx
This PR fixes the test connection notification for honeycomb 
- Adds honeycomb to the no test connection array
=> fix(frontend): update honeycomb notification

web/src/providers/TestRun/TestRun.provider.tsx
This PR enables a polling mechanism in the getTestRun method.
- add polling interval in getTestRun method
-
=> fix(frontend): add polling mechanism for test run

docs/docs/configuration/telemetry.md, examples/tracetest-honeycomb/collector.config.yaml, examples/tracetest-honeycomb/tracetest-config.yaml
This PR updates the Honeycomb config to use Tracetest Server Telemetry.
-
-
=> examples(honeycomb): update config

web/src/providers/DataStore/hooks/useDataStoreNotification.tsx
This PR updates the OTLP test connection message.
- Updates the OTLP test connection message
- fixes #2507
=> fix(frontend): fix otlp test connection message

api/openapi.yaml, api/transactions.yaml
This PR reverts the PR that reverts the openapi changes in the transaction as resources branches.
=> fix: revert openapi changes revert

server/tests/transactions.go, server/tests/transactions_test.go
This PR fixes handling of transactions with no steps
-
-
=> Fix nil stepids

server/tests/transactions.go
=> fix count query

docs/docs/cli/creating-data-stores.md, docs/docs/concepts/versioning.md, docs/docs/configuration/connecting-to-data-stores/awsxray.md, docs/docs/configuration/opentelemetry-collector-configuration-file-reference.md
This PR fixes docs related to datastores changes introduced in previous versions.
- fix datastore docs
-
=> fix(docs): fix docs related to data stores

docs/docs/deployment/docker.md, docs/docs/deployment/kubernetes.mdx, docs/docs/getting-started/detailed-installation.md
This PR improves the content and formatting of the Deployment and Getting Started docs.
-
-
=> docs(install-deploy): improves Deployment and Getting Started pages

server/http/controller.go, testing/server-tracetesting/run.bash
=> hotfix: fix controller panic

cli/formatters/datastore.go, testing/cli-e2etest/testscenarios/datastore/list_datastore_test.go
=> Fixing corner case of listing datastores when on no-tracing mode

docs/docusaurus.config.js
This PR adds redirects to fix #2595 #2596 
-
-
=> docs(deployment): add redirects

cli/cmd/docgen_cmd.go
=> fix(cli): fixing setup function for the docgen cmd

docs/docs/configuration/upgrade.md, docs/sidebars.js
This PR adds an upgrade page for server+cli version mismatch.
-
-
=> docs(config): add upgrade page

server/executor/linter_runner.go
This PR moves the request logic to a separate function to avoid killing the worker
- Test runs stuck in analyzing trace
=> fix(backend): fixing analyzer runner return logic

web/src/components/AnalyzerResult/AnalyzerResult.tsx, web/src/components/Settings/Linter/Linter.tsx
This PR fixes the Trace Analyzer description used in the webApp.
- fix analyzer description
-
=> fix(frontend): fix analyzer description

web/src/components/TestResults/AddTestSpecButton.tsx
This PR fixes the onboarding flow in the webApp for the TestSpecs step.
- fix onboarding
-
=> fix(frontend): fix onboarding for test specs step

web/src/components/HeaderRow/HeaderRow.tsx, web/src/components/RunDetailTriggerResponse/ResponseHeaders.tsx
This PR fixes the expression used in the Header component to create TestSpecs from the response data.
- fix test spec expression
-
=> fix(frontend): fix test spec expression for header field

docs/docs/ci-cd-automation/overview.md, docs/docs/cli/configuring-your-cli.md
=> docs(cli with docker): update

server/http/controller.go, server/transaction/transaction_repository.go, testing/server-tracetesting/features/grpc_test/01_create_grpc_test.yml, testing/server-tracetesting/features/grpc_test/04_delete_grpc_test.yml, testing/server-tracetesting/features/grpc_test/05_create_grpc_test_with_invalid_metadata.yml, testing/server-tracetesting/features/transaction/create_transaction.yml, testing/server-tracetesting/features/transaction/create_transaction_step.yml, testing/server-tracetesting/features/transaction/delete_transaction_step.yml
This PR fixes the rest of the tracetests
=> fix: tracetests

testing/cli-e2etest/testscenarios/test/apply_test_test.go, testing/cli-e2etest/testscenarios/test/delete_test_test.go, testing/cli-e2etest/testscenarios/test/get_test_test.go, testing/cli-e2etest/testscenarios/test/list_test_test.go
This PR adds CLI e2e test coverage for the test resource
=> add cli e2e test for test resource

web/src/components/Settings/Analytics/AnalyticsForm.tsx, web/src/components/Settings/Demo/DemoForm.tsx, web/src/components/Settings/common/Settings.styled.ts
This PR fixes broken styles for the toggle component used in the Analytics and Demo Settings page.
- fix broken styles for label component
- fixes #2909
=> fix(frontend): fix toggle on settings page

server/traces/otel_http_converter.go
This PR fixes the trace poll from tempo 1.5
=> fix: tempo 1.5 http trace conversion

server/test/test_repository.go
This PR fixes the tests search functionality by repairing a sql query in the test repository.
- fix tests query
-
=> fix(server): fix test search query

README.md
=> readme: fix logo

README.md
=> readme: typos

cli/openapi/model_supported_data_stores.go, examples/tracetest-dynatrace/tracetest/collector.config.yaml, go.work.sum, web/src/constants/CollectorConfig.constants.ts, web/src/types/Generated.types.ts
This PR fix small details on docs to make Dynatrace example work correctly
-
-
=> fix(docs): fix small details on docs to make Dynatrace example work correctly

web/src/antd-theme/tracetest-antd-theme.less
This PR fixes the Antd Layout background color by adding it to our custom theme file.
- fix antd layout background
-
=> fix(frontend): update antd layout background

api/grpc.yaml, api/openapi.yaml, cli/openapi/api_api.go, cli/openapi/model_grpc_response.go, server/http/controller.go, server/openapi/api.go, server/openapi/api_api.go, server/openapi/model_grpc_response.go, web/src/types/Generated.types.ts
This PR adds a temporary endpoint to tracetest to update a test run, especially the trigger response
=> feat(server): add endpoint to update test trigger response

cli/config/configurator.go
=> fix(cli): adding path to the url

api/tests.yaml
=> fix: api type

examples/tracetest-opensearch/docker-compose.yml, examples/tracetest-opensearch/opensearch/opensearch-analytics.yaml
This PR updates the OpenSearch example to use the most recent releases from OpenSearch team.
- Update OpenSearch example
=> chore(examples): update OpenSearch example to use latest version

api/tests.yaml
=> fix api change

examples/observability-driven-development-go-tracetest/bookstore/part1/tracetest/docker-compose.yaml, examples/observability-driven-development-go-tracetest/bookstore/part2.1/tracetest/docker-compose.yaml, examples/observability-driven-development-go-tracetest/bookstore/part2.2/tracetest/docker-compose.yaml, examples/observability-driven-development-go-tracetest/bookstore/part3.1/tracetest/docker-compose.yaml, examples/observability-driven-development-go-tracetest/bookstore/part3.2/tracetest/docker-compose.yaml, examples/observability-to-the-rescue/docker-compose.yaml, examples/quick-start-go-and-kafka/docker-compose.yaml, examples/quick-start-jaeger-nodejs/tracetest/docker-compose.yaml, examples/quick-start-net-core/docker-compose.yaml, examples/quick-start-tail-sampling/docker-compose.yaml, examples/tracetest-jaeger/docker-compose.yml, examples/tracetest-k6/docker-compose.yml, examples/tracetest-otel-demo/docker-compose.yaml, examples/tracetest-provisioning-env/docker-compose.yml, examples/tracetesting-kubernetes/kubetracing/docker-compose.yaml, local-config/jaeger/docker-compose.yml, testing/cli-e2etest/environment/jaeger/server-setup/docker-compose-no-api.yaml, testing/load/infra/docker-compose.yaml
=> Pin jaeger version

agent/workers/trigger.go, agent/workers/trigger/http.go, agent/workers/trigger/instrument.go, agent/workers/trigger/triggerer.go
This PR makes the agent propagate the trace ID correctly
=> fix(agent): trace propagation

server/executor/trigger_result_processor_worker.go, server/otlp/ingester.go
=> fix: run state

k8s/agent/deploy-agent.sh
=> fix(agent): Deploy Agent yaml url

server/analytics/segment.go
This PR adds the logic to send the correct `userId` property to segment.
- segment userId validation
-
=> feat(server): add segment user id

web/src/pages/Settings/Content.tsx, web/src/providers/DataStore/DataStore.provider.tsx, web/src/providers/Settings/Settings.provider.tsx, web/src/providers/SettingsValues/SettingsValues.provider.tsx
This PR allows for settings page customization
=> feat(frontend): settings page customization

web/src/components/ResourceCard/ResourceCard.styled.ts, web/src/components/ResourceCard/ResourceCardRuns.tsx, web/src/components/RunDetailLayout/HeaderLeft.tsx, web/src/components/RunDetailLayout/RunDetailLayout.tsx, web/src/components/TestSuiteHeader/TestSuiteHeader.tsx, web/src/hooks/useRouterSync.ts, web/src/redux/Router.middleware.ts, web/src/redux/slices/User.slice.ts, web/src/selectors/User.selectors.ts, web/src/types/User.types.ts
This PR fixes the back button behavior in the test run detail page.
- back button in test run detail page
- fixes #3178
=> fix(frontend): update header back button logic

.github/PULL_REQUEST_TEMPLATE.md
This PR changes the PR template to include a loom video section
-
-
=> chore: add loom video to PR template

web/cypress/e2e/TestRunDetail/Onboarding.spec.ts, web/package-lock.json, web/package.json, web/src/components/GuidedTour/StepContent.tsx, web/src/components/GuidedTour/steps.ts, web/src/components/Header/HelpMenu.tsx, web/src/components/Layout/Layout.tsx, web/src/components/ResizablePanels/LeftPanel.tsx, web/src/components/ResizablePanels/Splitter.tsx, web/src/components/RunDetailTest/SpanDetailsPanel.tsx, web/src/components/RunDetailTest/TestPanel.tsx, web/src/pages/RunDetail/RunDetail.tsx
This PR fixes the test run detail page onboarding.
- fix test run onboarding
-
=> fix(frontend): fix test run onboarding

web/src/constants/DataStore.constants.tsx
This PR fixes the Agent UI docs
- Updates the link to match the actual documentation
- https://github.com/kubeshop/tracetest-cloud-frontend/issues/90
=> fix(UI): Agent docs url

.goreleaser.demo.yaml, .goreleaser.dev.yaml, .goreleaser.rc.yaml, .goreleaser.yaml, server/Makefile, server/app/app.go, server/telemetry/resource.go, server/telemetry/tracer.go, server/version/version.go
This PR includes the version of the Tracetest distribution as part of all telemetry data (traces and metrics).
https://www.loom.com/share/b4fdfa5db64147a08263a91ad305488f
=> feat: include oss version in telemetry data

cli/cmd/middleware.go, cli/pkg/resourcemanager/client.go
This PR improves the error handling on CLI to tell the users when they are not authenticated on the Tracetest server.
- Update error handling for 401 errors on CLI
=> fix: added support to unauthorized error

cli/cmd/start_cmd.go, cli/config/config.go, cli/config/configurator.go
=> fix(cli): consider env variables when running `tracetest start`

agent/client/workflow_listen_for_ds_connection_tests.go, agent/client/workflow_listen_for_poll_requests.go, agent/client/workflow_listen_for_trigger_requests.go, agent/client/workflow_shutdown.go, server/http/mappings/grpc.go
This PR adds error logging when an error is returned by any of the workers
-
-
=> fix: add error logging in agent workers

cli/cmd/configure_cmd.go, cli/config/configurator.go
This PR adds flags to configure the CLI with a token, environment and organization
=> feat: adding flags for token, environment and organization

docs/docs/live-examples/opentelemetry-store/overview.mdx, docs/docs/live-examples/opentelemetry-store/use-cases/add-item-into-shopping-cart.mdx, docs/docs/live-examples/opentelemetry-store/use-cases/check-shopping-cart-contents.mdx, docs/docs/live-examples/opentelemetry-store/use-cases/checkout.mdx, docs/docs/live-examples/opentelemetry-store/use-cases/get-recommended-products.mdx, docs/docs/live-examples/opentelemetry-store/use-cases/user-purchasing-products.mdx, docs/docs/live-examples/pokeshop/overview.mdx, docs/docs/live-examples/pokeshop/use-cases/add-pokemon.mdx, docs/docs/live-examples/pokeshop/use-cases/get-pokemon-by-id.mdx, docs/docs/live-examples/pokeshop/use-cases/import-pokemon-from-stream.mdx, docs/docs/live-examples/pokeshop/use-cases/import-pokemon.mdx, docs/docs/live-examples/pokeshop/use-cases/list-pokemon.mdx, docs/sidebars.js
This PR updates the live examples section with meta tags and `.mdx`.
-
-
=> docs(migrate to mdx): Update live examples section

docs/docs/getting-started/try-live-demos.mdx
This PR improves the wording and links for the live demos. #3358 
-
=> docs(trylivedemos): improve wording

web/src/components/RunDetailAutomateMethods/methods/CLICommand/SwitchControl.tsx
This PR adds the loading state for the switch control component
- Adds loading state to switch control
=> feat: Switch Loading State

agent/client/client.go
=> feat: make agent reconnect on expired token

agent/client/client.go
=> fix(agent): close connection before reconnecting

server/traces/span_entitiess.go
=> fix: lock attributes when marshalling/unmarshalling

web/src/components/AllowButton/AllowButton.styled.ts, web/src/components/AllowButton/AllowButton.tsx, web/src/components/CustomizationWrapper/CustomizationWrapper.tsx, web/src/constants/Common.constants.ts, web/src/providers/Customization/Customization.provider.tsx
This PR updates the customization provider to support role
- Updates allow button messaging based on role
- https://github.com/kubeshop/tracetest-cloud-frontend/pull/143
=> feat: Limited Access

.github/workflows/pull-request.yaml
=> upload coverage report to codecov

docs/docs/configuration/agent.mdx
This PR update agent configuration docs to show verbose mode
=> chore: update agent configuration to show verbose mode

examples/quick-start-sumologic-nodejs/readme.md
=> docs(hotfix): fix sumo logic example readme

agent/client/client.go
=> fix: make agent reconnect when it fails to get messages from stream

web/src/models/DataStore.model.ts
This PR defaults the agent type to oltp to avoid breaking the webapp
=> fix(frontend): fixing agent as tracing backend error

web/src/components/Settings/DataStorePlugin/forms/SumoLogic/SumoLogic.tsx
This PR improves the `SumoLogic` config screen
- improve config screen
- fixes https://github.com/kubeshop/tracetest/issues/3486
=> fix(frontend): improve sumo logic config screen

web/src/components/TriggerTypeModal/TriggerTypeModal.tsx
=> chore: Custom Trigger Type Modal

web/public/index.html
This PR adds the robots meta tag to our index.html
- add robots meta tag
- fixes https://github.com/kubeshop/tracetest/issues/3470
=> fix(frontend): add robots meta tag

examples/quick-start-sumologic-nodejs/docker-compose.yaml
This PR fix the SumoLogic quickstart config
- update app config so it sends traces to the collector instead of the agent
- #3496
=> fix(docs): update SumoLogic example collector config

docs/docs/examples-tutorials/recipes/running-tracetest-with-sumologic.mdx
This PR fixes collector URLs in the recipe.
-
-
=> docs(sumo): fix URLs in recipe 

docs/docs/configuration/overview.mdx
=> docs(sumo): add sumo to list of configs

web/src/components/Wizard/Content/Content.styled.ts, web/src/components/Wizard/Header/Header.styled.ts, web/src/components/Wizard/Header/Header.tsx, web/src/components/Wizard/Steps/TracingBackend/Configuration.tsx, web/src/components/Wizard/Steps/TracingBackend/Selector.tsx, web/src/components/Wizard/Steps/TracingBackend/TracingBackend.styled.ts, web/src/components/Wizard/Wrapper/Wrapper.tsx
This PR introduces UI and copy improvements for the Onboarding Wizard.
-
-
=> feat(frontend): add wizard ui improvements

server/http/controller.go, server/wizard/wizard_repository.go
This PR fixes the wizard CRUD bug
-
-
=> fix(backend): wizard crud

web/src/components/DataStoreConfiguration/DataStoreConfiguration.styled.ts, web/src/components/Settings/DataStoreForm/DataStoreForm.styled.ts, web/src/components/TriggerTypeModal/TriggerTypeModal.styled.ts, web/src/components/Wizard/Content/Content.styled.ts, web/src/components/Wizard/Content/Content.tsx, web/src/components/Wizard/Content/Tab.tsx, web/src/components/Wizard/Steps/CreateTest/CreateTest.styled.ts, web/src/components/Wizard/Steps/CreateTest/Tab.tsx, web/src/components/Wizard/Steps/CreateTest/index.ts, web/src/components/Wizard/Steps/TracingBackend/Configuration.tsx, web/src/components/Wizard/Steps/TracingBackend/Tab.tsx, web/src/components/Wizard/Steps/TracingBackend/TracingBackend.styled.ts, web/src/components/Wizard/Steps/TracingBackend/index.ts, web/src/components/Wizard/Wrapper/Wrapper.tsx, web/src/models/Wizard.model.ts, web/src/pages/Wizard/Wizard.tsx, web/src/providers/Wizard/Wizard.provider.tsx, web/src/redux/apis/Tracetest/endpoints/Wizard.endpoint.ts, web/src/types/Wizard.types.ts
This PR introduces UI updates to the onboarding wizard and the ability to mark a wizard step as completed.
- wizard UI
- mark wizard step as completed
-
=> feat(frontend): update wizard steps state

server/http/controller.go
=> fix: last span timestamp format

web/src/components/DataStoreConfiguration/DataStoreConfiguration.styled.ts, web/src/components/DataStoreConfiguration/DataStoreConfiguration.tsx, web/src/components/Settings/DataStore/DataStore.tsx, web/src/components/Settings/DataStoreForm/DataStoreForm.tsx, web/src/components/TestConnectionStatus/TestConnectionStatus.styled.ts, web/src/components/TestConnectionStatus/TestConnectionStatus.tsx, web/src/components/TestConnectionStatus/hooks/useTestConnnectionStatus.ts, web/src/components/Wizard/Steps/TracingBackend/Configuration.tsx, web/src/components/Wizard/Steps/TracingBackend/TracingBackend.tsx, web/src/models/OTLPTestConnectionResponse.model.ts, web/src/providers/DataStore/DataStore.provider.tsx, web/src/redux/apis/Tracetest/endpoints/DataStore.endpoint.ts, web/src/redux/apis/Tracetest/index.ts, web/src/services/DataStore.service.ts, web/src/services/DataStores/AwsXRay.service.ts, web/src/services/DataStores/AzureAppInsights.service.ts, web/src/services/DataStores/BaseClient.service.ts, web/src/services/DataStores/ElasticSearch.service.ts, web/src/services/DataStores/Jaeger.service.ts, web/src/services/DataStores/OtelCollector.service.ts, web/src/services/DataStores/SignalFx.service.ts, web/src/services/DataStores/SumoLogic.service.ts, web/src/types/DataStore.types.ts, web/src/types/Generated.types.ts
This PR enables the otlp tracing backends test connection
- Adds components and logic to support otlp tracing backend test connection
https://www.loom.com/share/4c7ab79f9e8e4a61a0bb36526c35bae6
=> feat(frontend): Wizard - OTLP Test connection

web/src/components/Wizard/Steps/TracingBackend/Configuration.tsx, web/src/components/Wizard/Steps/TracingBackend/TracingBackend.tsx, web/src/providers/DataStore/DataStore.provider.tsx, web/src/providers/Wizard/Wizard.provider.tsx, web/src/types/Wizard.types.ts
=> fix(frontend): fix next step for tracing backend

web/src/components/Wizard/Steps/TracingBackend/BackendCard.tsx, web/src/components/Wizard/Steps/TracingBackend/Selector.tsx, web/src/components/Wizard/Steps/TracingBackend/TracingBackend.styled.ts, web/src/components/Wizard/Steps/TracingBackend/TracingBackend.tsx
This PR fixes the selected tracing backend in the wizard
-
-
=> fix(frontend): fix selected tracing backend

web/src/pages/Wizard/HomeContent.tsx, web/src/pages/Wizard/Wizard.tsx
This PR adds the HomeContent component
-
-
=> feat(frontend): add HomeContent component

web/src/components/Fields/Auth/AuthApiKeyBase.tsx, web/src/components/Fields/Auth/AuthBasic.tsx, web/src/components/Fields/KeyValueList/KeyValueList.styled.ts, web/src/components/Fields/KeyValueList/KeyValueList.tsx, web/src/components/Fields/Metadata/Metadata.styled.ts, web/src/components/Fields/Metadata/Metadata.tsx, web/src/components/Fields/PlainAuth/Fields.tsx
This PR fixes an overflow issue in some fields used in the test creation page.
- fix overflow issue
- fixes https://github.com/kubeshop/tracetest/issues/3538
=> fix(frontend): fix overflow issue in fields

server/tracedb/tempodb.go
This PR makes our Tempo tracing backend support the protobuf format when connecting to the HTTP protocol.
https://www.loom.com/share/a9edab58e87849bb8147d330529d30d8
=> feat: support protobuf format in tempo HTTP protocol

server/otlp/http_server.go
=> fix: add cors to agent

docs/docs/examples-tutorials/recipes/testing-vercel-functions-with-opentelemetry-tracetest.mdx
=> docs(vercel): fix recipe typos

web/src/components/RunDetailAutomateMethods/methods/CLICommand/CliCommand.tsx, web/src/components/RunDetailAutomateMethods/methods/CLICommand/Command.tsx
This PR enables the customization of the CLI command component
- Enables a custom cli component
- https://github.com/kubeshop/tracetest-cloud/issues/359
=> feat(frontend): customizable cli command

web/src/providers/Span/Span.provider.tsx
This PR...
-
- fixes [clearSelectedSpan](https://github.com/kubeshop/tracetest-cloud/issues/327)
=> fix(frontend): clear selected span in test mode

web/src/components/ContactUs/ContactUs.tsx, web/src/components/ContactUs/Launcher.tsx
This PR adds the contact us launcher as a customizable widget.
-
-
=> feat(frontend): add customizable contact us widget

cli/config/configurator.go, examples/observability-stack/docker-compose.tracetest.yaml
This PR updates the observability stack to consider agent on verbose mode
=> chore: update observability stack to consider agent on verbose mode

agent/ui/dashboard/components/header.go, agent/ui/dashboard/components/message_banner.go, agent/ui/dashboard/components/render_scheduler.go, agent/ui/dashboard/dashboard.go, agent/ui/dashboard/events/errors.go, agent/ui/dashboard/events/events.go, agent/ui/dashboard/main/main.go, agent/ui/dashboard/pages/test_runs_page.go, agent/ui/dashboard/router.go, agent/ui/dashboard/sensors/sensor.go, agent/ui/dashboard/styles/styles.go, go.mod, go.sum
This PR adds the basic layout for the agent dashboard.
=> feat: agent dashboard header layout

.github/workflows/deploy-main.yml, .github/workflows/release-candidate.yml, .github/workflows/release-version.yml
This PR enables internal infra auto update
=> chore(infra): enable auto update

agent/ui/dashboard/components/header.go, agent/ui/dashboard/components/test_run_list.go, agent/ui/dashboard/dashboard.go, agent/ui/dashboard/events/events.go, agent/ui/dashboard/main/main.go, agent/ui/dashboard/models/test_runs.go, agent/ui/dashboard/pages/test_runs_page.go, agent/ui/dashboard/sensors/sensor.go, agent/ui/dashboard/styles/styles.go
This PR adds the changes asked by @olha23 and add the test run list. Everything is still mocked, but I'll start wiring things tomorrow.
=> feat: agent UI test run list

web/package-lock.json, web/package.json, web/src/components/RunDetailTrace/TracePanel.tsx, web/src/components/RunDetailTrace/Visualization.tsx, web/src/components/Visualization/components/DAG/TestSpanNode/TestSpanNode.tsx, web/src/components/Visualization/components/Timeline/BaseSpanNode/BaseSpanNodeV2.tsx, web/src/components/Visualization/components/Timeline/BaseSpanNode/ConnectorV2.tsx, web/src/components/Visualization/components/Timeline/Header.tsx, web/src/components/Visualization/components/Timeline/ListWrapper.tsx, web/src/components/Visualization/components/Timeline/NavigationWrapper.tsx, web/src/components/Visualization/components/Timeline/SpanNodeFactoryV2.tsx, web/src/components/Visualization/components/Timeline/Ticks/Ticks.styled.ts, web/src/components/Visualization/components/Timeline/Ticks/Ticks.tsx, web/src/components/Visualization/components/Timeline/Timeline.provider.tsx, web/src/components/Visualization/components/Timeline/TimelineV2.styled.ts, web/src/components/Visualization/components/Timeline/TimelineV2.tsx, web/src/components/Visualization/components/Timeline/TraceSpanNode/TraceSpanNodeV2.tsx, web/src/services/Timeline.service.ts, web/src/utils/Date.ts
This PR adds the new Timeline view with virtual list support.
-
-
https://www.loom.com/share/160b091ce6044a069eac9aa3de824533?sid=eb7c0e45-bcf2-43b2-b26a-0f8c60f41da2
=> feat(frontend): implement virtual list for timeline view

web/cypress/e2e/TestRunDetail/CreateAssertion.spec.ts, web/cypress/support/commands.ts, web/docker-compose.yaml, web/package-lock.json, web/package.json, web/src/components/RunDetailTest/TestPanel.tsx, web/src/components/RunDetailTest/Visualization.tsx, web/src/components/RunDetailTrace/TraceDAG.tsx, web/src/components/RunDetailTrace/Visualization.tsx, web/src/components/TestResults/TestResults.tsx, web/src/components/TestSpec/TestSpec.styled.ts, web/src/components/TestSpecDetail/Content.tsx, web/src/components/TestSpecDetail/ResultCard.tsx, web/src/components/TestSpecDetail/SpanHeader.tsx, web/src/components/TestSpecDetail/TestSpecDetail.styled.ts, web/src/components/TestSpecDetail/TestSpecDetail.tsx, web/src/components/TestSpecs/TestSpecs.styled.ts, web/src/components/TestSpecs/TestSpecs.tsx, web/src/components/Visualization/components/Timeline/BaseSpanNode/BaseSpanNodeV2.tsx, web/src/components/Visualization/components/Timeline/Timeline.provider.tsx, web/src/components/Visualization/components/Timeline/TimelineV2.tsx, web/src/components/Visualization/components/Timeline/TraceSpanNode/TraceSpanNodeV2.tsx, web/src/models/Trace.model.ts, web/src/redux/actions/Router.actions.ts, web/src/redux/actions/TestSpecs.actions.ts
This PR improves different parts of the FE section, including performance, adding search  and virtualized lists for the test run section
- Implements new timeline component to the test page
- Adds perf improvements to the overall app
- https://github.com/orgs/kubeshop/projects/52/views/5?pane=issue&itemId=52438219
[Add your loom video here if your work can be visualized](https://www.loom.com/share/02ea356b42564ac2b9979cacf4c5e355)
=> feat(frontend): Implemeting new Timeline for the Test Page

docs/vercel.json
=> docs(vercel): fix 404s

web/src/components/Layout/Layout.styled.ts, web/src/components/TriggerTypeModal/TriggerTypeModal.styled.ts, web/src/components/Wizard/Steps/CreateTest/CreateTest.styled.ts
This PR fixes some UI spacing issues in the layout page and the wizard component.
- fix ui spacing
- fixes https://github.com/kubeshop/tracetest-cloud-frontend/issues/233
- fixes https://github.com/kubeshop/tracetest-cloud-frontend/issues/231
=> fix(frontend): fix ui spacing in layout and wizard

agent/collector/ingester.go, agent/ui/dashboard/sensors/sensor.go, go.mod, go.sum
=> fix concurrency issues

agent/ui/dashboard/sensors/sensor.go
This PR fixes the deadlock caused at startup sometimes.
-
-
=> fix: agent ui sensor mutex

web/src/components/RunActionsMenu/RunActionsMenu.tsx, web/src/components/RunDetailTest/RunDetailTest.styled.ts, web/src/components/SpanResultDetail/Detail.tsx, web/src/pages/Home/TestsList.tsx
This PR fixes the links for the test run edit functionality.
- test run edit links
- small CSS fixes
-
=> fix(frontend): fix test run edit links

docs/vercel.json
=> docs(redirect): fix tekton 301

cli/cloud/cmd/run_cmd.go, cli/cloud/cmd/wait_cmd.go, cli/cloud/runner/multifile_orchestrator.go, cli/cloud/runner/rungroup.go, cli/cmd/resource_run_cmd.go, cli/cmd/wait_cmd.go, cli/formatters/multiple_runs.go, cli/runner/orchestrator.go
This PR adds the wait group command when executing multiple things at once and skipping waiting for results
- Adds new wait group cmd
- https://github.com/kubeshop/tracetest-cloud/issues/490
https://www.loom.com/share/7044c02303aa403a80a9aab52070d40a
=> feat(cli): Wait group CMD

docs/docs/concepts/agent.mdx, docs/docs/configuration/agent.mdx, docs/docs/configuration/cloud-agent.mdx, docs/docs/configuration/connecting-to-data-stores/overview.mdx, docs/docs/configuration/overview.mdx, docs/docs/examples-tutorials/recipes.mdx, docs/sidebars.js
Fix agent config, fix config root page, add connecting to tracing backends overview page.
#3754
-
-
=> docs(config): total rework 

docs/docs/examples-tutorials/recipes/running-playwright-performance-tests-with-artillery-and-tracetest.mdx, docs/docs/tools-and-integrations/artillery-engine.mdx, docs/docs/tools-and-integrations/artillery-plugin.mdx
=> docs(artillery): added callout for version requirement

docs/docs/concepts/variable-sets.mdx, docs/docs/web-ui/creating-variable-sets.mdx
to Web-UI and Concepts variable sets docs.
This PR...
-
-
=> docs: Add link to CLI Variables Sets Doc

README.md, docs/docs/configuration/overview.mdx, docs/docs/getting-started/open.mdx, docs/docs/getting-started/overview.mdx, docs/docs/index.mdx, docs/docusaurus.config.js, docs/src/components/WelcomeGuide/index.tsx
This PR improves the get started in the readme.
-
-
=> readme(get-started): improve get started section (ref issue 3793)

README.md
=> readme(hotfix): fix typos

examples/quick-start-artillery-playwright/package-lock.json, examples/quick-start-artillery-playwright/package.json, examples/quick-start-serverless/package-lock.json, examples/quick-start-serverless/package.json, examples/quick-start-tyk/package-lock.json, examples/quick-start-tyk/package.json, examples/quick-start-typescript/package.json, examples/setup-of-tracetest-tests/package.json, examples/tracetest-cypress/package-lock.json, examples/tracetest-cypress/package.json, examples/tracetest-playwright/package-lock.json, examples/tracetest-playwright/package.json, examples/tracetest-playwright/playwright/pokeshop.spec.ts
This PR updates the npm package versions everywhere in the examples folder to use latest
- Updates npm packages
=> chore(examples): updating the tracetest NPM pacakges version

docs/docs/getting-started/overview.mdx, docs/docs/index.mdx, docs/src/components/CoreGettingStartedGuide/index.tsx, docs/src/components/GettingStartedGuide/index.tsx, docs/src/components/WelcomeGuide/index.tsx
This PR...
-
- https://github.com/kubeshop/tracetest/issues/3792
=> docs(get-started): add features for cloud vs core

docs/docs/cli/creating-tests-grpc.mdx, docs/docs/cli/creating-tests-http.mdx, docs/docs/cli/creating-tests-kafka.mdx, docs/docs/cli/creating-tests-traceid.mdx, docs/docs/cli/creating-tests.mdx, docs/docs/web-ui/creating-tests-artillery.mdx, docs/docs/web-ui/creating-tests-cypress.mdx, docs/docs/web-ui/creating-tests-http.mdx, docs/docs/web-ui/creating-tests-k6.mdx, docs/docs/web-ui/creating-tests-kafka.mdx, docs/docs/web-ui/creating-tests-playwright.mdx, docs/docs/web-ui/creating-tests-traceid.mdx, docs/docs/web-ui/creating-tests.mdx, docs/sidebars.js, docs/src/components/WelcomeGuide/index.tsx
=> docs(webui+cli): add new create test pages

.github/workflows/scheduled-jobs.yml
This PR updates our Synthetic Monitoring to notify if all jobs failed.
- Update scheduled-jobs.yaml file
=> chore(synthetic-monitoring): adding notification when all jobs fail

cli/cmd/resources.go
=> fix(cli): Environment token type and route

api/variableSets.yaml, cli/openapi/model_variable_set_value.go
This PR updates our CLI to consider secrets in VariableSets
- Update CLI client
=> chore(cli): update cli to consider secrets in variable sets

.github/workflows/synthetic-monitoring-production.yml
This PR updates our Synthetic Monitoring messages to be simple.
=> chore(synthetic-monitoring): simplifying slack messages

.github/workflows/synthetic-monitoring-production.yml
=> fix(synthetic-monitoring): update synthetic monitoring messaging

docs/docs/examples-tutorials/recipes/running-playwright-performance-tests-with-artillery-and-tracetest.mdx, docs/docs/examples-tutorials/recipes/testing-cloudflare-workers-with-opentelemetry-tracetest.mdx, docs/docs/examples-tutorials/recipes/testing-distributed-services-with-tyk-opentelemetry-tracetest.mdx, docs/docs/examples-tutorials/recipes/testing-lambda-functions-with-opentelemetry-tracetest.mdx, docs/docs/examples-tutorials/recipes/testing-vercel-functions-with-opentelemetry-tracetest.mdx, docs/docs/tools-and-integrations/artillery-engine.mdx, docs/docs/tools-and-integrations/artillery-plugin.mdx, docs/docs/tools-and-integrations/k6.mdx, examples/tracetest-k6/README.md
Add working demo links.
-
- https://github.com/kubeshop/tracetest/issues/3766
=> docs(recipes): fix demo links

docs/docs/concepts/variable-sets.mdx
=> docs(var-sets): add subheading

examples/quick-start-nodejs-manual-instrumentation/docker-compose.yaml, examples/quick-start-nodejs-manual-instrumentation/tracing.otel.grpc.js, examples/quick-start-nodejs-manual-instrumentation/tracing.otel.http.js
=> examples(nodejs auto instr): add more enable:false

docs/docs/cli/creating-variable-sets.mdx, docs/docs/web-ui/creating-variable-sets.mdx
in Creating Variable Sets.
This PR...
-
-
=> docs: Add Secrets Management Link

.github/workflows/synthetic-monitoring-production.yml
=> chore: Updating tracetest tests frequency

docs/docs/cli/configuring-monitors.mdx, docs/docs/concepts/monitors.mdx, docs/docs/web-ui/creating-monitors.mdx, docs/sidebars.js
=> docs(monitors): add monitors docs

agent/workers/trigger/playwrightengine.go
=> chore(triggers): adding playwright engine resolve

Dockerfile.agent, agent/workers/trigger/playwrightengine.go
=> fix(agent): fixing agent image for playwrightt

.github/workflows/release-candidate.yml
This PR updates the GH Action to use the correct docker file for the agent.
=> fix(ci): change agent to use the correct docker image

agent/workers/trigger/playwrightengine_test.go
=> fix: playwright trigger test

web/src/services/Assertion.service.ts, web/src/services/__tests__/Assertion.service.test.ts
=> fix: escape quotes in assertion field

k8s/agent/deploy-agent.sh, k8s/agent/deploy-agent.yaml
This PR allows passing extra settings to the installer script, to further customize the agent deployment.
-
-
=> feat: allow extra args for k8s agent installer script

cli/config/configurator.go
=> fix(cli): correct configurator url cleanup

cli/config/api.go
=> fix(cli): removing suffix from path

docs/docs/concepts/open-source-vs-commercial-features.mdx, docs/docs/examples-tutorials/recipes/synthetic-monitoring-trace-based-api-tests.mdx, docs/docs/getting-started/overview.mdx, examples/quick-start-nodejs-synthetic-monitoring/tracetest-synthetic-monitor.yaml
This PR updates the docs to mention on-prem and adds links to get in touch.
-
-
=> docs(concepts): add on-prem mentions

server/expression/comparison.go, server/expression/executor.go, server/expression/executor_test.go, server/expression/filters/json_path_test.go
=> fix: string escaping comparisson with filters

.github/workflows/release-version.yml
=> feat: bump chart version on release

.github/workflows/release-version.yml
This PR updates the release version action so it triggers a version update on the core repository
-
-
=> chore: add trigger to update cli version on core

server/traces/otel_converter.go
=> adding resource attributes to spans

examples/quick-start-llm-python/tests/tracing-backend.yaml
=> fix(llm-example): add datastore setup

docs/docs/examples-tutorials/recipes/running-tracetest-without-a-trace-data-store-with-manual-instrumentation.mdx
Update small typo on manual instrumentation page
=> fix(docs): Update running-tracetest-without-a-trace-data-store-with-manual-instrumentation.mdx
