server/README.md, server/go.mod, server/go.sum, server/go/websocket/messages.go, server/go/websocket/router.go, server/go/websocket/websocket.go, server/main.go
This PR adds an endpoint to handle Websocket connections
- This only adds a `/ws` endpoint that does nothing yet;
- It creates the structure to handle message routing based on the message `type` attribute.
=> feat: websocket endpoint

server/go/subscription/manager.go, server/go/subscription/manager_test.go, server/go/subscription/message.go, server/go/subscription/subscription.go, server/go/subscription/watcher.go
This PR adds a module responsible for handling subscriptions and notifications in tracetest. This will be used to send updates from tracetest to the websocket endpoint.
- Add a new isolated module
- Enable messages to be sent from a place to another without coupling them. It is based on event-driven programming.
=> feat: add subscription module

docs/websocket.md, server/go/trace_poller.go, server/go/websocket/messages.go, server/go/websocket/router.go, server/go/websocket/subscribe.go, server/go/websocket/unsubscribe.go, server/go/websocket/websocket.go, server/main.go
This PR adds a websocket endpoint to receive updates when a test has run and the result (traces) are received.
Depends on #371 and #370 
- Add behavior to the `/ws` endpoint
- Enable users to subscribe to updates to a resource (right now only test results are supported)
- Enable users to cancel a subscription
- Adds the endpoint documentation on the `docs` folder.
Subscribing to updates of a test result (response was received ~60 seconds after the subscription was created)
Unsubscribing
=> feat: websocket result updates

web/src/components/CreateAssertionModal/CreateAssertionForm.tsx, web/src/components/CreateAssertionModal/CreateAssertionModal.tsx, web/src/components/CreateAssertionModal/useAttributeList.tsx, web/src/selectors/Assertion.selectors.ts, web/src/services/Assertion.service.ts, web/src/services/Span.service.ts
This PR changes the way we present the attribute list to the selector when trying to create/edit an assertion, it now shows all of the attributes across the affected spans and the specific ones to the selected span.
- Updates the CreateAssertionModal.
- https://github.com/kubeshop/tracetest/issues/402
- https://github.com/kubeshop/tracetest/issues/236
https://www.loom.com/share/981900079a79407299550ef660662335
=> 🏷  402 updating the attributes selection to match affected spans

server/assertions/selectors/builder.go, server/assertions/selectors/parser.go, server/assertions/selectors/pseudo_classes.go, server/assertions/selectors/selector_test.go
This PR enables users to use `:first` and `:last` on their selectors.
=> feat: support :first and :last pseudo classes

web/src/components/ErrorBoundary/ErrorBoundary.tsx, web/src/services/Assertion.service.ts, web/src/utils/Common.ts
This PR fixes a bug we had when trying to compare json strings.
- Add an isJson check to validate if the incoming value can be parsed.
- https://github.com/kubeshop/tracetest/issues/426
=> 🐛  426 bug enable json comparison

server/http/controller.go
This PR adds a validation in the backend so that the test result state can only be updated by the frontend if the state is `awaiting test results`. That is the only case where the FE should update the test state.
=> fix validation of result update

docs/advanced-selectors.md, server/assertions/selectors/parser.go, server/assertions/selectors/selector.go, server/assertions/selectors/selector_test.go
This PR enables an empty selector. The behavior for such selector is to select all spans in the tree.
=> feat: support empty selector

web/cypress.json, web/cypress/components/App.spec.tsx, web/cypress/integration/Home/CreateTest.spec.ts, web/cypress/integration/Home/ShowTestList.spec.ts, web/cypress/tsconfig.json, web/package.json, web/src/components/CreateTestModal/CreateTestForm.tsx, web/src/components/CreateTestModal/CreateTestModal.tsx, web/src/components/Header/Header.tsx, web/src/hooks/useGuidedTour.ts, web/src/pages/Home/HomeContent.tsx, web/src/pages/Home/TestList.tsx, web/src/pages/Test/Test.tsx, web/src/services/Analytics/Analytics.service.ts
This PR adds the highly necessary integration tests for the home page. It includes tests for scenarios such as:
1. Displaying the layout (header).
2. Displaying the list of tests.
3. Creating a test from scratch.
4. Creating a test using the examples.
- Fixing initialization process for analytics.
- Moving CreateTestForm to its own component.
- https://github.com/kubeshop/tracetest/issues/441
=> 441 adding integration tests for the home page

web/.gitignore, web/cypress/integration/Home/CreateTest.spec.ts, web/cypress/integration/Home/ShowTestList.spec.ts, web/cypress/integration/TestDetails/ShowTestDetails.spec.ts, web/package.json, web/src/hooks/useDoubleClick.tsx, web/src/pages/Home/TestList.tsx, web/src/pages/Test/Test.tsx, web/src/pages/Test/TestDetails.tsx, web/src/pages/Test/TestDetailsTable.tsx
This PR adds integration tests for the test details page
- Adds scripts to run all tests at once.
- Adds test specs for the details page.
- Includes `data-cy` for some dom elements.
- https://github.com/kubeshop/tracetest/issues/442
https://www.loom.com/share/45cfaf062179489fb0c93b2e5080a4fb
=> 🧪  442 adding integration tests for the test details page

Makefile, server/executor/integration_test.go, server/go.mod, server/go.sum, server/test/database.go, server/test/pokeshop.go
This PR adds a test function that starts the pokemon api demo so we can run integration tests against it.
=> feat: start pokemon api demo to run our integration tests

mkdocs.yml
This PR adds the selector documentation to our documentation nav bar.
=> docs: link selectors documentation on doc page

api/openapi.yaml, server/executor/runner_test.go, server/http/controller.go, server/openapi/api.go, server/openapi/api_api.go, server/testdb/postgres.go, server/testdb/testdb.go, server/testdb/testdb_test.go
This PR allows pagination in the getTests and getTestResults endpoints. It introduces query parameters `take` and `skip` to control how many tests to get and how many should be ignored.
=> feat: paginate /tests and /tests/:testID/results endpoints

web/src/components/AssertionCheckRow/AssertionCheckRow.styled.ts, web/src/components/AssertionCheckRow/AssertionCheckRow.tsx, web/src/components/TraceNode/TraceNode.styled.ts
This PR set background color to assertion span tags.
We don't have a design for this, but it was Ken's request.
Let me know if proposed styling looks good. 
-
=> use convention background color to span tags

Makefile
This PR enables people using AMD64 architecture to generate our protobuf code.
=> fix: use old proto image if amd64 arch

server/http/mappings.go
This PR maps the `parentID` field to the response object
=> map parentID in flat structure

api/openapi.yaml, server/http/controller.go, server/openapi/api.go, server/openapi/api_api.go, server/openapi/model_test_.go
This PR adds and endpoint to try test definitions against existing results without modifying the DB.
Example requests (works against beta db):
```bash
curl "http://localhost:8080/api/tests/f04330f2-56e8-4db4-8af5-2fbb4bf5d4c3/run/28c97b89-e5e9-4235-adc3-01ceddecf886/dry-run" \
-X PUT \
-H "Content-Type: application/json" \
-d '{
"definitions":[
{
"selector": "span[name=\"POST /pokemon/import\"]",
"assertions": [
{
"attribute": "tracetest.response.status",
"comparator": "=",
"expected": "200"
}
]
}
]
}'
```
**Result**:
```json
{
"allPassed": true,
"results": [
{
"selector": "span[name=\"POST /pokemon/import\"]",
"results": [
{
"assertion": {
"attribute": "tracetest.response.status",
"comparator": "=",
"expected": "200"
},
"spanResults": [
{
"spanId": "36888225769c0b39",
"observedValue": …
```
=> Add assertion feedback endpoint

api/tests.yaml, cli/openapi/model_span.go, cli/openapi/model_test_.go, cli/openapi/model_test_run.go, server/executor/runner.go, server/executor/runner_test.go, server/http/controller.go, server/http/mappings.go, server/migrations/4_test_version.down.sql, server/migrations/4_test_version.up.sql, server/model/repository.go, server/model/test_changes.go, server/model/tests.go, server/openapi/model_test_.go, server/openapi/model_test_run.go, server/testdb/mock.go, server/testdb/runs.go, server/testdb/tests.go, server/testdb/tests_test.go
This PR adds versioning to both tests and references the test in the `test run` as well. So now we know which test definition was used to create a specific run.
- add `version` field to test
- add `testVersion` field to run
=> feat: add version to Test and TestRun API definitions

server/http/controller.go
This PR creates a new test run when a run is rerun instead of updating the same run. It also uses the latest test version to run the assertions.
=> feat: rerun test run creates a new run and copy data from original one

server/testdb/tests.go
This PR solves the issue of deleting a test due to the wrong order of queries.
=> fix: test deletion

web/cypress/support/index.js, web/package.json, web/src/components/AssertionForm/AssertionForm.tsx, web/src/components/AssertionForm/AssertionFormCheckList.tsx, web/src/components/AssertionForm/AssertionFormProvider.tsx, web/src/components/TestHeader/TestHeader.tsx, web/src/components/TraceDrawer/TraceDrawer.tsx
This PR solves a couple of issues found on #513 
- We want to be able to click on 'Test Status: Finished' and have the bottom test area expand (we watch somebody do this... might as well help get them to the test if they do not see it at the bottom) ✅ 
- When editing an assertion, the 'Add' button should say 'Save' ✅ 
- If you add a second check line (ie add check), there is no way to delete that line. Should have a trash can next to it. ✅
=> 513 simple ux issues

server/testdb/runs.go
This PR fetches the test version from the proper location and returns it on all `run` endpoints.
=> fix: return test version on run object

api/trace.yaml, server/http/mappings.go, server/openapi/model_span.go
This PR changes the openapi span to use unix milli as the format for start and end time
- update openapi to use integer for start and end time
- update mappings to use the new format
=> change start and end time to unix milli

server/executor/integration_test.go, server/http/controller_integration_test.go, server/integration/rerun_test_run_test.go, server/integration/run_and_assert_pokemon_app_test.go, server/testfixtures/fixture.go, server/testfixtures/fixture_names.go, server/testfixtures/fixture_test.go, server/testfixtures/import_pokemon_test_fixture.go, server/testfixtures/import_pokemon_test_run.go, server/testfixtures/pokeshop_app_fixture.go, server/testfixtures/tracetest_app_fixture.go
This PR introduces a new testing structure called `fixtures` based on Python's pytest.
Fixtures are a way of obtaining a specific value that can be reused by tests. Fixtures also cache their value, so if you call a fixture twice, it will only generate the value once and all subsequent calls will use the cache.
1. Our integration test was complex
2. I wanted to be able to write more integration tests to prevent our changes from breaking things (versioning did that a couple of times and integration tests would have allowed us to see that during development). However, adding more tests that relied on the pokemon demo, the more our test suite would take to run. Thus, by adding a mechanism that would automatically cache those values and only run things once, we reduce this overhead.
One idea …
=> add test fixtures to improve test setup

web/src/components/AttributeRow/AttributeRow.styled.ts, web/src/components/AttributeRow/AttributeRow.tsx, web/src/components/AttributeRow/__tests__/AttributeRow.test.tsx
This PR fixes the alignment issue we had with the add assertion tooltip, it also adds a tooltip for the copy action.
- Copy action tooltip.
- https://github.com/kubeshop/tracetest/issues/549
=> ✨ 549 fixing tooltip alignment

server/http/controller.go, server/integration/add_assertion_test.go, server/integration/run_and_assert_pokemon_app_test.go, server/migrations/5_test_definition_version.down.sql, server/migrations/5_test_definition_version.up.sql, server/migrations/migration_test.go, server/model/test_changes.go, server/model/tests.go, server/testdb/definitions.go, server/testfixtures/fixture.go, server/testfixtures/fixture_test.go, server/testfixtures/import_pokemon_test_fixture.go, server/testfixtures/import_pokemon_test_run.go, server/testfixtures/options.go, server/testfixtures/pokeshop_app_fixture.go, server/testfixtures/tracetest_app_fixture.go
This PR fixes the issue of updating the test definition and the test is on the same 
- Version test definition
- Added option to disable cache in fixtures
- Added field to definitions table
=> fix: test definition versioning

server/testdb/runs.go
This PR fixes the order by field in the get runs query so they are display newest first.
- fix case typo in query
=> Fix test runs sorting

web/src/components/AssertionCard/AssertionCard.tsx
This PR fixes an issue with the onClick propagation in the assertion header.
- Fix onClick event.
- #567
=> Fix onClick propagation in assertion header

web/src/components/AssertionCard/AssertionCard.tsx, web/src/models/AssertionResults.model.ts, web/src/providers/TestDefinition/TestDefinition.provider.tsx, web/src/providers/TestDefinition/hooks/useTestDefinitionCrud.ts, web/src/redux/slices/TestDefinition.slice.ts, web/src/redux/slices/__tests__/TestDefinition.slice.test.ts, web/src/types/Assertion.types.ts, web/src/types/TestDefinition.types.ts
This PR add revert logic to individual assertions
- implement field originalSelector on assertions
=> implement revert logic by using originalSelector

server/assertions/assertions.go, server/assertions/assetions_test.go, server/executor/assertion_runner_test.go, server/http/controller.go, server/http/mappings.go, server/http/mappings_test.go, server/model/ordered_map.go, server/model/repository.go, server/model/run.go, server/model/test_changes.go, server/model/tests.go, server/model/tests_test.go, server/testdb/definitions.go, server/testdb/definitions_test.go, server/testdb/mock.go, server/testdb/runs_test.go, server/testmock/data/pokeshop_import_pokemon.json, server/testmock/data/pokeshop_import_pokemon_failed_assertions.json
This PR ensures consistent ordering of tests definition and results. The issue comes from go's map implementation, which we use as the internal representation. I've implemented an `OrderedMap` that allows us to keep using the map approach but maintaining the order.
I think this is the smallest change possible, since we are keeping the internal concepts untouched, it just updates the implementation.
NOTE: this is a **VERY** backwards incompatible change. All saved tests/results are unparseable now.
- Change internal model `Definition` and `Result` representation from maps to `OrderedMaps`
- Update consumers implementations, including tests
- Add tests to ensure order is consistent
- Inconsistent definition and results order
=> Fix: ensure consistent ordering of test definitions

server/model/tests.go, server/testdb/tests.go, server/testdb/tests_test.go
This PR adds `createdAt` field to test and sorts sql query.
- add `Test.createdAt` internally
- add sorting to get tests query
- test sort order
=> Fix: sort tests by newest first

web/src/components/AttributeRow/AttributeRow.styled.ts, web/src/constants/SemanticGroupNames.constants.ts
This PR fixes the issue with small screens not showing the copy and add assertion button for attributes with long values.
- attribute row styling
- https://github.com/kubeshop/tracetest/issues/618
https://www.loom.com/share/85841d3590de4f7a97d3f485c35865e4
=> 🪟 618 add assertion and copy buttons do not show next to attributes at all screen sizes

web/src/components/ResizableDrawer/ResizableDrawer.tsx, web/src/components/ResizableDrawer/useReferenceMemo.tsx, web/src/components/ResizableDrawer/useSetIsCollapsedCallback.tsx, web/src/components/TraceDrawer/TraceDrawer.tsx, web/src/components/TraceDrawer/TraceDrawerHeader.tsx, web/src/components/TraceDrawer/useChevronDirectionMemo.tsx
This PR make open drawerState not to be the max height the drawer can be set to
- adds a DrawerState.MAX to the drawerState
-  default chevron orientation to match open/close action
=> Latest drawer behaviour

server/assertions/assertions.go, server/assertions/assetions_test.go, server/assertions/comparator/basic.go, server/assertions/comparator/basic_test.go, server/http/controller_test.go, server/http/mappings.go
This PR fixes a bug detected when using the `contains` operator. The error was we were doing the comparations in the incorrect order (`expected < actual` instead of `actual < expected`), but we were also passing the conditions in an inverted order, so the error cancelled out. When using `contains`, we use the go `strings.Contains` function, and here the error doesn't cancel out.
- Fix expected/actual comparation order
=> Fix contains comparator not matching

web/src/constants/Operator.constants.ts, web/src/redux/slices/TestDefinition.slice.ts
This PR fixes the issue related to updating a draft assertion by using the right selector match.
=> 🐛 fixing update definition action

cli/actions/export_test_action.go, cli/cmd/test_export_cmd.go, cli/cmd/test_export_cmd_test.go, cli/conversion/openapi_definition_conversion.go, cli/conversion/openapi_definition_conversion_test.go, cli/file/definition.go, cli/openapi/model_test_run.go
This PR add a new command to the CLI: `tracetest test export --id <id> --output <output-file.yml>`
=> feat: export tests using the CLI

cli/conversion/openapi_definition_conversion.go, cli/conversion/openapi_definition_conversion_test.go
This PR quote string values in assertions when exporting a test
=> fix: quote string values in assertions when exporting a test

cli/definition/test.go
Our UI doesn't create a description, so by validating it, we automatically make all exported tests invalid because no test created via UI have this attribute.
=> fix: don't validate description because our server doesn't use it

cli/.gitignore, cli/actions/configure_action.go, cli/cmd/configure_cmd.go, cli/cmd/configure_cmd_test.go, cli/cmd/e2e/cli.go, cli/cmd/test_export_cmd_test.go, cli/cmd/test_list_cmd_test.go, cli/cmd/test_run_cmd_test.go, cli/config.yml, cli/config/config.go
This PR adds a command `tracetest configure` that allows you to define the configuration of the CLI. Now you don't have to manage the `config.yml` file manually.
Other than that, it also supports a global configuration inside `~/.tracetest/config.yml`. This is a fallback configuration that is only used if the current directory doesn't contain any config file in it. You also can write the configuration in the global config file by executing `tracetest configure --global`.
```shell
$ tracetest configure
Enter your Tracetest server URL (current value: http://localhost:8080): 
```
```shell
$ tracetest configure --global
Enter your Tracetest server URL (current value: http://localhost:1234): 
```
=> feat: better CLI configuration setup

cli/file/definition.go, cli/file/definition_test.go, cli/testdata/definitions/valid_http_test_definition_with_env_variables.yml
This PR enables users to define env variables in the definition file. Those variables will be replaced when the file is read from disk and its values are retrieved from the machine the CLI is running on.
Variables are declared as: `value: ${MY_VARIABLE}`. If the variable doesn't exist in the machine, it will be replaced with an empty string.
=> feat: support env variables in definition file

web/src/components/AttributeList/AttributeList.styled.ts, web/src/components/Diagram/Diagram.tsx, web/src/components/Diagram/__tests__/Diagram.test.tsx, web/src/components/Diagram/components/DAG.tsx, web/src/components/SkeletonDiagram/SkeletonDiagram.styled.ts, web/src/components/SkeletonDiagram/SkeletonDiagram.tsx, web/src/components/SkeletonDiagram/SkeletonNode.tsx, web/src/components/SkeletonDiagram/__tests__/SkeletonDiagram.test.tsx, web/src/components/SkeletonDiagram/index.ts, web/src/components/Trace/Trace.tsx, web/src/constants/Common.constants.ts, web/src/constants/Diagram.constants.ts, web/src/hooks/__tests__/useDAGChart.test.tsx, web/src/hooks/useDAGChart.ts
This PR adds the skeleton diagram component which displays when the trace is not ready.
- Skeleton Diagram
- Fix minor styling issues
- https://github.com/kubeshop/tracetest/issues/631
- https://github.com/kubeshop/tracetest/issues/654
https://www.loom.com/share/0336f061fc5843e69b251c907af18f4d
=> ☠️ 657 Displaying skeleton diagram when trace is not ready

web/src/components/Diagram/components/DAG.styled.tsx, web/src/components/Diagram/components/DAG.tsx
This PR adds the zoom in/zoom out controls for the trace diagram in the test view page.
- New zoom controls.
- #667 
https://user-images.githubusercontent.com/3879892/172200398-07bf947c-dd32-456f-abcb-7ecc0f2c4bd6.mov
=> Add zoom in and zoom out controls in test view page

web/src/components/MultiSelectInput/MultiSelectInputTag.tsx
This PR fixes an event propagation when removing a value from the `MultiSelectInput` component. 
With this change we want to handle the following use case: When you click the X to delete one filter it puts you in the `add a new filter` mode and prompts you for an attribute. We want to avoid the add a new filter mode in this situation.
- Antd lib uses the [rc-select](https://github.com/react-component/select) component. This component has an `onMouseDown` [event that was firing the function to open the options panel](https://github.com/react-component/select/blob/master/src/Selector/MultipleSelector.tsx#L127). With this change we are stopping the event propagation when doing a mouseDown in the close icon.
- #552 
https://user-images.githubusercontent.com/3879892/172238887-4b654a14-d512-4692 …
=> Fix event propagation when removing selector

api/openapi.yaml, cli/actions/run_test_action.go, cli/cmd/test_run_cmd.go, cli/cmd/test_run_cmd_test.go, cli/openapi/api_api.go, server/junit/junit.go
This PR adds an option in the CLI to save a test run result in JUnit format in a local file. It must be run with `--wait-for-result` so it has results to check.
- Add new option to `test run`
- nil pointer error in server when run has no results (i.e. run ended with error)
=> feat: save junit file from cli

web/src/components/AssertionCardList/AssertionCardList.styled.ts, web/src/components/AssertionCardList/AssertionCardList.tsx, web/src/components/FailedTrace/FailedTrace.tsx, web/src/components/FailedTrace/__tests__/FailedTrace.test.tsx, web/src/constants/Span.constants.ts, web/src/constants/SpanAttribute.constants.ts, web/src/pages/Trace/TraceContent.tsx, web/src/services/SpanAttribute.service.ts
This PR updates the empty state styling for assertions, updates the custom attributes to display better data and adds the `lastErrorState` to the failed trace component.
- No assertions state style update
- Last error state added to the failed trace component.
- Updating the custom attribute tab 
- https://github.com/kubeshop/tracetest/issues/656
=> 🐛 656 multiple minor fixes

server/model/json.go
This PR adds a check when unmarshalling `SpanAsseritonResult` so it can use the correc `comparator.ErrNoMatch` type when the original marshaled error was that.
=> fix: map correct error type for SpanAssertionResult.CompareErr

server/analytics/analytics.go, server/analytics/analytics_test.go, server/app/app.go, server/migrations/6_server_id.down.sql, server/migrations/6_server_id.up.sql, server/model/repository.go, server/testdb/mock.go, server/testdb/postgres.go
This PR allows for sending new install beacons to GA. It works by creating a `server` table, where we save the generated server id. This guarantees that each install will have only one ID, and we can detect when that id is being created. Thus, we can detect "new installs" and signal them.
- Add a new server table
- Move machineID generation to repo so it can be persisted
=> feat: GA Beacon for new server installs

web/src/selectors/TestDefinition.selectors.ts
This PR fixes a problem we are having when adding a new assertion. The affected spans are not showing up because of the selected assertion check we have doesn't exists in the state.
- Validates if the selected assertion has any value
- 
https://www.loom.com/share/bc58e5ff43484879ad3c6a285be7a889
=> 🦟 reverting selected assertion check on selector

server/http/custom_routes.go, server/tracing/tracer.go
This PR enables context propagation in our HTTP endpoints
=> fix: context propagation in http tracing controller

.github/workflows/deploy-beta.yml, .github/workflows/deploy-demo.yml, docker-compose.yaml, docs/websocket.md, server/app/app.go, server/http/websocket/router.go, server/http/websocket/subscribe.go, server/http/websocket/unsubscribe.go
This PR makes the websocket available when deployed behind a k8s ingress. Example with (temporary) deploy to beta:
- make the WS listen on the same port as regular http requests
- fix the deploy gh actions to set new settings for ingress
=> feat: correctly expose websockets 

cli/conversion/parser/assertion_parser.go, cli/conversion/parser/assertion_parser_test.go, cli/file/definition_test.go, cli/testdata/definitions/valid_http_test_definition.yml
This PR enables the usage of single quotes to escape double quotes in queries.
```yaml
assertions:
- tracetest.response.body contains '"some value that must be quoted"'
```
```yaml
assertions:
- tracetest.response.body contains "'some value that must be singled quoted'"
```
```yaml
assertions:
- 'tracetest.response.body contains "\"id\": 52"'
```
- #735
=> fix: assertion query quoting

server/http/websocket/messages.go
This PR adds openapi mapping to websocket response
=> feat: return openapi objects in websocket response

.github/workflows/deploy-beta.yml, .github/workflows/release-server.yml
This PR sets the correct annotations on the services deployed in demo and beta env so we can configure the correct timeout.
Depends on https://github.com/kubeshop/helm-charts/pull/191
=> fix: demo and beta settings for websocket timeout

cli/actions/run_test_action.go, cli/file/definition.go, cli/file/definition_test.go, cli/variable/injector.go, cli/variable/injector_test.go, cli/variable/options.go, cli/variable/provider.go
This PR injects variables in a better way using reflection and allows the injection to happen after the definition is loaded. This was done so the test definition doesn't have its variables replaced with the values present on the executor machine.
=> fix: better variable injection

api/tests.yaml, cli/conversion/openapi_definition_conversion_test.go, cli/openapi/model_test_.go, server/http/mappings.go, server/openapi/model_test_.go, web/src/components/TestHeader/TestHeader.tsx, web/src/models/Test.model.ts, web/src/types/Generated.types.ts, web/src/types/Test.types.ts
This PR removes the unused property `referenceTestRun`
- Remove field from openapi
- Update server generated models
- Update cli generated models
=> remove unused reference test run

web/src/services/Selector.service.ts
This PR fixes the selector parsing regex to make spaces around operators optional.
Examples:
- `selector: "span[tracetest.span.duration<=500]"` is valid
- `selector: "span[tracetest.span.type = http]"` is valid
=> fix: make spaces around operators optional in selector parsing regex

docs/websocket.md, server/app/app.go, server/executor/assertion_runner.go, server/executor/assertion_runner_test.go, server/executor/run_updater.go, server/executor/runner.go, server/executor/runner_test.go, server/executor/trace_poller.go, server/model/run.go, server/model/tests.go, server/subscription/manager.go, server/subscription/manager_test.go, server/testdb/runs.go, server/testfixtures/import_pokemon_test_run.go
This PR ensures that all testRun updates are correctly notified to subscriptions by changing the notification approach. Instead of having each step "manually" notifying when necessary, I've implemented a composite "RunUpdater" that encapsulates all the update related processes. Now, when a testRun is updated during the testing process, it will automatically notify any subscribers.
For cleanness, this PR also made the `ResourceID` a method of the `TestRun`, which required to have the `TestID` available on the TestRun entity. It is mainly an internal field, so no mappings to openapi where made.
-
-
=> Improve websockets notifications

web/cypress/integration/Home/CreateTestWithAuthentication.spec.ts, web/cypress/integration/Home/createTestWithAuth.ts, web/src/components/CreateTestModal/CreateTestForm.tsx, web/src/components/CreateTestModal/CreateTestFormAuthInput/CreateTestFormAuthInput.styled.ts, web/src/components/CreateTestModal/CreateTestFormAuthInput/CreateTestFormAuthInput.tsx, web/src/components/CreateTestModal/CreateTestFormAuthInput/CreateTestFormAuthTypeInput.tsx, web/src/components/CreateTestModal/CreateTestFormAuthInput/apiKeyFields.tsx, web/src/components/CreateTestModal/CreateTestFormAuthInput/basicFields.tsx, web/src/components/CreateTestModal/CreateTestFormAuthInput/bearerFields.tsx, web/src/components/CreateTestModal/CreateTestFormDemoHelper.tsx, web/src/components/CreateTestModal/CreateTestFormHeadersInput.tsx, web/src/components/CreateTestModal/CreateTestFormUrlInput.tsx, web/src/components/CreateTestModal/CreateTestModal.tsx, web/src/components/CreateTestModal/__tests__/CreateTestModal.test.tsx, web/src/components/CreateTestModal/useCreateTestFormHandleChangeCallback.tsx, web/src/types/Common.types.ts, web/src/utils/Tests.tsx
This PR add authentication options to the test creation form with integration & unit tests
=> Add HTTP auth options to Test creation

server/app/app.go, server/go.mod, server/go.sum, server/http/custom_routes.go
This PR enables gzip compression on our endpoints if the header `Accept-Encoding: gzip`is provided.
- Compress responses 
- Tested `/tests/{testID}/run/{runID}` using our `pokemon/import`: response got reduced from `10.35kb` to `1.71kb`
=> add gzip compression on responses

server/assertions/assertions.go, server/assertions/assetions_test.go, server/assertions/meta_attrs.go, server/http/mappings.go, server/junit/junit.go, server/model/json.go, server/model/tests.go, server/model/tests_test.go, server/testdb/runs_test.go
This PR adds the ability to assert on the collection level. For now it only adds support for a `spans_collection.count` attribute, which maps to the amount of spans selected by the selector query.
-
-
=> feat: Allow assertions at the span collection level

.github/workflows/pull-request.yaml, api/tests.yaml, server/assertions/selectors/builder.go, server/assertions/selectors/pseudo_classes.go, server/assertions/selectors/search.go, server/assertions/selectors/selector.go, server/http/mappings.go, server/openapi/model_selector_pseudo_class.go
This PR fixes the argument returned in the selector structure when the pseudo-class is nth_child.
=> fix: nth_child selector structure

web/src/components/AssertionCardList/AssertionCardList.tsx
This PR brings back the behavior of opening the bottom panel when editing an assertion.
- call OpenBottomPanel when editing as assertion
=> expand bottom panel when editing an assertion

.dockerignore, cli/Makefile, docker-compose.testrunner.yaml, docker-compose.yaml, run-tracetesting-tests.sh, testrunner.Dockerfile, tracetesting/config.main.yml, tracetesting/config.target.yml, tracetesting/funcs.bash, tracetesting/run.bash, web/. dockerignore
This PR adds a command to locally run dogfood tests with just one command. Without this, developing tests is annoying, because you need to carefully setup some port forwardings to a k8s instance.
-
-
=> Dogfood tests locally with docker compose

server/assertions/assertions.go
This PR fixes the bug where all selected spans had the same ID
=> fix: duplicated ids on span results

.github/workflows/pull-request.yaml, server/app/app.go, server/executor/poller_executor.go, server/executor/trace_poller.go, tracetesting/definitions/test_run.yml
This PR adds instrumentation for the `trace poller` process. Every time we try to get a trace, a new span is created. This also changes the integration test to check for the new instrumentation 
- Add instrumentation to the trace polling process
=> Feat: poller instrumentation

web/src/components/AssertionCheckRow/AssertionCheckRow.tsx
This PR remove tooltip issue emiting a warning
Same as the one described here
https://github.com/ant-design/ant-design/issues/21133
- add a span element between the tooltip and the badge
- removes warning
=> remove warning from console

docker-compose.testrunner.yaml, docker-compose.yaml, run-tracetesting-tests.sh, server/.dockerignore, server/testdb/tests.go, tracetesting/.gitignore, tracetesting/definitions/test_create_with_id_exists.yml, tracetesting/definitions/test_create_with_id_notexists.yml, tracetesting/definitions/test_list.yml, tracetesting/run.bash
This PR changes the way we fetch tests from DB. instead of having two separated methods to get tests and definitions, we get the definitions as a `JOIN` when getting tests.
- Adds tracetest for number of queries on select
- Use join to reduce number of queries.
-  several fixes on scripts/docker compose for running local tracetests
=> reduce number of db queries for getting tests

setup.sh
This PR adds the following demo params in `setup.sh`:
- image.tag=latest
- image.pullPolicy=Always
- image.tag=latest
- image.pullPolicy=Always
- N/A
=> Add latest demo image in setup.sh

.github/workflows/mkdocs.yml, docs/advanced-selectors.md, mkdocs.yml
Our selector graph was rendered without the colors. This PR fixes it.
Before:
After:
=> fix: graphs rendering on documentation page

.github/workflows/pull-request.yaml, cli/conversion/parser/assertion_parser.go, cli/conversion/parser/assertion_parser_test.go, cli/file/definition_test.go, cli/testdata/definitions/valid_http_test_definition.yml, cli/testdata/definitions/valid_http_test_definition_with_id.yml, server/app/app.go, server/executor/poller_executor.go, server/http/controller.go, server/http/controller_test.go, server/http/mappings.go, server/testdb/definitions_test.go, server/testfixtures/import_pokemon_test_fixture.go, server/testmock/data/pokeshop_import_pokemon.json, server/testmock/data/pokeshop_import_pokemon_failed_assertions.json, server/traces/conversion_config.go, server/traces/otel_converter.go, server/traces/time_converter.go, server/traces/time_converter_test.go, web/cypress/integration/Trace/RunTest.spec.ts
Today we show time attributes (especially `tracetest.span.duration`) as a number. That number represents the number of milliseconds that the took to execute the operation. However, there is no indication that is in `ms`, and worse, sometimes some operations take less than one millisecond and the duration appears as `0`. 
> :information_source: Note: Before that, we were displaying the duration as the number of nanoseconds to execute the operation. It was precise, but the number was too big to be easily understood.
Convert the duration from nanoseconds to a nice human-readable value and show the time unit. So instead of showing `1400000000`, Tracetest is going to show it as `1.4s` instead. It converts from nanoseconds (`ns`) to microseconds (`μs`), milliseconds(`ms`), seconds(`s`), …
=> feat: convert time into the right time unit

api/trace.yaml, cli/openapi/model_span.go, server/http/mappings.go, server/openapi/model_span.go, server/testdb/runs_test.go, server/traces/traces.go, server/traces/traces_test.go
This PR stores the start and end date as numbers instead of date formats in the database, so we don't lose precision.
=> fix:start end dates

web/src/components/Diagram/components/Timeline/Timeline.tsx
This PR fixes the timeline graph. It was using the `duration` field which now is a string value.
- Timeline graph
- N/A
=> Fix timeline graph duration

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/enhancement.md, .github/ISSUE_TEMPLATE/feature_request.md
This PR adds labels to issues opened via templates. This adds a new label `triage` that will help us to detect issues opened by our users.
=> add labels to issues opened by users

server/traces/traces.go, server/traces/traces_test.go
This PR reduces the size of our responses by removing children and parents from each span in the flattened structure.
It leaves us one step closer to #741
=> fix: reduce flatten trace size

docs/installing.md, install-cli.sh
This PR adds instructions of how to install the CLI and a script to help installing it on Mac and Linux
=> docs: add cli installation script and how to install it

web/cypress.json
This PR makes tracetest use our new cypress account
=> fix: use the new cypress project id

web/src/components/FailedTrace/FailedTrace.tsx, web/src/pages/Trace/TraceContent.tsx
This PR fixes the double request triggered to the backend when trying to rerun a failed trace.
It also changes the endpoint to use the `/rerun` one instead `/run`
- https://github.com/kubeshop/tracetest/issues/922
=> 🦟 922 fixing failed trace rerun

.github/workflows/deploy-main.yml, .github/workflows/pull-request.yaml, .github/workflows/release-server.yml, docker-compose.yaml, docs/installing.md, docs/run-locally.md, server/config.yaml.sample, server/config/config.go, server/config/config_test.go, server/config/testdata/basic_config.yaml, server/config/testdata/empty_exporter.yaml, server/config/testdata/exporter_config.yaml, server/config/testdata/inexistent_datastore.yaml, server/config/testdata/inexistent_exporter.yaml, server/config/testdata/jaeger_datastore.yaml, server/config/testdata/tempo_datastore.yaml, server/testmock/app.go, server/tracedb/jaegerdb_test.go, server/tracedb/tempodb_test.go, server/tracedb/tracedb.go, server/tracedb/tracedb_test.go, server/tracing/tracer.go, setup.sh
This PR reworks how we define telemetry configuration in the config file.
=> rework configuration file to deal with telemetry

web/src/components/CreateTestPlugins/Rest/steps/RequestDetails/RequestDetailsUrlInput.tsx, web/src/utils/Validator.ts, web/src/utils/__tests__/Validator.test.ts
This PR implements a custom validator for the url field because antd internal validation invalidates single word hostnames
- removes Form.Item rules
- adds a single new rule with custom validtor
- fix issue #920
=> make single word hostname a valid url

.github/workflows/pull-request.yaml, run-tracetesting-tests.sh, server/executor/trigger/grpc.go, server/executor/trigger/http.go, server/executor/trigger/instrument.go, server/go.mod, server/go.sum, server/model/grpc.go, tracetesting/definitions/grpc_test_create.yml, tracetesting/definitions/test_create.yml
This PR fixes the instrumentation for gRPC triggers, so that the parent Span ID is correctly set on the service under test.
=> Fix grpc parent span

local-config/config.tests.yaml, server/executor/trigger/grpc.go, server/model/grpc.go, tracetesting/definitions/grpc_test_create_invalid_metadata.yml, tracetesting/definitions/grpc_test_run_invalid_metadata.yml, tracetesting/grpc.bash, tracetesting/tests.bash
This PR fixes a panic caused by invalid Metadata set for a gRPC trigger
-
-
=> Fix gRPC panic with invalid headers

web/src/services/Triggers/Rpc.service.ts
This PR fixes the way we send the metadata array by default to the backend removing the faulty objects.
=> 🐛 Filtering metadata array for rpc requests

web/src/components/AssertionItem/AssertionHeader.tsx, web/src/components/AssertionItem/AssertionItem.styled.ts, web/src/components/AssertionItem/AssertionItem.tsx, web/src/components/AssertionList/AssertionList.tsx
This PR adds support for the `wizard` mode in the assertion header component.
- Assertion header.
- Fixes #942
=> Wizard toggle not working on an assertion that can be represented by a key value mode

.github/workflows/deploy-main.yml, .github/workflows/pull-request.yaml, docker-compose.yaml, k8s/collector.yml, local-config/collector.config.yaml, local-config/config.tests.yaml, server/tracing/tracer.go
This PR lowers the batching time out for the otel collector and server exporter to 100ms, so traces are almost instantly available to tracetest. This should result in more stable test results.
=> reduce otel batching timeout

web/src/constants/Common.constants.ts
This PR fixes the advanced selectors link in the app.
- Advanced selectors link
- Fixes #971
=> Query language reference link in the app should point to docs version

web/src/components/AssertionItem/AssertionItem.styled.ts, web/src/components/AssertionItem/CheckItem.tsx
This PR fixes a `word break` issue in the assertion check.
- Word break css for assertion check
- Fixes #969
=> Rendering issue in assertion results unless screen is wide

setup.sh
Add missing backslash which fixes helm install command
- Adds backslash to `helm upgrade --install` command
- Fixes installer
=> Add missing slash

web/src/components/AdvancedEditor/AdvancedEditor.tsx, web/src/components/AssertionForm/AssertionFormSelector.tsx, web/src/components/AssertionForm/AssertionFormSelectorInput.tsx, web/src/components/AssertionItem/AssertionHeader.tsx, web/src/selectors/Assertion.selectors.ts
This PR fixes some issues regarding the assertion form. including:
1. Attribute list for checks not being in alphabetical order.
2. Not able to select all spans
- Removing the required rules for the selector input.
- Adding a sorting for when fetching the attribute list.
- https://github.com/kubeshop/tracetest/issues/974
- https://github.com/kubeshop/tracetest/issues/973
=> 🐛 973 fixing minor assertions issues

web/src/components/AssertionForm/AssertionFormCheck.tsx
This PR adds the `equals` operator as a default value when adding a new check.
- Assertion form
- Fixes #968
=> When adding a second check in an assertion, the operator does not default to equals

server/testdb/tests.go
This PR preserves the createdAt timestamp of a test when it is updated.
=> Preserve createdAt when updating tests

web/src/components/AssertionItem/AssertionItem.tsx, web/src/redux/slices/TestDefinition.slice.ts, web/src/redux/slices/__tests__/TestDefinition.slice.test.ts, web/src/services/Assertion.service.ts, web/src/types/TestDefinition.types.ts
With the changed introduce in #974, we were having an incorrect behavior in the `select assertion` logic when you add an empty selector (to select all spans). 
The problem is caused because we use the `selector` as an identifier of the assertion, but now (having it as empty) it was collapsing with the logic for a `non-selected` assertion.
- Change the `selectedAssertion` state to be `undefined` if no assertion is selected.
- #974
=> Fix selected assertion

web/src/gateways/Test.gateway.ts, web/src/gateways/__tests__/Test.gateway.test.ts, web/src/pages/Home/Home.styled.tsx, web/src/pages/Home/NoResults.tsx, web/src/pages/Home/TestList.tsx, web/src/redux/apis/TraceTest.api.ts, web/src/redux/apis/__tests__/useGetTestListQuery.test.tsx
This PR adds support for infinite scroll pagination in the Test list.
- Implement the infinite scroll hook in the Test list
- Fixes #991
=> Add pagination in Test list

setup.sh
This PR fixes the setup script when calling it remotely by removing the dependency on the local `k8s/deploy-collector.sh` script.
=> Fix setup script

web/src/components/WithAnalytics/WithAnalytics.tsx, web/src/services/Analytics/Analytics.service.ts, web/src/types/Common.types.ts
This PR adds the server-side info to all of the analytics events (track, page, identify).
- Adds the server info to each analytics method.
- Analytics
=> 👁  Adding extra server info to all analytics events

web/src/components/AdvancedEditor/AdvancedEditor.styled.ts, web/src/components/Diagram/components/DAG/DAG.tsx
This PR fixes the issue where the advanced editor looked like read-only when not focusing it and the issue regarding the selector not matching any spans looked like the spans were active.
- Advanced editor outline is always visible.
- Adding OR condition for create assertion form status.
- https://github.com/kubeshop/tracetest/issues/1035
- https://github.com/kubeshop/tracetest/issues/1036
=> 🐛 1035 minor fixes

web/src/components/Diagram/components/DAG/DAG.tsx
This PR sets the DAG min zoom to `0.1` to make the `fit-view` action work properly.
- DAG min zoom.
- Fixes #1037
=> Fix fit in view function from the DAG

server/traces/otel_converter.go
This PR changes the spans with no defined type from semantic conventions from "unknown" to "general" in the backend
=> Rename "unknown" spans to "general" in backend

server/assertions/selectors/search.go, server/assertions/selectors/selector_test.go
This PR makes the selector doesn't match the parent span when a child span is provided.
=> fix: don't match parent span when child selector is provided

.github/workflows/pull-request-installer.yaml, docs/installing.md, install-cli.sh
This PR adds a GH actions workflow to ensure basic functionality of the CLI installer. Right now it only tests linux on amd64, since that's the only arch we have runners configured, but can be extended to other OSs/architectures by creating self-hosted runners
=> add workflow to test installer

web/src/components/AssertionForm/AssertionForm.styled.ts, web/src/components/AttributeRow/AttributeRow.styled.ts, web/src/components/AttributeRow/AttributeRow.tsx, web/src/components/AttributeRow/AttributeTitle.tsx
This PR deals with attributes name being trucated
- increase AttributeCheck grid column size
- Add tooltip to attribute table if key is longer than 26 characters
- #914
=> Long trace attributes

setup.sh
This PR is a quick fix for the setup script. The script installs otel collector to the `default` namespace, but tracetest config expects it to be on the same namespace as tracetest, so the startup fails.
This quick fix moves the otel collector to the same ns as tracetest
=> fix: setup script otel collector config

cli/actions/run_test_action.go, cli/file/definition.go
This PR fixes the problems related to empty fields being added to the test file after running a test. It only adds the id property to the file if it doesn't exist and replaces it if it exists.
Related to issue #976
=> fix: replace id in test file instead of rewriting whole file

examples/tracetest-opensearch/README.md, examples/tracetest-opensearch/collector.config.yaml, examples/tracetest-opensearch/docker-compose.yml, examples/tracetest-opensearch/opensearch/opensearch-analytics.yaml, examples/tracetest-opensearch/opensearch/opensearch-data-prepper-config.yaml, examples/tracetest-opensearch/opensearch/opensearch.yaml, examples/tracetest-opensearch/tests/list-tests.yaml, examples/tracetest-opensearch/tracetest-config.yaml
This PR adds an example of how one can setup tracetest to connect to an opensearch instance and use it as a tracing backend.
=> add example of how to connect tracetest and opensearch

server/tracedb/opensearchdb.go
This PR fixes the way tracetest converts spans from opensearch to its internal format
=> fix: opensearch span convertion

web/cypress/integration/Trace/CreateAssertion.spec.ts, web/cypress/support/commands.ts, web/src/components/AssertionForm/AssertionForm.tsx, web/src/components/AssertionForm/AssertionFormCheck.tsx, web/src/components/AssertionForm/AssertionFormCheckList.tsx, web/src/components/AssertionForm/hooks/useGetOTELSemanticConvertionAttributesInfo.tsx, web/src/constants/AttributesTags.json, web/src/constants/SpanAttribute.constants.ts, web/src/react-app-env.d.ts, web/src/redux/apis/OTELYaml.d.ts, web/src/redux/apis/OtelRepo.api.ts, web/src/redux/apis/TraceTest.api.ts, web/src/redux/store.tsx, web/tsconfig.json
This PR adds secondary filter options by tags to assertion-check-attribute
- implements #1053 
Fixes #1053
=> add secondary filter options by tags to assertion-check-attribute

web/src/providers/TestDefinition/TestDefinition.provider.tsx
This PR fixes an issue when trying to exit the selected mode after arriving to the run view with a selected assertion
=> 🐛 fixing wrong empty assertion selector

examples/tracetest-tempo/README.md, examples/tracetest-tempo/collector.config.yaml, examples/tracetest-tempo/docker-compose.yml, examples/tracetest-tempo/tempo.config.yaml, examples/tracetest-tempo/tests/list-tests.yaml, examples/tracetest-tempo/tracetest-config.yaml, server/tracedb/tempodb.go, server/traces/otel_converter.go
This PR fixes a panic that happens when connecting to tempo while polling traces. It also adds an example on how to connect to tempo using Tracetest.
=> example: add example using tempo as the tracing backend and fix support for tempo

server/traces/otel_converter.go, server/traces/traces.go
This PR makes our OTEL converter use our new `traces.New` function instead of reimplementing it by hand.
=> fix: use traces.New to create trace instead of manually converting it

web/src/components/FailedTrace/__tests__/FailedTrace.test.tsx, web/src/components/RunDetailTrace/RunDetailTrace.tsx, web/src/components/RunDetailTrigger/RunDetailTrigger.tsx, web/src/components/SpanDetail/SpanDetail.tsx
This PR fixes the creation of a test spec from the Drawer in the Trace mode.
- Add navigate function to move to the Test mode.
-
=> Fix create test spec from drawer

docs/installing.md
This PR reduces friction from trying out tracetest with Jaeger backend.
Note that I know this is a very small thing, and I just want to also say it mostly struck me because the fonts on the installation page led me to believe I needed _both_ the script _and_ helm (which I now know I don't!). If you look at `Install script` vs the bold `Using Helm` is the reason the font threw me off despite them both having the same heading level:
This change does two things:
1. Makes the inline bash comments run without error
2. Updates the endpoints to respect the multi-namespace install
This was debugged but viewing [#1056](https://github.com/kubeshop/tracetest/issues/1056) which also indicates a 
longer term fix in the works. However until that is in place this would
remove a lot of friction for …
=> Update Jaeger install instructions

server/http/mappings/tests.go
This PR fixes the dry-run method running with expressions.
Why it broke: frontend doesn't send the assert expected value wrapped in quotes.
=> fix: expression dry run

server/encoding/yaml/conversion/definition_openapi_conversion.go, server/encoding/yaml/conversion/parser/assertion_parser.go
This PR fixes string fields conversion in expressions
=> fix: assertion parsing infering wrong type of field

cli/Makefile, cli/installer/docker_compose.go, cli/installer/installer.go, cli/installer/kubernetes.go, cli/installer/tracetest.go
This PR installs the basic dependencies needed by the CLI to install the tracetest server to a k8s cluster.
This also fixes docker-engine installation on Ubuntu
=> install dependencies to install tracetest in k8s cluster

cli/analytics/analytics.go, cli/cmd/config.go, server/analytics/analytics.go, server/app/app.go, server/http/controller.go, server/http/custom_routes.go
This PR updates the server and CLI so the client can pass its machineID to the server and use that info to relate events from cli/server
=> Add clientID to analytics

cli/installer/docker_compose.go, cli/installer/tracetest.go, cli/installer/ui.go
This PR adds improvements and bugfix to docker compose installer
- fixes the file mount path for configs
- enforces and helps creating a base docker-compose file
- fixes the otelcol jaeger config
- fixes jaeger/tempo tls config
=> CLI Installer: Docker Compose improvements

cli/installer/kubernetes.go, cli/installer/util.go
This PR adds k8s config questions. It asks the common tracetest settings, plus the specific options for k8s:
- Kubeconfig file
- kubectl context
- expose via ingress
=> CLI installer: add k8s config questions

server/encoding/yaml/conversion/object_to_yaml_conversion.go, server/encoding/yaml/conversion/object_to_yaml_conversion_test.go, server/http/controller.go
This PR removes any empty value from the generated yaml file when exporting the test definition.
**Before**:
**After**:
=> feat: remove any field with empty value from definition file

web/package-lock.json, web/package.json, web/src/providers/TestSpecs/TestSpecs.provider.tsx, web/src/redux/actions/Router.actions.ts, web/src/selectors/TestSpecs.selectors.ts, web/src/utils/Common.ts
This PR updates the way we handle deeplink for the selected assertion, now instead of using the encrypted selector we are using the position index.
- Uses position index instead of encrypted selector
- https://github.com/kubeshop/tracetest/issues/1178
Example URLs:
http://localhost:3000/test/bf18fc27-31c5-49c3-a58e-15a8fb12b071/run/d69064bf-146d-45ed-a29a-7c399cf1ce74/test?selectedAssertion=0
http://localhost:3000/test/bf18fc27-31c5-49c3-a58e-15a8fb12b071/run/d69064bf-146d-45ed-a29a-7c399cf1ce74/test?selectedAssertion=-1
=> 1178 Reference specs by index and not by selector for deep links

server/executor/trigger/http.go, server/executor/trigger/http_test.go
=> fix: don't break if response is not a json response

examples/tracetest-jaeger/tracetest-config.yaml, examples/tracetest-opensearch/tracetest-config.yaml, examples/tracetest-signalfx/tracetest-config.yaml, examples/tracetest-tempo/tracetest-config.yaml
This PR disables the analytics from all examples
=> fix: disable analytics from examples

web/src/components/EditTest/EditTest.tsx
This PR disable the edit form submit button while the test is being run
=> disabled edit form submit button when running test

server/assertions/assertions.go, server/assertions/assetions_test.go, server/model/tests.go, server/model/tests_test.go
This PR converts duration fields before comparing them, so we don't have problems with precision when comparing two duration values.
=> fix: duration comparators

server/executor/trigger/http.go, server/executor/trigger/http_test.go
Reverts kubeshop/tracetest#1198
=> Revert "fix: don't break if response is not a json response"

.github/workflows/pull-request-installer.yaml, docs/installing.md, install-cli.sh
This PR fixes the CLI installer script. It was incorrectly detecting the arch on darwin arm, and generating a wrong download link for that arch
-
-
=> Fix darwin CLI install 

web/src/components/FileViewerModal/FileViewerModal.styled.ts, web/src/components/FileViewerModal/FileViewerModal.tsx
This PR allows users to copy the content of the file to clipboard when looking at the test definition or the JUnit reports.
- Adds copy to clipboard from the file viewer modal.
- https://github.com/kubeshop/tracetest/issues/1217
https://www.loom.com/share/400b39d978564c3e978bb97d226d1242
=> 📄 1217 [Implementation] Need a 'copy to clipboard' option when viewing a test definition#1217

server/encoding/yaml/conversion/definition_openapi_conversion.go, server/http/mappings/tests.go, web/.npmrc, web/cypress/e2e/TestRunDetail/CreateAssertion.spec.ts, web/package-lock.json, web/src/components/TestSpecForm/AssertionCheck.tsx, web/src/components/TestSpecForm/AssertionCheckList.tsx, web/src/components/TestSpecForm/ExpectedInputContainer.ts, web/src/components/TestSpecForm/Fields/AttributeField.tsx, web/src/components/TestSpecForm/TestSpecForm.styled.ts, web/src/components/TestSpecForm/useExpectedInputLanguage.tsx, web/src/constants/Plugins.constants.ts, web/src/redux/apis/TraceTest.api.ts, web/src/services/Assertion.service.ts, web/src/services/__tests__/Assertion.service.test.ts
This PR make necessary changes to support assertions expressions on the frontend
- The backend to fix some implementation bug
- Add new Code Mirror component for expected assertion value
- Removes Duration Field
- Format expected assertion value the proper way so backend works
- #1009 
- #1160
=> Add support for expressions in assertion

cli/actions/run_test_action.go, cli/formatters/test_run.go, cli/formatters/test_run_test.go
This PR adds DeepLink to assertion/result on the CLI results output. Example:
=> Add DeepLink to assertion/result on the CLI results output

web/src/components/AttributeRow/AttributeCheck.tsx, web/src/components/RunCard/RunCard.styled.ts, web/src/components/RunCard/RunCard.tsx, web/src/components/RunDetailTest/RunDetailTest.styled.ts, web/src/components/RunDetailTest/RunDetailTest.tsx, web/src/components/TestResults/TestResults.tsx, web/src/components/TestSpecDetail/TestSpecDetail.styled.ts, web/src/components/TestSpecDetail/TestSpecDetail.tsx, web/src/components/TestSpecForm/TestSpecForm.provider.tsx, web/src/components/Visualization/components/DAG/Actions.tsx, web/src/providers/TestSpecs/TestSpecs.provider.tsx, web/src/providers/TestSpecs/hooks/useTestSpecsCrud.ts, web/src/redux/actions/Router.actions.ts, web/src/selectors/TestSpecs.selectors.ts
This PR fixes multiple UX issues we had with the run detail test mode, including:
- When selecting a spec the first span is targeted and autoselected.
- When creating a spec with an empty selector the app should allow users to navigate correctly.
- Fixed issue when clicking on a span from a assertion result was doing nothing.
- #1207 
- [] added new dependencies
https://www.loom.com/share/7fd3a5a758434308b07b3f76682f2cb8
=> 👀 1207 Selecting a test spec should show the attributes for the first span

web/src/components/Visualization/components/DAG/Actions.tsx, web/src/components/Visualization/components/DAG/DAG.styled.tsx
This PR adds `tooltips` for the DAG actions and also fixes the `mini map` position in the Trace/Test modes.
- Add tooltips and css changes.
- fixes #1237
=> Add DAG tooltips and fix minimap position

web/src/models/DAG.model.ts, web/src/types/DAG.types.ts
This PR sorts the DAG nodes based on the startTime attribute.
- Sorting DAG nodes
- fixes #1243
=> Show DAG with elements ordered left to right based on time

cli/actions/run_test_action.go, cli/cmd/config.go, cli/cmd/root.go, cli/formatters/outputs.go, cli/formatters/test_run.go, cli/formatters/test_run_test.go, k8s/collector.yml, k8s/tracetest.beta.yaml, k8s/tracetest.demo.yaml, k8s/tracetest.integration.yaml, local-config/collector.config.yaml, local-config/config.tests.yaml, tracetesting/grpc.bash
This PR adds a new `output` flag to the CLI, so users can choose between pretty and json output
=> add json output option to CLI

cli/actions/list_tests_action.go, cli/formatters/test_list_test.go, cli/formatters/test_run_test.go, cli/formatters/tests_list.go, cli/go.mod, cli/go.sum, tracetesting/tests.bash
This PR adds formatting for CLI tests list. Examples:
No tests:
With tests:
=> Format CLI tests list

mkdocs.yml
The CSS file was removed on version 8.0 and afterward. This was here because we were using version 7 before.
=> fix: remove mermaid css file

web/src/components/TestSpecForm/TestSpecForm.tsx
This PR removes the `Test Spec name` step in the `Test Spec form`.
- Removes unused field.
- fixes #1258
=> Hide step #3 (Test Spec name) in create Test Spec form

cli/installer/util.go
This PR fixes docker-compose installation on Linux when brew is available.
=> fix: prefer apt over brew

docker-compose.yaml, local-config/collector.config.yaml, local-config/config.tests.yaml, local-config/docker-compose.demo.yaml, local-config/docker-compose.opensearch.yaml, run-tracetesting-tests.sh
This PR uses the otlp dataStore when locally running dogfood tests.
=> Move local dogfood tests to use otlp dataStore

web/src/providers/Test/hooks/useTestCrud.ts
This PR updates the useTestCrud to match the mode from the location and if a mode already exists it is used when rerunning a test.
- https://github.com/kubeshop/tracetest/issues/1268
=> 1268 keeping the same mode when running a test

.github/workflows/pull-request-installer.yaml
This PR fixes GHA settings for installer check
-
-
=> make installer check run on push to main only

cli/installer/tracetest.go, k8s/deploy.sh
This PR changes the `retryDelay` config set by the installer. It was set to `1s`, and it's too low to get consistent results. Setting it to `3s` makes it more consistent.
=> cli installer: lower default retry delay

cli/installer/docker_compose.go
This PR fixes the flow for installing Tracetest with an existing tracing backend
=> fix: opensearch install

web/src/components/CreateTestPlugins/Postman/steps/UploadCollection/UploadCollectionForm.tsx, web/src/components/CreateTestPlugins/Rest/steps/RequestDetails/BodyField/BodyField.tsx, web/src/components/CreateTestPlugins/Rest/steps/RequestDetails/BodyField/useBodyMode.tsx, web/src/components/CreateTestPlugins/Rest/steps/RequestDetails/RequestDetailsForm.tsx
This PR fixes 2 bugs
- First one is described [here](https://github.com/kubeshop/tracetest/issues/1281)
- The second one is when trying to set the body to none, would not make the frontend send the body as empty to the backend. It would still send the same body as before.
=> fix body input bugs

README.md, docs/index.md
Added v0.7 blog and repointed all blog links to tracetest.io/blog except for 3 that only exist on the kubeshop.io site. Also changed the main blog link on the readme to point to tracetest.io.
=> Added v0.7 blog and repointed all blog links to tracetest.io/blog

web/src/components/RunDetailTest/RunDetailTest.styled.ts, web/src/components/RunDetailTest/RunDetailTest.tsx, web/src/components/RunDetailTest/Visualization.tsx, web/src/components/RunDetailTrace/RunDetailTrace.styled.ts, web/src/components/RunDetailTrace/RunDetailTrace.tsx, web/src/components/Visualization/components/Timeline/Label.tsx
This PR adds the visualization switch to the `test mode` to include the timeline view.
- Add timeline view to test mode
- fixes #1238
=> Add timeline view in test mode

server/http/controller.go, server/http/mappings/mappings_test.go, server/http/mappings/tests.go
This PR forces Tracetest to only accept valid mappings. So if an assertion is invalid, it will reject the request by returning a `400 response status` instead of silently failing the request when running the test.
=> fix: validate mappings instead of ignoring errors

.github/workflows/pull-request.yaml, cli/actions/configure_action.go, cli/cmd/configure_cmd.go, cli/cmd/configure_cmd_test.go, cli/installer/cmd.go, cli/installer/constants.go, cli/installer/docker_compose.go, cli/installer/installer.go, cli/installer/kubernetes.go, cli/installer/tracetest.go, cli/installer/util.go, cli/installer/windows.go, cli/ui/ui.go, docs/command-line-tool.md, examples/tracetest-jaeger/README.md, examples/tracetest-opensearch/README.md, examples/tracetest-otel-demo/README.md, examples/tracetest-signalfx/README.md, examples/tracetest-tempo/README.md
This PR extracts the UI code used in the installer to its own package and changes the configure cmd to use that package instead of using the fmt package directly.
Also, it enables setting values using the flags `--endpoint` and `--analytics`
=> feat: cmd configure uses ui package and enable setting values from flags

k8s/deploy.sh
This PR sets a higher timeout for the deploy script. This should help prevent false negatives in deployments.
We get a lot of timeout fails because the cluster sometimes takes a long time to scale the nodes up.
=> set higher timeout for deployments

web/src/redux/actions/TestSpecs.actions.ts, web/src/redux/apis/TraceTest.api.ts, web/src/services/TestDefinition.service.ts
This PR fixes a bug in the Test Spec form by adding the proper format to the `expected` field.
- Format expected field.
-
=> Fix format of expected field

web/src/components/CreateTestPlugins/Default/steps/BasicDetails/BasicDetailsForm.tsx
This PR fixes an issue with the k8 deployment when users wouldn't select a demo as part of the installation.
I'm creating a tech debt ticket to improve the config validation and parsing from the FE side.
=> 🦟 Adding demo enabled check for null values

api/tests.yaml, cli/definition/test.go, docker-compose.yaml, server/assertions/assertions.go, server/assertions/assetions_test.go, server/encoding/yaml/conversion/definition_openapi_conversion.go, server/encoding/yaml/conversion/openapi_definition_conversion.go, server/encoding/yaml/definition/test.go, server/executor/assertion_executor.go, server/http/mappings/mappings_test.go, server/http/mappings/tests.go, server/model/json.go, server/model/json_test.go, server/model/test_changes.go, server/model/tests.go, server/model/tests_test.go, server/openapi/impl.go, server/openapi/model_test_specs_specs.go
This PR enables the user to define a name to a group of assertions. This is retro-compatible with the existing test spec format.
=> feat: support assertion names

examples/collector/docker-compose.yml, examples/tracetest-jaeger/docker-compose.yml, examples/tracetest-opensearch/docker-compose.yml, examples/tracetest-signalfx/docker-compose.yml, examples/tracetest-tempo/docker-compose.yml
This PR fixes the docker configuration for examples to support making requests to host. this is needed for the feature to work on setups created with the installer
-
-
=> fix examples to support network request to host

.github/workflows/pull-request.yaml, examples/docker-compose.opensearch.yaml, k8s/tracetest.beta.yaml, k8s/tracetest.demo.yaml
This PR disables otel demo on beta and demo envs. The config of our otel-demo deployment is not yet ready to correctly interact with these tracetest deployments
=> disable otel demo on beta and demo envs

README.md, docs/command-line-tool.md, docs/introduction.md, docs/run-locally.md, docs/supported-backends.md, examples/tracetest-jaeger/README.md, examples/tracetest-opensearch/README.md, examples/tracetest-signalfx/README.md
Change links to point to new docs.tracetest.io domain.
Also altered the line talking about supported backends to emphasis 'we just work'
=> Change links to point to new docs.tracetest.io domain

cli/actions/run_test_action.go, cli/formatters/test_run.go, cli/formatters/test_run_test.go, cli/openapi/api_api.go, cli/openapi/model_test_specs_specs.go, server/openapi/api_api.go, server/openapi/impl.go
This PR makes the CLI show tests as successful when not waiting for resutls. Before, when a test was run without the `--wait-for-result` option, it would show the test as FAILED, when in fact it still didn't have the result.
Also it pretty prints json so it is easier to read while still being parseable
Before: 
After:
JSON indented:
-
-
=> fix formatting when not waiting for results

web/public/index.html, web/src/components/CreateTestPlugins/Default/steps/BasicDetails/BasicDetailsForm.tsx, web/src/components/Router/Router.tsx, web/src/constants/Demo.constants.ts, web/src/gateways/WebSocket.gateway.ts, web/src/providers/Transaction/Transaction.provider.tsx, web/src/services/Analytics/Analytics.service.ts, web/src/types/Common.types.ts, web/src/utils/Env.ts, web/src/utils/ExperimentalFeature.ts
This PR adds a FE Env utility to read env variables used by Tracetest. It also parses the env variables to a proper type.
- Env util to read parsed variables
- Parse env variables
Types support:
- fixes #1347
=> Add FE env configuration layer

.github/workflows/release-version.yml, scripts/choco/tools/chocolateyinstall.ps1, scripts/choco/tools/chocolateyuninstall.ps1, scripts/choco/tracetest.nuspec
This PR creates a new choco package and releases it when a new tag is created.
=> ci: release CLI on Chocolatey when a new tag is released

cli/actions/run_test_action.go, web/src/components/EnvironmentForm/EnvironmentForm.tsx, web/src/components/EnvironmentSelector/EnvironmentSelector.tsx, web/src/components/EnvironmentSelector/index.ts, web/src/components/Header/Header.tsx, web/src/components/Layout/Layout.tsx, web/src/constants/Test.constants.ts, web/src/models/Environment.model.ts, web/src/models/__mocks__/Environment.mock.ts, web/src/pages/Environments/EnvironmentCard.tsx, web/src/pages/Environments/EnvironmentContent.tsx, web/src/pages/Environments/EnvironmentList.tsx, web/src/pages/Environments/EnvironmentModal.tsx, web/src/pages/Environments/IEnvironment.ts, web/src/providers/Environment/Environment.provider.tsx, web/src/providers/Environment/index.ts, web/src/redux/apis/TraceTest.api.ts, web/src/redux/apis/endpoints/Environment.endpoint.ts, web/src/redux/apis/endpoints/Test.endpoint.ts, web/src/redux/apis/endpoints/TestRun.endpoints.ts, web/src/redux/apis/endpoints/Transaction.endpoint.ts, web/src/redux/slices/User.slice.ts, web/src/redux/store.tsx, web/src/selectors/Environment.selectors.ts, web/src/selectors/User.selectors.ts, web/src/services/UserPreferences.service.ts, web/src/types/Environment.types.ts, web/src/types/Test.types.ts, web/src/types/User.types.ts
This PR wires up the environment dropdown from the header to the rest of the application, it adds the user state to redux where we are going to be storing preferences and in the future things like username, email, roles etc.
The requests are mocked and return stale data, in the future we'll have to revisit the changes to include the BE requests.
- User and user preferences state management
- Environment selector wiring up
- Refactored tracetest endpoints to a folder.
- #1235 
https://www.loom.com/share/7e948e0930264cc9892ab4e4cd8b9939
=> 1235 [Transactions] Wire up environment dropdown with the app

server/executor/trigger/http.go
This PR allows users to send multiple headers with the same name.
Implementation was based on HTTP [RFC 2616](https://www.rfc-editor.org/rfc/rfc2616#section-4.2) which states:
> Multiple message-header fields with the same field-name MAY be
present in a message if and only if the entire field-value for that
header field is defined as a comma-separated list [i.e., #(values)].
Therefore, sending multiple headers with the same name results in a single header with all values concatenated and separated by commas.
Related to issue #1372
=> feat: concatenate multiple header values together using commas

cli/installer/docker_compose.go
This PR fixes the problem @kdhamric found when installing tracetest on windows using docker-compose
=> fix: convert service port to int in generated docker-compose file

docs/expressions.md, server/executor/outputs_processor.go, server/expression/comparison.go, server/expression/executor.go, server/expression/executor_test.go, server/expression/filters.go, server/expression/filters/get_index.go, server/expression/filters/get_index_test.go, server/expression/filters/json_path.go, server/expression/filters/json_path_test.go, server/expression/filters/length.go, server/expression/filters/length_test.go, server/expression/filters/regex.go, server/expression/filters/regex_group.go, server/expression/filters/regex_group_test.go, server/expression/filters/regex_test.go, server/expression/filters/type.go, server/expression/filters/type_test.go, server/expression/filters/utils.go, server/expression/parser_rules.go, server/expression/parser_test.go, server/expression/types/types.go, server/expression/value/value.go
This PR adds a new `type` filter and allows users to declare arrays to run comparisons.
This was based on #950. It is useful for checking if some field is a number or a string
1. Imagine a field can be either a `string` or a `number`. We don't have a way of writing an assertion like that. So instead, we could work with arrays to overcome this issue:
```yaml
["string", "number"] contains attr:my_json | json_path '.id' | type
```
2. Imagine you want to compare multiple values from a json_path query at once:
```yaml
attr:my_json | json_path '$.array[*].id' = [35, 38]
```
=> feat: add "type" filter and support arrays in expressions

server/assertions/selectors/parser.go, server/assertions/selectors/selector_test.go
This PR enables users to define `span[]` as a valid selector to select all spans.
Without this, there's no way of selecting all spans that are descendent of a parent span. With this change, you can define it as `span[parent-attrs] span[]`
=> feat: allow span[] as a valid selector

.github/workflows/pull-request.yaml, cli/actions/run_test_action.go, cli/file/definition.go, cli/file/definition_test.go, cli/openapi/api_api.go, cli/variable/injector.go, cli/variable/injector_test.go, server/assertions/assetions_test.go, server/expression/executor.go, tracetesting/definitions/grpc_test_create.yml, tracetesting/definitions/grpc_test_create_invalid_metadata.yml, tracetesting/definitions/grpc_test_run.yml, tracetesting/definitions/grpc_test_run_invalid_metadata.yml, tracetesting/definitions/test_create.yml, tracetesting/definitions/test_create_with_id_exists.yml, tracetesting/definitions/test_create_with_id_notexists.yml, tracetesting/definitions/test_delete.yml, tracetesting/definitions/test_list.yml, tracetesting/definitions/test_rerun.yml, tracetesting/definitions/test_run.yml, tracetesting/definitions/test_run_delete.yml, tracetesting/definitions/testdata/pokemon_list.yml, tracetesting/transactions/tests/create-existing-id.yaml, tracetesting/transactions/tests/create-nonexisting-id.yaml, tracetesting/transactions/tests/http/test-create.yaml, tracetesting/transactions/tests/http/test-list.yaml, tracetesting/transactions/tests/http/tests-run.yaml
=> fix: make failed assertions to return the formatted duration field

web/src/components/Header/HeaderMenu.tsx, web/src/redux/actions/Router.actions.ts
This PR fixes a couple of small issues on the app, primarily the error where the 1 of X component was disappearing when clicking on the arrows from the test mode.
The second one was a wrong flow when clicking show onboarding as it would display the alert instead of starting the onboarding right away.
- #1401 
- #1418
=> 🐛 1401 1 of X goes away when cycling through spans

web/src/components/CreateTestPlugins/Rest/steps/RequestDetails/RequestDetailsAuthInput/apiKeyFields.tsx, web/src/components/CreateTestPlugins/Rest/steps/RequestDetails/RequestDetailsAuthInput/basicFields.tsx, web/src/components/CreateTestPlugins/Rest/steps/RequestDetails/RequestDetailsAuthInput/bearerFields.tsx
This PR fixes a style issue with the `Authorization Type` in the create test form.
- Style issue
- fixes #1439
=> Fix style issue with the Authorization Type in the create test form

server/http/controller.go, server/model/yaml/encoding.go, server/model/yaml/environment.go, server/model/yaml/file.go, web/public/index.html
This PR adds the definition yaml execution support for environment files, same logic as for tests, if the id exits we update, if not we create a new brand entry to the DB.
- Adds execution support for environment definition files
- #1434 
https://www.loom.com/share/78716627311d45209f14214d6cb0c961 [NO SOUND]
=> 1434 [Transactions] Environment definition execution

web/src/components/TestSpecDetail/Content.tsx, web/src/components/TestSpecDetail/TestSpecDetail.styled.ts
This PR adds an improvement in the UX of the Test Spec detail screen by making the parent container clickable.
- New onClick event and styles
- fixes #1438
=> Add click area in test spec detail

server/http/controller.go, tracetesting/definitions/environment_delete.yml, tracetesting/definitions/environment_list.yml, tracetesting/environments.bash
=> fix environment tracetest tests

web/cypress/e2e/TestRunDetail/TestRunDetail.spec.ts, web/src/components/AttributeList/AttributeList.tsx, web/src/components/AttributeList/__tests__/AttributeList.test.tsx, web/src/components/AttributeRow/AttributeRow.styled.ts, web/src/components/AttributeRow/AttributeRow.tsx, web/src/components/AttributeRow/__tests__/AttributeRow.test.tsx, web/src/components/SearchInput/SearchInput.tsx, web/src/components/SpanDetail/Attributes.tsx, web/src/components/SpanDetail/SpanDetail.styled.ts, web/src/components/SpanDetail/SpanDetail.tsx, web/src/components/SpanDetail/__tests__/SpanDetail.test.tsx, web/src/components/TestSpecForm/Fields/AttributeField.tsx, web/src/components/TestSpecForm/hooks/useGetOTELSemanticConventionAttributesInfo.tsx, web/src/redux/apis/OtelRepo.api.ts, web/src/services/SpanAttribute.service.ts, web/src/services/__tests__/SpanAttribute.service.test.ts
This PR removes the tabs in the search detail view and adds search capabilities to the list of attributes.
- Remove tabs
- Search attributes
- fixes #1449
https://www.loom.com/share/5264974020dc457ca8bac663af5dda29
=> Add search in span detail

.github/workflows/release-version.yml
This PR fixes the CI for deploying the chocolatey package to our internal choco server
- Wrong shell being used in the workflow
=> fix chocolatey deploy

cli/actions/configure_action.go, cli/cmd/config.go, cli/config/config.go
This PR makes the CLI ignore the slash at the end of the endpoint and prevent that from making the API calls from failing.
`http://localhost:1234/` becomes `http://localhost:1234`
This PR also considers that the configuration can be edited by hand and still removes the slash from other places when configuring the CLI HTTP client.
=> fix: ignore extra slash at end of cli endpoint

cli/cmd/config.go, cli/cmd/root.go, cli/cmd/server_cmd.go, cli/cmd/server_install_cmd.go, cli/cmd/test_cmd.go, cli/cmd/test_export_cmd.go, cli/cmd/test_list_cmd.go, cli/cmd/test_run_cmd.go, cli/cmd/version.go
This PR makes the CLI validate if it is configured before running any command.
It also makes the CLI logger print logs as messages and not JSON messages. This doesn't affect test outputs or other formatted outputs. Example:
=> feat: validate cli config

api/transactions.yaml, server/http/mappings/tests.go, server/openapi/impl.go, server/openapi/model_transaction.go, server/openapi/model_transaction_run.go, server/testdb/transactions.go
This PR adds the summary to the transaction endpoints and returns the transaction version in the transaction run object.
=> feat: add summary to transaction listing endpoint and return version in transaction run

server/executor/outputs_processor.go, server/executor/transaction_runner.go, server/model/environments_test.go, server/model/transactions.go, server/model/transactions_test.go
This PR fixes the output processor and environment merging when running transactions.
=> fix: env merging and output processing

web/src/components/ResourceCard/ResourceCardSummary.tsx, web/src/components/RunDetailLayout/RunDetailLayout.tsx, web/src/components/TransactionRunLayout/TransactionRunLayout.tsx, web/src/components/TransactionRunResult/ExecutionStep.tsx, web/src/components/TransactionRunResult/TransactionRunResult.styled.ts, web/src/constants/Common.constants.ts, web/src/hooks/useDocumentTitle.ts, web/src/pages/Test/Content.tsx, web/src/pages/Transaction/Content.tsx, web/src/pages/TransactionRunDetail/Content.tsx, web/src/providers/TransactionRun/TransactionRun.provider.tsx, web/src/providers/TransactionRun/index.ts
This PR has the changes to display the results summary for each of the execution steps on the transaction run page.
It allows users to see the passed and failed assertions.
- Adds the assertions summary to execution steps
- Adds logic to update the document title for tests and transactions
- #1505 
- #1475 
https://www.loom.com/share/812f1b3cb17d414f8b48ae55efca65bf
=> 1505 1475 [Transactions] Display test spec summary results for transaction test runs

server/app/app.go, server/executor/transaction_runner.go, server/executor/transaction_runner_test.go, server/subscription/manager.go
This PR makes the transaction runner send step updates using the subscription manager.
=> send step run updates using the transaction subscription

server/testdb/tests.go, server/testdb/transactions.go, server/testdb/transactions_test.go
This PR fixes the bug where transactions would have duplicated steps when a new test version was created.
=> fix step duplication in transactions

web/src/components/AttributeRow/AttributeRow.styled.ts, web/src/components/AttributeRow/AttributeRow.tsx
This PR implements the new UI for the attribute description popup.
- New info icon for attribute description
- Fix text overflow
- Fix tags space
- fixes #1485
=> Improve attribute section

api/openapi.yaml, docker-compose.yaml, server/http/controller.go, server/model/repository.go, server/openapi/api.go, server/openapi/api_api.go, server/testdb/mock.go, server/testdb/transaction_runs.go, server/testdb/transactions_runs_test.go, web/src/components/ResourceCard/TransactionCard.tsx
This PR enables pagination for the transaction-run service
- Open API and transaction run controller update
- https://github.com/kubeshop/tracetest/issues/1517
=> 1517 [Transactions] Enable Transaction Runs Service Pagination

server/executor/runner.go
This PR makes the transaction runner mark the transaction as FAILED if any of the steps fail.
=> fix: fail transaction when step fail to trigger operation

k8s/tracetest.beta.yaml, web/package-lock.json, web/package.json, web/src/components/RunDetailTest/Visualization.tsx, web/src/components/RunDetailTrace/RunDetailTrace.tsx, web/src/components/RunDetailTrace/Visualization.tsx, web/src/components/Visualization/components/Flame/Flame.styled.tsx, web/src/components/Visualization/components/Flame/Flame.tsx, web/src/components/Visualization/components/Flame/__tests__/FlameView.test.tsx, web/src/components/Visualization/components/Switch/Switch.styled.ts, web/src/components/Visualization/components/Switch/Switch.tsx, web/src/services/Flamegraph.service.ts
This PR add a new trace view called Flame view.
We use the same library jager is using called @pyroscope/flamegraph
So we can benefit from future development for the specific trace visualization goal like this [one](https://github.com/pyroscope-io/pyroscope/pull/1679) 
- Add new Trace view
=> Add Flame Graph as a Trace view

web/public/index.html, web/src/components/OutputModal/OutputModalForm.tsx, web/src/pages/RunDetail/RunDetail.tsx
This PR fixes an issue we have with the creative output modal where the selector field doesn't work as expected.
- Moving span provider to wrap the output modal provider.
- [Fix adding otput flow#1534](https://github.com/kubeshop/tracetest/issues/1534)
=> fix(frontend): fixing output selector input

api/tests.yaml, cli/openapi/api_api.go, cli/openapi/model_test_summary_last_run.go, server/http/mappings/tests.go, server/openapi/model_test_summary_last_run.go
This PR fixes the bug when a test has no runs, the backend would return the last run date as `0001-01-01`, making the UI show `run 2022 years ago`. Now the last run time is optional, so the UI looks like this now:
=> fix(server): make last run time optional in openapi

Makefile, cli/Makefile, cli/openapi/api_api.go, server/Makefile, web/src/types/Generated.types.ts
This PR creates a centralized makefile in the proejct root, so we can regenerate openapi code for all modules with a single command. This will prevent desyncronization between web, cli and server openapi code.
=> chore: merge openapi generation into main makefile

server/executor/assertion_runner.go, server/model/run.go, server/testdb/tests.go, tracetesting/definitions/test_create.yml
This PR fixes two problems with outputs:
1. Right now it's not possible to export output and use it within the same test. This fixes this limitation by injecting the outputs into the environment before running the test assertions;
2. When updating a test that contains outputs, the new version of the test doesn't contain those outputs.
=> feat: allow tests to reference outputs declared in them

.dockerignore, cli/actions/run_test_action.go, cli/cmd/test_run_cmd.go, cli/go.mod, server/http/controller.go, tracetesting/transactions/envs/localhost.env, tracetesting/transactions/test-ids.yaml, tracetesting/transactions/tests/create-existing-id.yaml, tracetesting/transactions/tests/create-nonexisting-id.yaml
This PR adds the `--environment` or `-e` flag. This allows to pass an environment ID to be used when running the test/transaction.
This will use the environment with ID `localhost`
This will create (or update) an env with name/id of `localhost.env` (base path) and run the test/transaction using that id
=> feat(cli): add `--environment` flag

web/cypress/support/commands.ts, web/cypress/support/index.d.ts
This PR fixes an unstable e2e test. The Cypress selector to match autocomplete options in the Assertions form was failing when the `id` of the `<ul />` element had the number '0' in it.
- Fix cypress selector
-
=> fix(e2e): change cypress selector to match autocomplete options

web/cypress/e2e/TestRunDetail/CreateAssertion.spec.ts, web/cypress/e2e/TestRunDetail/TestRunDetail.spec.ts, web/cypress/support/commands.ts, web/public/index.html, web/src/components/Editor/Editor.styled.ts, web/src/components/Editor/Expression/Expression.tsx, web/src/components/Editor/Interpolation/Interpolation.tsx, web/src/components/Editor/hooks/useTooltip.ts, web/src/components/TestSpecForm/AssertionCheck.tsx, web/src/components/TestSpecForm/AssertionCheckValue.tsx
This PR fixes a couple of UI bugs happening when working with the test spec form.
- The sample values for an assertion check are only displayed on focusing the input
- Parsed values for expressions are only displayed when the input has value and its not loading.
- [Improve add assertion behaviour](https://github.com/kubeshop/tracetest/issues/1532)
=> fix(frontend): fixing small UI/UX bugs

server/traces/traces.go, tracetesting/definitions/test_run.yml
This PR adds `tracetest.span.startTime` and `tracetest.span.endTime` to the span attributes. This allows users to check if an operation happened within X seconds since another operation by using test outputs.
=> feat: add startTime and endTime span attributes

examples/quick-start-nodejs/.gitignore, examples/quick-start-nodejs/Dockerfile, examples/quick-start-nodejs/app.js, examples/quick-start-nodejs/docker-compose.yaml, examples/quick-start-nodejs/package.json, examples/quick-start-nodejs/readme.md, examples/quick-start-nodejs/tracetest/collector.config.yaml, examples/quick-start-nodejs/tracetest/docker-compose.yaml, examples/quick-start-nodejs/tracetest/tracetest.config.yaml, examples/quick-start-nodejs/tracing.otel.grpc.js, examples/quick-start-nodejs/tracing.otel.http.js
This PR adds a quick start sample app for configuring a Node.js app to use OpenTelemetry and Tracetest.
- N/A
- N/A
=> examples(quick-start-nodejs): Add tutorial on how to configure Node.js app with OTel and Tracetest

server/model/run.go, server/testdb/runs.go
This PR fixes missing data when rerunning a test. The issue was that the create query was ignoring some fields.
=> fix(server): add missing data to insert query

web/cypress/e2e/Home/CreateTest.spec.ts, web/cypress/e2e/Home/CreateTestFromCurl.spec.ts, web/cypress/e2e/Home/CreateTestFromPostman.spec.ts, web/cypress/e2e/Transactions/Transactions.spec.ts, web/cypress/e2e/Transactions/TransactionsRun.spec.ts, web/cypress/e2e/constants/Transactions.ts, web/cypress/e2e/utils/Common.ts, web/cypress/e2e/utils/Transactions.ts, web/cypress/support/commands.ts, web/cypress/support/index.d.ts, web/src/components/CreateModal/CreateModal.tsx, web/src/components/CreateSteps/CreateStepFooter.tsx, web/src/components/CreateSteps/CreateSteps.tsx, web/src/components/CreateTestModal/CreateTestModal.tsx, web/src/components/CreateTransactionModal/CreateTransactionModal.tsx, web/src/components/TransactionHeader/TransactionHeader.tsx, web/src/components/TransactionPlugin/steps/TestsSelection/TestsSelectionInput/TestsSelectionInput.tsx, web/src/components/TransactionRunResult/ExecutionStep.tsx
This PR adds e2e tests for transactions and transaction runs.
- Updates the different selector strings to match the tests.
- Adds transaction utils with context holding for creating and deleting tests.
- [[Transactions] E2E tests: Transactions#1539](https://github.com/kubeshop/tracetest/issues/1539)
- [[Transactions] E2E tests: Transactions Run#1540](https://github.com/kubeshop/tracetest/issues/1540)
=> test:  adding e2e tests for transactions and transactions runs

README.md
The documentation paths have changed and we need to update the readme to point to the correct locations.
=> Update readme to point to correct locations for documentation items

server/testdb/environments.go, server/testdb/tests.go, server/testdb/transactions.go
This PR fixes the mapping used to sort transactions by `createdAt` field.
- #1598
=> fix(server): map transactions createdAt sort field to correct db field

web/src/components/Layout/Layout.tsx, web/src/components/ResourceCard/ResourceCardRuns.tsx, web/src/components/ResourceCard/TestCard.tsx, web/src/components/ResourceCard/TransactionCard.tsx, web/src/components/RunDetailLayout/HeaderLeft.tsx, web/src/components/RunDetailLayout/RunDetailLayout.styled.ts, web/src/components/RunDetailLayout/RunDetailLayout.tsx, web/src/components/TestHeader/TestHeader.tsx, web/src/components/TransactionHeader/TransactionHeader.tsx, web/src/components/TransactionPlugin/steps/TestsSelection/TestsSelectionInput/TestItem.tsx, web/src/components/TransactionPlugin/steps/TestsSelection/TestsSelectionInput/TestsSelectionInput.styled.ts, web/src/components/TransactionRunLayout/TransactionRunLayout.tsx, web/src/components/TransactionRunResult/ExecutionStep.tsx, web/src/pages/Home/Content.tsx, web/src/pages/Test/Content.tsx, web/src/pages/Transaction/Content.tsx, web/src/providers/Test/hooks/useTestCrud.ts
This PR updates the navigation logic to use anchor tags instead of programmatically redirect the user so it can decide to open the target URL in a separate tab.
- [Show links to tests from transaction run page](https://github.com/kubeshop/tracetest/issues/1597)
- [Most links should support 'right click' to open a new window](https://github.com/kubeshop/tracetest/issues/1601) (Partially)
=> feature(frontend): moving navigation logic to use anchor tags when possible

web/src/components/TransactionPlugin/steps/TestsSelection/TestsSelectionInput/TestItem.tsx, web/src/components/TransactionPlugin/steps/TestsSelection/TestsSelectionInput/TestItemList.tsx, web/src/components/TransactionPlugin/steps/TestsSelection/TestsSelectionInput/TestsSelectionInput.tsx
This PR fixes an issue when trying to delete a test from the item list.
- Uses the sortable id to delete the test from the value array, matching the id + index.
- 1604
=> fix(frontend): deleting the last remaining test when creating a transaction has issues

docs/docusaurus.config.js
This PR fixes the broken `edit this page` link.
-
-
=> docs(edit-link): fixed broken link

cli/actions/run_test_action.go, cli/formatters/test_run.go, cli/formatters/test_run_test.go, cli/formatters/transaction_run.go
This PR implements `--wait-for-result` for transaction runs and improve the result output.
=> feat: implement option for waiting for result when running transactions

web/src/components/AssertionResultChecks/AssertionResultChecks.styled.ts, web/src/components/AssertionResultChecks/AssertionResultChecks.tsx, web/src/components/AssertionResultChecks/ResultCheck.tsx, web/src/components/AttributeList/AttributeList.tsx, web/src/components/AttributeRow/AttributeRow.styled.ts, web/src/components/AttributeRow/AttributeRow.tsx, web/src/components/SpanDetail/Header.tsx, web/src/components/SpanDetail/SpanDetail.tsx, web/src/components/Visualization/components/DAG/SpanNode.styled.ts, web/src/components/Visualization/components/DAG/SpanNode.tsx, web/src/redux/testOutputs/slice.ts, web/src/selectors/TestSpecs.selectors.ts, web/src/services/Span.service.ts, web/src/services/SpanAttribute.service.ts, web/src/types/Assertion.types.ts
This PR fixes an issue caused by the expression changes introduced with Transactions. Before showing the results checks for each attribute span we would match the attribute string, as that changed it broke the logic.
- Now we are looking at the assertion string to see if the attribute exists as part of the operation.
- https://github.com/kubeshop/tracetest/issues/1498
=> fix(frontend): fixes summary checks not opening the proper test spec

web/src/components/Layout/Layout.styled.ts, web/src/components/Layout/Layout.tsx, web/src/components/Router/Router.tsx, web/src/components/Settings/DataStore/DataStore.tsx, web/src/components/Settings/DataStore/index.ts, web/src/pages/Settings/Content.tsx, web/src/pages/Settings/Settings.styled.ts, web/src/pages/Settings/Settings.tsx, web/src/pages/Settings/index.ts
This PR adds the initial settings page structure with tabs support for different groups of settings.
- New settings page
- fixes #1625
=> feat(frontend): add initial settings page

web/src/components/Settings/DataStoreDocsBanner/DataStoreDocsBanner.styled.ts, web/src/components/Settings/DataStoreDocsBanner/DataStoreDocsBanner.tsx, web/src/components/Settings/DataStoreDocsBanner/index.ts, web/src/components/Settings/DataStoreForm/DataStoreForm.tsx, web/src/constants/DataStore.constants.ts, web/src/services/DataStore.service.ts
This PR adds the documentation banner for each data store form.
- Adds documentation banner for each data store form
- [[In-App Config] Add documentation link to each trace data store screen#1657](https://github.com/kubeshop/tracetest/issues/1657)
https://www.loom.com/share/37b74450e69140e8a07cfcd49fdcfdad
=> feature(frontend): adding docs banner to data store config forms

api/config.yaml, web/src/components/Settings/DataStore/DataStore.tsx, web/src/constants/Theme.constants.ts, web/src/providers/DataStore/DataStore.provider.tsx, web/src/redux/apis/endpoints/Config.endpoint.ts, web/src/styled.d.ts, web/src/types/Config.types.ts, web/src/types/Generated.types.ts
This PR adds the FE logic to support the test connection service.
- Adds mock config API to test
- Includes triggering the service from the form
- Adds notification theme styling
- [[In-App Config] Setup Wizard#1622](https://github.com/kubeshop/tracetest/issues/1622)
https://www.loom.com/share/cd6ba23ae4a742b98bd5195925112570
=> feature(frontend): test connection data store logic

web/src/components/Settings/DataStorePlugin/forms/GrpcClient/GrpcClientSecure.tsx, web/src/services/DataStores/GrpcClient.service.ts, web/src/types/Config.types.ts
This PR adds support for file uploads for Cert files in the `GRPC Data Store` client config.
- File upload support
- fixes #1627
=> feat(frontend): add file upload for cert files in grpc data store config

web/src/App.tsx, web/src/components/Header/Header.styled.tsx, web/src/components/Header/Header.tsx, web/src/components/Layout/Layout.tsx, web/src/components/NoTracingPopover/NoTracingPopover.styled.ts, web/src/components/NoTracingPopover/NoTracingPopover.tsx, web/src/components/SetupAlert/SetupAlert.tsx, web/src/constants/Theme.constants.ts, web/src/redux/apis/endpoints/Config.endpoint.ts, web/src/styled.d.ts
This PR adds the no tracing mode global warning to let users know that a part of the Tracetest setup is missing.
- Adds new popover at the header component level
- #1628 
https://www.loom.com/share/89be91d5bc714cb49e667c980491d6c6
=> feature(frontend): adding no tracing mode warning

docs/docs/getting-started/installation.md
This PR fixes broken links in the docs.
-
-
=> docs(quick-start): fix links

server/tracedb/signalfxdb.go
This PR adds the test connection logic for the signal fx data store
- Adds the test connection functionality for signal fx
- #1700
=> feature(backend): adding signalfx test connection logic

k8s/tracetest.beta.yaml, k8s/tracetest.integration.yaml
This PR disables instances to generate the trigger span as it is already generated when the trace is received.
=> fix: disable trigger span from being generated

web/src/components/SetupAlert/SetupAlert.styled.ts, web/src/components/SetupAlert/SetupAlert.tsx, web/src/providers/DataStoreConfig/DataStoreConfig.provider.tsx, web/src/services/UserPreferences.service.ts, web/src/types/User.types.ts
This PR updates the `SetupAlert` to work with a unique preference key. Otherwise, you won't be able to see the alert message in a test.
- Fix `SetupAlert` component logic
-
=> fix(frontend): change SetupAlert to work with a unique preference key

cli/actions/apply_datastore_action.go, cli/actions/list_datastore_action.go, cli/cmd/datastore_apply_cmd.go, cli/cmd/datastore_cmd.go, cli/cmd/datastore_list_cmd.go, cli/formatters/datastore_list.go, cli/go.mod, cli/openapi/api_api.go, server/model/yaml/encoding.go, server/model/yaml/file.go, server/openapi/impl.go, server/testdb/data_stores.go, server/testdb/data_stores_test.go
This PR adds a command `tracetest datastore apply -f <file>` which creates/updates a data store based on the file. And also creates a command for listing data stores
=> feat: create/update/list data stores via CLI

web/src/components/Settings/DataStorePlugin/forms/GrpcClient/GrpcClient.tsx, web/src/providers/DataStore/DataStore.provider.tsx, web/src/providers/DataStore/hooks/useDataStoreNotification.tsx
This PR updates the data store confirmation message to remove the `restart server` warning. It also adds a success notification when saving a data store.
- Updates data store confirmation message
- Add success notification when saving a data store
-
=> fix(frontend): fix data store confirmation message

cli/installer/configuration.go, cli/installer/docker_compose.go, cli/installer/installer.go, cli/installer/kubernetes.go, cli/installer/tracetest.go, cli/installer/windows.go, examples/collector/collector.config.yaml, k8s/collector.yml
This PR removes much of the installer logic to just center on installing tracetest and its immediate dependencies.
There are two new branches, one for the express install where only tracetest + Postgres are installed
And a second option includes the pokeshop app plus the otel collector.
- Removed automatic install for heml, minikube, docker, docker compose, etc.
- Only two main branches when installing.
- #1630 
Docker compose
https://www.loom.com/share/3050548a668b4add96d77f0528350ef0
Kubernetes
https://www.loom.com/share/479305e6b30a418c8765a98ab5e8c813
=> feature(cli): improve installer experience

cli/installer/kubernetes.go
This PR removes the question asked to the user if he wants to install tracetest in a local or remote cluster.
- Removes minikube check and question
- #1630
=> feature(cli): removing the remove vs local k8 question

server/model/data_stores.go, server/testdb/data_stores.go, server/testdb/data_stores_test.go, web/src/services/DataStore.service.ts
This PR fixes a duplicate key issue when trying to create data stores with the same name.
- Change ID generation method in the backend service
- Fix frontend to always update instead of creating new records
-
=> fix(frontend): fix update dataStores service

examples/docker-compose.demo.yaml
This PR downgrades the rabbit MQ version to avoid a bug with some docker versions
-
-
=> fix(cli): fixing rabbitMQ version

Makefile, cli/Makefile, docs/docs/cli/creating-tests.md, server/Makefile
This PR aims to update minor typos in the documentation and add Makefile documentation on go-related makefiles
- Added `make help` command on go-related Makefiles
- YAML config on "creating tests" doc
=> chore: update typos on test docs and add Makefile docs

docs/docs/pokeshop/index.md
This PR fixes typos in the docs flowchart under Pokeshop (https://docs.tracetest.io/pokeshop/)
-
-
=> docs(pokeapi): replace img with mermaid chart

web/src/components/Settings/DataStore/DataStore.tsx, web/src/components/Settings/DataStoreForm/DataStoreForm.tsx, web/src/components/Settings/DataStorePlugin/forms/GrpcClient/GrpcClient.tsx, web/src/components/Settings/DataStorePlugin/forms/OpenSearch/OpenSearch.tsx, web/src/components/Settings/DataStorePlugin/forms/SignalFx/SignalFx.tsx, web/src/pages/Settings/Content.tsx, web/src/providers/DataStore/DataStore.provider.tsx, web/src/services/DataStore.service.ts, web/src/services/DataStores/OpenSearch.service.ts
This PR adds a standard layout for the data store forms and also fixes minor UI issues.
- Data store forms layout
- Remove required `username`/`password` for `openSearch`
- Fix `insecure switch` issue in the grpc client form (`jaeger`/`tempo`)
-
=> fix(frontend): add standard layout for data store forms and ui fixes

web/src/components/FileViewerModal/FileViewerModal.styled.ts
This PR fixes a small bug with the copy to clipboard icon overlapping with the save settings modal
- Updates the z-index property for the copy to clipboard container
- #1739
=> fix(frontend): fixing overlapping icon

local-config/collector.config.yaml, server/otlp/server.go
This PR adds a check to the Export function that is part of the otlp listener to validate if a default data store is enabled and its the otlp one.
- Adds otlp default data store validation
- #1739 
https://www.loom.com/share/71080bf4b5a64192a2867bbdb148b1b1
=> fix(backend): ignoring incoming otel collector traffic when data store is not enabled

docs/docs/cli/creating-data-stores.md, docs/sidebars.js
This PR adds documentation on how you can create data stores using the CLI.
=> docs: add docs about creating data stores using the CLI

cli/formatters/transaction_run.go
This PR makes the CLI print the last step error if the transaction fails during execution.
=> fix: show last step error message if transaction fails

docker-compose.yaml, examples/collector/docker-compose.yml, examples/quick-start-jaeger-nodejs/tracetest/docker-compose.yaml, examples/quick-start-nodejs/tracetest/docker-compose.yaml, examples/quick-start-opensearch-nodejs/tracetest/docker-compose.yaml, examples/quick-start-tempo-nodejs/tracetest/docker-compose.yaml, examples/tracetest-jaeger/docker-compose.yml, examples/tracetest-lightstep/tracetest/docker-compose.yaml, examples/tracetest-new-relic/tracetest/docker-compose.yaml, examples/tracetest-no-tracing/docker-compose.yml, examples/tracetest-opensearch/docker-compose.yml, examples/tracetest-otel-demo/docker-compose.yaml, examples/tracetest-signalfx/docker-compose.yml, examples/tracetest-tempo/docker-compose.yml, server/app/app.go
This PR disables analytics if the env `TRACETEST_DEV` is defined.
=> feat: disable analytics if `TRACETEST_DEV` env is defined in the host machine

Dockerfile, server/config/machine-id.go, server/migrations/17_reset_server_id.down.sql, server/migrations/17_reset_server_id.up.sql, server/testdb/postgres.go, server/testdb/server.go, server/testdb/server_test.go
This PR makes tracetest consider the hostname as a fallback in case it cannot get the machine-id from the host. It also will make old servers reset the server table, so all old users will get new server ids.
=> fix: machine id fallback

examples/tracetest-elasticapm-with-otel/.env, examples/tracetest-elasticapm-with-otel/Dockerfile, examples/tracetest-elasticapm-with-otel/README.md, examples/tracetest-elasticapm-with-otel/app.js, examples/tracetest-elasticapm-with-otel/collector.config.yaml, examples/tracetest-elasticapm-with-otel/docker-compose.yaml, examples/tracetest-elasticapm-with-otel/kibana.yml, examples/tracetest-elasticapm-with-otel/package.json, examples/tracetest-elasticapm-with-otel/tracetest-config.yaml, examples/tracetest-elasticapm-with-otel/tracing.otel.grpc.js, examples/tracetest-elasticapm-with-otel/tracing.otel.http.js
This PR adds a docker-compose example of Elastic stack with APM server integrated with OTel collector and Tracetest.
Adds an e2e example for #1777
=> Adding an example docker-compose test for Elastic APM

Dockerfile
This PR adds the CLI on PATH env in our docker image, permitting us to run `tracetest` command on the container without the `./` prefix.
=> fix(cli): add cli on PATH env

cli/ui/ui.go
This PR adds the version  of CLI on tracetest logo when running the installer.
-
=> feat: add version to tracetest logo on installer

examples/keptn-integration/README.md, examples/keptn-integration/job-config.yaml, examples/keptn-integration/shipyard.yaml, examples/keptn-integration/test-definition.yaml, examples/keptn-integration/tracetest-cli-config.yaml
This PR aims to add documentation on how we can use Tracetest with [Keptn](https://keptn.sh/) to test services.
- Add documentation for this integration
- #1772
=> chore(docs): adding documentation for Keptn integration

.github/workflows/community-issue-notification.yml
This PR adds @danielbdias  to the team and remove the PR notification pipeline
-
-
=> ci: add danielbdias to team and remove issue notification

examples/tracetest-elasticapm-with-elastic-agent/.env, examples/tracetest-elasticapm-with-elastic-agent/Dockerfile, examples/tracetest-elasticapm-with-elastic-agent/README.md, examples/tracetest-elasticapm-with-elastic-agent/app.js, examples/tracetest-elasticapm-with-elastic-agent/collector.config.yaml, examples/tracetest-elasticapm-with-elastic-agent/docker-compose.yaml, examples/tracetest-elasticapm-with-elastic-agent/kibana.yml, examples/tracetest-elasticapm-with-elastic-agent/package.json, examples/tracetest-elasticapm-with-elastic-agent/tracetest-config.yaml, examples/tracetest-elasticapm-with-otel/README.md, examples/tracetest-elasticapm-with-otel/tracetest-config.yaml, package-lock.json, package.json
This PR adds an example with Elastic APM Nodejs agent and Elastic APM stack.
#1834 by specifying the correct name of APM datastream
Additional cleanup instructions after docker build for OTel and Elastic native APM agents
=> Added an example with native Elastic APM agent

cli/actions/apply_environment_action.go, cli/cmd/environment_apply.go, cli/cmd/environment_cmd.go, docs/docs/cli/creating-environments.md, server/testdb/environments.go
This PR introduces the command `tracetest environment apply -f file.yaml` to make the CLI more coherent
=> feat: add environment apply command

tracetesting/features/http_test/05_create_http_test.yml, tracetesting/features/transaction/01_create_transaction_step.yml
This PR aims to fix a change in a dogfood test. As we updated Pokeshop example, one of the spans that we were validating has his name changed.
Context: https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1306 needed to change they way that the spans where reported for `pg`
=> fix(test): update trace names asserition on Pokeshop

docs/docusaurus.config.js
This PR adds a 301 redirect from `/introduction` to `/`.
-
-
=> docs(redirect): add introduction redirect

server/tracedb/tracedb.go
We were using `1` so we would ignore traces that only contained only the trigger root span. Now that we are not sending that span, we have to set the minimum as `0` instead. Otherwise, traces with only one span will never be polled.
- #1858
=> fix min span count for trace poller after removal of trigger span

web/src/components/CreateTestPlugins/TraceID/TraceID.ts, web/src/components/CreateTestPlugins/TraceID/steps/VariableName/VariableName.tsx, web/src/components/CreateTestPlugins/TraceID/steps/VariableName/VariableNameForm.tsx, web/src/components/CreateTestPlugins/TraceID/steps/VariableName/index.ts, web/src/components/EditTestForm/EditRequestDetails/TraceID/TraceID.tsx, web/src/constants/Plugins.constants.ts, web/src/services/Triggers/TraceID.service.ts
This PR updates the trigger trace form to ask users to add the variable name instead of the actual trace id, to have the trace id be always dynamic.
- Updates the trace id trigger
- #1857
=> feature(frontend): updating trace id trigger form

web/src/components/RunDetailTriggerResponse/ResponseEnvironment.tsx, web/src/components/RunDetailTriggerResponse/RunDetailTriggerResponse.styled.ts, web/src/constants/Common.constants.ts
This PR adds an empty state in the `environment` tab in the run detail page
- empty state for environment tab
- fixes #1816
=> feat(frontend): add empty state in environment tab

web/src/components/TestOutput/TestOutput.styled.ts
This PR fixes some styles in the `output` container.
- fix css styles
- fixes #1814
=> fix(frontend): fix output container styles

web/src/components/RunCard/TransactionRunCard.tsx
This PR adds the `Transaction Definition` option to the TransactionRun row
- Add Transaction Definition option
- fixes #1623
=> fix(frontend): add transaction definition option in run card

web/cypress/e2e/TestRunDetail/Outputs.spec.ts, web/src/components/TestOutputForm/SelectorInput.tsx, web/src/components/TestOutputForm/TestOutputForm.tsx, web/src/components/TestOutputs/TestOutputs.tsx, web/src/constants/Common.constants.ts
This PR adds the logic to pre-fill the selector when adding a `test output` based on the current selected span. It also adds a link to the expressions docs in the test output form.
- pre-fill selector in test output
- add link to expressions docs in test output form
- fixes #1809 
- fixes #1807 
https://www.loom.com/share/fd90c71d8795404191e3de1962b83e35
=> feat(frontend): pre fill selector when adding an output

web/src/components/ConfirmationModal/ConfirmationModal.tsx, web/src/providers/ConfirmationModal/ConfirmationModal.provider.tsx, web/src/providers/DataStore/DataStore.provider.tsx
This PR adds a warning when changing the data store configuration explaining that your current configuration will be deleted.
The message does not include the warning if:
- you have no data store configured
- if you are just altering the current config (ie staying with the same data store type)
- Data store warning message
- fixes #1799
=> feat(frontend): add data store warning when saving config

examples/tracetest-elasticapm-with-elastic-agent/README.md, examples/tracetest-elasticapm-with-elastic-agent/app.js, examples/tracetest-elasticapm-with-elastic-agent/docker-compose.yaml, examples/tracetest-elasticapm-with-elastic-agent/elastic-apm-agent.js, examples/tracetest-elasticapm-with-elastic-agent/package.json, examples/tracetest-elasticapm-with-elastic-agent/tracetest-config.yaml, examples/tracetest-elasticapm-with-otel/README.md, examples/tracetest-elasticapm-with-otel/docker-compose.yaml, examples/tracetest-elasticapm-with-otel/tracetest-config.yaml
This PR updates the Elastic APM examples to leverage the `insecureSkipVerify` option. It also changes the default names of the `app.js` containers to avoid names clash.
=> Update Elastic APM examples to leverage `insecureSkipVerify` option

web/src/components/TransactionPlugin/steps/BasicDetails/BasicDetails.tsx, web/src/redux/apis/endpoints/TestRun.endpoints.ts, web/src/redux/apis/endpoints/TransactionRun.endpoint.ts
This PR fixes an issue where the home page wasn't refreshing after running or executing an action over the resources displayed in the list.
- Updates the invalidate tags config to refresh the resource list
- #1598
=> fix(frontend): fixing home page not refreshing after transaction or test run

web/src/components/ResourceCard/ResourceCardActions.tsx, web/src/components/ResourceCard/TestCard.tsx, web/src/components/ResourceCard/TransactionCard.tsx, web/src/components/ResourceCard/__tests__/ResourceCardActions.test.tsx, web/src/components/ResourceCard/__tests__/TestCard.test.tsx, web/src/components/RunActionsMenu/RunActionsMenu.tsx, web/src/components/TestHeader/TestHeader.tsx, web/src/components/TestHeader/__tests__/TestHeader.test.tsx, web/src/components/TransactionRunActionsMenu/TransactionRunActionsMenu.tsx, web/src/models/TestSummary.model.ts, web/src/models/__mocks__/Transaction.mock.ts, web/src/pages/Home/Resources.tsx, web/src/pages/Test/Content.tsx, web/src/pages/Transaction/Content.tsx, web/src/types/Test.types.ts
This PR aims to add an edit button on some menus, redirecting the user to the last test/transaction run. The idea is to help the user to find quick ways to edit a test/transaction name/description.
Loom: https://www.loom.com/share/04d0f6d596744800abead6364970c909
- Add Edit button on Tests/Transactions context menu on Resources page
- Add Edit button on context menu on Test page
- Add Edit button on context menu on Transactions page
- #1848
=> add(ui): edit button on context menu

.github/workflows/pull-request.yaml
This PR archives the CLI build so it's not neccesary to rebuilt it on every step that needs to use the cli
=> chore: reuse cli build on pr pipeline

cli/actions/run_test_action.go, cli/formatters/test_run.go, cli/formatters/test_run_test.go, cli/formatters/transaction_run.go
This PR changes the CLI to only display result information when the option `--output json` is defined. This makes it simpler for users to parse the result of the tests.
- #1854
=> fix: only print test and transaction result in json format

web/src/constants/DataStore.constants.tsx
This PR fixes the documentation url for elasticapm
=> fix(docs): fixing elasticapm docs url

api/tests.yaml, cli/openapi/api_api.go, cli/openapi/model_test_run.go, server/http/mappings/tests.go, server/model/tests.go, server/openapi/model_test_run.go, server/testdb/runs.go, web/src/components/RunActionsMenu/RunActionsMenu.tsx, web/src/components/RunCard/TestRunCard.tsx, web/src/components/RunDetailLayout/HeaderLeft.tsx, web/src/components/RunDetailLayout/HeaderRight.tsx, web/src/components/RunDetailLayout/RunDetailLayout.styled.ts, web/src/models/TestRun.model.ts, web/src/types/Generated.types.ts
This PR adds the part of a transaction legend for test runs and test run cards in case the run belongs to a transaction run.
- Backend changes to fetch the values from the `transaction_run_steps`
- Font end changes to display the new component
- #1522 
https://www.loom.com/share/7d302a65fafb4e2e826d7321bc59dada
=> feature: adding part of transaction info to the test run page

cli/actions/run_test_action.go
This PR fixes the CLI when a test response returns an empty object.
-
-
=> fix: fix CLI panic when response is empty

server/testdb/runs.go
This PR fixes a bug we have in meta where all runs are matching at least one transaction because a missing condition as part of the join query.
- Fixing the query at the testdb level
=> fix(backend): fixing the get test run query join condition

cli/actions/configure_action.go, cli/cmd/config.go, cli/cmd/root.go, cli/config/config.go
This PR allows users to override the target endpoint of cli requests through a flag. Example:
```
tracetest test list --address http://some-host.com:1234
tracetest test list -a http://some-host.com:1234
````
**UPDATE** renamed flag from `--endpoint|-e` to `--server-url|-s` to avoid conflict with `--environment|-e` flag
-
- #1893
=> feat: allow cli to accept an `address` override param

docs/docusaurus.config.js
This PR fixes the documentation build process, which was broken on #1892
=> Removing unused redirect that was breaking docusaurus build

Makefile, docker-compose.yaml
This PR adds new root makefile targets to build locally.
New targets:
- `make build-go`: builds both server and CLI, and puts them in `dist/tractest-server` and `dist/tracetest` respectively
- `make build-web`:  installs deps and builds the frontend
- `make build-docker`: build the docker image with the `latest`
=> chore: add makefile targets for local builds

docs/docs/getting-started/installation.md
Displayed command does not work with the extra `-f` argument.
=> Correcting docker-compose command in quickstart

.github/TEAM_MEMBERS.txt, .github/workflows/community-issue-notification.yaml, .github/workflows/community-label-user-requests.yaml
This PR add a label `user-request` for issues opened by external users.
This also changes how we maintain team members.
=> chore: add labels to external issues

cli/cmd/datastore_cmd.go, cli/cmd/environment_cmd.go, cli/cmd/server_cmd.go, cli/cmd/test_cmd.go
If user tries to run the following commands, it will get a help page for the command:
* tracetest
* tracetest datastore
* tracetest environment
* tracetest server
* tracetest test
based on @danielbdias's idea.
=> feat: show help page when user tries to run placeholder commands

cli/analytics/analytics.go, server/app/app.go
This PR adds the validation of the TRACETEST_DEV env variable to disable CLI analytics.
- Add TRACETEST_DEV validation
-
=> fix(cli): check TRACETEST_DEV env to disable analytics

.github/workflows/deploy-main.yml, .github/workflows/pull-request.yaml, .github/workflows/release-version.yml, Makefile, cli/go.mod, cli/go.sum
This PR updates goreleaser version (depends on https://github.com/kubeshop/tracetest/pull/1964)
-
-
=> chore: Update goreleaser version

examples/quick-start-datadog-nodejs/.gitignore, examples/quick-start-datadog-nodejs/Dockerfile, examples/quick-start-datadog-nodejs/app.js, examples/quick-start-datadog-nodejs/docker-compose.yaml, examples/quick-start-datadog-nodejs/package.json, examples/quick-start-datadog-nodejs/test-api.yaml, examples/quick-start-datadog-nodejs/tracetest/collector.config.yaml, examples/quick-start-datadog-nodejs/tracetest/docker-compose.yaml, examples/quick-start-datadog-nodejs/tracetest/tracetest.config.yaml, examples/quick-start-datadog-nodejs/tracing.otel.grpc.js, examples/quick-start-datadog-nodejs/tracing.otel.http.js
This PR aims to create a first example of how to integrate Datadog with Tracetest.
To run it just replace the placeholder `${DATADOG_API_KEY}` for a valid Datadog API Key and run this demo using the command:
```sh
docker compose -f docker-compose.yaml -f tracetest/docker-compose.yaml up
```
- Added example with a `collector.config.yaml` tailored to send data to Datadog and Tracetest.
- https://github.com/kubeshop/tracetest/issues/1959
=> chore(examples): adding quick start example on how to integrate Tracetest and Datadog

cli/openapi/api_api.go, go.work.sum, server/tracedb/connection/connection.go, server/tracedb/connection/connectivity_step.go, server/tracedb/connection/options.go, server/tracedb/connection/tester.go, server/tracedb/connection/trace_polling_step.go, server/tracedb/datasource/datasource.go, server/tracedb/datasource/grpc.go, server/tracedb/datasource/http.go, server/tracedb/elasticsearchdb.go, server/tracedb/jaegerdb.go, server/tracedb/opensearchdb.go, server/tracedb/signalfxdb.go, server/tracedb/tempodb.go
This PR changes the internals of how we test the connection of each data store. Instead of having a long function with repetitive code, it uses a new `connection.Tester` which allow test steps to be chained and reused.
This is a required change to make it easier to expand our validations in the future.
=> refactor connectivity test to reuse components

docs/sidebars.js
This PR removes datadog from docs sidebar
=> fix: Remove datadog from docs sidebar

k8s/tracetest.demo.yaml
This PR disables the application exporter config from our demo environment
=> chore: disable application exporter in demo

Dockerfile
This PR aims to add our CLI to `PATH` env, so our users can run the CLI directly from docker. This is necessary to guarantee that our integrations will not break.
- Update Dockerfile to add CLI on `$PATH` env var
=> Adding CLI on Dockerfile path

web/src/components/CreateTestPlugins/Postman/steps/UploadCollection/UploadCollection.tsx, web/src/components/CreateTestPlugins/Postman/steps/UploadCollection/UploadCollectionForm.tsx, web/src/components/CreateTestPlugins/Postman/steps/UploadCollection/fields/CollectionFileField.tsx, web/src/components/CreateTestPlugins/Postman/steps/UploadCollection/fields/SelectTestFromCollection.tsx, web/src/services/Triggers/Postman.service.tsx
This PR fixes some wrong error messages in the `Postman Trigger` form. It also removes the error messages the first time you see the screen, the messages only appear when you are interacting with the input if needed.
- fix postman trigger validation
- fixes #2023 
- fixes #1971
=> fix(frontend): fix postman trigger validation

server/config/server.go, server/config/server_test.go
This PR makes the new config retro compatible with the old configuration file format. This means that `postgresConnString` will be used if present in the config file.
- #1996
=> fix: postgres config retrocompatibility 

api/config.yaml, cli/openapi/model_connection_result.go, cli/openapi/model_connection_test_step.go, go.work.sum, server/http/mappings/datastore.go, server/openapi/model_connection_result.go, server/openapi/model_connection_test_step.go, server/tracedb/connection/connection.go, server/tracedb/connection/connectivity_step.go, server/tracedb/connection/options.go, server/tracedb/connection/port_linting.go, server/tracedb/connection/port_linting_test.go, server/tracedb/connection/tester.go, server/tracedb/connection/trace_polling_step.go, server/tracedb/datasource/datasource.go, server/tracedb/datasource/grpc.go, server/tracedb/datasource/http.go, server/tracedb/elasticsearchdb.go, server/tracedb/jaegerdb.go, server/tracedb/opensearchdb.go, server/tracedb/tempodb.go, web/src/components/TestConnectionNotification/TestConnectionNotification.styled.ts, web/src/components/TestConnectionNotification/TestConnectionNotification.tsx, web/src/components/TestConnectionNotification/TestConnectionStep.tsx, web/src/models/ConnectionResult.model.ts, web/src/models/ConnectionResultStep.model.ts, web/src/types/Config.types.ts, web/src/types/Generated.types.ts
This PR adds a step to the data store test which validates the used port. If it's not a standard port, show a warning to the user and point to the correct port.
Loom: https://www.loom.com/share/7105d6d5268c411a84665d896eb3cf4e
=> feat: validate port and show warning if using a non-standard port

server/executor/poller_executor.go, server/executor/poller_executor_test.go, server/executor/trace_poller.go, server/tracedb/tracedb.go
This PR aims to update our Trace collection polling logic to remove an assumption about "Tracetest trigger" node and add unit tests to handle more cases on our poller.
I'll tackle the problem of using the "Tracetest trigger" node in another PR.
- Updating polling logic to make the stop condition explicit
- Remove logic that considers "Tracetest trigger" span on stopping criterion
=> fix(server): removing MinSpanCount span logic from trace poller and adding unit tests

go.work.sum, server/http/mappings/data_store.go
This PR fixes a bug introduced when decoupling the `model` package from the `openapi` package in the server (they were coupled by the `DataStoreType` constants). In that change, the internal representation of the possible data store types changed it's casing to all lowercase, in contrast with the openapi one that has a mixed casing.
This fix adds a new mapper function so this discrepancy is kept within the domain of the `mappers` package.
- add mapper function for DataStoreTypes
=> fix(server): fix mapping between openapi dataStoreTypes and model dataStoreTypes

server/config/configresource/config_resource.go, server/testdb/data_stores.go, server/testdb/environments.go, server/testdb/runs.go, server/testdb/tests.go, server/testdb/transaction_runs.go, server/testdb/transactions.go
This PR aims to add a `defer` logic into every transaction that we open on `database/sql` package, following this: https://go.dev/doc/database/execute-transactions
- Added `defer` logic to every `tx.Rollback()`
=> Adding defer logic to config resource

go.work.sum, server/config/config.go
This PR removes a duplicated function call to `readConfigFile` when checking for deprecated configs
=> chore(server): remove duplicated call to `readConfigFile` func

go.work.sum, server/config/config.go, server/config/config_test.go, server/config/deprecation_test.go
The server was accepting a config file with a name matching the expected config name but without the extension as a valid config file. This caused that in docker, where we have the cli binary in `/app/tracetest`, the server was trying to read said binary as a config file, obviously failing.
- enforce config file with extension to avoid collisions.
- #2071
=> fix(server): force extension on config file lookup

server/Makefile
This PR fixes the `run` target in server's makefile, so now it's easy to run quickly run the serve standalone. Intended for develoment use
=> chore(server): fix run target in makefile

server/tracedb/connection/connectivity_step.go
This PR fixes the bug that @xoscar found. When testing an endpoint with a schema, the reachability would fail with "too many colons" error.
=> fix: test that checks if endpoint is reachable

examples/collector/docker-compose.yml, examples/collector/tracetest-provision.yaml, examples/observability-driven-development-go-tracetest/bookstore/part1/tracetest/docker-compose.yaml, examples/observability-driven-development-go-tracetest/bookstore/part1/tracetest/tracetest-provision.yaml, examples/observability-driven-development-go-tracetest/bookstore/part1/tracetest/tracetest.yaml, examples/observability-driven-development-go-tracetest/bookstore/part2.1/tracetest/docker-compose.yaml, examples/observability-driven-development-go-tracetest/bookstore/part2.1/tracetest/tracetest-provision.yaml, examples/observability-driven-development-go-tracetest/bookstore/part2.1/tracetest/tracetest.yaml, examples/observability-driven-development-go-tracetest/bookstore/part2.2/tracetest/docker-compose.yaml, examples/observability-driven-development-go-tracetest/bookstore/part2.2/tracetest/tracetest-provision.yaml, examples/observability-driven-development-go-tracetest/bookstore/part2.2/tracetest/tracetest.yaml, examples/observability-driven-development-go-tracetest/bookstore/part3.1/tracetest/docker-compose.yaml, examples/observability-driven-development-go-tracetest/bookstore/part3.1/tracetest/tracetest-provision.yaml, examples/observability-driven-development-go-tracetest/bookstore/part3.1/tracetest/tracetest.yaml, examples/observability-driven-development-go-tracetest/bookstore/part3.2/tracetest/docker-compose.yaml, examples/observability-driven-development-go-tracetest/bookstore/part3.2/tracetest/tracetest-provision.yaml, examples/observability-driven-development-go-tracetest/bookstore/part3.2/tracetest/tracetest.yaml, examples/quick-start-datadog-nodejs/tracetest/docker-compose.yaml, examples/quick-start-datadog-nodejs/tracetest/tracetest-provision.yaml, examples/quick-start-datadog-nodejs/tracetest/tracetest.config.yaml, examples/quick-start-go/tracetest/docker-compose.yaml, examples/quick-start-go/tracetest/tracetest-provision.yaml, examples/quick-start-go/tracetest/tracetest.config.yaml, examples/quick-start-jaeger-nodejs/tracetest/docker-compose.yaml, examples/quick-start-jaeger-nodejs/tracetest/tracetest-provision.yaml, examples/quick-start-jaeger-nodejs/tracetest/tracetest.config.yaml
This PR changes the following examples to use the provision file
* collector
* observability-driven-development-go-tracetest
* quick-start-datadog-nodejs
* quick-start-go
* quick-start-jaeger-nodejs
=> docs: fix examples to use provision file

.github/workflows/merge-gate.yaml
This PR changes the check interval of the merge gate step of our CI. Instead of 10s, we use 30s now to prevent the `API rate exceeded` error from GitHub API.
=> ci: set merge gate interval to 30s instead of 10 (default)

.github/workflows/pull-request.yaml, examples/collector/tests/list-tests.yaml, examples/tracetest-jaeger/tests/list-tests.yaml, examples/tracetest-opensearch/tests/list-tests.yaml, examples/tracetest-provisioning-env/tests/list-tests.yaml, examples/tracetest-tempo/tests/list-tests.yaml
This PR fixes the example tests run for PullRequest validation. It now checks for spans that can only exists if they were fetched from the data store.
- #2095
=> fix: correct example tests

server/model/data_stores.go, server/otlp/server.go
This PR aims to allow users to setup different options to use on OTel Collector setup.
Context: https://github.com/kubeshop/tracetest/issues/2053
- Data Store validation on internal OTLP server
- https://github.com/kubeshop/tracetest/issues/2053
=> Fixing block for OTLP based data stores

server/cmd/root.go, server/config/config.go, server/config/config_test.go, server/config/demo_test.go, server/config/deprecation_test.go, server/config/pooling_test.go, server/config/server_test.go, server/executor/poller_executor_test.go, server/executor/runner_test.go, server/testmock/app.go, server/testmock/database.go
The `config` object is needs to hold reference to different repositories to gather configs from DB, so it's much easier to handle the growing amount of dependencies by using the functional options patter.
This tiny pr just updates that internally without affecting any functionality.
=> chore(server): accept functional options in config

server/cmd/root.go, server/config/config.go, server/config/config_test.go, server/config/demo_test.go, server/config/deprecation_test.go, server/config/pooling_test.go, server/config/server_test.go, server/executor/poller_executor_test.go, server/executor/runner_test.go, server/testmock/app.go
This PR takes advantage of the new functional option pattern for configuring the `Config` object and converts the optional `flags` param to a functional option for creating a new config instance
=> chore(server): convert optional FlagSet param to functional option in `config.New`

server/tracedb/tracedb.go, server/tracedb/tracedb_test.go
This PR fixes a bug found on [#2118](https://github.com/kubeshop/tracetest/issues/2118): 
With Datadog, Lightstep, and New Relic, we can use them as a Data Store provisioning the OTLP datastore or a specific Data Store for them. However, setting up a specific Data Store crashes Tracetest on a Test run.
- Fix Data Store instantiation
- #2118
=> Fixing bug on TraceDB instantiation

server/config/configresource/config_resource.go, server/config/configresource/config_resource_test.go, server/resourcemanager/resource_manager.go, server/resourcemanager/resource_manager_test.go, server/resourcemanager/testutil/common_functions.go, server/resourcemanager/testutil/content_type.go, server/resourcemanager/testutil/contenttype.go, server/resourcemanager/testutil/operations.go, server/resourcemanager/testutil/operations_create.go, server/resourcemanager/testutil/operations_delete.go, server/resourcemanager/testutil/operations_get.go, server/resourcemanager/testutil/operations_list.go, server/resourcemanager/testutil/operations_update.go, server/resourcemanager/testutil/test_resource.go
This PR aims to add pagination tests to Resource Manager and update the tests for the first resource to consider that
- Refactor resource manager tests to simplify the readability of each operation
- Added tests for resource manager
- Added pagination capabilities for config_resource
- Added pagination tests for config_resource
- https://github.com/kubeshop/tracetest/issues/2060
=> Add pagination tests to resource manager

api/config.yaml, api/openapi.yaml, server/resourcemanager/resource_manager.go, server/resourcemanager/testutil/operations_update.go
This PR adds the API resource definition for the `Config` resource
- Updated OpenAPI definition to have `/config/{id}` endpoints
- Added configuration resource definition
- (partially) #2063
=> Adding OpenAPI docs for Config Resource

web/src/components/Settings/Polling/PollingForm.tsx, web/src/models/Polling.model.ts, web/src/pages/Settings/Content.tsx, web/src/types/Settings.types.ts
This PR integrates polling profile settings with the resources API.
- Integrate web UI with resources API
- #2100
=> feat(frontend): integrate pollingprofile settings with API

server/app/app.go, server/provisioning/config.go, server/provisioning/data_stores_test.go, server/provisioning/provisioning.go, server/provisioning/provisioning_test.go
The current config file value `googleAnalytics.enabled` is now ignored, since it's read from DB. We need to allow provisioning of this config. This PR adds support for the provisioning of this config.
- Implements Config provisioning
- fixes #2106
=> feat(server): add config analytics provision

server/config/configresource/config_resource_test.go, server/executor/pollingprofile/polling_profile_resource.go, server/executor/pollingprofile/polling_profile_resource_test.go
This PR makes sure that there's only one polling profile for now.
=> feat: limit polling profiles to one

web/src/models/Config.model.ts, web/src/redux/apis/endpoints/Setting.endpoint.ts
This PR adds live updates for the config resource in the front, allowing the FE to switch analytics on an off based on user input
- Setting endpoint now listens to config live updates
- FE enables/disabled analytics based on the backend WebSocket
- #2125
=> feature(frontend): adding live updates for analytics changes

.github/workflows/release-candidate.yml, .github/workflows/release-version.yml
This PR splits the RC pipeline so we have more control of what happens for this special case release. In particular at this time we don't want to deploy brew/apt/rpm/helm repositories.
-
-
=> chore(cicd): split RC pipeline

cli/actions/demo.go, cli/cmd/apply_cmd.go, cli/cmd/delete_cmd.go, cli/cmd/export_cmd.go, cli/cmd/get_cmd.go
This PR adds CLI validations to prevent users from having invalid input when using the resources commands.
- Updates resources commands to have validations
- Changes the file flag to match the rest of the specs
=> feature(cli): adding resource cmd CLI validations

.github/workflows/release-candidate.yml, .goreleaser.rc.yaml
our current RC approach is not working correctly. Since we introduced the `nightly` flag to avoid publishing brew/linux binaries, goreleaser does not create a release in GH, nor does it use the correct versioning for files. It uses the `nightly` settings: reuses the `latest` release, and all files are labeled `latest`. This behaviour is great for keeping the last commit in `main` built and ready to test, but RCs needs to be kept in history. This approach doesn't allow that.
This PR creates a goreleaser setting specific for RC. It's essentially the same as prod but forces the `prereleas` flag to true, and removes all references to brew/linux repos. It will only create correctly tagged docker images, a GH release tagged as `pre-release`, and attached to it all the binaries, labeled …
=> chore(cicd): use separated goreleaser settigns for RC

web/src/services/Setting.service.ts, web/src/types/Settings.types.ts
This PR aims to fix the visualization of the demo settings on our UI.
- Changing Settings.service to consider different names to OTel Store types
- #2191
=> Fixing visualization of OTel demo settings

server/config/configresource/config_resource.go, server/config/configresource/config_resource_test.go
This PR updates the default config to have analytics enabled unless updated
=> feat: make analytics enabled by default

examples/tracetest-aws-step-functions/infra/tracetest.tf, examples/tracetest-aws-step-functions/infra/variables.tf, examples/tracetest-datadog/docker-compose.yaml, examples/tracetest-datadog/http-test.yaml, examples/tracetest-datadog/tracetest/docker-compose.yaml, examples/tracetest-datadog/tracetest/tracetest-config.yaml, examples/tracetest-elasticapm-with-elastic-agent/docker-compose.yaml, examples/tracetest-elasticapm-with-otel/docker-compose.yaml, examples/tracetest-k6/docker-compose.yml, examples/tracetest-lightstep-otel-demo/docker-compose.yaml, examples/tracetest-lightstep-otel-demo/tracetest/tracetest-provision.yaml, examples/tracetest-lightstep-otel-demo/tracetest/tracetest.config.yaml, examples/tracetest-lightstep/docker-compose.yaml, examples/tracetest-lightstep/tracetest/tracetest-provision.yaml
This PR fixes the second batch of examples to use the new config features.
- #2169
=> chore(examples): fixing second batch of examples

docs/docs/configuration/analytics.md, docs/docs/configuration/demo.md, docs/docs/configuration/trace-polling.md
Changed from using -file to -f
Changed so there is no id in example for demo settings as that was causing it to disappear.
=> Changed settings docs

cli/actions/demo.go, cli/actions/polling.go
This PR fixes the error which makes the CLI erase the content from the demo definition file if it has an id that doesn't exist on the server.
The same patch was applied to polling profile resources.
=> fix: validate if server returns 404 error on inexisting id in demo and polling profile

.github/workflows/deploy-demo.yml, .github/workflows/deploy-main.yml, .github/workflows/pull-request.yaml, .github/workflows/release-candidate.yml, .github/workflows/release-version.yml, .goreleaser.rc.yaml, .goreleaser.yaml, Makefile
This PR updates goreleaser. It also addresses the [deprecation notice](https://github.com/kubeshop/tracetest/actions/runs/4484739631/jobs/7885557141):
=> chore: Update goreleaser

web/src/components/TestActions/TestActions.tsx, web/src/providers/TestSpecs/hooks/useTestSpecsCrud.ts
This PR renames the `Publish` button to `Save`.
- Rename publish button
- fixes #2236
=> fix(frontend): rename publish button to save

docs/docs/deployment/docker.md, docs/docs/deployment/overview.md
This PR fixes a config file in the deployment overview page (docs).
- Fix docs
- related #2237
=> fix(docs): fix deployment page to match new config file

web/src/components/RunDetailLayout/RunDetailLayout.styled.ts
This PR fixes an small issue where the links in the `test run` tabs (trigger, trace, test) were not clickable in the white space.
- fix css styles in tab links
-
=> fix(frontend): fix links in test run tabs

.github/workflows/docusaurus.yml
This PR makes the documentation be built when a command in the CLI is updated. This is important because we now generate the CLI reference using cobra
=> add cli cmd folder to trigger docusaurus workflow

server/migrations/23_add_test_run_events.down.sql, server/migrations/23_add_test_run_events.up.sql, server/model/repository.go, server/model/test_run_event.go, server/testdb/mock.go, server/testdb/test_run_event.go, server/testdb/test_run_event_test.go
This PR adds the repository to manage test run events
=> feat: test run event repository

docs/docusaurus.config.js
This PR adds a redirect to the a CLI page that was removed.
-
-
=> docs(fix): add cli redirect

api/openapi.yaml, api/testEvents.yaml, cli/openapi/api_api.go, cli/openapi/model_test_run_event.go, server/http/controller.go, server/http/mappings/test_run_events.go, server/openapi/api.go, server/openapi/api_api.go, server/openapi/model_test_run_event.go, web/src/types/Generated.types.ts
This PR adds the endpoint to get events from a test run: `GET /api/tests/:testID/run/:runID/events`
=> feat: add endpoint to list events from a test run

server/integration/ensure_server_prefix_test.go
This PR aims to fix a problem on TestServerPrefix when running it on OSX.
Running `make test` inside `./server` should correctly now.
- Add one sync statement to avoid racing conditions on TestServerPrefix test (made with @mathnogueira ).
=> Added test change to stop flaky test

docs/package.json
This PR adds a hook to generate the CLI reference docs before running the `build` and `start` scripts.
=> docs: add pre scripts for start and build

server/executor/assertion_runner.go, server/http/mappings/test_run_events.go, server/model/events/events.go, server/model/test_run_event.go, server/model/test_run_event_test.go
This PR aims to add TestSpec events when executing the assertion engine.
- #2268
=> Add TestSpec events

server/executor/runner.go, server/model/events/events.go
This PR adds events when trying to triggering http and grpc endpoints but they are unreachable
=> feat: emit unreachable host events for http and grpc triggers

local-config/jaeger/collector.config.yaml, local-config/jaeger/docker-compose.yml, local-config/jaeger/tracetest.config.yaml, local-config/jaeger/tracetest.provision.yaml, server/executor/assertion_runner.go, server/executor/outputs_processor.go, server/model/events/events.go, server/model/tests.go
This PR aims to add more events on test specs, when dealing with outputs
- https://github.com/kubeshop/tracetest/issues/2278
=> Add more events on test specs

server/http/mappings/test_run_events.go
This PR makes the openapi mapping function to set the title to the event response
=> fix: add title to test run event response

server/executor/runner.go
This PR detects if tracetest is running in a container and emits an event in case of a connection error to tell the user about using "localhost"
=> feat: docker host mismatch event

.github/workflows/pull-request.yaml
This PR fixes the PR pipeline. Lately, it's been failing because the PR environment is not ready when the integration instance starts sending requests. I was restarting the Tracetest pod in the PR namespace in order for to it start faster after failing to connect to the database.
This PR aims to allow the tests to be run after the instance is up and running.
=> fix: wait until PR environment is ready before running tests

server/executor/assertion_runner.go, server/expression/errors.go, server/expression/executor.go, server/expression/parser.go, server/expression/parser_errors_test.go, server/expression/tokens.go
This PR makes the assertion runner emit a `TEST_SPECS_ASSERTION_ERROR` in case of invalid syntax in the assertion.
=> feat: emit error event when expression engine return parsing errors

api/tests.yaml, cli/actions/run_test_action.go, cli/formatters/test_run.go, cli/formatters/transaction_run.go, cli/openapi/api_api.go, cli/openapi/api_resource_api.go, cli/utils/run_state.go, server/executor/assertion_runner.go, server/executor/runner.go, server/executor/trace_poller.go, server/executor/transaction_runner_test.go, server/model/json_test.go, server/model/run.go, server/model/tests.go, web/src/components/EditTest/EditTest.tsx, web/src/components/RunCard/TestRunCard.tsx, web/src/components/RunCard/TransactionRunCard.tsx, web/src/components/RunDetailLayout/Info.tsx, web/src/components/RunDetailLayout/RunDetailLayout.styled.ts, web/src/components/RunDetailTrigger/RunDetailTrigger.tsx, web/src/components/RunEvents/RunEventsTrace.tsx, web/src/constants/TestRun.constants.ts, web/src/models/TestRun.model.ts, web/src/models/TransactionRun.model.ts, web/src/types/Generated.types.ts, web/src/types/TestRun.types.ts
This PR makes the TestRun state more accurate by providing a new set of statuses: `TRACE_FAILED`, `TRIGGER_FAILED` and `ASSERTION_FAILED`.
- add new states and implement where applicable
- #2285
=> feat(sever): for test runs, split the failed state into more descriptive statuses

.github/workflows/pull-request.yaml, server/executor/eventemitter.go, server/subscription/manager.go
This PR aims to fix a concurrency error that is happening on Tracetest:
```
persistentRunner job. ID 1, testID JFxVPFY4R, TraceID 8ec5afeaca8d38668e5053fc4fb79998, SpanID b8a543d68fd34165
fatal error: concurrent map read and map write
goroutine 49 [running]:
github.com/kubeshop/tracetest/server/subscription.(*Manager).Publish(0x1a97540?, {0xc002b95740, 0x1a}, {0x1a97540, 0xc0033331e0})
/home/runner/work/tracetest/tracetest/server/subscription/manager.go:59 +0x65
github.com/kubeshop/tracetest/server/executor.(*internalEventEmitter).Emit(_, {_, _}, {0x0, {0x1b2908b, 0xc}, {0x1b1a196, 0x7}, {0x1b5697d, 0x1c}, ...})
/home/runner/work/tracetest/tracetest/server/executor/eventemitter.go:35 +0x18d
github.com/kubeshop/tracetest/server/executor.persistentRunner.processExecQueue({0xc0006b7fb0, …
```
=> Added mutex to avoid concurrency errors on SubscriptionManager

server/http/websocket/subscribe.go
This PR adds OpenAPI mapping to websocket response for `TestRunEvents`.
- fix TestRunEvent mapping in WebSocket
-
=> fix(server): fix TestRunEvent mapping in WebSocket

docker-compose.yaml, docs/docs/examples-tutorials/recipes/running-tracetest-with-datadog.md, docs/docs/examples-tutorials/recipes/running-tracetest-with-lightstep.md, docs/docs/examples-tutorials/recipes/running-tracetest-with-new-relic.md, examples/quick-start-datadog-nodejs/tracetest/docker-compose.yaml, examples/tracetest-datadog/tracetest/docker-compose.yaml, examples/tracetest-lightstep-otel-demo/README.md, examples/tracetest-lightstep-otel-demo/docker-compose.yaml, examples/tracetest-lightstep/tracetest/docker-compose.yaml, examples/tracetest-new-relic-otel-demo/README.md, examples/tracetest-new-relic-otel-demo/docker-compose.yaml, examples/tracetest-new-relic/tracetest/docker-compose.yaml, examples/tracetest-otel-demo/docker-compose.yaml
This PR pins a specific postgres version (14) to some docker compose files that didn't have it. Not having the version pinned can create problems. For example, today for some reason docker decided that I needed to use the `15` version on my existing DB, and the storage formats are not compatible, so tracetest was not starting.
This fixes this issue
-
-
=> chore: pin postgres version on docker compose files

server/model/yaml/yamlconvert/datastore.go
This PR adds missing nil pointer checks that causes panic when trying to export a datastore that has only been configured as otlp, making `Values` nil.
-
-
=> fix: add nil pointer checks

docs/docs/configuration/overview.md, docs/docs/configuration/provisioning.md, docs/docs/configuration/server.md, docs/sidebars.js
Adding provisioning and server db config docs. Did not add an overall 'what is resources' as our cli is fairly fragmented right now. We need to add a resources page once we put out the CLI improvements.
=> Adding provisioning and server db config docs

server/executor/poller_executor.go, server/http/controller.go, server/model/connection_test_result.go, server/tracedb/otlp.go, server/tracedb/tracedb.go
This PR fixes the issue when unmarshalling the data store test struct
=> fix json unmarshal and remove connection test event from untestable datastores

docs/docs/configuration/server.md
Update server.md to add http server  options for server, including TRACETEST_SERVER_HTTPPORT and TRACETEST_SERVER_PATHPREFIX
This PR...
-
-
=> Update server.md to add http server  options for server

docs/docs/configuration/overview.md
Adding links to configuration options to overview page. Some of the statements are a bit 'forward looking', such as 'configuring most aspects of your Tracetest server environment'.
This PR...
-
-
=> chore(docs): Adding links to configuration options to overview page

web/src/components/TestResults/AddTestSpecButton.tsx, web/src/components/TestResults/Header.tsx, web/src/components/TestResults/TestResults.styled.ts, web/src/components/TestResults/TestResults.tsx, web/src/constants/TestSpecs.constants.ts
This PR adds a way for users to select a predefined test spec snippet so they have a quick start when adding checks for a trace
- Updating add test spec button
- Adding source for snippets
- #2174 
https://www.loom.com/share/dee7d821ab7d4bb1b4f53d81659e02c3
=> feature(frontend): adding test spec snippets

Makefile, api/openapi.yaml
This PR updates our OpenAPI spec to consider changes we did on Resource Manager-based APIs.
To test it locally, just run `make view-open-api` and follow the instructions.
- Updated `api/openapi.yaml`
=> Update OpenAPI spec for resource manager APIs

web/src/components/RunDetailLayout/HeaderRight.tsx, web/src/components/RunDetailTest/RunDetailTest.tsx, web/src/components/SpanDetail/Header.tsx
This PR introduces some minor improvements related to the error handling epic.
- Fix Span Attributes header
- Remove trace visualization Switch when the trace stage failed
- Add RunTest button in header if run failed
- fixes #2326
=> fix(frontend): add minor improvements for error handling

web/src/components/Pagination/Pagination.tsx, web/src/components/RunDetailLayout/HeaderLeft.tsx, web/src/components/RunDetailLayout/RunDetailLayout.tsx, web/src/components/TestHeader/TestHeader.tsx, web/src/components/TransactionHeader/TransactionHeader.tsx, web/src/hooks/usePagination.ts
This PR updates the behavior of the navigation logic when navigating across different pages, it also keeps track of the page number the list was for so users can come back to what exactly they were looking at.
- Updates back buttons for headers to use the `goback` method
- Pagination component now updates the search params on page change
- `usePagination` hook now checks for a `defaultPage` from the search params
- #2173 
https://www.loom.com/share/7fd3bfc0781d4bfb9e9102dc4e47e0b9
=> feature(frontend): adding persistent page number for list

server/analytics/analytics.go, server/app/app.go, server/executor/assertion_runner.go, server/executor/runner.go, server/executor/trace_poller.go, server/http/custom_routes.go
This PR adds analytics events for the checkpoints that end a test run execution
- Adding analytics events at the different levels where a test run ends
- #2245
=> feature(backend): adding analytics events for test run checkpoints

.github/workflows/pull-request.yaml
This PR makes the cleanup step of the PR pipeline run only when the run is successful. This change makes it easier to debug failed runs, and makes it faster to re run if needed.
=> chore(cicd): make pr pipeline clenaup only on success

server/resourcemanager/testutil/common_functions.go, server/resourcemanager/testutil/operations_create.go, server/resourcemanager/testutil/operations_get.go, server/resourcemanager/testutil/operations_list.go, server/resourcemanager/testutil/operations_update.go, server/resourcemanager/testutil/test_resource.go
This PR adds a new JSON comparer on ResourceManager tests, to help with custom comparisons like [this one](https://github.com/kubeshop/tracetest/pull/2385/files#diff-cd7dc885f7101522d2abd1018432f17e64eae778fc1fa7c73efe4b411f3001cfR17) that I needed to build while migrating DataStores to RM.
- Add support to custom JSON comparer on ResourceManager tests
- (partially) https://github.com/kubeshop/tracetest/issues/2341
=> Adding customJSON comparer to RM tests

cli/analytics/analytics.go, cli/installer/docker_compose.go
This PR applies a fix to the installer to allow us to use the `TRACETEST_DEV` environment variable in our shell to populate the value inside the Compose file generated by the installer.
- CLI installer fix
- fixes #2348
=> fix(cli): fix TRACETEST_DEV in docker compose installer

web/src/components/Header/Menu.tsx
This PR updates the `Discord` menu to `Online Chat`.
- discord menu
- fixes #2391
=> fix(frontend): update discord menu to online chat

server/executor/trace_poller.go, web/src/components/RunEvents/RunEventDataStore.tsx, web/src/components/RunEvents/RunEvents.styled.ts
This PR improves the error messaging from the trace section
- Adds a link to the settings page when the data store connection fails
- Includes the trace id as part of the error message if the poller times out
- #2389 
https://www.loom.com/share/a0ce8f8c0a36499c8323ff4cb914a639
=> feature(frontend): improving error messaging for the trace results

api/openapi.yaml
This PR updates the OpenAPI definition to consider the DataStore API on the resources API architecture.
**Note:** We are only running `make generate` to change the types on the backend PRs (#2385), just to avoid breaking things on this PR.
**Loom:** https://www.loom.com/share/0870ffdc991b4f37b8e35faf281a6605
- Update `api/openapi.yaml` definitions
- https://github.com/kubeshop/tracetest/issues/2343
- (partially) https://github.com/kubeshop/tracetest/issues/2334
=> Updating DataStore API definition to consider ResourcesAPI structure

server/executor/assertion_runner.go, server/executor/poller_executor.go, server/executor/trace_poller.go, server/model/events/events.go, web/src/components/RunEvents/RunEventPolling.tsx
This PR adds several improvements to the events triggered by the BE when executing a test run
- Updates event sequence to match the initial vision I never documented 🥴
- Adds better information for the FE when it comes to polling iteration info
- #2400 
https://www.loom.com/share/9353520fe43c49c6897f26b45975c2c3
=> fix: improvements to the test run events

api/tests.yaml, cli/openapi/model_test_run_outputs_inner.go, server/executor/assertion_runner.go, server/executor/outputs_processor.go, server/http/mappings/tests.go, server/model/events/events.go, server/model/json.go, server/model/tests.go, server/openapi/model_test_run_outputs_inner.go, web/src/components/TestOutput/TestOutput.styled.ts, web/src/components/TestOutput/TestOutput.tsx, web/src/models/TestOutput.model.ts, web/src/models/TestRunOutput.model.ts, web/src/redux/testOutputs/slice.ts, web/src/types/Generated.types.ts
This PR adds support for `errors` in `Test Outputs`. Now we are including an error icon and message in the list of outputs.
- Support for errors in Test Outputs
- Include the output error as part of the event log
- fixes #2256 
https://www.loom.com/share/56c97a5650424e6c9743566378d1be92
=> feat: improve test outputs error handling

.github/workflows/deploy-demo.yml, .github/workflows/deploy-main.yml, .github/workflows/pull-request.yaml, .github/workflows/release-candidate.yml, .github/workflows/release-version.yml, Makefile
This PR upgrades goreleaser to v1.17.2
=> chore: upgrade goreleaser to v1.17.2

server/config/configresource/config_resource_test.go, server/config/demoresource/demo_resource_test.go, server/executor/pollingprofile/polling_profile_resource_test.go, server/resourcemanager/main_test.go, server/resourcemanager/resource_manager_test.go, server/resourcemanager/testutil/test_provisioning.go, server/resourcemanager/testutil/test_resource.go, server/testdb/data_stores_test.go
This PR adds a database connection cleanup on RM tests to avoid surpassing PG connection capabilities when testing a package.
- Changed RM tests to receive a database connection
- Added code to manage database connection cleanup on Resource Manager tests
- (partially) #2341
=> Adding database connection cleanup procedure on Resource Manager tests

.github/workflows/deploy-main.yml
This PR replaces method for transmitting builds between the steps of the `deploy main` pipline from a `cache` to an `arctifact`. The difference is that an cache will fail silently to upload or download, while an arctifact fully fails on error.
This prevents issues like on [this run](https://github.com/kubeshop/tracetest/actions/runs/4767008554/jobs/8474956842), where the pipeline succeeded but the actual result was a nightly release with the linux binaries missing.
-
-
=> chore(cicd): replace cache with arctifacts so pipeline fails on error

server/app/app.go, server/model/events/events.go, server/otlp/grpc_server.go, server/otlp/http_server.go, server/otlp/ingester.go
This PR adds events logs for the otlp server endpoints when receiving spans
- Adds the event emitter instance to the ingester module
- Triggers new event after saving spans to the run object
- #2383 
https://www.loom.com/share/9334810050d44bd59caa392b6921a0d4
=> feature(backend): adding event logs for otlp endpoints

go.work.sum, server/executor/trigger/http.go, server/go.mod, server/go.sum, server/otlp/ingester.go
This PR fixes the HTTP url parsing by introducing a library that resolves the strings in a proper way
- Includes urlx to parse http triggers
- #2374 
Check what URLX does instead of whatever the core url package tries to do:
=> bug(backend): fixing url parsing for http requests

cli/cmd/config.go
This PR fixes the CLI base URLs for resources: `Config`, `PollingProfile` and `Demo`
- Fix CLI base URLs for resources
-
=> fix(cli): fix resources URLs

cli/formatters/test_run.go, cli/formatters/transaction_run.go
This PR improves the generated output when a test or a transaction step fails. Instead of showing `Failed to execute transaction: <reason>` it shows the test name and the link for the user to see more details on the UI.
=> fix: improve test and transaction output when it fails

.github/workflows/deploy-main.yml, .github/workflows/pull-request.yaml, .goreleaser.rc.yaml, .goreleaser.yaml, server/arch.yaml
This PR adds an auto generated image of the backend architecture, so we can keep track of how it evolves over time.
-
-
=> chore: generate server arch graph for releases

TESTING.md, local-config/tempo-cloud/collector.config.yaml, local-config/tempo-cloud/docker-compose.yaml, local-config/tempo-cloud/tracetest.config.yaml, local-config/tempo-cloud/tracetest.provision.yaml, server/tracedb/datasource/http.go
This PR fixes a server crash error that happens when we configure Tempo Cloud with HTTP client
=> Fix nil reference error when starting Tempo

server/tracedb/datastoreresource/repository_test.go, server/tracedb/datastoreresource/resource_types.go
This PR fixes the access id key for the aws data store
-
-
=> fix(be): updating aws access key id

examples/tracetest-lightstep-otel-demo/tracetest/tracetest-provision.yaml, examples/tracetest-lightstep/tracetest/tracetest-provision.yaml
This PR changes the Lightstep provider id to `lightstep` on our examples.
=> Fixing typo on Lightstep examples

server/migrations/25_update_data_stores_id.down.sql, server/migrations/25_update_data_stores_id.up.sql
This PR adds a server migration to guarantee that preexisting data_stores will continue working on Tracetest.
- Add migration
=> Add migration to fix data_store ids

docs/docs/configuration/telemetry.md, docs/sidebars.js, examples/quick-start-github-actions/readme.md
This PR adds a config page in the docs for setting up internal telemetry.
-
-
=> docs(config): add page for internal telemetry

web/src/components/TestResults/AddTestSpecButton.tsx, web/src/components/TestResults/Header.tsx, web/src/components/TestSpecs/Empty.tsx, web/src/components/TestSpecs/TestSpecs.styled.ts, web/src/constants/Common.constants.ts, web/src/pages/Home/Resources.tsx
This PR implements a new behavior for Test Specs snippets. We are introducing the following changes:
- Add snippets to the Empty screen
- Remove the "auto open" from the dropdown menu
- Include a disabled state until the trace is fetched
- Add snippets in the Empty screen, 
- Removing the auto open from the dropdown menu
- Include a disabled state until the trace is fetched
- fixes #2376 
https://www.loom.com/share/5cc8c5f1a02b4af09cda1173305f18fa
=> fix(frontend): fix test specs snippets

web/src/components/CreateTestPlugins/Curl/steps/ImportCommand/ImportCommand.tsx, web/src/components/CreateTestPlugins/Curl/steps/ImportCommand/ImportCommandForm.tsx, web/src/components/Editor/CurlCommand/CurlCommand.tsx, web/src/services/Triggers/Curl.service.ts
This PR fixes/improves the Test creation flow when using the CURL plugin.
- Remove errors messages when mounting the form
- Improve messages and hints
- fixes #2451
=> fix(frontend): fix test creation with curl command

cli/cmd/server_install_cmd.go, cli/installer/docker_compose.go, cli/installer/installer.go, cli/installer/kubernetes.go, cli/installer/types.go
This PR removes a warning that users receive when trying to install Tracetest with docker (as shown on the image below) and add two optional params to skip user input on `tracetest server install`.
- Added empty "TRACETEST_DEV" env when reading `docker-compose` for the first time to avoid warning
- Adding arguments to avoid user input when running CLI
- #2165
=> Fix installer tracetest dev docker warning and add options to run installer directly without user input.

docs/docs/configuration/connecting-to-data-stores/lightstep.md, docs/docs/configuration/connecting-to-data-stores/new-relic.md, docs/docs/configuration/connecting-to-data-stores/opensearch.md, docs/docs/configuration/connecting-to-data-stores/signalfx.md
This PR adds some fixes for the Connection to DataStores section in our docs.
- Fix datastore types
-
=> fix(docs): fix connecting to datastores docs

api/environments.yaml, cli/openapi/api_api.go, cli/openapi/api_resource_api.go, cli/openapi/model_environment.go, tracetesting/run.bash, web/src/types/Generated.types.ts
This PR updates the environment format used for the pipelines, it also fixes an issue of having the environment id to be read-only as the generated types were not adding it to structs when marshaling it into a string
- environment format for pipelines
- read-only id fix
I found a potential problem, when using an environment as part of a test/transaction run, for the first environment creation the id can be omitted, but for the following runs the id needs to be present in order to update the existing one.
This will cause teams having to manually add the ids to their env files in case it already exists
=> fix(pipelines): fixing environment format

server/resourcemanager/operations.go, server/resourcemanager/resource_manager.go, server/resourcemanager/resource_manager_test.go, server/resourcemanager/testutil/operations.go, server/resourcemanager/testutil/operations_augmented.go, server/resourcemanager/testutil/operations_get.go, server/resourcemanager/testutil/operations_get_augmented.go, server/resourcemanager/testutil/test_resource.go
This PR adds support for augmented entities. This is a feature needed, for example, in transactions. We have 2 "representations" of transactions: the one used in files, which looks like this:
```yaml
type: Transaction
spec:
id: transactionID
name: some feature
description: do stuff in sequence
steps:
- testID_1
- testID_2
```
it contains just the information needed to create/update the transaction, and just a test ID to reference the step tests.
We also have another representation used in the API, that looks like this: (redacted)
```json
{
"id": "_2yuIhL4g",
"name": "01- Transaction",
"version": 1,
"steps": [
{
"id": "XK1UI2L4R",
"name": "01- Pokeshop - List",
"description": "Get a Pokemon",
// the rest of the test
},
{
"id": "K74lShYVR",
"name": "02 - Pokeshop - Add",
"description": "Add …
```
=> feat: add support for get augmented

server/environment/manager.go
This PR enables upsert when trying to create an environment with no id, this allows users to initialize a new environment without having to specify and id in case it exists.
- Route now tries finding the environment before creating
=> feature(backend): Enabling environment upsert endpoint when creating

cli/installer/tracetest.go
This PR fixes the hostname for the demo rpc endpoint when installing tracetest using docker and the pokeshop demo
=> fix(installer): updating grpc host when installing the docker version with pokeshop

api/openapi.yaml, api/transactions.yaml
This PR changes the CRUD operations on transactions to use the resource manager strategy
=> feat: change openapi spec for transactions to consider resource manager

cli/formatters/config.go, cli/formatters/datastore.go, cli/formatters/demo.go, cli/formatters/environment.go, cli/formatters/polling.go, cli/utils/api.go, go.work.sum
This PR fixes an issue we had when parsing YAML strings into structs when having nested structures similar to the Demo.
When parsing the Demo objects the values for the pokeshop and the open telemetry store objects were empty.
In this case, we are now using the open API provided logic to unmarshal JSON bytes into structs.
- The API now uses JSON
- Removing usage of yaml parsing for responses and relying on the open API functionality
Wrong output:
Fixed output:
=> fix(cli): fixing nested structs output format

api/openapi.yaml, api/transactions.yaml
Reverts kubeshop/tracetest#2486
=> Revert "feat: change openapi spec for transactions to consider resource manager"

cli/cmd/server_install_cmd.go, cli/installer/installer.go, cli/installer/kubernetes.go
This PR adds a context flag to allow users to bypass the inputs on our CLI.
With that, we can install tracetest on Kubernetes by running the following command:
```sh
tracetest server install --run-environment kubernetes --mode with-demo --kubernetes-context docker-desktop
```
- Added `kubernetes-context` flag on `server install` command
=> Adding context flag on server install

cli/cmd/datastore_legacy_cmd.go, cli/cmd/environment_legacy_cmd.go
This PR labels the `tracetest environment` and `tracetest datastore` commands as deprecated using the `Deprecated` cobra field. This prints a warning message in the CLI, and also removes the command from the `CLI reference documentation`.
- Label the `tracetest environment` and `tracetest datastore` commands as deprecated
-
=> fix(cli): fix datastore and environment deprecated commands

docs/docs/configuration/overview.md
This PR adds Honeycomb to the list of supported trace data stores.
-
-
=> docs(config): add honeycomb to list of supported trace data stores

server/app/app.go, server/http/spa.go, web/public/index.html, web/src/services/Analytics/Analytics.service.ts, web/src/types/Common.types.ts, web/src/utils/Env.ts
This PR fixes an issue to prevent the webApp to send analytics (`segment` & `posthog`) when the `TRACETEST_DEV` variable is present
- fix fe analytics when TRACETEST_DEV is present
-
=> fix: block fe analytics if TRACETEST_DEV is present

server/model/traces.go, server/model/traces_test.go
This PR allows our traces to have multiple root spans. They will always be children of the trigger span
=> feat: allow multiple root spans to exist in a tracetest trace

server/resourcemanager/encoding.go, server/resourcemanager/resource_manager.go, server/resourcemanager/resource_manager_test.go
This PR splits the request and response encoding in resource manager. This allows for clients to do requests in one format but expect the response to be in another.
This is useful for example in the CLI, where the client issues a request with a body in YAML format, from the contents of a user created yaml definition file), but then it needs to parse the response to beautify it. Also the user can request the output to be in json.
Instead of having the client manipulate responses, it can just configure the requests with standard http headers.
This reduction in manipulation along the pipeline reduces the need for client code, and reduces the chances of inconsistencies in formats.
Request: 
```
POST /api/exampleresources
Content-Type: text/yaml
Accept: application/json
type: ExampleResource …
```
=> feat(server): decouple request and response encoding in resource manager
